### ISSUE TITLE
Can't include css file

### ISSUE THREAD

**Issue by Dominux** [leptos-rs/leptos#1027]
Hello there

I create a simple website with a couple of components so I need a single small css file for it. But I can't force to include it into the dist folder during local development cause everytime I save any file, trunk triggers and overrides all the content of the folder

Neither LeptosOptions nor Trunk.toml has such an option to include a css file. Only cargo-leptos crate has this thing, but I'm struggled to setup it and I don't think it's a better choice for me since that package seems to be created for complex projects with SSR and so on (like a NextJS, NuxtJS and so on)

The only solution I found is to write all the css styles right into html file like it was 30 years ago. Please, tell me I just missed some place to tell the trunk to include css files

**Comment by gbj** [comment]
The way you configure Trunk is via tags like this in your `index.html`

`<link data-trunk rel="…`

You probably want their `css` or `copy-file` or `copy-dir` asset types. See Trunk docs [here](https://trunkrs.dev/assets/)

**Comment by Dominux** [comment]
Thanks, u helped a lot

Just spent some hours trying to solve it some days ago
