### ISSUE TITLE
form designer 、Generator

### ISSUE THREAD

**Issue by songlinshu** [leptos-rs/leptos#1028]
Do you have any plans to create a form designer?

**Comment by songlinshu** [comment]
Yes , UI design tool

https://github.com/MrXujiang/h5-Dooring

**Comment by gbj** [comment]
This seems like a large project that I'd be pretty bad at but that doesn't need any particular support from the framework itself to accomplish. I don't have any plans to build something like it, but am happy to provide support to anyone who's working on something like it.

**Comment by gbj** [comment]
I'm going to close this issue. I think this is out of scope for the framework, and I don't have any plans to work on it.
