### ISSUE TITLE
404 Support

### ISSUE THREAD

**Issue by Jaffa-Cakes** [leptos-rs/leptos#1031]
Hello, I was wondering if there was functionality supporting 404/not found pages when using the `leptos_router`?

I'm running on `leptos_actix` and receive standard 404 pages with no "app" when a page that isn't in the router is requested. This does make sense in order for loading additional assets to work, however, it would be nice if a route guard or similar could be manually added returning a rendered 404 page in Leptos.

**Comment by luoxiaozero** [comment]
Can view https://github.com/leptos-rs/leptos/blob/main/docs/book/src/router/16_routes.md

```rust
<Routes>
  <Route path="/" view=|cx| view! { cx, <Home/> }/>
  <Route path="/users" view=|cx| view! { cx, <Users/> }/>
  <Route path="/users/:id" view=|cx| view! { cx, <UserProfile/> }/>
  <Route path="/*any" view=|cx| view! { cx, <NotFound/> }/>
</Routes>
```

The '/*any' setting should match 404

**Comment by gbj** [comment]
It's worth taking a look at how the `errors_axum` example implements this with its [fallback static-file/404 handler](https://github.com/leptos-rs/leptos/blob/main/examples/errors_axum/src/fallback.rs). Obviously that's Axum not Actix, but they're similar enough that it should be pretty straightforward to adopt a similar approach.

**Comment by gbj** [comment]
We figured out a fairly convenient way to do this in Actix, anyway. I will update the starter template to make it harder to run into this accidentally, as well as updating the examples.

Basically if you make the static file servers a little more specific, so that they serve `pkg` at `/pkg` and `assets` at `/assets`, there's no conflict with a `/*any`-style catch-all 404 page for everything else. In the example below, I also implemented a custom handler for the favicon so it's still at `/favicon.ico` but you could instead use `<Link rel="icon" type_="image/x-icon" href="/assets/favicon.ico"/>` of course.

```rust
#[cfg(feature = "ssr")]
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    use actix_files::Files;
    use actix_web::*;
    use leptos::*;
    use leptos_actix::{generate_route_list, LeptosRoutes};
    use leptos_start::app::*;

    let conf = get_configuration(None).await.unwrap();
    let addr = conf.leptos_options.site_addr;
    // Generate the list of routes in your Leptos App
    let routes = generate_route_list(|cx| view! { cx, <App/> });

    HttpServer::new(move || {
        let leptos_options = &conf.leptos_options;
        let site_root = &leptos_options.site_root;

        App::new()
            .route("/api/{tail:.*}", leptos_actix::handle_server_fns())
            // serve JS/WASM/CSS from `pkg`
            .service(Files::new("/pkg", format!("{site_root}/pkg")))
            // serve other assets from the `assets` directory
            .service(Files::new("/assets", site_root))
            // serve the favicon from /favicon.ico
            .service(favicon)
            .leptos_routes(
                leptos_options.to_owned(),
                routes.to_owned(),
                |cx| view! { cx, <App/> },
            )
            .app_data(web::Data::new(leptos_options.to_owned()))
        //.wrap(middleware::Compress::default())
    })
    .bind(&addr)?
    .run()
    .await
}

#[cfg(feature = "ssr")]
#[actix_web::get("favicon.ico")]
async fn favicon(
    leptos_options: actix_web::web::Data<leptos::LeptosOptions>,
) -> actix_web::Result<actix_files::NamedFile> {
    let leptos_options = leptos_options.into_inner();
    let site_root = &leptos_options.site_root;
    Ok(actix_files::NamedFile::open(format!(
        "{site_root}/favicon.ico"
    ))?)
}
```
