### ISSUE TITLE
<For/> rerenders the whole list when I insert new elements in front

### ISSUE THREAD

**Issue by Dominux** [leptos-rs/leptos#1033]
Hi

I insert new elements at the start of the vector, it causes rerender of the whole list and flickering. When I tried to push the element (inserting at the end) it renders only that element leaving others untouched.

Is there any way to prevent such a behaviour?

**Comment by gbj** [comment]
The `<For/>` component has some bugs and is being rewritten (#533, #897, #955). Could you please provide a reproduction of your issue so we can test against it when that's complete, or determine whether it's actually a bug or not?

**Comment by gbj** [comment]
I don't know if this was related to #1078 but I'm not able to reproduce: in the example below, inserting items at the front definitely only renders the new nodes, in either debug or release mode.

If you're able to provide a reproduction of your issue that's still broken against latest git main I'm happy to reopen this.

Here's my test case:
```rust
use std::collections::VecDeque;

use leptos::*;

fn main() {
    mount_to_body(|cx| {
        let (list, set_list) = create_signal(cx, (0..5).collect::<VecDeque<usize>>());

        view! { cx,
            <button on:click=move |_| set_list.update(|n| n.push_front(n.len()))>"Add item"</button>
            <Table list=list />
        }
    });
}

#[component]
fn Table(cx: Scope, list: ReadSignal<VecDeque<usize>>) -> impl IntoView {
    view! { cx,
        <table>
            <tr>
                <td>"Header"</td>
            </tr>

            <For each=list key=|&e| e view=move |cx, e| view! { cx,
                <tr>
                    <td>{leptos::log!("rendering {e}"); e}</td>
                </tr>
            }/>
        </table>
    }
}
```
