### ISSUE TITLE
Extra escaping with SSR rendering

### ISSUE THREAD

**Issue by searound** [leptos-rs/leptos#1035]
Using the latest version on main, the following view component
```
    view! {cx,
        <p>
        "The number is 2. Are these doubled? { }"
        </p>
        <p>
        "The number is calculated as "{2}". Are these doubled? { }"
       </p>
    }
```
renders fine on the client. But when generated on the server it shows

> The number is: 2. Are these doubled? { }
> 
> The number is: 2. Are these doubled? {{ }}

**Comment by gbj** [comment]
Ahh yeah that makes sense. There are some SSR optimizations that use `format!()` internally to render static parts of your `view` templates to HTML at compile time, which meant that `{ }` braces had to be escaped. But of course if there are no further dynamic parts in that chunks, they don't. Good catch, this PR should fix it.

**Comment by searound** [comment]
Great, thank you. That fixes the issue for me.
