### ISSUE TITLE
cargo leptos fails on custom build target-dir

### ISSUE THREAD

**Issue by mbuczko** [leptos-rs/leptos#1041]
Hey, seems like I'm unable to compile examples having a custom target-dir set up. This is my config in `/home/foo/.cargo/config`:
```
[build]
target-dir = ".cargo/target"
```

and following is the error being thrown on `cargo leptos`:
```sh
~/github/leptos/examples/hackernews_axum ❯ cargo leptos watch
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Could not remove base "/home/foo/github/leptos/examples/hackernews_axum" from "/home/foo/.cargo/target"', /home/foo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.1.8/src/ext/cargo.rs:73:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by gbj** [comment]
Thanks. But could you open an issue in [the `cargo-leptos` repo](https://github.com/leptos-rs/cargo-leptos) instead?

**Comment by mbuczko** [comment]
sure. created https://github.com/leptos-rs/cargo-leptos/issues/127.
