### ISSUE TITLE
StoredValue docs inconsistency

### ISSUE THREAD

**Issue by elliotwaite** [leptos-rs/leptos#1045]
The [StoredValue](https://docs.rs/leptos/latest/leptos/struct.StoredValue.html) docs say:
> Unlike the signal types, it is not reactive; accessing it does not cause effects to subscribe, and updating it does not notify anything else.

...yet its [get_value](https://docs.rs/leptos/latest/leptos/struct.StoredValue.html#method.get_value) method says:
> Returns a clone of the signals current value, subscribing the effect to this signal.

This seems like an inconsistency. Is this an error in the documentation, or am I misunderstanding something?

**Comment by bluenote10** [comment]
I was wondering the same. Same for the paragraphs mentioning _if the signal is still valid ..._ in the other functions. I was suspecting that it might have been just a copy/paste thing, if the code was originating from the actual signal implementations.

**Comment by elliotwaite** [comment]
Ah, got it.

Then another question I have is, I noticed that this latest 0.3.0 release removed the previously deprecated [`get()`](https://docs.rs/leptos/0.3.0-alpha2/leptos/struct.StoredValue.html#method.get) method, which had this deprecation message:
> Deprecated: Please use `get_value` instead, as this method does not track the stored value. This method will also be removed in a future version of `leptos`

But if the `get_value()` method also does not track the stored value, why was the `get()` method deprecated? It seems like the shorter `get()` syntax would be more convenient and more aligned with the signal syntax.

**Comment by gbj** [comment]
> Ah, got it.
> 
> Then another question I have is, I noticed that this latest 0.3.0 release removed the previously deprecated [`get()`](https://docs.rs/leptos/0.3.0-alpha2/leptos/struct.StoredValue.html#method.get) method, which had this deprecation message:
> 
> > Deprecated: Please use `get_value` instead, as this method does not track the stored value. This method will also be removed in a future version of `leptos`
> 
> But if the `get_value()` method also does not track the stored value, why was the `get()` method deprecated? It seems like the shorter `get()` syntax would be more convenient and more aligned with the signal syntax.

This was proposed by a user as a disambiguation: the signal methods `.get()`/`.with()`/etc., `Resource::with()`, and so on are all reactive/tracked. The intention is to make it more obvious that `.get_value()` is **not** a reactive `.get()`. 

Like signals, stored values also implement the `Fn` traits, so if you don't mind the syntactic ambiguity, want the shortest syntax, and are on nightly, you can just do `some_value()` instead of `some_value.get_value()`

**Comment by elliotwaite** [comment]
> This was proposed by a user as a disambiguation: the signal methods `.get()`/`.with()`/etc., `Resource::with()`, and so on are all reactive/tracked. The intention is to make it more obvious that `.get_value()` is **not** a reactive `.get()`.

I see, that's a fair point. I think I'd still prefer the shorter syntax for both, but maybe the "_value" syntax will grow on me now that I understand the reasoning behind it.

> Like signals, stored values also implement the `Fn` traits, so if you don't mind the syntactic ambiguity, want the shortest syntax, and are on nightly, you can just do `some_value()` instead of `some_value.get_value()`

Nice. Thanks for pointing that out. I hadn't realized this syntax was also available for stored values.
