### ISSUE TITLE
wasm-bindgen version mismatch when running example

### ISSUE THREAD

**Issue by maninalift** [leptos-rs/leptos#1051]
I checked checked out the current master branch of leptos and tried to run the session_auth_axum example but got a wasm-bindgen version mismatch error (between `cargo_leptos` and the example project)

```
git clone https://github.com/leptos-rs/leptos

cd leptos/examples/session_auth_axum

direnv allow

cargo install --locked --force cargo-leptos
    Updating crates.io index
    Installing cargo-leptos v0.1.8
    ...  
    Compiling wasm-bindgen-wasm-conventions v0.2.84
    ...
    Compiling wasm-bindgen-wasm-interpreter v0.2.84
    Compiling wasm-bindgen-threads-xform v0.2.84
    ...
    Compiling wasm-bindgen-externref-xform v0.2.84
    Compiling wasm-bindgen-multi-value-xform v0.2.84
    ```

cargo leptos watch
   Compiling session_auth_axum v0.1.0 (/home/caz/Repos/projects/doify/experiments/leptos/examples/session_auth_axum)
    Finished dev [unoptimized + debuginfo] target(s) in 1.13s
       Cargo finished cargo build --package=session_auth_axum --lib --target-dir=target/front --target=wasm32-unknown-unknown --no-default-features --features=hydrate
Error: at `/home/caz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.1.8/src/compile/front.rs:42:30`

Caused by:
    0: at `/home/caz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.1.8/src/compile/front.rs:108:10`
    1:

       it looks like the Rust project used to create this wasm file was linked against
       version of wasm-bindgen that uses a different bindgen format than this binary:

         rust wasm file schema version: 0.2.85
            this binary schema version: 0.2.84

       Currently the bindgen format is unstable enough that these two schema versions
       must exactly match. You can accomplish this by either updating the wasm-bindgen
       dependency or this binary.

       You should be able to update the wasm-bindgen dependency with:

           cargo update -p wasm-bindgen

       or you can update the binary with

           cargo install -f wasm-bindgen-cli

       if this warning fails to go away though and you're not sure what to do feel free
       to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!
```

I tried running 

```
cargo install -f wasm-bindgen-cli --version 0.2.85

cargo update -p wasm-bindgen
```

but that only led to 

```
cargo leptos watch
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
       Cargo finished cargo build --package=session_auth_axum --lib --target-dir=target/front --target=wasm32-unknown-unknown --no-default-features --features=hydrate
Error: at `/home/caz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.1.8/src/compile/front.rs:42:30`

Caused by:
    0: at `/home/caz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.1.8/src/compile/front.rs:108:10`
    1:

       it looks like the Rust project used to create this wasm file was linked against
       version of wasm-bindgen that uses a different bindgen format than this binary:

         rust wasm file schema version: 0.2.86
            this binary schema version: 0.2.84

       Currently the bindgen format is unstable enough that these two schema versions
       must exactly match. You can accomplish this by either updating the wasm-bindgen
       dependency or this binary.

       You should be able to update the wasm-bindgen dependency with:

           cargo update -p wasm-bindgen

       or you can update the binary with

           cargo install -f wasm-bindgen-cli

       if this warning fails to go away though and you're not sure what to do feel free
       to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!

```

Trying to downgrade `wasm-bindgen` results in a conflict with dependencies from leptos 

```
cargo update -p wasm-bindgen --precise "0.2.84"
    Updating crates.io index
error: failed to select a version for the requirement `wasm-bindgen = "^0.2.85"`
candidate versions found which didn't match: 0.2.84
location searched: crates.io index
required by package `js-sys v0.3.62`
    ... which satisfies dependency `js-sys = "^0.3"` (locked to 0.3.62) of package `leptos_reactive v0.3.0 (/home/caz/Repos/projects/doify/experiments/leptos/leptos_reactive)`
    ... which satisfies path dependency `leptos_reactive` (locked to 0.3.0) of package `leptos v0.3.0 (/home/caz/Repos/projects/doify/experiments/leptos/leptos)`
    ... which satisfies path dependency `leptos` (locked to 0.3.0) of package `leptos_axum v0.3.0 (/home/caz/Repos/projects/doify/experiments/leptos/integrations/axum)`
    ... which satisfies path dependency `leptos_axum` (locked to 0.3.0) of package `session_auth_axum v0.1.0 (/home/caz/Repos/projects/doify/experiments/leptos/examples/session_auth_axum)`
perhaps a crate was updated and forgotten to be re-vendored?
```

**Comment by JacobHaig** [comment]
I too am having the same issue.

**Comment by gbj** [comment]
If you just change the `wasm-bindgen` dependency in `Cargo.toml` to 0.2.84 is it resolved? It should be.

**Comment by JacobHaig** [comment]
It wasnt working for me either, but I was able to fix it by changing

`wasm-bindgen = "0.2.84"`
to
`wasm-bindgen = "=0.2.84"`

in my cargo.toml file to force the exact version to be download. It seems no matter what I did, Cargo was downloading 0.2.86 even if it was 0.2.84... Can someone else test this?

**Comment by maninalift** [comment]
Great, I set wasm bindgen version with 

`wasm-bindgen = "=0.2.84"`

As suggested. I did this in the Cargo.toml of `leptod_reactive`, `leptos_dom`, `router` and `meta`. I guess I only really needed to set it in one place to pin the version. But in any case it solved the issue.

**Comment by gbj** [comment]
See also https://github.com/leptos-rs/cargo-leptos/pull/126. It looks like `wasm-bindgen` released `0.2.85` and then immediately `0.2.86`, which is odd, so I guess we'll see if we need to update `cargo-leptos` again, but this is fixed on git main of `cargo-leptos` now and will be in the next release. Will leave this open for a while in case anyone else runs into it.

**Comment by gbj** [comment]
This should be completely handled by `cargo-leptos 0.1.9`, just released, so I'm closing this issue.

**Comment by gbj** [comment]
@j00p34 The answer here is the same as above, I think: the `wasm-bindgen-cli` crate which `cargo-leptos` uses to run `wasm-bindgen` requires that the patch versions be the same between `wasm-bindgen-cli` as compiled into `cargo-leptos` and the `wasm-bindgen` dependency in your own crate. In your case, updating to the latest `cargo-leptos` 0.2.16 and then running `cargo update` in your application will likely resolve the issue.

**Comment by j00p34** [comment]
Yes, that works, can't thank you enough for the swift reply
