### ISSUE TITLE
Table is not re-rendering when using create_action and fetching data onclick

### ISSUE THREAD

**Issue by jackbackes** [leptos-rs/leptos#1052]
I'm facing an issue with the reactivity system while using create_action to fetch data based on user button clicks. The reactivity system doesn't seem to trigger a re-render when the fetched data is updated.

Here's a high-level overview of the code:

1. I have a create_signal for a user input (a stock symbol).
2. There's a create_action block that fetches information based on the input stock symbol when a button is clicked.
3. The fetched data needs to be rendered in a table component.
4. The problem is that my table does not get re-rendered when the data is changed, i.e., after fetching through the create_action. 

Below is the relevant part of my code:

The table does not re-render when the fetch is complete, and it is not reactive to the fetched data updates.

```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    let (name, set_name) = create_signal(cx, String::new());

    // Fetch options contracts
    let fetch_options_contracts = create_action(
        cx,
        move |input: &String| {
            let symbol = input.clone();
            async move {
                let args = to_value(&OptionsContractsArgs { symbol: symbol.as_str() }).unwrap();
                // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
                let options_contracts = invoke("fetch_options_contracts", args)
                    .await;
                let response = from_value(options_contracts);
                if response.is_err() {
                    return MaybeOptionsContracts::default();
                }
                let response = response.unwrap();
                response
            }
        }
    );

    let update_name = move |ev| {
        let v = event_target_value(&ev);
        set_name.set(v);
    };


    let onSubmit = move |ev: SubmitEvent| {
        ev.prevent_default();
        fetch_options_contracts.dispatch(name.get());
    };

    view! { cx,
        <main class="container">
            <div class="row">
                <a href="https://tauri.app" target="_blank">
                    <img src="public/tauri.svg" class="logo tauri" alt="Tauri logo"/>
                </a>
                <a href="https://docs.rs/leptos/" target="_blank">
                    <img src="public/leptos.svg" class="logo leptos" alt="Leptos logo"/>
                </a>
            </div>

            <p>"Click on the Tauri and Leptos logos to learn more."</p>

            <p>
                "Recommended IDE setup: "
                <a href="https://code.visualstudio.com/" target="_blank">"VS Code"</a>
                " + "
                <a href="https://github.com/tauri-apps/tauri-vscode" target="_blank">"Tauri"</a>
                " + "
                <a href="https://github.com/rust-lang/rust-analyzer" target="_blank">"rust-analyzer"</a>
            </p>

            <form class="row" on:submit=onSubmit>
                <input
                    id="greet-input"
                    placeholder="Enter a stock symbol..."
                    on:input=update_name
                />
                <button type="submit">"Fetch"</button>
            </form>

            {
                if fetch_options_contracts.pending().get() {
                    view! {cx, <div><TableIsLoading /></div>}
                } else {
                    view! {cx, <div><Table options_contracts=fetch_options_contracts.value().get() /></div>}
                }
            }
        </main>
    }
}
```

I feel I am definitely missing something here. Any guidance on how to proceed would be appreciated.

**Comment by gbj** [comment]
Your `if fetch_options` etc needs to be in a closure: `move || if_options` etc. 

I'd recommend reading this section of the guide: https://leptos-rs.github.io/leptos/view/01_basic_component.html#the-view

This is a common problem people run into when first using the framework, but once you're used to it you'll be used to it!

**Comment by gbj** [comment]
The same issue is true for `<Table options_contracts=fetch_options_contracts.value().get()>` for what it's worth -- if you want this to respond to changes you should pass the signal in, not the static value you get from `.get()`

Happy to help you troubleshoot more in GitHub Discussions or [on Discord](https://discord.gg/x8NhWWYTV2). I'm going to close this issue to keep issues focused on bugs and feature requests.
