### ISSUE TITLE
Leptos project release error: -Zbuild-std requires --target

### ISSUE THREAD

**Issue by Sol-Ell** [leptos-rs/leptos#1059]
### How to get an error

```
cargo leptos new -n project-name --git leptos-rs/start-axum
cd project-name
```  

Then follow this(+ unstable): [Appendix: Optimizing WASM Binary Size](https://leptos-rs.github.io/leptos/appendix_binary_size.html#appendix-optimizing-wasm-binary-size)
``` 
cargo leptos build 
```

Output:
>Finished dev [unoptimized + debuginfo] target(s) in 0.20s
>Cargo finished cargo build --package=start-axum --lib --target-dir=target/front --target=wasm32-unknown-unknown --no-default-features --features=hydrate
**error: -Zbuild-std requires --target**

### My attempt
I added this to _.cargo/config.toml_:
> [build]
> target = "x86_64-unknown-linux-gnu"

But after i got this:

<details><summary>Details</summary>
<p>

Finished dev [unoptimized + debuginfo] target(s) in 0.21s
       Cargo finished cargo build --package=start-axum --lib --target-dir=target/front --target=wasm32-unknown-unknown --no-default-features --features=hydrate
   Compiling core v0.0.0 (/home/.../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
error[E0080]: evaluation of constant value failed
  --> /home/.../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic.rs:61:9
   |
61 |         $crate::panicking::panic_fmt($crate::const_format_args!($($t)+));
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'panic_immediate_abort requires -C panic=abort', /home/.../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:33:15
   |
  ::: /home/.../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:33:15
   |
33 | const _: () = assert!(cfg!(panic = "abort"), "panic_immediate_abort requires -C panic=abort");
   |               ------------------------------------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
error: could not compile `core` (lib) due to previous error`

</p>
</details>

**Comment by gbj** [comment]
Thanks, I guess I'd tested this with `wasm-pack` or `trunk` only, not with `cargo-leptos`. 

I'll add your note about 
```toml
[build]
target = "x86_64-unknown-linux-gnu"
```
to the docs.

The error you list suggests that you should also add `panic = "abort"` to `[profile.release]` in `Cargo.toml`

If I make those changes it builds for me with `cargo-leptos`

**Comment by gbj** [comment]
Update: There's a much better solution here. For me, this compiles, gating the unstable build features to WASM only, which is what we really want here

```
[unstable]

[target.'cfg(target_arch = "wasm32")']
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]
```

**Comment by Sol-Ell** [comment]
That also works for me. Thanks for explanation!

**Comment by gbj** [comment]
Huh I'm not sure it actually applies the feature anywhere -- testing, it looks like I get the same WASM binary size doing this as doing nothing. So it seems like that wasm32 flag just blocks either of them from applying?

**Comment by johnbchron** [comment]
@gbj Correct. According to [here](https://stackoverflow.com/questions/76580751/how-to-set-cargo-unstable-options-for-a-target), you cannot set target-specific `unstable` options. On newer versions of cargo-leptos you can see that cargo logs that the keys are unused.

Maybe we should include this into cargo-leptos, where we can modify the cargo invocations directly. Add `build-std: bool` and `build-std-features: list` options where when `build-std` is enabled, we send the appropriate flags to only the wasm build?

I'd be willing to do a PR.
