### ISSUE TITLE
feat: Specify path of Server Functions

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#1061]
Basically I'd like to define an API with Leptos for external consumption, and use Leptos server functions on it. I believe I can do that if I can specify the path the server function will accept paths on.

As an example, I could define /login and the server function
```rust
// I know there are more args to the macro, but we'd add on or replace the prefix section
#[server("/login")]
pub fn login() -> Result<(), ServerFnError>{
...
}
```

**Comment by gbj** [comment]
This is is very doable. The two questions to settle are just
1. What should the syntax be?
2. Implementing it in the macro.

`url()` is just an associated function in the `ServerFn` trait (which is implemented on the `ServerFnType` you give the name of). Currently it's defined in the macro by passing in the server function name and a hashed path.
https://github.com/leptos-rs/leptos/blob/2cb68c0bd45a99d03665bdac3ef25ce7fd4d0b01/server_fn_macro/src/lib.rs#L215-L217
