### ISSUE TITLE
feat: manually implement PartialEq, Eq and Hash for signals

### ISSUE THREAD

**Issue by elias098** [leptos-rs/leptos#1074]
Currently signals implement PartialEq, Eq and Hash with derive, which requires T to implement said traits.

Signals only use T in phantomdata and as such the actual implementation does not require T to implement any traits.

Manually implementing the traits would allow for any signal to use them without T having them implemented.

**Comment by gbj** [comment]
Note for anyone interesting in contributing: this could be done for *every* single reactive type (RwSignal, ReadSignal, WriteSignal, Memo, Signal) as well as StoredValue. Possibly for the Debug trait as well. rust-analyzer should even be able to fill in the most of the definitions for you...
