### ISSUE TITLE
Is axum with_state broken?

### ISSUE THREAD

**Issue by sebastian** [leptos-rs/leptos#1079]
First: thank you for this wonderful project! I look forward to fully absorbing all this framework can do! I am entirely new to this project, so might be missing something obvious. Therefore, please bear with me.

**TL;DR** 
I have an issue using `with_state` setting up my axum routers. The `leptos_routes` call seems to force the axum router to become a `Router<()>`-router (i.e. without any meaningful state?).

**Long version:**
I have setup my leptos project using the `https://github.com/leptos-rs/start-axum` template using `cargo-leptos`. Because I want to pass other state through to non-leptos routes I wanted to use `with_state` to manage my app state in axum, rather than `Extension`-method the starter template is using. I see [`with_state` support](https://github.com/leptos-rs/leptos/pull/1032) was recently added, and from what I gather this should also have made it into the 0.3.0 release which I am using.

The problem I am observing is that as soon as I call [`leptos_routes`](https://github.com/sebastian/leptos_with_state/blob/main/src/main.rs#L41) the type of the router becomes `Router<()>` which then causes a compilation error when I subsequently call `with_state`:

```
error[E0308]: mismatched types
   --> src/main.rs:43:21
    |
43  |         .with_state(state);
    |          ---------- ^^^^^ expected `()`, found `State`
    |          |
    |          arguments to this method are incorrect
    |
note: method defined here
   --> /Users/sebastian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.6.18/src/routing/mod.rs:294:12
    |
294 |     pub fn with_state<S2>(self, state: S) -> Router<S2, B> {
    |            ^^^^^^^^^^
```

I created a minimal reproducible (well, it reproduces nicely on my end...) version here: https://github.com/sebastian/leptos_with_state

Could the reason be that `leptos_routes` calls into:

```
/// The default implementation of `LeptosRoutes` which takes in a list of paths, and dispatches GET requests
/// to those paths to Leptos's renderer.
impl LeptosRoutes for axum::Router {
    #[tracing::instrument(level = "info", fields(error), skip_all)]
    fn leptos_routes<IV>(
        self,
        options: LeptosOptions,
        paths: Vec<RouteListing>,
        app_fn: impl Fn(leptos::Scope) -> IV + Clone + Send + 'static,
    ) -> Self
    where
        IV: IntoView + 'static,
```

where `axum::Router` isn't specified as `axum::Router<S, B>`?

**Comment by gbj** [comment]
Thanks for bringing this up. To be clear, the `.with_state` PR you note was merged after 0.3.0. In fact we need to do some more work on it previously `.with_state` was broken in one way (assumed to be `()`), but folks have brought up some rough edges with the new API. @benwis is planning to take a look at it so I'm tagging him here.

**Comment by sebastian** [comment]
Thank you @gbj.

Please let me know if there is anything you would like me to test @benwis - but by the sound of it you have it all under control.

**Comment by akarras** [comment]
The way it's currently implemented is workable, but maybe not ideal?

Currently you'd need to implement for your state struct.
```rs
#[cfg(feature = "ssr")]
impl leptos_axum::LeptosOptionProvider for State {
    fn options(&self) -> LeptosOptions {
        (*self.leptos_options).clone()
    }
}
```
Just to demo this to unblock you- I forked your [example and made the changes to get it working](https://github.com/akarras/leptos_with_state)


IMO, long term we should probably look into dropping LeptosOptionsProvider and following what Axum does with [substates](https://docs.rs/axum/latest/axum/extract/struct.State.html#substates). As far as I can tell, LeptosOptionsProvider is basically identical to AsRef<LeptosOptions>, but is an explicit trait.

**Comment by benwis** [comment]
> The way it's currently implemented is workable, but maybe not ideal?
> 
> Currently you'd need to implement for your state struct.
> 
> ```rust
> #[cfg(feature = "ssr")]
> impl leptos_axum::LeptosOptionProvider for State {
>     fn options(&self) -> LeptosOptions {
>         (*self.leptos_options).clone()
>     }
> }
> ```
> 
> Just to demo this to unblock you- I forked your [example and made the changes to get it working](https://github.com/akarras/leptos_with_state)
> 
> IMO, long term we should probably look into dropping LeptosOptionsProvider and following what Axum does with [substates](https://docs.rs/axum/latest/axum/extract/struct.State.html#substates). As far as I can tell, LeptosOptionsProvider is basically identical to AsRef, but is an explicit trait.

Yeah, I think the addition of some docs to make the distinction more clear, and switching to AsRef<LeptosOptions> instead of LeptosOptionsProvider should tidy things up nicely. I'll make the changes today

**Comment by sebastian** [comment]
Thank you, both of you 🎉

(and I have to say: what a nice a friendly welcome to the leptos community!)
