### ISSUE TITLE
Typo inside docs guide 3.4 Iteration's codesandbox example (line 114, they should be the)

### ISSUE THREAD

**Issue by luckynumberke7in** [leptos-rs/leptos#1087]
https://github.com/leptos-rs/leptos/blob/d86339bae3dad552b66d92238e9dfd6681a45f0f/docs/book/src/view/04_iteration.md?plain=1#L106

I can do a pr to a new codesandbox with the fix, if you don't mind reminding me / guiding me to the contribution guide!

**Comment by gbj** [comment]
Thanks, fixed! Good catch.
