### ISSUE TITLE
Animated route history.back only triggers once

### ISSUE THREAD

**Issue by arturleao** [leptos-rs/leptos#1088]
I have multiple routes setup and they are "chained" together (in a workflow sense, they are not nested) and if I go from Page A to Page B and then back, the animated route works properly and setups the appropriate classes in the main div. But if I go from Page A to Page B to Page C, and then start going back, the animated route only works properly from Page C to Page B, when going back from Page B to page A, it only triggers the normal classes and not the back ones.

Maybe I'm doing something wrong and the setup should be made differently?

**Comment by gbj** [comment]
Could you provide some example code so I can try to reproduce this and either fix it or see what's going wrong?
