### ISSUE TITLE
Difficulty passing WriteSignal to #server function

### ISSUE THREAD

**Issue by MinaMatta98** [leptos-rs/leptos#1103]
Hello,

Was there any way to pass through a writesignal to a server function?

I have attempted the provide_context/use_context duo, but it seems to not appropriately trigger with server functions, as they are not a reactive component.

Any commentary on this would be greatly appreciated.

**Comment by gbj** [comment]
No, reactivity does not pass between the client and the server.

As [the docs for the `#[server]` macro](https://docs.rs/leptos/0.3.0/leptos/attr.server.html) say, 
> **The `Scope` comes from the server.** Optionally, the first argument of a server function can be a Leptos `Scope`. This scope can be used to inject dependencies like the HTTP request or response or other server-only dependencies, but it does *not* have access to reactive state that exists in the client.

I'm not sure what exactly you're trying to do, but it's almost certainly best solved by using `create_resource` to call a server function, and returning a value from the server function.

**Comment by MinaMatta98** [comment]
Hello,

My server function had multiple steps. I was looking for a way to use the
server function and provide updates for progress based on the stage.

I will instead have to simply split the function and call multiple instead.

Cheers.

**Comment by gbj** [comment]
There's not currently a way to return multiple values from a server function like this.
