### ISSUE TITLE
Triggering Router Redirection outside the reactive environment

### ISSUE THREAD

**Issue by MinaMatta98** [leptos-rs/leptos#1108]
Hello,

I have made a few attempts to cause a redirect that is supported by hydration.

Initially, I ran the following:

* web-sys location-API
```rust
let window = web_sys::window().expect("Failed to access the window object.");

    // Redirect to the /login page
    if let Some(location) = window.location() {
        let _ = location.set_href("/login");
    }
```
This causes a hard-reload which bypasses hydration.

* web-sys History-api
```rust
    if let Ok(window) = window() {
        if let Ok(location) = window.location() {
            if let Ok(history) = window.history() {
                let _ = history.push_state_with_url(&JsValue::NULL, "", Some("/login"));
            } else {
                location.set_href(url).expect("Failed to change URL");
            }
        }
    }
```
This causes a change in the URL without actually changing the contents of the page or causing a redirect.

* leptos router BrowserIntegration
```rust
let navigation_init = BrowserIntegration {};
      let navigation = navigation_init.navigate(cx, LocationChange {
               value: "/login",
               replace: true,
               scroll: true,
               state: None,
});
```
From memory, this results in the same changes as those introduced by the History API.

I have also used [leptos_router](https://docs.rs/leptos_router/latest/leptos_router/index.html)::[Redirect](https://docs.rs/leptos_router/latest/leptos_router/fn.Redirect.html#) as well as [leptos_actix](https://docs.rs/leptos_actix/latest/leptos_actix/index.html)::[redirect](https://docs.rs/leptos_actix/latest/leptos_actix/fn.redirect.html#) to no avail.

I couldn't find anything about hydration supported refresh on the [Leptos-Book](https://leptos-rs.github.io/leptos/). 

I'm assuming that the implementation of redirect, should be similar to the implementation of the <A/> component, but the presence of a reactive environment in this case would be the only difference. I had assumed up until now that control of State could be easily managed by passing Scope, but I am no longer sure that this is the case.

Any commentary would be deeply appreciated.

**Comment by gbj** [comment]
I guess I don't understand what you mean by "outside the reactive environment," as you seem to have access to a `Scope` in your `BrowserIntegration` example.

Are you looking for something like [`use_navigate`](https://docs.rs/leptos_router/latest/leptos_router/fn.use_navigate.html). See an example of its use [in the `router` example](https://github.com/leptos-rs/leptos/blob/475566837efcb3b5b4f95337a4f9a1415c4008f5/examples/router/src/lib.rs#L195-L206) in this repo.

**Comment by MinaMatta98** [comment]
Cheers,

I will move these questions to discord moving forward.

I have tried use_navigate and it has unfortunately not worked. 
**I am trying to redirect from an on:submit callback fn.**

**Comment by gbj** [comment]
`use_navigate` is the correct way to do what you're trying to do, I think, but I don't see it in your original post. Could you share some of what you tried, and what didn't work about it?

**Comment by MinaMatta98** [comment]
Ok,

After submitting the form, using the following portion of the callback:

```rust
                success_signal_value.set(view!{cx,
                    <div>
                        <Suspense fallback=move || view!{cx, 
                            <svg class="animate-spin h-5 w-5 mr-3" viewBox="0 0 24 24"/>
                        }>
                        <div class="flex justify-center">
                        { move || signup.value().get().map(|val| {
                        loading_indicator_setter.set("hidden");
                        view!{cx, <p class="text-center mx-2">
                            { match val {
                                    Ok(FormValidation::Success {random_string}) => { 
                                    use_navigate(cx)("/validate", NavigateOptions{
                                        replace: true,
                                        resolve: true,
                                        scroll: true,
                                        state: State(None)
                                    }).unwrap(); <------ // THIS IS THE REDIRECTION SIGNAL//
                                    "Successful Signup"
                                },
                                     Ok(FormValidation::Error) => "Ensure that all input criteria has been met",
                                     Ok(FormValidation::EmailPresent) => {
                                        image_setter.set("cross.png");
                                        "Email is already registered on the server"
                                    },
                                     Ok(FormValidation::PhonePresent) => {
                                        image_setter.set("cross.png");
                                        "Phone number is already in use"
                                    },
                                     Err(e) => {
                                        log!("{e:?}");
                                        image_setter.set("cross.png");
                                        "Server Error has occured. Please try again later"
                                    }
                            }}
                            </p>
                        <img src=image style="width: 16px"></img>
                        }})}
                    </div>
                    </Suspense>
                    </div>
                });
```


I have noted where I call redirection within that code block. Note that it's actually called while setting the value of a signal, which I am sure was not the original intention of WriteSignals. 

What happens is that the url will change: http://localhost:8000/ -> http://localhost:8000/validate...but there will be no difference in rendering. After doing a hard reload, the change will appear.

This is the routing configuration. Note that I use <A/> tags to move from "/" to "/login" just fine, however I `use_navigate` does not seem to trigger the same effect:
```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context(cx);

    view! {
        cx,

        // injects a stylesheet into the document <head>
        // id=leptos means cargo-leptos will hot-reload this stylesheet
        <Stylesheet id="leptos" href="/pkg/zing.css"/>

        // sets the document title
        <Title text="ZING!"/>

        // content for this welcome page
        <Router>
            <main>
                <Routes>
                    <Route path="/" view=|cx| view! { cx, <HomePage toggle=AppState::Signup/> } ssr = SsrMode::Async/>
                    <Route path="/login" view=|cx| view! { cx, <HomePage toggle=AppState::Login/> } ssr = SsrMode::Async/>
                    <Route path="/validate" view=|cx| view! { cx, <HomePage toggle=AppState::Validate/> } ssr = SsrMode::Async/>
                </Routes>
            </main>
        </Router>
    }
}
```

**Comment by gbj** [comment]
So if I understand correctly, you're setting a signal to hold a view, which includes a `<Suspense/>` that doesn't read from any resources, and either sets another signal (`image_setter`) or navigates while rendering? 

Do you get any errors etc. in the browser console?

**Comment by MinaMatta98** [comment]
Hello,

No, the suspense tag is directly rendering the server action attached to the signup binding:

```rust
        let signup = create_server_action::<crate::server_function::SignUp>(cx);
        signup.dispatch(crate::server_function::SignUp { form: sign_up_schema } );
```

Based on this, and the fact that "Successful Signup" renders, I take that <Suspense/> is being used correctly.

**Comment by MinaMatta98** [comment]
Just to demonstrate that the signal is working:

![image](https://github.com/leptos-rs/leptos/assets/81748812/488af8b0-72f1-4f7f-abf9-3de375f5c442)

Note that the error cases also render where necessary. So the signal is being correctly updated, and the redirection IS occurring, but is only changing the browser url without actually causing a render.

**Comment by gbj** [comment]
If you can share either a minimal reproduction or you're actual code, I'd be very happy to take a look and see if I can figure out what's going on.

**Comment by MinaMatta98** [comment]
Hello,

Were you looking for something like this, or a full version?

https://pastebin.com/JBS7w55C

**Comment by gbj** [comment]
Well, right off the bat: it looks like you're wrapping every component in a `<Router>`, which is really not how this works. [As its docs say](https://docs.rs/leptos_router/latest/leptos_router/fn.Router.html), `<Router>` should be used once, near the root of your application. When you add all those additional `<Router>`s you're basically overriding the root router context.

Otherwise, what you pasted in doesn't compile, but hopefully that's enough to fix your issue.

I'd recommend looking at some of the examples in this repository, or the docs, if you haven't already, to understand how to use the router.

**Comment by MinaMatta98** [comment]
Ahh,

Awesome. I'll give that a go. It actually makes perfect sense. I didn't know that the context was overwritten.

Just  a heads up, using <Router/> multiple times does compile.

Thanks for your help. This may actually fix quite a few problems I was having.

**Comment by MinaMatta98** [comment]
Fixed!

**Comment by gbj** [comment]
Awesome, glad to hear it!
