### ISSUE TITLE
Resource output will not correspond to the input if first request arrives after second request

### ISSUE THREAD

**Issue by prscoelho** [leptos-rs/leptos#1124]
Resource output will not correspond to the input if first request arrives after second request, here's a small example:

```rust
#[server(Foo, "/api")]
async fn server_foo(with_delay: bool) -> Result<bool, ServerFnError> {
    use tokio::time::{sleep, Duration};

    if with_delay {
        sleep(Duration::from_secs(5)).await;
    }

    Ok(with_delay)
}

async fn fetch_server_foo(with_delay: Option<bool>) -> Option<bool> {
    if let Some(with_delay) = with_delay {
        server_foo(with_delay).await.ok()
    } else {
        None
    }
}

#[component]
fn HomePage(cx: Scope) -> impl IntoView {
    let (with_delay, set_with_delay) = create_signal(cx, None);
    let resource = create_resource(cx, with_delay, fetch_server_foo);

    let on_click_with_delay = move |_| {
        set_with_delay(Some(true));
    };

    let on_click_without_delay = move |_| {
        set_with_delay(Some(false));
    };

    view! { cx,
        <button on:click=on_click_with_delay>"With delay"</button>
        <button on:click=on_click_without_delay>"Without delay"</button>
        { move || with_delay().map(|delay| if delay {
            view! { cx, <p>"Input has delay"</p> }
        } else {
            view! { cx, <p>"Input has no delay"</p> }
        }) }
        <Suspense fallback=move || view!{ cx, <p>"Loading.."</p> }>
        { move || resource.read(cx).flatten().map(|delay| if delay {
            view! { cx, <p>"Output had delay"</p> }
            } else {
                view! { cx, <p>"Output had no delay"</p> }
            }) }
        </Suspense>
    }
}
```

You can also run it at [this repo](https://github.com/prscoelho/server-fn-delay)

Reproducing: click with delay, then click without delay.

Expected: it should show loading until you click on without delay, and it should show "Input has no delay", "Output had no delay". 
Result: it shows loading until the slowest (outdated) resource finishes, and it shows "Input has no delay", "Output had delay".

**Comment by gbj** [comment]
Basically I think all we need is to have an internal version counter that increments every time the fetcher fires, and that (when the fetcher resolves) checks version that version number is still correct. If the resource’s version number is now higher than the one that’s expected, do nothing

We can’t generically cancel in flight futures with wasm-bindgen-futures so this is the closest we can get, at least ensuring that the value is not stale
