### ISSUE TITLE
Optimized images ala NextJS

### ISSUE THREAD

**Issue by SleeplessOne1917** [leptos-rs/leptos#1139]
**Is your feature request related to a problem? Please describe.**
I think an optimized image tag like that used by [NextJS](https://nextjs.org/docs/pages/building-your-application/optimizing/images) would be a good addition to leptos.

**Describe the solution you'd like**
I'd like there to be a component that fulfills the same role as NextJS optimized image components.

**Describe alternatives you've considered**
n/a

**Additional context**
I'm willing to open a PR for this one.

**Comment by gbj** [comment]
Would definitely welcome a PR. I've never used NextJS but this seems like a useful addition. It seems to me it would involve some kind of macro, though, rather than only a component, as it involves compile-time image processing?

**Comment by SleeplessOne1917** [comment]
I'm not entirely sure if it will need a macro or not. I don't think the image processing is at compile time though.

**Comment by Megajin** [comment]
In my humble opinion, I would highly recommend exploring the Gatsby image optimization feature, as it extensively utilizes the powerful library known as sharp. This library has already implemented a Rust version, which can be found at https://github.com/image-rs/image. By leveraging Gatsby's image optimization capabilities, you can significantly improve the performance and efficiency of your website's images.

It is important to note that the optimization process can vary depending on whether you are creating a static site or a server-side rendered (SSR) site. Gatsby's runtime optimization plays a crucial role in achieving optimal results. By carefully considering the specific requirements and characteristics of your project, you can effectively leverage Gatsby's features to achieve the best possible performance for your website.

**Comment by SleeplessOne1917** [comment]
Thanks for making me aware of that. I have no experience with gatsby, but I am familiar with sharp.

**Comment by gbj** [comment]
I'm going to close this in favor of https://github.com/nicoburniske/leptos_image which does more or less exactly what this asks for! If there are other enhancements to this kind of functionality that you'd like to see, I'd suggest working on them in that library.

**Comment by SleeplessOne1917** [comment]
Looks like someone picked up slack lol.
