### ISSUE TITLE
rustdoc support for server functions

### ISSUE THREAD

**Issue by PlGGS** [leptos-rs/leptos#1163]
**Is your feature request related to a problem? Please describe.**
Running `cargo doc` on a Leptos project doesn't generate documentation for server functions to any degree

**Describe the solution you'd like**
I'd like for the server functions to generate documentation from outer doc comments like this:
![image](https://github.com/leptos-rs/leptos/assets/20197872/d6783cff-aac5-4457-bb40-c2071574ed19)

**Describe alternatives you've considered**
I'm considering switching to mdBook, but I haven't tried it yet because my project is due in less than 24 hours and rustdoc is good enough for now even without server function docs

**Additional context**
<img width="665" alt="image" src="https://github.com/leptos-rs/leptos/assets/20197872/c654c95a-16d8-4739-a233-124a14bc687f">
<img width="962" alt="image" src="https://github.com/leptos-rs/leptos/assets/20197872/07059b67-d9aa-4053-a4da-664da8227550">

**Comment by gbj** [comment]
Thanks for pointing it out; this was fairly quick for me to add. Could you test against #1164 and let me know if that works well?

**Comment by PlGGS** [comment]
That worked! Thank you! Glad it was a quick addition
