### ISSUE TITLE
<!-- <EachItem> -->` leftovers from dynamic iteration <For /> (debug mode only)

### ISSUE THREAD

**Issue by jsprog** [leptos-rs/leptos#1168]
**Describe the bug**

When rendering  `Vec<T>` dynamically with `<For />`, each element is wrapped between `<!-- <EachItem> -->` and `<!-- </EachItem> -->` (of course, debug mode). The problem is that the upper HTML comment may not get removed with the removal of its related item.

**Leptos Dependencies**

No other dependencies. leptos@0.3.0 isn't affected and I could confirm this issue with both "abf90358fa60de0334077da5f38fc3cff0494916" and "8096d7c416d6321380a0ce0276d3a64df4d1d0bf"
```toml
leptos = { git = "https://github.com/leptos-rs/leptos", rev = "abf90358fa60de0334077da5f38fc3cff0494916" }   # affected
# leptos = { git = "https://github.com/leptos-rs/leptos", rev = "8096d7c416d6321380a0ce0276d3a64df4d1d0bf" } # affected
# leptos = "0.3.0" # not affected
```

**To Reproduce**

The code below contains 6 different views. Make sure to un-comment `let view = .....` line by line to test with different possibilities.

```rust
use leptos::*;

fn main() {
    leptos::mount_to_body(move |cx| {
        view! { cx, <App /> }
    })
}

#[component]
fn App(cx: Scope) -> impl IntoView {
    let (count, set_count) = create_signal(cx, 0);
    let (items, set_items) = create_signal(cx, Vec::<(usize, View)>::new());

    // push a new view every 4-seconds
    set_interval(move || {
        set_count.update(|c| *c += 1);

        set_items.update(move |items| {
            let key = count.get_untracked();

            // test-1 (issue): string literal
            let view_literal = view! { cx, "text node"};

            // test-2 (issue): string slice
            let view_str = view! { cx, {"string slice"} };

            // test-3 (issue): owned string
            let view_string = view! { cx, {"owned-string".to_owned()}};

            // test-4 (issue): direct content (not wrapped in quotes)
            //   - leptos@0.3.0 won't allow this, and not sure it it's a bug from recent updates.
            let view_direct_content = view! { cx, direct_content};

            // test-5 (issue): the same issue with Fragment containing multiple elements
            let view_fragment = view! { cx, 
                <div>"line-1"</div>
                <div>"line-2"</div>
            };

            // test-6 (no-issue):wrapping content in `HTMLElement` is not a problem
            let view_single_element = view! { cx,
                <div>
                    "wrapped in a single element"
                    <div>"line - 1"</div>
                    <div>"line - 2"</div>
                </div>
            };

            // un-comment to select a view for testing
            let view = view_literal.into_view(cx);        // test-1 (affected)
            // let view = view_str.into_view(cx);            // test-2 (affected)
            // let view = view_string.into_view(cx);         // test-3 (affected)
            // let view = view_direct_content.into_view(cx); // test-4 (won't compile with leptos@0.3.0)
            // let view = view_fragment.into_view(cx);       // test-5 (affected)
            // let view = view_single_element.into_view(cx); // test-6 (not-affected)

            // push view to list
            items.push((key, view));

            // remove the pushed view, after 2-second timeout
            set_timeout(move || {
                log!("key: {}", key);
                set_items.update(move |items| {
                    items.remove(0);
                });
            }, std::time::Duration::from_secs(2));
        });

    }, std::time::Duration::from_secs(4));


    view! { cx,
        <h3>"issue with dynamic rendering <For />"</h3>

        <div class="views">
            <For
                each=items
                key=|item| { item.0 }
                view=move |_cx, (_, view)| view 
                // view=move |_cx, (_, view)| view! { cx, {view}} // replacing the above line with this won't stop the issue
            />
        </div>
    }
}
```

**Expected behavior**

Full removal of the upper comment after removing its related item from list.

**Screenshots**

![issue - EachItem - doc-comment - cleanup](https://github.com/leptos-rs/leptos/assets/3159108/26b67ac1-8b47-4246-8e4e-6814df7b4180)

**Additional context**
- Linux
- rustc 1.72.0-nightly (1c53407e8 2023-05-28)
- this issue is affecting debug mode; `trunk build` is affected but not `trunk build --release`

**Comment by gbj** [comment]
Thanks. This should be resolved now.

**Comment by jsprog** [comment]
Again, This issue is affecting version 0.4.5

**Comment by luxalpa** [comment]
This is an issue again in 0.5.4. Minimal repro:

```rs
use leptos::*;

#[component]
pub fn App() -> impl IntoView {
    let count = RwSignal::new(0);
    let items = RwSignal::new(Vec::<usize>::new());

    let add = move || {
        count.update(|c| *c += 1);

        items.update(move |items| {
            let key = count.get_untracked();

            items.push(key);
        });
    };

    let remove = move || {
        items.update(move |items| {
            _ = items.remove(0);
        });
    };

    create_effect(move |_| {
        add();
        add();
        add();
        add();
        remove();
        remove();
        remove();
    });

    view! {
        <h3>"issue with dynamic rendering <For />"</h3>

        <div class="views">
            <For
                each=items
                key=|item| { *item }
                children=move |_| view! { "nothing" }
            />
        </div>
    }
}
```

**Comment by duncanawoods** [comment]
@gbj Can you reopen this please?

If you use `For` to implement a virtual scroller, you get +10,000s of these comment nodes added just by a bit of scrolling.

This turns into a fatal issue for Chrome and Tauri (probably all webkit browsers) if the container is contenteditable. With just ~2,000 excess comment nodes, the view will become unresponsive. Firefox appears to tolerate comment nodes a little better.

Here is a minimal repro instead of a full virtual scroller. Each click replaces the content of the `For`. After about a 20 redraws, reaching 2000 nodes, subsequent redraws start to take 10s of seconds in Chrome.

- OS: Ubuntu 22.04
- Leptos: 0.6.12
- Chrome:  125.0.6422.141
- Tauri: beta 2

``` rust
#[derive(Debug, Clone, PartialEq)]
pub struct VirtualItem {
    pub index: usize,
    pub data: String,
}

#[component]
pub fn DemoEditor() -> impl IntoView {
    let need_redraw = create_rw_signal(0);

    let list = create_memo(move |_| {
        (0..100)
            .map(|i| VirtualItem {
                index: i + 100 * need_redraw.get(),
                data: format!("This is item {}\n", i + 100 * need_redraw.get()),
            })
            .collect::<Vec<VirtualItem>>()
    });

    view! {
        <main>
            <button 
                on:click={move |_| need_redraw.update(|f| *f += 1)} 
                style="background: red; color: white">Redraw</button>            
            <div 
                contentEditable 
                style="background: black; color: white; font-family: monospace;">                
                <For
                    each=move || list.get()
                    key=|item| item.index
                    let:item >
                    <div id=item.index>
                        <span >{item.data}</span>
                    </div>
                </For>
            </div>
        </main>
    }
}
```
And a utility function to count the DOM nodes:

``` javascript
function countDOMNodes(node = document.body) {
    let count = 1; // Start with one to count the current node
    node.childNodes.forEach(child => {
        count += countDOMNodes(child); // Recursively count children
    });
    return count;
}
```

With `trunk server --release` I do not see the problem with leaking comments but I still see two empty comment nodes for each item. Are they intentional? Given comment nodes are not "free" and have a performance impact, can they be removed too?

``` html
<!---->
<!---->
<div id="2"><span>This is item 2</span></div>
<!---->
<!---->
```

**Comment by gbj** [comment]
@duncanawoods I'm happy to reopen it, with these caveats:
1. It's not something I will have time to work on in the near future
2. In the case of the example you give above, there's no point in using `<For/>` rather than plain iteration: every row is rerendered on every redraw, because the keys are always new (It may be different in your actual example, if you are reusing keys)
3. I just tested this against the `leptos_0.7` branch and it is steady at exactly 308 DOM nodes total, no matter how many redraws (with 0 total comment nodes)

If you want to work on hunting down the debug-mode leaking comments, that's fine by me, but I think my time is better spent getting 0.7 into an alpha and beta state and then to release, as it is doing much better here by all measures! (including removing the excess comments you note)

**Comment by duncanawoods** [comment]
1. 
2. In a real implementation of a virtual scroller, there is overlap in the items for scroll increments smaller than the view. This is just a minimal repro of the problem without the distraction of scroll events, element sizing and such which requires a half a dozen more signals.
3. Sounds promising!

> If you want to work on hunting down the debug-mode leaking comments, that's fine by me

I've had a quick look and can see a likely problem. The code to remove the comment looks like it is excluded by a `not(debug_assertions)` conditional compilation:

https://github.com/leptos-rs/leptos/blob/b22f3bb3bdae9a7253751100f743af5509c1512a/leptos_dom/src/components/each.rs#L413-L435

I've tried some printf debugging using `trunk serve` but with all the generic params in this function, I can't even turn state into strings lol.

**Comment by gbj** [comment]
I think this one is no longer relevant in 0.7.
