### ISSUE TITLE
.focus() can not be called on custom elements having a tabindex

### ISSUE THREAD

**Issue by lpotthast** [leptos-rs/leptos#1215]
When using a custom element with the `tabindex` property set, like in
```rust
let node_ref: NodeRef<Custom> = create_node_ref(cx);
view! {cx,
    <my-elem tabindex=0 node_ref=node_ref>
}
```
i would expect, as the rendered element in the page is focussable by tabbing to it, that the element can also be focused programatically by calling `.focus()` on the underlying `web_sys::HtmlElement` retrievable through `node_ref`.
It can be called by transforming the node ref using `into_any` which can than deref into `web_sys::HtmlElement`.

But that call fails with the JS error `Uncaught TypeError: focus is not a function`...

Is my expectation appropriate? In that case, could leptos be configure to support the focus function in such cases?
Or should that case be avoided entirely?

**Comment by gbj** [comment]
I don't know anything about implementing focus on custom elements, but from what you've written, I'm not sure this has much to do with Leptos. It sounds like it is correctly attempting to call the `.focus()` method on an element, and the browser is responding with a JavaScript `TypeError` that `focus is not a function` on that element. 

I guess it's worth double-checking that the element you get from `.into_any()` is the correct one, but otherwise, it sounds like everything is fine from the framework's end, and the error is coming from somewhere between the custom element and the browser.

**Comment by lpotthast** [comment]
Hmm, i though, without looking at the code, that there would be some registration going on for custom elements.
Like seen in https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements.
I honestly do not have any experience with them..

I tried to double-check it by performing a `document.getElementById(...).focus()` directly in the browser and got the same error.

ChatGpt also responded with something similar:
> Custom Element Definition: Verify that the custom element is correctly defined and registered. The custom element's definition should include the necessary attributes, properties, and methods to support the focus() method. Make sure the custom element's JavaScript class or prototype extends or inherits from a focusable element like <input> or <button>.

For anybody looking, a **workaround** would be to just wrap the custom elment in a div and put the tabindex as well as any focus-logic on the div.

As an example..
```rust
<div
            node_ref=wrapper
            class="wrapper"
            tabindex=0
            on:blur=move |_| set_focused.set(false)
            on:focus=move |_| set_focused.set(true)
>
    <my-elem />
</div>
```

**Comment by lpotthast** [comment]
I was talking about Leptos. There were no libraries involved. You are right, this seems to be on the browser side and leptos can not do anything about the initial problem. There was also a misunderstanding on my end, sorry for bringing up the topic.

To recap:

Anyone can write `view! { <foo> "..." </foo> }`, which will render a non-standard, and therefore **custom**, element on the page.

There are only two types of custom elements:
- Autonomous Custom Elements, like `<foo></foo>` and
- Customized Built-In Elements, like `<div is=foo></div> (where `foo` was registered before)

From the linked article:
> (standalone) Autonomous custom elements — **they don't inherit from standard HTML elements**. You use these on a page by literally writing them out as an HTML element. For example <popup-info>, or document.createElement("popup-info").

Only the latter option must be registered (like `customElements.define("word-count", WordCount, { extends: "p" });`) using the `customElements` object. But they can only be used with the aforementioned `is=...` syntax, which I didn't use and don't anticipate to use.

So. When the `view!` macro sees something like `<foo></foo>`, it cannot and should not register anything using any browser api.

The "[Autonomous Custom Elements] **don't inherit from standard HTML elements**" phrase probably explains why the `focus` method was not present. I do not currently see a way to make that appear, as it seems that autonomous custom elements are just not supposed to extend any native element.

So this problem is certainly not something that Leptos can help with.
@gbj Thanks for your feedback, pushed me in the right direction. Feel free to close this issue.

**Comment by gbj** [comment]
Ah, okay, I see the source of the confusion.

Yes, Leptos is perfectly capable of consuming custom elements.

However, it does not do anything to define undefined custom elements for you. 

Typically, using a custom element means you are importing a library (yours or someone else's) that defines that custom element.

I do actually have [a crate](https://github.com/gbj/custom-elements) to make it easier to define your own custom elements from Rust. It maps pretty closely onto the Web Components API, which you linked to.

"Web Components" are of course, in this sense, a framework-agnostic alternative to "framework components," so if you're just trying to add some reusable custom behavior then an ordinary Leptos component may be all you need.
