### ISSUE TITLE
Could you add a variant of "create_resource" that only reacts to the last triggered response in case of concurrent reqeusts

### ISSUE THREAD

**Issue by indrekluuk** [leptos-rs/leptos#1236]
I am following the Leptos book and currenlty the example in the "Transition" chapter has a race condition.
https://leptos-rs.github.io/leptos/async/12_transition.html

To make it more apparent I changed the "important_api_call" method to this:
```
async fn important_api_call(id: usize) -> String {
    match id {
        0 => {
            TimeoutFuture::new(5_000).await;
            "Alice"
        },
        1 => {
            TimeoutFuture::new(1_000).await;
            "Bob"
        },
        2 => {
            TimeoutFuture::new(1_000).await;
            "Carol"
        },
        _ => {
            TimeoutFuture::new(1_000).await;
            "User not found"
        },
    }
        .to_string()
}
```

1. Klick on "Tab A" -> it starts loading.
2. Now immediatelly clik on "Tab B" -> Afer one second it stops loading and "Bob" is displayed.
3. When the five seconds of the click on "Tab A" is up then "Bob" will be replaced with "Alice".

In this use-case all the previous requests should be discarded no matter how long it takes for the response.
It doesn't make sense that "Alice" is displayed in the end if the last click was on "Tab B".

I am sure there are use-cases for the current behaviour of "create_resource", but this problem can be resolved if Leptos had a separate method (like "create_single_concurrent_load_resource") that discards all previous concurrent requests if new request is made.

**Comment by gbj** [comment]
Unless I'm mistaken, this is the same as #1124 and was handled in #1165. Does that look right to you?

(The sandboxes typically use the latest released version and there has not been a release since this was changed, so I'm not disputing the behavior in the example you created, just saying that what you're asking for has already been done, I think.)

**Comment by indrekluuk** [comment]
Yes, it seems like it might be the same issue. Thank you!

Is there a possibility to get nightly Leptos from crates.io or should I wait for the next release to test it myself on my computer?

I will close the issue since it probably is the same thing.

**Comment by gbj** [comment]
The way to use Git dependencies with Cargo is like this:
```toml
leptos = { git = "https://github.com/leptos-rs/leptos" }
leptos_router = { git = "https://github.com/leptos-rs/leptos" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos" }
```
etc.

**Comment by indrekluuk** [comment]
Thaks! I just tried it out and now it works exactly as expected.
