### ISSUE TITLE
On latest `main`, debug/release discrepancy when removing all items for a <For />

### ISSUE THREAD

**Issue by nguiard** [leptos-rs/leptos#1258]
**Describe the bug**

*As I know your latest commits already fixed problems with the reactive system (thanks!), I think it's useful to say that I'm on the latest commit on `main` at the time of writing.* 

When displaying a Vec with a few elements in a <For />, and then emptying the Vec:
- in dev/debug mode: leptos correctly empties the list in the DOM
- in release mode: all elements except the first are cleared (the first element remains displayed in the DOM) - this is despite the fact that if I log the contents of the Vec in the `each` attribute of <For />, the log correctly shows an empty Vec.

**Minimal example**

Try this component:

```rust
#[component]
fn BuggyFor(cx: Scope) -> impl IntoView {
    let elements = create_rw_signal(cx, vec![0, 1]);

    view! {
        cx,
        <section>
            <ul>
                <For
                    each=elements
                    key=|x| x.clone()
                    view=|cx, x| view! { cx, <li>{ format!("Element {}", x) }</li> }
                />
            </ul>
            <button
                on:click=move |_| elements.set(vec![])
            >
                "Clear list"
            </button>
        </section>
    }
}
```

**Comment by gbj** [comment]
I can't reproduce that behavior with the example you've given or with similar "clear all items" examples in our test bench, both in release mode.

https://github.com/leptos-rs/leptos/assets/286622/ae4090e8-babd-47cd-88e1-679bee07b693

**Comment by nguiard** [comment]
Oh... Sorry for the misreport then, I suppose something else in my code is interacting with that... 

The bigger context is I have a "server-streaming" resource fetched over `grpc-web`, and I am at the same time trying to do optimistic UI updates, and also having the server render the resource on first load... I found a "solution" for that is quite messy and involves : 

1) an `auto_todos` signal initialized as None, that will hold the updates from the server
2) a `todos` resource that:
  * on the server, fetches the current todos and is used in a <Transition> later
  * on the client, just returns `auto_todos` 
  (this resource is just to get the server to render the initial state as streaming... I might be better trying to load the resource and `render_with_context`...)
3) an effect that spawns a long running async block that receives the updates from the server, and on a successful received update, runs:
```rust
auto_todos.set(Some(updated_todolist));
todos.refetch();
``` 
4) a `todos_view` signal that will is reset to the resource contents (by 5) )when the resource is updated, but that can hold temporary optimistic UI changes
5) an isomorphic effect that resets `todos_view` to the `todos` resource contents whenever the latter is updated  
```rust
    create_isomorphic_effect(
        cx, 
        move |_| {
            todos_view.set(
                todos.read(cx)
                    .map(|todolist| todolist.iter().map(|todo| ReactiveTodo::from_todo(cx, todo.clone())).collect())
            );
        }
    );
```

(Yeah I know all this looks convoluted... There might be a better solution. I figured `create_signal_from_stream` didn't fit my needs because it returns None on the server, and I also need an async block to setup the stream... but maybe I'm wrong and there's a much nicer solution)

So I suppose the the discrepancy between debug and release mode I'm seeing is related to something in this mess... Oh and I thought that my "minimal component" was maybe wrapped in a `<Transition>` with the other stuff, and maybe that was why I see a problem. But no, it's actually *not* inside a `<Transition>`. When I put it alone on a page, the problem disappears, but when it's together with the `todos` page I'm trying to build, even outside the <Transition> block, the minimal component is buggy. When I get the time I'll try to pinpoint the problem. Maybe you have ideas?

But also maybe my approach is way too messy?...

**Comment by nguiard** [comment]
To clarify, if I strip out the optimistic UI layer code (the `todos_view` signal and the related effect) and just render the resource, everything seems to work fine.

**Comment by nguiard** [comment]
So... I've had a bit of time to try and make a full minimal reproduction. Rather than reducing components in my app, I started by just following the "Getting started" simple CSR setup in the book. And I rapidly get the bug in release mode actually! Doesn't seem to have anything to do with my convoluted app setup.

I'll try to put the precise steps:
1. did a `rustup update`
2. cleared build cache (I use `sccache`)
3. followed exact steps in "Getting Started"
4. verified everything builds correctly
5. modified `main.rs` to be:
```rust
use leptos::*;

fn main() {
    mount_to_body(|cx| view! { cx,  <BuggyFor /> })
}

#[component]
fn BuggyFor(cx: Scope) -> impl IntoView {
    let elements = create_rw_signal(cx, vec![0, 1]);

    view! { cx,
        <For
            each=elements
            key=|el| el.clone()
            view=|cx, el| view! { cx, <p>{ el }</p> }
        />
        <button on:click=move |_| elements.set(vec![])>"Clear"</button>
    }
}
```
6. tried `trunk serve`. The button clears the full list
7. tried `trunk serve --release`. The button clears the "1" but leaves the "0" in the list

I tried this in Chrome and Firefox, same results. Tried building on two separate machines, same results. If you can't reproduce this, we may have a difference in setup somewhere that we need to pinpoint...

More info:

- `Cargo.toml`:
```toml
[package]
name = "leptos-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.4.1", features = ["csr", "nightly"] }
```

- `index.html`:
```html
<!DOCTYPE html>
<html>
  <head></head>
  <body></body>
</html>
```

- rustc version: `rustc 1.72.0-nightly (6162f6f12 2023-07-01)`
- trunk version: `0.17.1`
- OS - tried on:
  * Debian 11 (bullseye)
  * Ubuntu 22.04

I can give you additional info if needed

**Comment by gbj** [comment]
Sweet, this latest example helped me reproduce it and showed me the problem — it's specifically 
1. clearing a list
2. in release mode
3. when `<For/>` has a previous sibling (in your case, it's actually the `<script>` tag that Trunk injects for its live-reloading feature! I reproduced with a button etc. Same is true if you move the button before the `<For/>`, etc.)

**Comment by nguiard** [comment]
Great! Works perfect, thanks a lot for the fix :)
