### ISSUE TITLE
Deeply nested routes have an exponential impact on compile times

### ISSUE THREAD

**Issue by cottandr** [leptos-rs/leptos#1283]
**Describe the bug**
When nesting routes like so:
```
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    view! {
        cx, 
        <Router>
            <Routes>
                <Route path = "foo" view = Outlet>
                <Route path = "foo" view = Outlet>
                <Route path = "foo" view = Outlet>
- snip -
                    <Route path = "" view = move |cx| view! { cx, "Hi" }/>
- snip -
                </Route>
                </Route>
                </Route>
            </Routes>
        </Router>
    }
}
```

Compile times increase exponentially when adding more layers. Building a sample app with 3 layers of "wrapper" routes, the crate build time for the app is 2 seconds on my Ryzen 3600. It take 2 seconds again at 4 layers. However, at 5 layers it increases to 4 seconds. 6 layers takes 10 seconds, and 7 layers takes 40 seconds. This also affects cargo check, which causes slowdown in rust-analyser.

In leptos 0.3.1, the same 7 layer sample app builds in 0.93s. 

I ran into this issue working on an actual app with 4 layers of wrapper routes, but more complex leaf route views - I am seeing 30 second cargo build / check on 0.4, where I was seeing ~1 second on 0.3.

**Leptos Dependencies**

```toml
leptos = { version = "0.4.1", features = ["csr"] }
leptos_router = { version = "0.4.1", features = ["csr"] }
```

**To Reproduce**
1. Create a new binary crate with leptos and leptos router
2. Add the following code to main.rs:
```rust
use leptos::*;
use leptos_router::*;

#[component]
pub fn App(cx: Scope) -> impl IntoView {
    let outlet = move |cx| view!{ cx, <Outlet/> };

    view! {
        cx, 
        <Router>
            <Routes>
                <Route path = "foo" view = outlet>
                <Route path = "foo" view = outlet>
                <Route path = "foo" view = outlet>
                <Route path = "foo" view = outlet>
                <Route path = "foo" view = outlet>
                <Route path = "foo" view = outlet>
                    <Route path = "" view = move |cx| view! { cx, "Hi" }/>
                </Route>
                </Route>
                </Route>
                </Route>
                </Route>
                </Route>
            </Routes>
        </Router>
    }
}

fn main() {
    mount_to_body(|cx| view! {cx, <App/>})
}
```
3. Run ```cargo build --timings```
4. Observe the crate compile time for the app is longer than expected
5. Add another ```<Route>``` layer
6. Run ```cargo build --timings```
7. Observe the crate compile time for the app doubles or more
8. Switch the leptos dependencies to 0.3.1
9. Observe the crate compile time returns to normal

**Expected behavior**
App compile time does not grow exponentially when deeply nesting routes.

**Comment by gbj** [comment]
Yikes. I'll take a look. Any help narrowing this down to a particular commit or to some point between 0.3.0 and 0.4.0 would be very much appreciated.

**Comment by cottandr** [comment]
I did a quick manual bisect, and it seem to have been introduced here: https://github.com/leptos-rs/leptos/commit/17adf7cc1467aa1ddd41ffa16fcd3c438068bb98

**Comment by gbj** [comment]
Thanks so much, that's very helpful. That certainly makes sense as it is making some significant change to the way the compiler thinks about components.

**Comment by gbj** [comment]
I spent a little time exploring this, this afternoon. Interestingly, it looks like it doesn't affect release mode, at least not in anything close to an exponential way; i.e., going from 10 to 20 deep brought me from 5s to 10s compile time in release mode.

Otherwise, everything in that commit is just sort of a changing around how our trait magic works and adding some trait implementations. So it's hard for me to figure out how to address the compile-time issue.

**Comment by cottandr** [comment]
After some testing, I've identified a workaround. Moving the deepest routes into a closure that gets called resolves the compile time issue:

```
    let routes = move || view! {
        cx, 
        <Route path = "foo" view = outlet>
        <Route path = "foo" view = outlet>
        <Route path = "foo" view = outlet>
        <Route path = "foo" view = outlet>
        <Route path = "foo" view = outlet>
        <Route path = "foo" view = outlet>
            <Route path = "" view = move |cx| view! { cx, "Hi" }/>
        </Route>
        </Route>
        </Route>
        </Route>
        </Route>
        </Route>
    };

    let routes = move || view! {
        cx, 
        <Route path = "foo" view = outlet>
        <Route path = "foo" view = outlet>
        <Route path = "foo" view = outlet>
        <Route path = "foo" view = outlet>
        <Route path = "foo" view = outlet>
        <Route path = "foo" view = outlet>
            {routes()}
        </Route>
        </Route>
        </Route>
        </Route>
        </Route>
        </Route>
    };

    view! {
        cx, 
        <Router>
            <Routes>
                [routes]
            </Routes>
        </Router>
    }
```

I tried not calling the closure, which compiled, but panicked - presumably the routes must be defined once and can't be updated dynamically. 

Interestingly, inlining the function (i.e. nesting the view macro) still causes long compile times.

**Comment by lpotthast** [comment]
This is also discussed here: https://discord.com/channels/1031524867910148188/1135202584672608277
