### ISSUE TITLE
Rename Leptos config options to kebab-case via serde, instead of replacing characters

### ISSUE THREAD

**Issue by filipdutescu** [leptos-rs/leptos#1295]
**Is your feature request related to a problem? Please describe.**

My app is using a bigger config file, which contains a member of the `leptos::LeptosOptions` type. The config is serialized as a `.toml`, which adheres to the `kebab-case` naming convention. Since `leptos::LeptosOptions` does not use `#[serde(rename_all = "kebab-case")]`, if I want to deserialize it, I would need to specify all Leptos options I set under the snake_case.

**Describe the solution you'd like**

Add `#[serde(rename_all = "kebab-case")]` to the `leptos::LeptosOptions` struct. This can be easily done by modifying the [this line](https://github.com/leptos-rs/leptos/blob/main/leptos_config/src/lib.rs#L25).

```rust
// ...
#[derive(TypedBuilder, Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct LeptosOptions {
// ...
```

This would also lead to not needing to [replace '-' characters in the *entire* config file](https://github.com/leptos-rs/leptos/blob/main/leptos_config/src/lib.rs#L180).

**Describe alternatives you've considered**

Duplicating the Leptos config options in a struct I own, using the rename method and implementing `From<T>` to allow conversion to `leptos::LeptosOptions`. This seems however a bit meaningless, since Leptos *already* uses kebab-case, just not in a manner in which it could satisfy my use case. 

**Additional context**

Example of my `config.toml`:

```toml
log-level = "Debug"
application-address = "0.0.0.0:3000"

# ...

[leptos]
output-name = "my-awesome-app"
# ...
```

My `config.rs`:

```rust
#[derive(Deserialize)]
#[serde(rename_all = "kebab-case")]
pub(crate) struct Config {
    #[serde(default = "default_application_address")]
    pub application_address: String,

    #[serde(
        default = "default_log_level",
        deserialize_with = "deserialize_log_level"
    )]
    pub log_level: Level,

    pub leptos: LeptosOptions,
}
```

**Comment by filipdutescu** [comment]
Yes, I'd love to contribute! Should I have any concerns in mind while implementing this? Ie do any tests, other areas of serialization depend on the current behaviour?

**Comment by gbj** [comment]
If you run it against a couple of the `examples` directory or templates (say, `examples/todo_app_sqlite` and the [`start-axum-workspace`](https://github.com/leptos-rs/start-axum-workspace) template) with `cargo-leptos build` and it builds, it should be fine. But I'll make sure to do some testing on my end too.
