### ISSUE TITLE
<For /> is inconsistent when values are inserted out of order

### ISSUE THREAD

**Issue by Schwartzmorn** [leptos-rs/leptos#1297]
**Describe the bug**
`<For />` seems to be buggy when fed with a signal where values are inserted out of order.

The code below inserts a few strings in a vector everytime "Add values" is clicked, keeping the vector in alphabetical order and the values unique, but the displayed result does not correspond to the value of the vector.

**Leptos Dependencies**
```toml
leptos = { version = "0.4.1", features = ["csr"] }
console_error_panic_hook = "0.1.7"
```

**To Reproduce**
Using rust nightly and a basic index.html. Here is the whole main.rs file, served with trunk:
```Rust
use leptos::*;

static VALUES: [&str; 26] = ["AA", "BB", "CC", "DD", "EE", "FF", "GG", "HH", "II", "JJ", "KK", "LL", "MM", "NN", "OO", "PP", "QQ", "RR", "SS", "TT", "UU", "VV", "WW", "XX", "YY", "ZZ"];

fn add_values(
  values_: RwSignal<Vec<String>>,
  new_values: Vec<String>
) {
  let mut all_values = std::collections::BTreeSet::<String>::new();
  values_.with(|current_values| { current_values.iter().for_each(|value| { all_values.insert(value.to_owned()); } ) });
  new_values.iter().for_each(|value| { all_values.insert(value.to_owned()); } );
  values_.set(all_values.iter().map(|value| value.to_owned()).collect());
  log!("{:?}", values_.get());
}

#[component]
pub fn ValuesList(cx: Scope) -> impl IntoView {
  let values_ = create_rw_signal(cx, Vec::new());

  let mut i = 17;

  let feed_values = move |_| {
    let mut values = Vec::new();
    for _ in 0..3 {
      let index = i % VALUES.len();
      values.push(VALUES.get(index).unwrap().to_string());
      i = i.wrapping_mul(i); // to generate vaguely random numbers
    }

    add_values(values_, values);
  };

  view! { cx,
    <button on:click=feed_values>"Add values"</button>
    <span>"["</span>
    <For
      each=move || values_.get()
      key=|value| value.to_owned()
      view=move |cx, value| {
        view! { cx,
          <span>"\""{value}"\", "</span>
        }
      }
    />
    <span>"]"</span>
  }
}

fn main() {
    mount_to_body(|cx| view! { cx, <ValuesList/> })
}
```

**Expected behavior**
The signal values_ eventually takes the value `["BB", "DD", "FF", "HH", "JJ", "LL", "NN", "PP", "RR", "TT", "VV", "XX", "ZZ"]` as seen in the browser console, so I would expect the page to display that but the page displays `["DD", "FF", "JJ", "HH", "RR", "XX", "NN", "VV", ]` instead.

**Additional context**
Note: I tried the same code with leptos 0.3 (the version in the playground currently linked in the README.md) and it works as expected, so it seems to be a regression.

```toml
leptos = "0.3"
console_error_panic_hook = "0.1.7"
```

**Comment by gbj** [comment]
This is fixed by #1296.
