### ISSUE TITLE
`<input name="host">` breaks event delegation

### ISSUE THREAD

**Issue by serbanrobu** [leptos-rs/leptos#1331]
**Describe the bug**
If you have a form with an input named _host_ and submit, the event listener for the _onsubmit_ event is executed repeatedly.

**Leptos Dependencies**
```toml
leptos = "0.4.2"
```

**To Reproduce**
1. Go to https://codesandbox.io/p/sandbox/prod-dew-9tmdjw?file=%2Fsrc%2Fmain.rs%3A17%2C38
2. Open the console
3. Click on the **Submit** button
4. See the message `submit` printed repeatedly

**Expected behavior**
The message `submit` printed only once

**Comment by gbj** [comment]
#1332 should have fixed this. Thanks!
