### ISSUE TITLE
Server functions redirect returns html, instead of data.

### ISSUE THREAD

**Issue by alexichepura** [leptos-rs/leptos#1358]
**Describe the bug**
Redirect from server function leads to html being in response instead of data.
For example:
```rs
leptos_axum::redirect(cx, "/");
Ok(())
```
I found that it's NOT axum/actix specific. But could not identify exact cause.

**Leptos Dependencies**
main and 4.x same

**To Reproduce**
easiest is 
1 `cd examples/session_auth_axum`
2 open network panel -> persist logs, login, see it returns html instead of null, even though return is Ok(())
3 optional is to look value(), it has error `Some(Err(Deserialization("expected value at line 1 column 1")))`
```rs
let login = create_server_action::<Login>(cx);
...
create_effect(cx, move |_| {
    log!("{:?}", login.value().get());
});
```

**Expected behavior**
instead of html, data should be returned

**Screenshots**
![Leptos redirect returns html](https://github.com/leptos-rs/leptos/assets/5582266/9749bef1-509a-4cc7-a18c-e6221fdc6470)

**Comment by gbj** [comment]
**The Response**
The behavior you're describing is not actually HTML being returned in the response from the server.

In the case of the screenshot, this is Firefox's choice of how to represent the response when it redirects.

Note that this is how Chrome chooses to represent the same response.
<img width="433" alt="Screenshot 2023-07-16 at 3 39 33 PM" src="https://github.com/leptos-rs/leptos/assets/286622/7836ac48-971e-4d76-a511-fa20f4c4ae2c">

You can see that the response actually contains the data by making the request via curl instead: it correctly returns `null` as the body of the response.

**The Parsing of the Response**
As far as I know, though, the browser simply *won't* return the body of the response here, if it's redirected. I've tried a variety of different configurations and get either a) the HTML (with the default redirect mode) or b) an empty text body (with `"redirect": "manual"`). I'm not sure if there's a way around this, but would love to fix it if it's possible!

Do you have any idea if there's a way to get the body of a fetch response in the browser when the response includes a redirect like this?

**Comment by alexichepura** [comment]
Oh, very true.
So I went to read latest standard. HTTP Semantics RFC 9110  (15.4.  Redirection 3xx) https://datatracker.ietf.org/doc/rfc9110/

`The server SHOULD generate a [Location](https://www.rfc-editor.org/rfc/rfc9110#field.location) header field in the response containing a URI reference for the different URI. The user agent MAY use the Location field value for automatic redirection. The server's response content usually contains a short hypertext note with a hyperlink to the different URI(s).`

It says response usually have HTML although older standart states that for 302 `the entity of the response SHOULD contain a short hypertext note with a hyperlink to the new URI(s).`
https://datatracker.ietf.org/doc/html/rfc2616#section-10.3.3

And whole internet says body is not processed for redirects.

Another thing is why to have get request and SSR it and hydrate again after redirect.
So now I think it's need to disable redirect if js enabled (SPA mode). And to do so I add hidden input inside effect.
Then using this skip_redirect field, I return normal 200 with user data instead of redirect, then redirect on client.
Note, this works for disabled js, because it will return 302 in that case.
Maybe this will be helpful to someone:
<https://github.com/alexichepura/lapa/blob/main/admin/src/auth/auth_login.rs>
```rs
#[component]
pub fn Login(cx: Scope, children: Children) -> impl IntoView {
    let login = create_server_action::<Login>(cx);
    let pending = login.pending();
    let value = login.value();
    let user_signal = use_user_signal(cx);

    let (is_skip_redirect, set_skip_redirect) = create_signal(cx, false);
    create_effect(cx, move |_| {
        request_animation_frame(move || {
            set_skip_redirect(true);
        });
    });
    let skip_redirect_view = move || match is_skip_redirect() {
        true => view! { cx, <input type="hidden" name="skip_redirect" value="1"/> }.into_view(cx),
        false => ().into_view(cx),
    };
    create_effect(cx, move |_| {
        if let Some(v) = value() {
            let login_result = v.map_err(|_| AuthError::ServerError).flatten();
            if let Ok(login_result) = login_result {
                user_signal.set(Some(login_result));
                let navigate = use_navigate(cx);
                navigate(&"/", Default::default()).expect("home route");
            }
        }
    });

    view! { cx,
        <fieldset disabled=move || pending() class="login-card">
            <legend>"Log in"</legend>
            <ActionForm action=login>
                {skip_redirect_view}
                <Input name="username" label="User"/>
                <Input name="password" label="Password" type_="password"/>
                <Checkbox name="remember" label="Remember me?"/>
                <FormFooter action=login/>
                <hr/>
                <div>{children(cx)}</div>
            </ActionForm>
        </fieldset>
    }
}
```
Server part:
```rs
if skip_redirect.is_none() {
    leptos_axum::redirect(cx, "/");
}
Ok(User {
    id: user.id,
    username: user.username,
})
```

**Comment by gbj** [comment]
You know, that's a very smart way to handle this! That way you get the benefit of the redirect from the server without JS/WASM, and the benefit of having access to the returned data if you do have JS/WASM. Very cool.
