### ISSUE TITLE
Unquoted text nodes broken in SSR

### ISSUE THREAD

**Issue by sebadob** [leptos-rs/leptos#1384]
**Describe the bug**
Based on the `start-axum` template with SSR, the basic `<details>` element is not rendered correctly during SSR.
You can only see the icon from the `<summary>` component but not text, neither in summary nor in details.
When you add a `<Router>` to the mix and switch route on the client side, the content is rendered. But even when rendered after client side routing, when you inspect the HTML code, you see no text inside the components even though they are being shown.

**Leptos Dependencies**
Latest leptos `0.4.5` with the `start-axum` example.

**To Reproduce**
copy & paste the following code into the `app.rs` from the `start-axum` leptos example:

```rust
use leptos::*;
use leptos_router::*;
use crate::error_template::{AppError, ErrorTemplate};

#[component]
pub fn App(cx: Scope) -> impl IntoView {
    view! { cx,
        <Router fallback=|cx| {
            let mut outside_errors = Errors::default();
            outside_errors.insert_with_default_key(AppError::NotFound);
            view! { cx, <ErrorTemplate outside_errors/> }.into_view(cx)
        }>
            <nav>
                <A href="">A</A>
                <A href="/b">B</A>
            </nav>

            <main>
                <Routes>
                    <Route
                        path=""
                        view=|cx| view! { cx,
                            <details>
                                <summary>Details A</summary>
                                Something small enough to escape casual notice.
                            </details>
                        }
                    />
                    <Route
                        path="/b"
                        view=|cx| view! { cx,
                            <details>
                                <summary>Details B</summary>
                                Something small enough to escape casual notice.
                            </details>
                        }
                    />
                </Routes>
            </main>
        </Router>
    }
}
```

When you then run `cargo leptos serve` you will only see the `<details>` icon but no text. As soon as you switch routes on the client side, you see the content rendered correctly, even though it does not seem to show up in the HTML code when you inspect it.

**Expected behavior**
See the content rendered correctly before the hydration happens.

**Screenshots**
The html elements do exist, but they have no content:

![Bildschirmfoto vom 2023-07-19 12-40-12](https://github.com/leptos-rs/leptos/assets/62848396/3e1b79fc-a73d-46cb-a794-4e2c0e77f37d)

**Comment by gbj** [comment]
Perhaps better titled "Unquoted text nodes broken in SSR," as I notice the following:
1. Works fine if you quote the text nodes
2. Also broken with a much simpler
```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    view! { cx,
        <p>Unquoted text nodes broken?</p>
    }
}
```

**Comment by sebadob** [comment]
Ouh, sorry, my bad. Yes of course I should have added the quotes.

**Comment by gbj** [comment]
No worries! And it's a good catch, this is supposed to work.
