### ISSUE TITLE
lint error: incorrect_clone_impl_on_copy_type

### ISSUE THREAD

**Issue by agilarity** [leptos-rs/leptos#1401]
**Describe the bug**

Clippy [error: incorrect_clone_impl_on_copy_type](https://rust-lang.github.io/rust-clippy/master/index.html#/incorrect_clone_impl_on_copy_type)

**Leptos Dependencies**

N/A

**To Reproduce**
1. Remove the occurences of `#![allow(clippy::incorrect_clone_impl_on_copy_type)]`
2. Run `cargo make lint` from leptos root directory

**Expected behavior**
Should not see the `incorrect_clone_impl_on_copy_type` lint error.

**Screenshots**
N/A

**Additional context**
Deferred from (#1379)

**Comment by gbj** [comment]
When I remove `#![allow(clippy::incorrect_clone_impl_on_copy_type)]` and run `cargo make lint` I don't get an error. I may be doing something wrong.

**Comment by agilarity** [comment]
I will take a look at it shortly.

**Comment by agilarity** [comment]
I merged the latest changes and verified that removing the `allow` lines from the following files raised errors.

- leptos_dom/src/lib.rs
- leptos_reactive/src/lib.rs
- leptos_server/src/lib.rs

**Comment by sebadob** [comment]
I just saw that same error when I fixed some pipeline errors for a PR.
It occurred when I executed `cargo make --profile=github-actions ci` locally to check this step. My cargo is on stable by default. As soon as I added the `+nightly` the error was gone.

`cargo make --profile=github-actions ci` throws this error

`cargo +nightly make --profile=github-actions ci` does not throw it

**Comment by agilarity** [comment]
@gbj Were you able to reproduce the issue?

**Comment by gbj** [comment]
I actually now get a warning that it's an unknown lint, which makes sense as it's quite a recent addition. I'm sure if I update by a bit I'll see it.
