### ISSUE TITLE
SSR + axum + >0.4.5: panic - `ExtractorHelper` apparently does not exist in the context

### ISSUE THREAD

**Issue by sebadob** [leptos-rs/leptos#1426]
**Describe the bug**
SSR + axum + `--release` build produces a panic:

```
thread '<unnamed>' panicked at 'should have had ExtractorHelper provided by the leptos_axum integration', /mnt/dev-data/work/git/projects/leptos/integrations/axum/src/lib.rs:1369:10
```

This does not happen with a debug build.

When I pin all leptos versions to `=0.4.4` is does not appear and everything is fine, but as soon as I switch to 0.4.5, it panics and only with `--release` flag. This happens on the current `main` branch too.

I already found out, that it has nothing to do with the new `nonce` feature I am using. I am still trying to nail it down further which action exactly causes this. This is a bit tedious and time consuming though since it only happens with a release build.

As soon as I hopefully find out more about the cause, I will add a comment here.

**Leptos Dependencies**

SSR + `start-axum` example + leptos >0.4.5

**To Reproduce**
I am still trying to find the cause of this, which is not too easy.

If i remember correctly, there was a memory leak issue with axum, right? Seems like it could have something to do with the fix.

**Comment by gbj** [comment]
Is there any chance it's the same as #1397?

**Comment by sebadob** [comment]
Could be. I nailed it down to a section where it happens in my testing project, but I am stil trying to reproduce it in a minimal example currently.

What I am doing on this scenario is a manual `.set` for a `create_resource` when the component is running on the server to actually get initial values out of an `additional_context`.
As soon as I am commenting out these lines, the panic does not happen again.

**Comment by sebadob** [comment]
Okay, I managed to reproduce it, actually in 2 different versions:

1. The "good" thing is, it happens in debug mode too. I just did not see it before, because of a lot of debug logs and axum just restarted the worker silently
2. The root cause might be the same as in #1397 but I don't know enough about the deep internals of leptos yet to be sure
3. It has definitely something to do with `leptos_axum::extract`

The base for this example is the `start-axum`, just paste the following content into the `app.rs`:

```rust
use leptos::*;

#[server(AccessServer, "/api")]
pub async fn access_server(cx: Scope) -> Result<String, ServerFnError> {
    let _headers = leptos_axum::extract(
        cx,
        |headers: axum::headers::HeaderMap| async move { headers },
    )
    .await
    .map_err(|err| ServerFnError::ServerError(format!("extraction error: {:?}", err)))?;

    Ok("Hi from Server".to_string())
}

// create panic version 1
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    let res = create_resource(
        cx,
        || (),
        move |_| async move { access_server(cx).await.expect("access_server") },
    );

    // if we do the manual `.set` here AND extract the headers in `access_server` -> panic
    // if we do not extract the headers and just `.set` -> fine
    // if we extract only the headers and don't do the `.set` here -> fine
    res.set("Manual Hi".to_string());

    view! { cx,
        <h1>"We don't even need to access the result to get the panic"</h1>
    }
}

// // create panic version 2
// #[component]
// pub fn App(cx: Scope) -> impl IntoView {
//     let res = create_resource_with_initial_value(
//         cx,
//         || (),
//         move |_| async move { access_server(cx).await.expect("access_server") },
//         // if we just create the resource with an initial value other than None, the same
//         // as above applies: if Som(..) + extractor in the server fn -> panic
//         Some("Manual Hi".to_string()),
//         // None,
//     );
//
//     view! { cx,
//         <h1>"We don't even need to access the result to get the panic"</h1>
//     }
// }

```

I stumbled about this issue while creating an i18n component which absolutely needs the initial translations before the very first render on the server for a good SEO, so that the values do not end up in the `<template>` section in the browser, but actually in the `<body>` directly.

**Comment by sebadob** [comment]
Yes that's what I do.

The result of the resource will alter on be used during client side rendering / routing, because then the translations will be fetched async. The same happens when I use `create_resource_with_initial_value`. The result is the same, I just have it wrapped in an `if on_server() { }` block to make it better readable in my code.

This example is really stripped down. In the project where I found the error, the translations are inserted into the `additional_context` in a custom handler for the leptos routes. This means instead of setting a default value, I can retrieve it from the context directly as long as I am on the server while still using OutOfOrder streaming, which gives me exactly the result I want.

I did some experiments with `create_blocking_resource` too, but then I have the values in the `<template>` again and not in the body, which means that not a single translation would work without Javascript / WASM on the client side.

I will take a look at `SsrMode::PartiallyBlocked` too. If I can specify the "i18n <Transition>" to block and all other's to resolve out of order like before, this might work too.

**Comment by sebadob** [comment]
Oh, yeah, maybe I was just a little bit too dumb and made my life harder than it needed to be.

When I switch to `create_blocking_resource` + `render_app_to_stream_with_context_and_replace_blocks` as you suggested, it is giving me the same result without panicking.

The panic does still appear when you just use `create_resource_with_initial_value` which gives the same result, but this is now working in my case. Thank you a lot!

**Comment by gbj** [comment]
Yeah makes sense to me. If it's all right with you, I'll close the issue. I think it falls under the annoying category of "you're holding it wrong" leading to an unclear result, rather than a bug per se. Although I'd be very open to a suggestion of how to document this kind of thing better, if you have any thoughts.

**Comment by sebadob** [comment]
Yes sure we can close it then.

But shouldn't the `create_resource_with_initial_value` not panic in that case? Basically my second example in the code above.  Just out-comment the first `<App>` and use the second one. That should throw the same panic.
I cleary was a bit stupid, which is why I created this issue, but when I am using `create_resource_with_initial_value` I would not expect it to panic if I am accessing a server fn which has a custom extractor.

How to document this a bit better is a really good question. I guess at some point we could add a section to the docs with "typical use cases or tasks", or something like that. But on the other hand it kind of falls into the section "hydration bugs" and it could maybe be mentioned there (if it not already is and I just missed it).

**Comment by sebadob** [comment]
I just tested it with the `0.5.0-alpha` and I was unable to reproduce the problem with this version.  
I would say we can close this issue.

**Comment by gbj** [comment]
Oh, excellent. I love finding all the little unexpected bugs this fixed.
