### ISSUE TITLE
`Suspense` duplicates entries in release mode 

### ISSUE THREAD

**Issue by rambip** [leptos-rs/leptos#1456]
**Describe the bug**
The same code that displays an element using a `Suspense` works differently on `debug` mode and on `release`.
- On debug, one gets the expected behavior (the item is displayed when the Future ends)
- On release, the entries are duplicated

**Leptos Dependencies**

```toml
leptos = {version="0.4.6", features=["csr", "nightly"]}
```

**To Reproduce**

1. create an empty leptos project with the dependencies above
2. Create an empty `index.html`
3. Add this to `main.rs`:

```rust
use leptos::*;


async fn greet_name(name: String) -> String {
    format!("hi {} !\n", name)
}

#[component]
fn App(cx: Scope) -> impl IntoView {
    let names = vec!["alice".to_string(), 
                     "bob".to_string(), 
                     "charlie".to_string()
    ];
    let (name, set_name) = create_signal(cx, "alice".to_string());

    let response = create_resource(
        cx,
        name,
        greet_name
    );

    let make_button = |name: String| 
        view!(cx,
            <button on:click={let name=name.clone(); move |_| set_name(name.clone())}>
                {name}
            </button>
        )
    ;

    let buttons =
        names
        .into_iter()
        .map(make_button)
        .collect_view(cx);

    view!{cx,
        <ul>
            {buttons}
        </ul>
        <Suspense fallback=move || "please wait">
            {move || response.read(cx)}
        </Suspense>
    }
}

fn main() {
    mount_to_body(|cx| view!{cx, <App/>})
}
```

4. Build in debug mode (`trunk serve`)
5. Click on button `alice`, then `bob`. The page displays `hi bob !`

6. Build in release mode (`trunk serve --release`)
7. Click on button `alice` then `bob`. The page displays `hi alice ! hi bob !`

**Expected behavior**
In release mode, the code should behave the same as in debug mode: one single entry after each click

**Comment by rambip** [comment]
It may be linked to https://github.com/leptos-rs/leptos/issues/1223

**Comment by gbj** [comment]
This turned out to be a much more interesting issue than usual, and in fact surfaced a bug that had not been revealed in the 6 months or so since this rendering! So, thanks. I think the PR should fix this nicely.

**Comment by rambip** [comment]
I'm glad to have found this bug !
And thank's for fixing this so quickly !
