### ISSUE TITLE
`view!` macro should support struct fields as its first argument

### ISSUE THREAD

**Issue by rambip** [leptos-rs/leptos#1466]
**Is your feature request related to a problem? Please describe.**
I have a module in my code to render some abstract syntax tree.
To make it more readable and more concise, I created a struct with all the options and context I needed:
```rust
struct RenderContext {
    option1: bool,
    option2: bool,
    callback: ...,
    cx: Scope
}
```

And every function in this module take a reference to `RenderContext`.
So inside one of the functions I used 
```rust
fn render_stuff(context: &RenderContext) -> impl IntoView {
    view!{context.cx,
       <div> </div>
    }
}
```

But here, I got a compile error from the proc-macro: `context.cx` is not allowed !

**Describe the solution you'd like**
It would be nice that the token stream before the comma (here `context.cx`) could be an arbitrary rust expression, or at least include dots if it's a record of a struct.

**Describe alternatives you've considered**
In this case, I wrote
```rust
cx = context.cx
view!{cx, ...}
```

It does just add one line of code, but for future-proofing that would be nice to support what I described

PS: I wasn't sure if I should issue this as a bus or as a feature request.

**Comment by gbj** [comment]
The future proofing is kind of irrelevant here, because `cx,` here is going away in the next release, which is already in alpha. 

I'm not planning to change this behavior but if you want it and want to make a PR so it's available between now and the time of the 0.5 release I'd take it.
