### ISSUE TITLE
<For /> component panics when inserting an item

### ISSUE THREAD

**Issue by brofrain** [leptos-rs/leptos#1473]
**Describe the bug**
Hello,

I was working on a simple grid with numbers and buttons to add / remove / shuffle them. 
It seems that adding a few items at random indexes to vector powering `<For />` component causes a panic and the list stops updating. The number of items needed to trigger the bug is variable - sometimes even the first addition is enough.

**Leptos Dependencies**

```toml
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.2.10", features = ["js"] }
leptos = { version = "0.5.0-alpha2", features = ["csr", "nightly"] }
rand = "0.8.5"
```

Simple application reproducing the bug:

```rust
use leptos::*;
use rand::{thread_rng, Rng};

fn main() {
    std::panic::set_hook(Box::new(console_error_panic_hook::hook));
    leptos::mount_to_body(|| view! { <App/> })
}

#[component]
fn App() -> impl IntoView {
    let mut total_item_count = 4;

    let items = create_rw_signal((1..=total_item_count).collect::<Vec<usize>>());

    let mut rng = thread_rng();

    let add_in_random_place = move |_| {
        items.update(|items| {
            let i = rng.gen_range(0..items.len());
            total_item_count += 1;
            let v = total_item_count;
            items.insert(i, v);
        });
    };

    view! {
        <div>
            <div> {items} </div>
            <button on:click=add_in_random_place>"Add"</button>
            <For
                each=items
                key=|v| *v
                view=move |v| {
                    view! { <div>{v}</div> }
                }
            />

        </div>
    }
}
```

**To Reproduce**
1. Run the app with `trunk serve`
2. Keep clicking the button until an error appears in console.

The problem applies only to `<For ... />` - the `<div> {items} </div>` part continues to work. Commenting out the `<For ... />` makes the app not to throw any errors.

**Expected behavior**
The list generated by `<For />` components is being updated by changes to `items` and no panics are printed in console.

**Screenshots**
![image](https://github.com/leptos-rs/leptos/assets/57999434/9c83467e-a683-4e4c-b738-52d5953e92a1)

**Additional context**
I'm almost certain that there were no duplicate values in `items` and keys were always unique.
Adding multiple items always at the same position (e.g. always at 0) does not trigger the problem. Removing elements from the vector or shuffling them works perfectly fine.

**Comment by gbj** [comment]
Thanks. Looks like I missed pulling in a couple of the `<For/>` fixes from main; if you try this example on 0.4.6 you'll notice it works fine. I've fixed it in the latest commit to the `effect-cleanups` branch that's driving 0.5
