### ISSUE TITLE
XSS protection in SSR

### ISSUE THREAD

**Issue by Bechma** [leptos-rs/leptos#1475]
**Is your feature request related to a problem? Please describe.**
When a component is rendered in the server and it has some kind of javascript injection value like `<script>alert('tag')</script>`, the alert is executed when fetching the page from the server, but it doesn't execute if you do a client side navigation.

**Describe the solution you'd like**
When a component is processed in the server, we should have some kind of feature that allow us to protect from XSS attacks.

**Describe alternatives you've considered**
Taking care of the user input should be always treated with cautious, but I think this kind of protection should be taken into consideration in the framework as the first line of deffense.

**Comment by gbj** [comment]
The `nonce` feature in Leptos and the server integrations can serve this purpose very well. Enabling it and using the appropriate meta tag sets a Content Security Policy (CSP) that will require a server-generated `nonce` to evaluate any inline `<script>` or `<style>` element. This should prevent most XSS attacks as far as I'm aware.

```
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    provide_meta_context(cx);

    view! { cx,
        <p>"Test"</p>
        <Meta
            http_equiv="Content-Security-Policy"
            content=move || {
                use_nonce(cx)
                    .map(|nonce| {
                        format!(
                            "default-src 'self'; script-src 'strict-dynamic' 'nonce-{nonce}' \
                            'wasm-unsafe-eval'; style-src 'nonce-{nonce}';"
                        )
                    })
                    .unwrap_or_default()
            }
        />
        // manually insert nonce during SSR on inline script 
        <script nonce=use_nonce(cx)>"console.log('Hello, world!');"</script>
        // leptos_meta <Style/> and <Script/> automatically insert the nonce
        <Style>"body { color: blue; }"</Style>
    }
}
```

**Comment by Bechma** [comment]
Let me modify your example just a bit to make my point:

```rust
// this is not exported automatically with use leptos::*;
use leptos::nonce::use_nonce;
use leptos::*;
use leptos_meta::*;

#[component]
pub fn App(cx: Scope) -> impl IntoView {
    provide_meta_context(cx);
    let xss = create_rw_signal(cx, "<script>alert('xss')</script>");

    view! { cx,
        <p>"Test"</p>
        <Meta
            http_equiv="Content-Security-Policy"
            content=move || {
                use_nonce(cx)
                    .map(|nonce| {
                        format!(
                            "default-src 'self'; script-src 'strict-dynamic' 'nonce-{nonce}' \
                            'wasm-unsafe-eval'; style-src 'nonce-{nonce}';"
                        )
                    })
                    .unwrap_or_default()
            }
        />
        // manually insert nonce during SSR on inline script
        <script nonce=use_nonce(cx)>"console.log('Hello, world!');"</script>
        // This produces an xss
        <p>{move || xss.get()}</p>
        // This doesn't produce it
        <p>{xss.get_untracked()}</p>
        // leptos_meta <Style/> and <Script/> automatically insert the nonce
        <Style>"body { color: blue; }"</Style>
    }
}
```

This is tested in leptos 0.4.6
It will produce one alert in the screen with the text 'xss'. Which it's not intended unless you want to force unsafe behaviour(or force an `into_view` maybe). However, when it's not a dyn element, it doesn't produce it(as expected).

**Comment by gbj** [comment]
Just for the sake of clarity, I think there are two things going on here:
1) In 0.4.6, with the `nonce` feature enabled on `leptos` **and** on `leptos_actix` (or `leptos_axum`), this does not alert anything. Please double-check that the `nonce` feature is enabled on both crates and, if so, this is definitely a bug with the `nonce` feature. So this feature seems to me to be working as intended and preventing the execution: with `nonce` enabled, Chrome gives me the console error
```
localhost/:433 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'nonce-...' 'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('...'), or a nonce ('nonce-...') is required to enable inline execution.
```

2) Separately, one of the two text nodes is not being escaped as it already should have been. See PR #1478.

Either one of the two prevents the behavior in your example, so — thanks for bringing this up!

**Comment by Bechma** [comment]
Got it, my problem was that I didn't have the feature enabled. Why is then available if it requires the feature to work?
