### ISSUE TITLE
A terminal backend like dioxus

### ISSUE THREAD

**Issue by dev-ardi** [leptos-rs/leptos#1487]
Does the current architecture allow for a different backend? like dioxus-tui

**Comment by gbj** [comment]
@jquesada2016 has done some exploration in this area (see [`leptos-tui`](https://github.com/jquesada2016/leptos-tui) There's not much overlap between the DOM and a TUI so it's mostly using Leptos reactivity to drive a TUI.

**Comment by stappersg** [comment]
_terminal backend_ triggered me to post https://github.com/pwnwriter/rustycli
which I discovered at https://www.reddit.com/r/rust/comments/15a2c7q/access_the_rust_playground_right_in_terminal/
