### ISSUE TITLE
Using signals (tracked) in `on_cleanup` callback causes warnings/errors

### ISSUE THREAD

**Issue by tqwewe** [leptos-rs/leptos#1494]
**Describe the bug**
In some cases (I could only reproduce the issue within a resource & transition), when using on_cleanup and trying to access a signal with `.get()` or calling it as a function, a warning is shown in the console about incorrect usage of the signal.

The solution is to use `.get_untracked()`, though there are a few issues with it currently:

1. The warning in the console doesn't point to the right place in the file.
   I couldn't replicate this in this repo, but in my real project it was simply pointing to the line that the signal was defined in which led me down a rabbit hole of confusion I only solved days later when trying to reproduce the issue in a new repo.

2. It would be nice if Leptos could understand that we're in a cleanup context and not show any errors for this.

I'm not sure if this actually causes any errors in the app and the if the warning can be safely ignored or not.
If this is intentional, perhaps the `on_cleanup` docs should mention that `.get_untracked()` should be used for signals. However, it can cause a bad developer experience, in cases where you have a helper function which uses tracked methods, and you want to reuse it for  your `on_cleanup` callback.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.5.0-alpha2", features = ["csr"] }
```

**To Reproduce**
1. Clone https://github.com/tqwewe/leptos-cleanup-issue
2. Run `trunk serve --open`
3. Observe the warning in the browser console after the 1 second delay

**Expected behavior**
`on_cleanup` should be okay with using tracked function calls for signals.

**Comment by tqwewe** [comment]
I also get this error spammed in my real project when I switch from `<For>` to `.into_iter().map().collect_view()`, but I can't reproduce it in the small example I made :/
![image](https://github.com/leptos-rs/leptos/assets/16362377/3a008e79-740a-446a-af69-3491d8558667)

**Comment by gbj** [comment]
Fair enough, easy fix.

Re: the second issue— The only way I can see this happening is some kind of nested `on_cleanup` situation. Looking at the `.borrow_mut()`s here it's hard for me to picture. If you can reproduce it I'd be very happy to look at it and you can open a separate issue.
