### ISSUE TITLE
HTML boolean attributes

### ISSUE THREAD

**Issue by psynt** [leptos-rs/leptos#1502]
**Is your feature request related to a problem? Please describe.**
Some HTML attributes (e.g. `disabled`) are considered true if they are present on an element, and false if they are missing.      
For example,    
`<span disabled> </span>` is disabled,      
`<span disabled="true"> </span>` is still disabled,      
`<span disabled="false"> </span>` is still disabled,      
and only `<span> </span>`, is **not** disabled.      

I can not seem to find a way to make these attributes appear or disappear on elements programatically, e.g. using a conditional

**Describe the solution you'd like**
Something like
```rust
view! {cx, 
    <span disabled:{move || predicate}> </span>
}
```
seems like something that would keep consistency with existing syntax.

**Describe alternatives you've considered**
```rust
view! {cx, 
    <span {move || if predicate { disabled } }> </span>
```
Seems to be less clean syntactically

**Additional context**
N/A

**Comment by gbj** [comment]
You can use boolean attributes with either booleans or Options.

```rust
view! { cx, 
<button disabled=false>"Enabled"</button>
<button disabled=true>"Disabled"</button>
<button disabled={None::<String>}>"Enabled"</button>
<button disabled=Some("disabled")>"Disabled"</button>
<button disabled=move || items.with(Vec::is_empty)>
    "Reactive Boolean"
</button>
<button disabled=move || items().is_empty().then_some("disabled")>
    "Reactive Option"
</button>
}
```

**Comment by psynt** [comment]
Okay, thank you for your help!    
Once again, genius!
