### ISSUE TITLE
Invalid html syntax cause a hydration bug

### ISSUE THREAD

**Issue by dpytaylo** [leptos-rs/leptos#1535]
**Describe the bug**
I encounter a hydration bug when attempting to use invalid HTML syntax like this:
```html
<input 
    type="checkbox" 
    id="menu_button"
    class="hidden"
>
    <span class="sr-only">"Open main menu"</span>
</input>
```

from warning:
![image](https://github.com/leptos-rs/leptos/assets/18236144/ee844e97-f068-4ddd-b5b8-d1d2fb8cefde)
to panic:
![image](https://github.com/leptos-rs/leptos/assets/18236144/b10b7329-52c9-4c02-9803-db7383152d23)

**Leptos Dependencies**
Default start axum workspace depedencies

**To Reproduce**
1. Add a component with invalid html syntax inside the `view!` macro.
2. `cargo leptos watch`
3. Open a browser console

**Expected behavior**
We can add this case in this chapter: https://leptos-rs.github.io/leptos/ssr/24_hydration_bugs.html.
Maybe, we could improve the error message for enhanced clarity, if it is possible.

**Additional context**
I completely understand that it was entirely my mistake, but I believe individuals who aren't familiar with frontend technologies could encounter the same error and have difficulty identifying the issue. 😊

**Comment by gbj** [comment]
We can do a little better than that: the linked PR gives a compile error if you try to put children inside a self-closing tag.

**Comment by dpytaylo** [comment]
> We can do a little better than that: the linked PR gives a compile error if you try to put children inside a self-closing tag.

I think that sounds much better) Thank you
