### ISSUE TITLE
Await local

### ISSUE THREAD

**Issue by gitmalong** [leptos-rs/leptos#1567]
**Is your feature request related to a problem? Please describe.**
There is `create_resource` and `create_local_resource` but there is no `AwaitLocal`. Wouldn't this make sense ?

**Describe the solution you'd like**
`AwaitLocal` that does not require T to be serializable.

https://docs.rs/leptos/latest/leptos/fn.Await.html
https://docs.rs/leptos/latest/leptos/fn.create_local_resource.html

**Comment by gbj** [comment]
This should be trivial to implement as a 
```rust
/// If `true`, this will use `create_local_resource`
#[prop(optional)] local: bool
```
added to `Await`, and then using `create_local_resource` vs. `create_resource` depending on the prop. Would you like to make a PR?
