### ISSUE TITLE
Missing class after navigation

### ISSUE THREAD

**Issue by jsmouret** [leptos-rs/leptos#1592]
Hello,

There is a behavior that is not consistent between the first page load and after hydration.

Starting from a template like:
```bash
cargo leptos new --git leptos-rs/start-axum
```

Adjust the App code to something like:
```rust
#[component]
pub fn Home(cx: Scope) -> impl IntoView {
    view! { cx,
        <div
            class="uppercase"
            class="text-green"
        >
            "Home is green uppercase"
        </div>
    }
}

#[component]
pub fn Other(cx: Scope) -> impl IntoView {
    view! { cx,
        <div
            class="underline"
            class="text-red"
        >
            "Other is red underline"
        </div>
    }
}

#[component]
pub fn App(cx: Scope) -> impl IntoView {
    view! { cx,
        <Router>
            <nav>
                <a href="/">Home</a>
                <a href="other">Other</a>
            </nav>
            <main>
                <Routes>
                    <Route path="" view=Home/>
                    <Route path="other" view=Other/>
                </Routes>
            </main>
        </Router>
    }
}
```

Repro steps:
* Load the page, all fine
```html
<div class="uppercase text-green">Home is green uppercase</div>
```
* Click on Other to navigate, the `underline` class is missing
```html
<div class="text-red">Other is red underline</div>
```
* Refresh the page, all fine again
```
<div class="underline text-red">Other is red underline</div>
```

The workaround is to combine all classes in a single `class=format!("everything {}", and_more)` but that's a bit limiting.

Thank you :)

**Comment by gbj** [comment]
This *should* use the second value you provide in both cases; the inconsistency between the SSR version and the client-rendered version is unfortunate but the client-rendered version which only uses the second of the two values is the correct behavior. This is expected to behave like HTML: providing multiple of the same attribute overrides the previous value.

**Comment by jsmouret** [comment]
Fair enough :)

From the documentation, because we can also write dynamic classes like:
```
<div
   class=("something", true)
   class="other"
/>
```
It felt that multiple `class=` would be combined.

**Comment by gbj** [comment]
The intended form for this is
```
<div
   class:something=true
   class="other"
/>
```
The `class=("something", true)` syntax is solely a workaround for very complicated class names that our view macro parser can't handle properly like `class:some-crazy-tailwind-[var(--something-200)]`

**Comment by jsmouret** [comment]
Alright, thanks for the explanations :)
