### ISSUE TITLE
Support for static site generation (SSG) and incremental static regeneration (ISR)

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#1594]
## Is your feature request related to a problem? Please describe.

Currently, Leptos renders HTML on the server as part of a simple request/response cycle: someone makes an HTTP request for a certain page, Leptos responds by rendering that page on demand. This allows you to flexibly do things like "look this blog post up in a database" or "look up the preferences for the current user, they're logged in."

There are two kinds of pages that do not need on-demand rendering: 
1. Content pages, like a blog post, that are known at build time (which may or may not = compile time, but is a single discrete event; e.g., adding a row to a `posts` table or adding a `.md` file to a directory)
2. Static pages, like an About page, that are known at compile time 

Either of these sorts of pages can be rendered to HTML ahead of time, and served directly on request.
 
Leptos is quite efficient at rendering the second category of static pages. Because of the way that the `view` macro optimizes for server rendering, a large static page that just consists of HTML rendered by the `view` macro is converted, at compile time, into a big string, and this is served in response to a request. Whether it's faster or slower to serve it from a file will probably depend on the server, how deeply nested routes and components are, etc. In any case, it is already very fast.

But for the category of things like "read this Markdown file, convert it to HTML, and then serve it" there's a potential for a significant performance improvement by using static site generation or incremental static regeneration.

## Describe the solution you'd like 

Just to define these terms
- Static site generation (SSG) has a defined "build step" that builds the page for every possible option up front. The cost for any page request is O(1), as it just serves the pre-built HTML file.
- Incremental static regeneration (ISR) lets you build individual pages without needing to build the entire site up front. The cost for page requests amortizes to O(1): there is an initial O(n) rendering of the page the very first time it is requested, but this is cached as an HTML file which is what's served for every subsequent request.

The Leptos `<Route/>` component can, I think, be extended, possibly by extending `SsrMode`, to include `Static` and `Incremental`. `SsrModes` work on a per-route priority system, so in this case any path that contains a (nested or plain) route with `Static` will be statically generated; if there's no `Static`, but there is `Incremental`, it will be incrementally built and cached; then the current behavior.

## Additional requirements

**Path generation** `Static` would require some equivalent to [`getStaticPaths()`](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration), and async function that tells you which paths you need to build.

**Build hooks** At least for `Static`, there probably needs to be some way to indicate "hey, there's some new content, please build," if it's going to be possible to do something like publishing a new blog post without recompiling your server.

**Invalidation** At least for `Incremental`, there probably needs to be some way to indicate "hey, you need to rebuild this page" (e.g., I edited the blog post in the database or edited the file)

## Describe alternatives you've considered

Rather than adding additional complexity to `leptos_router`, building a separate CLI tool that is basically a Leptos-based static site generator.

Rather than adding additional complexity to Leptos core, hoping that this develops in the ecosystem naturally.

Honestly, I have limited experience using any kind of static site builder or similar framework (NextJS, Gatsby, Eleventy, Zola, etc.) so API design is going to be a weak point for me here. Help wanted from anyone who wants to see work on this progress.

**Comment by Pitasi** [comment]
This plays really well with the `islands` feature, since it goes in the same direction of Astro: static by default with opt-in hydration of certain parts of the app, when needed.

I tried to experiment a bit with existing Leptos features, and built a toy version of a fully-static site generator: https://github.com/Pitasi/leptos-ssg. This is similar to the "separate CLI tool" you mentioned in the alternatives.

However, I think that integrating this feature in the router would allow a more wider range of use cases.

**Comment by gbj** [comment]
See also #1649

**Comment by erlend-sh** [comment]
See also SSG in [Perseus](https://framesurge.sh/perseus/en-US/docs/0.4.x/fundamentals/hydration):

- https://framesurge.sh/perseus/en-US/docs/0.4.x/fundamentals/hydration
- https://framesurge.sh/perseus/en-US/docs/0.4.x/fundamentals/static-content

**Comment by gbj** [comment]
At least an initial form of this is accomplished in #1649. It would be helpful to have
1) an example
2) some kind of build hooks
3) some kind of invalidation

**Comment by NiklasEi** [comment]
> This plays really well with the islands feature, since it goes in the same direction of Astro: static by default with opt-in hydration of certain parts of the app, when needed.

Is SSG mode currently supposed to work with the `island` feature? I am getting the error "Uncaught (in promise) TypeError: mod[("_island_" + l)] is not a function".
My code: https://github.com/NiklasEi/test-leptos (my leptos fork only removes the `.static` from generated html files; the error is the same using leptos' `main` branch)

**Comment by floric** [comment]
Hey :) typically, I don't like these "plus-one-comments" for new features. In this case I was looking today exactly for this as SSG would combine both advantages between CSR and SSR. Can you estimate the amount of changes this would require?

Based on my very limited knowledge I would expect a function to collect all static routes based on the router and then call something like the current server side rendering method for each path. If the client side is a big bundle and not split, then the same bundle could be attached each time.

If the changes are more clear, I would be interested to dive deeper into it. For now I can stick to Astro + Solid though.

**Comment by gbj** [comment]
> Hey :) typically, I don't like these "plus-one-comments" for new features. In this case I was looking today exactly for this as SSG would combine both advantages between CSR and SSR. Can you estimate the amount of changes this would require? – @floric 

You can effectively do this now:
- Start with the Actix or Axum template (doesn't matter)
- Do the other setup for using static routes, i.e., add `<StaticRoute/>`s that define the pages you want to build statically and adapt the main.rs. The instructions for this can be found in the 0.5.0 release notes under [Static Site Generation](https://github.com/leptos-rs/leptos/releases/tag/v0.5.0)
- On first server startup, this will actually build all the routes you want it to build, and you can then deploy those files. I think they're located in `target` somewhere at present.

(See @NiklasEi's note above re: removing `.static` from those HTML files, which may be a good idea to just do by default in a future Leptos version.)

The missing pieces are all around things like hooks for when to rebuild those static routes or invalidate them. But if you just want to manually build static routes and deploy them you can do that.

It's not likely that I will develop this feature any further in the near future, as I've kind of been head down on changes leading up to 0.6, which will benefit everyone. I have never used a static site generator so don't have a good sense of needs and patterns. But I'm very open to proposals and contributions.

**Comment by floric** [comment]
> > Hey :) typically, I don't like these "plus-one-comments" for new features. In this case I was looking today exactly for this as SSG would combine both advantages between CSR and SSR. Can you estimate the amount of changes this would require? – @floric
> 
> You can effectively do this now:
> 
>     * Start with the Actix or Axum template (doesn't matter)
> 
>     * Do the other setup for using static routes, i.e., add `<StaticRoute/>`s that define the pages you want to build statically and adapt the main.rs. The instructions for this can be found in the 0.5.0 release notes under [Static Site Generation](https://github.com/leptos-rs/leptos/releases/tag/v0.5.0)
> 
>     * On first server startup, this will actually build all the routes you want it to build, and you can then deploy those files. I think they're located in `target` somewhere at present.
> 
> 
> (See @NiklasEi's note above re: removing `.static` from those HTML files, which may be a good idea to just do by default in a future Leptos version.)
> 
> The missing pieces are all around things like hooks for when to rebuild those static routes or invalidate them. But if you just want to manually build static routes and deploy them you can do that.
> 
> It's not likely that I will develop this feature any further in the near future, as I've kind of been head down on changes leading up to 0.6, which will benefit everyone. I have never used a static site generator so don't have a good sense of needs and patterns. But I'm very open to proposals and contributions.

Oh, I missed the part in the Release Notes. Thanks a lot. I will give it a try.

Regarding usecases for SSG: I noticed in the past, how many websites are completely or nearly static (including only small client side features). It might be surprising, but many small organizations would be fine with this regarding minimal hosting costs, better performance and better SEO.

**Comment by gbj** [comment]
This was completed in #2875 by adding incremental regeneration and integrating static routes fully into the router as an `SsrMode`. See the [`static_routes`](https://github.com/leptos-rs/leptos/tree/main/examples/static_routing) example.
