### ISSUE TITLE
Leptos Router <a href=""> ignores `e.prevent_default()`

### ISSUE THREAD

**Issue by chunleng** [leptos-rs/leptos#1601]
**Describe the bug**

In the following code:

```rust
        <a href="abc">
            <div>
                <button on:click=|e: ev::MouseEvent| {
                    e.prevent_default();
                    log!("A");
                }>"TEST"</button>
            </div>
        </a>
```

When pressing on the button, it should log `A` and not redirect to page `abc` because in the child onclick event, we use `e.prevent_default` to stop the redirect. It works in the default leptos, but however, leptos router did not take into the consideration of `e.prevent_default`

**Leptos Dependencies**

```toml
leptos = { version = "0.4.10", features = ["csr"] }
leptos_router = { version = "0.4.10", features = ["csr"] }
```

**To Reproduce**
1. Use the following code:
```
use leptos::*;
use leptos_router::*;

fn main() {
    mount_to_body(|cx| {
        view! { cx,
            <Router>
                <main>
                    <Routes>
                        <Route path="/" view=TestComponent/>
                    </Routes>
                </main>
            </Router>
        }
    });
}

#[component]
fn TestComponent(cx: Scope) -> impl IntoView {
    view! { cx,
        <a href="abc">
            <div>
                <button on:click=|e: ev::MouseEvent| {
                    e.prevent_default();
                    log!("A");
                }>"TEST"</button>
            </div>
        </a>
    }
}
```
2. Click on the button

**Expected behavior**

`A` is logged but the page is not redirected

**Screenshots**

**Additional context**

**Comment by gbj** [comment]
This has to do with the way that event delegation works by bubbling events up to the window level and handling them there. In your case, using `on:click:undelegated` results in the intended behavior.

For what it's worth, [a `<button>` inside an `<a>` is invalid HTML](https://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5).
