### ISSUE TITLE
Add a compile-time alternative to `get_config`

### ISSUE THREAD

**Issue by jquesada2016** [leptos-rs/leptos#1633]
**Is your feature request related to a problem? Please describe.**
Most use cases would benefit from having a `get_config` at compile-time.

**Describe the solution you'd like**
Add a proc macro to fetch the config at compile-time.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chrisp60** [comment]
I know this is an old issue. But, if you want to close it, this is already available through a somewhat hidden helper in `leptos_config`. The below snippet will embed the cargo toml at compile time and allow it to be parsed as a config while not needing to be present at runtime

```rust
let cargo_toml = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/Cargo.toml"));
let config = leptos::leptos_config::get_config_from_str(cargo_toml).unwrap();
```

or flagged to load from filesystem when developing, and embed the config on `--release` 
```rust
#[cfg(debug_assertions)]
let config = leptos::get_configuration(None).await.unwrap();

#[cfg(not(debug_assertions))]
let config = leptos::leptos_config::get_config_from_str(include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/Cargo.toml"
)))
.unwrap();
```

I believe that would solve your use case @jquesada2016, if you still need it of course

**Comment by rakshith-ravi** [comment]
I think that would work fine. Perhaps we can document this?

**Comment by chrisp60** [comment]
@rakshith-ravi I have a pending #2208 that I may wait to get merged but otherwise I could add some notes onto `LeptosConfig`. It maybe be nice if a `LeptosConfig` could just take a `std::io::Reader` and grab bytes from there. But, this way works and is already in the public API, so maybe its fine as is.
