### ISSUE TITLE
`log`, `warn`, and `error` macros conflict with other logging crates

### ISSUE THREAD

**Issue by jquesada2016** [leptos-rs/leptos#1634]
**Describe the bug**
`log!()`, `warn!()`, and `error!()` both are macro names used by `log` and `tracing` and should be renamed, as these crates are used far more throughout the ecosystem and should therefore have higher priority to our crate-local helper macros.

**Leptos Dependencies**

N/A

**To Reproduce**
1. Create a new `leptos` project
2. Add `tracing` as a dependency
3. Add
    ```rust
    #[macro_use]
    extern crate tracing;
    
    use leptos::*;
    
    fn my_func() {
      warn!("This is an ambiguity error!");
    }
    ```

**Expected behavior**

Not need to disambiguate these logging macros when using them.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by jquesada2016** [comment]
@gbj this a breaking change and is needed before `0.5` releases.

**Comment by gbj** [comment]
Maybe we export ours as a `leptos::logging` module without changing the names of the macros? Then a glob import won't conflict but people only need to add `use leptos::logging::*;` to get the current behavior.

**Comment by jquesada2016** [comment]
That's one thing we could do. Another option is to rename them to be more specific of what they do, which is log to the console. So we can rename `warn!()` to `console_warn!()`, for example.

Whatever you prefer.

**Comment by rakshith-ravi** [comment]
Alternative idea:

We could use [wasm-logger](https://lib.rs/crates/wasm-logger) and just re-export the `log` macros in leptos. That way, they would provide a nice logger out of the box, with support for the `log` crate

**Comment by jquesada2016** [comment]
> Alternative idea:
> 
> We could use [wasm-logger](https://lib.rs/crates/wasm-logger) and just re-export the `log` macros in leptos. That way, they would provide a nice logger out of the box, with support for the `log` crate

That's a good idea! Although we're currently relying more on |tracing| than on |log|.

**Comment by rakshith-ravi** [comment]
Based on the tracing feature flag, we could perhaps export different macros? Log by default, and tracing if the feature is enabled

**Comment by rakshith-ravi** [comment]
Based on the tracing feature flag, we could perhaps export different macros? Log by default, and tracing if the feature is enabled

**Comment by gbj** [comment]
I don't think reexporting the macros from `log` or `tracing` is ideal here, because using them then requires setting up the additional machinery from those crates. At least as I understand it, if I just use `log!` somewhere without registering a logger as well nothing happens. The macros we currently export are dead simple: `log!` is a `println!` in SSR mode or a `console.log(format!())` in the browser, nothing else required.

I think I'll just move them to a `logging` module, which prevents the name conflict but keeps these very simple utilities available without additional overhead.
