### ISSUE TITLE
Add a derive macro for `create_slice()`

### ISSUE THREAD

**Issue by jquesada2016** [leptos-rs/leptos#1635]
**Is your feature request related to a problem? Please describe.**
It's cumbersome to use `create_slice()`.

**Describe the solution you'd like**
Create a derive macro that implements `create_slice()` on each field of a tuple or field struct.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SadraMoh** [comment]
@jquesada2016 

Hi, I hope you are having a good day,

I have been thinking about this for couple of hours now, and have a few questions for you.

Are you referring to the the cumbersome process of having to repeat this snippet of code below everytime one wants to create a new slice into a single field?
```rust
let (count, set_count) = create_slice(
    state,
    |state| state.count,
    |state, n| state.count = n,
);
```
If so, I'm not sure how a `derive macro` is a good solution for this.
The `create_slice` function requires an instance of the state struct, wrapped in a signal (a `RwSignal<T>` as per docs) not the instance itself.
I suppose one could make a generator that would implement the new accessors in a `impl RwSignal<GlobalState>` block, 
Something along the lines of:
```rust
#[derive(MyDerivedMacro, Clone, Debug, Default)]
pub struct GlobalState {
    count: i32,
    name: String,
}

// generated by derive_macro
impl RwSignal<GlobalState> {
    fn count_slice(self) -> (Signal<i32>, SignalSetter<i32>) {
        create_slice(
            self,
            |state| state.count,
            |state, n| state.count = n,
        )
    }

   fn name_slice...
}
```
and on the user end:
```rust
let (count, set_count) = state.count_slice();
```

But I don't think of it as a desirable solution for a couple of reasons
-  I'm not sure if the accessors are going to be the same in every single case, taking the freedom away from the user feels limiting. A single slice with a combination of multiple fields would make more sense in some cases.
- `count_slice` consumes `self` making multiple slices into the same state difficult.
- Generating `<field_name>_slice` versions of every field is kind of awkward, if only there was a way to "namespace" these functions under field names...
- I think there are better ways to handle this

I think there is a big overlap between this topic and `Lenses` so I had a quick look at how they were integrated in rust.

[Druid](https://github.com/linebender/druid) a desktop UI framework also utilizes lenses to address the issue of global state.
They seem to be using a `Lens` trait which allows composition through a combinator (`then`), a `derive_macro` to derive the lens trait and a function-like `proc_macro` to generate lenses on the fly (for foreign types).

I'll look more into this and come up with a better solutino incorporating lenses, I think taking a look at how solid deals with this is also worth a shot.
