### ISSUE TITLE
Support context inside event listeners, etc. in 0.5.0

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#1653]
**Is your feature request related to a problem? Please describe.**
Pre-0.5.0, `use_context` works in event listeners because the `Scope` is explicitly brought in from the component. Now, it doesn't, because there is a reactive `Owner` when the listener is created, but not when it is run. 

So the following panics:
```rust
#[derive(Clone)]
pub struct MyCtx;

#[component]
pub fn Child() -> impl IntoView {
    view! {
        <div on:click=move |_| { expect_context::<MyCtx>(); }>"child-div"</div>
    }
}

#[component]
pub fn App() -> impl IntoView {
    provide_context(MyCtx);
    view! {
        <Child />
    }
}
```

**Describe the solution you'd like**
We could store `Owner::current()` when an event listener (timeout, etc.) is *created* and restore it when the callback runs, as a wrapper.

**Describe alternatives you've considered**
Recognizing this is a breaking change: you need to use context outside the callback and move the object in:
```rust
#[derive(Clone)]
pub struct MyCtx;

#[component]
pub fn Child() -> impl IntoView {
    let ctx = expect_context::<MyCtx>();;
    view! {
        <div on:click=move |_| { ctx }>"child-div"</div>
    }
}

#[component]
pub fn App() -> impl IntoView {
    provide_context(MyCtx);
    view! {
        <Child />
    }
}
```

**Comment by gbj** [comment]
I'm not actually able to reproduce this report; I will reopen when I have a working (broken) example, I guess.

**Comment by gbj** [comment]
Okay, so here's a version that does reproduce it.
```rust
#[derive(Clone, Debug)]
pub struct MyCtx(i32);

#[component]
pub fn Child() -> impl IntoView {
    logging::log!("owner B {:?}", Owner::current());
    view! {
        <button on:click=move |_| {
            logging::log!("owner inside event is {:?}", Owner::current());
            logging::log!("{:?}", use_context::<MyCtx>());
        }>
            "child-div"
        </button>
    }
}

#[component]
pub fn App() -> impl IntoView {
    let (value, set_value) = create_signal(3);
    move || {
        if value() > 2 {
            logging::log!("owner A {:?}", Owner::current());
            provide_context(MyCtx(42));
            view! { <Child/> }
        } else {
            todo!()
        }
    }
}
```

**Comment by mscofield0** [comment]
I don't consider it that bad to require contexts be drawn outside of event listeners and such. Is there any other benefit aside from ergonomics?

**Comment by gbj** [comment]
Nope, it's just a breaking change from 0.4 to 0.5; but supporting it would come at the cost of a small additional overhead for every event listener, so I'm not inclined to do it. Having looked around a little, it seems SolidJS (for example) just doesn't support accessing context in event listeners, etc., which makes perfect sense.
