### ISSUE TITLE
add ADOPTERS.md

### ISSUE THREAD

**Issue by derekperkins** [leptos-rs/leptos#1667]
I'd love to see more examples of production leptos apps. Are you opposed to adding an ADOPTERS.md file like many other projects, where users can PR their details?
- https://github.com/backstage/backstage/blob/master/ADOPTERS.md
- https://github.com/linkerd/linkerd2/blob/main/ADOPTERS.md
- https://github.com/knative/community/blob/main/ADOPTERS.MD
- https://github.com/dapr/community/blob/master/ADOPTERS.md

**Comment by gbj** [comment]
I am not opposed, and it's not something I have the capacity to create or maintain.

**Comment by rakshith-ravi** [comment]
I'd be happy to help create and maintain this, but I'm unsure what it would involve though.

It would definitely be a nice to have since it would add significant trust in the project to see other people using it. What, in your opinion, are the essential things to be included in an adopters file @derekperkins?

**Comment by derekperkins** [comment]
@rakshith-ravi I like the Backstage setup, where there's a link to the organization using it, GitHub handles for the primary people behind it, and a description for how it's used. 

It should be pretty easy to maintain, as individuals PR their own companies / usage into the file. An initial PR that sets up the basic structure, with a link from the README is probably sufficient, and then asking for PRs in the Discord channel.

**Comment by gbj** [comment]
Closing this as "not planned" in favor of the existing list at [`awesome-leptos`](https://github.com/leptos-rs/awesome-leptos), which I'll make sure to add to the README as well.
