### ISSUE TITLE
Directives in leptos

### ISSUE THREAD

**Issue by hchockarprasad** [leptos-rs/leptos#1668]
**Is your feature request related to a problem? Please describe.**
Currently we have to create custom components if we need to add/modify minor functionality for native elements like customized click events e.t.c.

**Describe the solution you'd like**
We can have directives like solidjs.

**Describe alternatives you've considered**
Now we have to create a component wrapper and then pass every props to the native element via component props which makes our code bit messy.

**Comment by gbj** [comment]
I have never used directives in SolidJS. Could you provide some examples of the code you'd like to be able to write, and what it would do/expand to?

**Comment by hchockarprasad** [comment]
Directives are just functions which will be called once with native element reference & a callback.

example: 
```
export default function clickOutside(el, accessor) {
  const onClick = (e) => !el.contains(e.target) && accessor()?.();
  document.body.addEventListener("click", onClick);

  onCleanup(() => document.body.removeEventListener("click", onClick));
}


function App() {
  const [show, setShow] = createSignal(false);

  return (
    <Show
      when={show()}
      fallback={<button onClick={(e) => setShow(true)}>Open Modal</button>}
    >
      <div class="modal" use:clickOutside={() => setShow(false)}>
        Some Modal
      </div>
    </Show>
  );
}
```

I think we can currently achieve this via `on:mount` and passing a custom function with the attached element's ref.
like...
```
<div class="modal" on:mount=|e| { click_outside(e.element__ref) }>
    Some Modal
  </div>
```
But will this work inside custom function?
```
onCleanup(() => document.body.removeEventListener("click", onClick));
```

**Comment by blorbb** [comment]
ooh yeah this could be nice. might wanna have a look at [Svelte actions](https://learn.svelte.dev/tutorial/actions) as well for reference. if setting on_cleanup doesn't work in the function, returning the function instead could work.

**Comment by mscofield0** [comment]
Yeah, this would be nice. Svelte actions are very ergonomic and useful.

**Comment by maccesch** [comment]
VueUse has directives for some of it's functions. `click_outside` would be an obvious one. So this might be quite nice for leptos-use as well.
