### ISSUE TITLE
RouteResource - Use of resources in routing

### ISSUE THREAD

**Issue by aldenmoreton** [leptos-rs/leptos#1676]
**Is your feature request related to a problem? Please describe.**
Routing using resources seems to be a topic of confusion for many people in the community. One of the common patterns people struggle with is protected routing using a resource. Often, routes become unreachable as developers protect them using an asynchronous resource that will synchronously always resolve to ```None``` (because it is loading). 

**Describe the solution you'd like**
A ```<RouteResource>```. I would like to develop a component which behaves similarly to the [`<Await>`](https://docs.rs/leptos/latest/leptos/fn.Await.html) component, but for routing. This component would not contain a route (I suppose it could), but rather a resource to be used by its children. Developers could bind to the resolved value, which they could then use for conditional routing, or for any other use inside a subcomponent. 

**Describe alternatives you've considered**
The official solution to this problem currently is to add routing into the protected component itself behind a ```<Suspense>``` component like [this](https://discord.com/channels/1031524867910148188/1138056578004688937/1138069245167681566). This gets confusing as it means there is decentralized routing happening outside of the ```<Routes>``` component (making it hard to track down behvaior). Many people have already combated this by abstracting this up a layer by combining resources and routes together in their projects using a custom component. A great example of this is [ResourceProtectedRoute](https://github.com/jcourson8/ResourceProtectedRoute) by @jcourson8. This is a great project, but it introduces lots of unnecessary coupling between the resource (which must resolve a bool) and the condition. 

**Desired Usage**
```rust
let user_fetch = create_resource(cx, ||(), get_user());
...
<RouteResource resource=user_fetch bind:user fallback=view!{cx, <p>"Loading..."</p>}>
     // Usually a ProtectedRoute with a resource is a no-no
     // because it will always be None as it loads
     // However, RouteResource insures that we will await the resource
     // before checking the ProtectedRoute condition
    <ProtectedRoute 
           path="/" 
           redirect_path="login" 
           condition=|_| user.is_auth() 
           view=|| view!{cx, <p>"Foo"</p>}
     />
</RouteResource>
```

Notice that the result of the resource can be used inside of the child component's view
```rust
let user_fetch = create_resource(cx, ||(), get_user());
...
<RouteResource resource=user_fetch bind:user fallback=view!{cx, <p>"Loading..."</p>}>
     // It wouldn't make sense to block loading just for the resource to resolve
     // but since we already had to block loading to wait for the condition
     // might as well pass the binded variable in to save a refetch
     <ProtectedRoute 
             path="/" 
             redirect_path="login" 
             condition=|_| user.is_auth() 
             view=|| view!{cx, <p>"Hello "{user.name}</p>}
     />
</RouteResource>
```

The resource can also be used multiple times. Notice how we can have one resource used for many different conditions, rather than a ```<ResourceProtectedRoute>``` and a separate resource to be created for each one. 
```rust
let user_fetch = create_resource(cx, ||(), get_user());
...
<RouteResource resource=user_fetch bind:user fallback=view!{cx, <p>"Loading..."</p>}>
    <ProtectedRoute path="/" redirect_path="login" condition=|_| user.is_auth() view=|| view!{cx, <p>"Foo"</p>}/>
    <ProtectedRoute path="/admin" redirect_path="/" condition=|_| user.is_admin() view=|| view!{cx, <p>"Foo"</p>}/>
</RouteResource>
```

**Comment by gbj** [comment]
This is not possible as described, i.e., as a wrapper around route definitions (`Route` or `ProtectedRoute`), as the router is currently implemented. I also don't think it's advisable: `Routes` is the set of route definitions, and the route definitions (as distinct from the set of views) should be known synchronously and unconditionally.

I think it's a great idea to provide an async protected route, or a resource-loading route, as a utility.

I would recommend using nested routing, with `Suspense` as a wrapper around `Outlet` to implement this pattern. For example:
```rust
view! {
  <Routes>
    // parent route
    <Route path="/dashboard" view=ResourceProtectedRoute>
      // nested child routes
      <Route path="/" view=Home/>
    </Route>
  </Routes>
}

// ...

// this can be abstracted, of course
#[component]
pub fn ResourceProtectedRoute() -> impl IntoView {
  let data = create_resource(/* ... */);
  view! {
    <Suspense fallback=/* ... */>
      {move || data.read().map(|value| {
        // once the data has loaded, we provide its value via context and
        // then render the nested route's outlet
        provide_context(value);
        view! { <Outlet/> }
      })}
    </Suspense>
  }
}
```

**Comment by gbj** [comment]
ProtectedRoute now works as expected with async resources on git main/0.7 (because it uses Suspense), so I am going to close this issue.
