### ISSUE TITLE
`with!` macro for signals

### ISSUE THREAD

**Issue by blorbb** [leptos-rs/leptos#1682]
**Is your feature request related to a problem? Please describe.**

Using `signal.with` is cumbersome and takes a lot of writing.
This is especially true for using multiple signals, e.g:
```rust
let first = create_rw_signal("Greg".to_string()); let middle = ...; let last = ...;
let name = move || first.with(|first| middle.with(|middle| last.with(|last| format!("{first} {middle} {last}"))));
```

Making it easier to use `with` would also encourage less cloning.

**Describe the solution you'd like**

A `with!` macro that makes it a little easier to use `Signal::with`.

Not sure about the syntax, maybe something like this:
```rust
with!(|first, middle, last| format!("{first} {middle} {last}"))
```
That would expand to the same thing as the manual implementation above.

The identifiers `first` `middle` and `last` are captured from the environment, and can be used in the closure's body with the same identifier.

**Pros**: Closure-like syntax reflects the closure used in `Signal::with`. The variables that are defined in the context of the closure are clear. Might also be able to be formatted with rustfmt? (not sure how it works with macros)
**Cons**: It might be too closure-like, it's not clear that first, middle and last are captured from the environment, rather than arguments of a closure.

An alternative could be:
```rust
with!(first, middle, last; format!("{first} {middle} {last}"))
```
Where the captured idents and the body of the closure are separated by a `;`.

**Pros**: It is clearer that this is not an ordinary closure.
**Cons**: don't really like how this looks.

A corresponding macro for `Signal::update` could also be made.

For both of these syntaxes, only identifiers would be accepted (so for something like `settings.big_thing.with(|thing| ...)`, you would need to `let thing = settings.big_thing` first).
I don't think this is much of an issue, as you could do something like
```rust
let something = {
    let thing = settings.big_thing;
    with!(|thing| ...)
}
```

**Describe alternatives you've considered**

[`.write()` and `.read()` for signals](https://github.com/leptos-rs/leptos/pull/1678). I personally don't like the idea of having `Ref` or `RefMut`s that could be used anywhere, as it can lead to panics.

**Additional context**
N/A

I can work on this feature if you like the idea.

**Comment by gbj** [comment]
I *believe* that this is fairly easy to implement as a simple, declarative `macro_rules!` macro, and I quite like it. I agree with you that this syntax is preferable if its possible:
```rust
with!(|first, middle, last| format!("{first} {middle} {last}"))
```
I think we can definitely do this, regardless of #1678. Do you want to try implementing it?

**Comment by blorbb** [comment]
Yeah I should be able to make this pretty quickly. Where in the repo should I make it though? Also, do you think a corresponding `update!` macro is needed?

**Comment by gbj** [comment]
> Yeah I should be able to make this pretty quickly. Where in the repo should I make it though? Also, do you think a corresponding `update!` macro is needed?

`leptos_reactive/src/macros.rs` maybe? Somewhere in `leptos_reactive`, in any case.

**Comment by flo-at** [comment]
> Yeah I should be able to make this pretty quickly. Where in the repo should I make it though? Also, do you think a corresponding `update!` macro is needed?

`with!` is pretty cool, thanks for that! What about `get!` to make the list complete? Or is get different in a way that it wouldn't work as a macro?

**Comment by blorbb** [comment]
> > Yeah I should be able to make this pretty quickly. Where in the repo should I make it though? Also, do you think a corresponding `update!` macro is needed?
> 
> `with!` is pretty cool, thanks for that! What about `get!` to make the list complete? Or is get different in a way that it wouldn't work as a macro?

I'm guessing you're talking about get on signals? Get is a simple method `signal.get()`, there's no need for a macro here. Multiple signals are just `s1.get(), s2.get(), s3.get()` (or in nightly `s1(), s2(), s3()`). A `with!` macro was only useful because there's an additional closure and things get messy when using multiple.

**Comment by flo-at** [comment]
I wasn't very clear about which `get` I'm talkin about, sorry. I mean the `get` (that used to be `read`) on resources.
