### ISSUE TITLE
Add `cargo-make` inside flake.nix

### ISSUE THREAD

**Issue by rambip** [leptos-rs/leptos#1689]
The only rust toolchain I have on my machine is installed through nix.

It is very nice to have a `flake.nix` with the entire rust toolchain, but there is something missing:
**`cargo-make`**

That would be very nice to add `cargo-make` to the shell `buildInputs`

**Comment by gbj** [comment]
I don't use nix and don't know what this means, but would be happy to accept a PR making this change.
