### ISSUE TITLE
Multiple `class` attributes behave differently when compiling in SSR vs Hydrate.

### ISSUE THREAD

**Issue by k1rowashere** [leptos-rs/leptos#1692]
**Describe the bug**
A useful pattern is to have multiple class attributes on an html element like: `view! {<div class="class_1" class=function_that_returns_class()></div>};`
This is more ergonomic than the alternative: `view! {<div class="class_1".to_string() + function_that_returns_class()></div>};`

This works fine in SSR mode (while loading the page for the first time).
However it doesn't work in Hydrate mode (after client side routing): the second class overrides the first.

**Leptos Dependencies**
```toml
leptos = { version = "0.5.0-beta", features = ["nightly"] }
leptos_meta = { version = "0.5.0-beta", features = ["nightly"] }
leptos_router = { version = "0.5.0-beta", features = ["nightly"] }
```

**To Reproduce**
1. Use leptos with SSR and Hydrate.
2. Create a simple component that returns: `view! {<div class="class_1" class="class_2"></div>};`
3. Navigate to the page using the url bar (to load the SSR version).
4. Observe that `class_1` and "class_2" are both present in the class attribute.
5. Navigate to another page, then back, using client side navigation (ex: by following `<A/>` tags)
6. Only "class_2"  is found.

The reason is apparent when expanding the macro in different compile modes:
```rs
// Problematic view macro.
view! {<div class="class_1" class=function_that_returns_class()></div>};

// Cleaned SSR expansion of macro: this works fine.
::leptos::HtmlElement::from_chunks(
    ::leptos::leptos_dom::html::Div::default(),
    [leptos::leptos_dom::html::StringOrView::String(
        format!(
            "<div id=\"_{}\" class=\"class_1 {}\"></div>",
            ::leptos::leptos_dom::HydrationCtx::peek(),
            &(function_that_returns_class())
                .into_attribute()
                .as_nameless_value_string()
                .map(|a| leptos::leptos_dom::ssr::escape_attr(&a).to_string())
                .unwrap_or_default()
        )
        .into(),
    )],
);

// Cleaned Hydrate expansion of macro: the second call to attr() overrides the first (expected)
::leptos::leptos_dom::html::div()
    .attr("class", "class_1")
    .attr("class", function_that_returns_class());
```

**Expected behavior**
It should behave the same in all contexts, or at least give an error/warning that something is wrong.
Example of a fixed macro expansion for hydrate mode:
```rs
::leptos::leptos_dom::html::div()
    .attr("class", "class_1")
    .classes(function_that_returns_class());
```
Perhaps it could require special syntax or smth.

**Comment by gbj** [comment]
This should not be expected to work correctly; the fact that it works as you intend it in SSR mode is accidental. Setting the class attribute multiple times should use the last invocation of it, rather than merging them together. 

This is the correct way to do this:
```
<div class=format!("class_1 {}", function_that_returns_class())>
```

**Comment by rakshith-ravi** [comment]
> I'm open to a solution that gives a compile error if you add multiple attributes of the same name, this just doesn't exist at the moment.

I can't help but feel like you'd need some kind of macro magic for that, since the `.attr` takes a string as a parameter

**Comment by gbj** [comment]
Yes to be clear I'm talking about emitting a compile error from the view macro -- the reason for this discrepancy is the difference between the SSR and browser codegen for the view macro; if you use .attr() twice for the same key the latter will always wipe out the former, so there won't be a compile error but the behavior will be consistent (and will match the behavior of setting an attribute twice in HTML or in the DOM)
