### ISSUE TITLE
`create_resource` and multiple derived signals do not load in one `<Transition />`

### ISSUE THREAD

**Issue by cometship** [leptos-rs/leptos#1711]
**Describe the bug**
When using `create_resource`, two derived signals (from this resource) and one `<Transition />`. Then only the first signal (`s1`) would load/show. The second signal (`s2`) not. 

A workaround here is to use a separate `<Transition />` for each signal. Then both load as expected. Another workaround is to switch the order of the signals inside of the `<Transition />` (`s2` before `s1`). 

I did not have this problem pre `v0.5.0-rc1` (and using `.read()` instead of `.get()`).

Here is a minimal reproducible example (the rest is the same like in the `todo_app_sqlite_axum` example):
```rust
#[server]
async fn get_data() -> Result<Vec<String>, ServerFnError> {
    Ok(vec!["a".to_string(), "b".to_string(), "c".to_string()])
}

#[server]
async fn add_data() -> Result<(), ServerFnError> {
    std::thread::sleep(std::time::Duration::from_millis(1250));
    Ok(())
}

/// Renders the home page of your application.
#[component]
fn HomePage() -> impl IntoView {
    let add_data = create_server_multi_action::<AddData>();
    let data = create_resource(add_data.version(), move |_| get_data());

    let s1 = move || {
        data.with(|data| {
            if let Some(Ok(data)) = data {
                data.iter().count()
            } else {
                0
            }
        })
    };
    let s2 = move || {
        data.get().map(|data| match data {
            Err(e) => view! { <pre>"Server Error: " {e.to_string()}</pre>}.into_view(),
            Ok(data) => data
                .into_iter()
                .map(|item| view! { <li>{item}</li> })
                .collect_view(),
        })
    };

    view! {
        <Transition fallback=move || view! { <p>"Loading..."</p> }>
            {s1}
            {s2}
        </Transition>
    }
}
```

Possibly related: #1709.

**Leptos Dependencies**
```toml
leptos = { version = "0.5.0-rc1", features = ["nightly"] }
leptos_axum = { version = "0.5.0-rc1", optional = true }
leptos_meta = { version = "0.5.0-rc1", features = ["nightly"] }
leptos_router = { version = "0.5.0-rc1", features = ["nightly"] }
```

**To Reproduce**
1. Run the code above
2. Only the first signal loads

**Expected behavior**
Both signals should resolve/load/show (no matter the order). Like pre `v0.5.0-rc1`.

**Screenshots**
`s1` before `s2`: 
![image](https://github.com/leptos-rs/leptos/assets/95552213/fe77910a-591a-444a-b56d-5bcfb3ba9898)

Separate `<Transition />`s:
![image](https://github.com/leptos-rs/leptos/assets/95552213/d3db0bb0-9615-428c-9b9f-c8bccfa68fa5)

`s2` before `s1` (in one `<Transition />`):
![image](https://github.com/leptos-rs/leptos/assets/95552213/6fdb09f8-6e13-4438-b38a-b1fe16ddf81b)

**Comment by gbj** [comment]
When you say pre-0.5.0-rc1, could you clarify which version you mean? (0.5.0-beta2, 0.5.0-beta, 0.4.10, etc)

**Comment by cometship** [comment]
> When you say pre-0.5.0-rc1, could you clarify which version you mean? (0.5.0-beta2, 0.5.0-beta, 0.4.10, etc)

Sure, I used v0.4.6.

**Comment by gbj** [comment]
Looks like this is a discrepancy between the behavior of the new `Resource::with()` and `Resource::map()` (the old `Resource::with()`), in which the new `Resource::with()` is actually not registering with Suspense properly.
