### ISSUE TITLE
Fn: Into<Signal>

### ISSUE THREAD

**Issue by smessmer** [leptos-rs/leptos#1722]
With the 0.5.0 changes to the reactive system, it's now easier than ever to convert a `Fn` into a `Signal`, just call `.into_signal()` on it. However, I think `.into()` would be even better. If `Fn` implemented `Into<Signal<_>>`, then those `Fn` could be passed directly to any components taking a `#[prop(into)] Signal<T>`.

`Fn: Into<MaybeSignal<_>>` probably makes sense too. Most of my components currently take `#[prop(into)] MaybeSignal<T>` so that call sites can decide whether to pass in a signal or a function.

**Comment by gbj** [comment]
As far as I know this is impossible if signals can implement `Fn()`, because it conflicts with the global trait `impl From<T> for T`, as far as I know.

If you try to 
```rust
impl<T, F> From<F> for Signal<T> where F: Fn() -> T {}
```
you get a compiler error that says exactly that
```
error[E0119]: conflicting implementations of trait `From<signal_wrappers_read::Signal<_>>` for type `signal_wrappers_read::Signal<_>`
  --> /Users/gjohnston/Documents/Projects/leptos-main/leptos/leptos_reactive/src/signal_wrappers_read.rs:85:1
   |
85 | impl<T, F> From<F> for Signal<T> where F: Fn() -> T {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `core`:
           - impl<T> From<T> for T;

For more information about this error, try `rustc --explain E0119`.
```

**Comment by gbj** [comment]
(To be clear it's a great idea and I would love it if the compiler would allow it, but it does not)

**Comment by smessmer** [comment]
I see, that makes sense. Can we maybe change #[prop(into)] in some way that it allows passing in `IntoSignal` types on top of `Into` types then?

**Comment by gbj** [comment]
Sure, I'd be happy to review a PR that adds something like `#[prop(into_signal)]`. I don't think it's possible to handle with the current `#[prop(into)]` as that just adds `.into()`.

**Comment by rambip** [comment]
I don't know how to solve this issue, but I have a similar one:
For my callback proposal, I would like to:
1) convert a `Fn(A) -> B` to a `Callback<A, B>`
2) implementing `Fn(A) -> B` for `Callback<A, B>`

But it is not possible exactly for the same reason.

**Comment by rambip** [comment]
If the `prop(into_signal)` is a real thing, maybe `prop(into_callback)` should also

**Comment by rambip** [comment]
Ok I have found another way to do it:
```rust
struct SignalAdapter<T>(Signal<T>);

impl From<F: Fn() -> T> for SignalAdapter<T>(Signal<T>){
    fn from(f: F) -> Self {
        SignalAdapter(f.into_signal())
    }
}
```

Then, in your component, you can use
```
#[component]
fn Test(
    #[prop(into)]
    foo: SignalAdapter<String>
) -> impl IntoView {
    let foo = foo.0;

    todo!()
}
```

**Comment by rambip** [comment]
This issue would be solved by #1759

**Comment by gbj** [comment]
> Given that implementing `Fn() -> T` for `Signal<T>` requires nightly, couldn't we use `#![feature(min_specialization)]` (see [specialization](https://github.com/rust-lang/rust/issues/31844))? 

Adding `min_specialization` and/or `specialization` and trying to implement `From` here yields the same error
```
error[E0119]: conflicting implementations of trait `From<signal_wrappers_read::Signal<_>>` for type `signal_wrappers_read::Signal<_>`
  --> leptos_reactive/src/signal_wrappers_read.rs:38:1
   |
38 | impl<F, T> From<F> for Signal<T>
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `core`:
           - impl<T> From<T> for T;
```

**Comment by gbj** [comment]
> Sorry, my bad. I've also seen type constraints like `F: SomeTrait + !OtherTrait`, but can't find its name or if it is even implemented. Do you know anything about that? And could it be used here like `impl<T, F> From<F> for Signal<T> where F: Fn() -> T + !SignalMarker`?

Ooh yeah `auto_traits` and `negative_impls` are the features here! Good call, I'll give that a quick try this evening.

**Comment by gbj** [comment]
Nope. It's possible I'm doing something wrong but even the fairly straightforward version fails.

```rust
#![feature(negative_impls)]
#![feature(auto_traits)]

struct Foo;

auto trait NotFn {}
impl<T, F> !NotFn for F where F: Fn() -> T {}

impl<T> From<T> for Foo
where
    T: NotFn,
{
    fn from(value: T) -> Self {
        todo!()
    }
}

// conflicting implementations of trait `std::convert::From<_>` for type `Foo`
impl<T, F> From<F> for Foo
where
    F: Fn() -> T,
{
    fn from(value: F) -> Self {
        todo!()
    }
}
```

**Comment by rambip** [comment]
> But this does:
> 
> ```rust
> #![feature(unboxed_closures)]
> #![feature(fn_traits)]
> #![feature(negative_impls)]
> #![feature(auto_traits)]
> 
> struct Signal<T, F: FnOnce() -> T>(F);
> 
> impl<T, F> FnOnce<()> for Signal<T, F>
> where
>     F: FnOnce() -> T,
> {
>     type Output = T;
>     extern "rust-call" fn call_once(self, _: ()) -> Self::Output {
>         self.0()
>     }
> }
> 
> auto trait NotSignalMarker {}
> impl<T, F: FnOnce() -> T> !NotSignalMarker for Signal<T, F> {}
> 
> impl<T, F> From<F> for Signal<T, F>
> where
>     F: FnOnce() -> T + NotSignalMarker,
> {
>     fn from(value: F) -> Self {
>         Self(value)
>     }
> }
> ```
> 
> Could we use it like this, or am I missing something?

That's amazing !
We could do the same thing for `Callback` and `IntoView` !

**Comment by gbj** [comment]
@rambip Thanks. The conflict when I was playing with it in the `leptos_reactive` crate itself was actually with `From<T> for Signal<T>`. Here's an adjusted version that reflects that. I wasn't able to get a `NotFn` marker worker, but if there's a way to adjust the below so it compiles... awesome!

(In other words, at present you can do `3.into()` and get a `Signal<i32>`, and you can do `(|| 3).into_signal()` and get a `Signal<i32>`, but you can't do `(|| 3).into()`. If there's a way to do them all without dropping `From<T>` support then that's great, I just haven't found it yet.)
```rust
#![feature(unboxed_closures)]
#![feature(fn_traits)]
#![feature(negative_impls)]
#![feature(auto_traits)]

struct Signal<T>(Box<dyn FnOnce() -> T>);

impl<T> FnOnce<()> for Signal<T> {
    type Output = T;
    extern "rust-call" fn call_once(self, _: ()) -> Self::Output {
        self.0()
    }
}

auto trait NotSignalMarker {}

impl<T> !NotSignalMarker for Signal<T> {}

impl<T, F> From<F> for Signal<T>
where
    F: FnOnce() -> T + NotSignalMarker,
{
    fn from(value: F) -> Self {
        Self(value)
    }
}

impl<T> From<T> for Signal<T>
where
    T: 'static,
{
    fn from(value: T) -> Self {
        Self(value)
    }
}
```

**Comment by rambip** [comment]
where is `From<T>` implemented for `Signal<T>` ?
I thought `MaybeSignal` was implemented for that reason ...
I guess it is a breaking change to remove that implementation, but I don't get why it was in the first place.

**Comment by gbj** [comment]
> why is `From<T>` implemented for `Signal<T>` ? I thought `MaybeSignal` was created for that exact reason ... Maybe there is something I don't get
> 
> I guess it is a breaking change to remove that implementation, but I don't get why it was in the first place.

We can certainly remove it for now. It would've been new in 0.5 in any case.

It has the potential to be very useful for future work with persistent islands, because it allows for updating an island with data from the server in a way that's reactive, by replacing the props of an island with new props without actually rerendering, and without the server component able to pass plain data...

But it was basically just implemented because it's possible, so I'm fine with removing it. 

***

@smessmer @rkuklik @rambip Thanks to all of you for asking, pushing on this, and coming up with some great ideas. The attached PR implements this so this you can do something like the following and it works, assuming I didn't do something stupid with the implementation that breaks a bunch of things during CI. 

I think this will be another big improvement in usability, so... thanks.

```rust
#[component]
pub fn Child(#[prop(into)] signal: Signal<bool>) -> impl IntoView {
    todo!()
}

/// Parent
#[component]
pub fn App() -> impl IntoView {
    let (signal, set_signal) = create_signal(false);
    view! {
        <Child signal/>
        <Child signal=move || !signal.get()/>
    }
}
```
