### ISSUE TITLE
Relax bounds on `leptos_axum::LeptosRoutes`

### ISSUE THREAD

**Issue by ChristopherPerry6060** [leptos-rs/leptos#1727]
**Is your feature request related to a problem? Please describe.**
https://github.com/leptos-rs/leptos/blob/afa67726c1f153c29e6e180098e7b5518e108a24/integrations/axum/src/lib.rs#L1289

`leptos_axum::LeptosRoutes` is bounded by `LeptosOptions: FronRef<S>`. I *think* that bound should only exist on the implementation and not the trait definition. If someone wants to use the integration they must supply LeptosOptions within the router

**Describe the solution you'd like**
I deleted that line on my local repo and CI is cooking without issues (so far). Bounds should try to only exist where absolutely needed. Everyone will likely use the default impl for `Router<S>` which is already bounded by `LeptosOptions`

**Describe alternatives you've considered**
Writing the integration for Routes without using that trait, it would just be very convenient to remove
a few instances of LeptosOptions from signatures if possible. I could also just use LeptosOptions, but I do not think I benefit if I just want to do full SSR (I could be wrong though).

Would be interested to understand why / if that bound is actually needed for some edge case. Otherwise, I can submit a PR?

**Comment by gbj** [comment]
Sure, PR welcome if removing it works fine.
