### ISSUE TITLE
`examples/tailwind_csr_trunk` `opacity-0` class not working

### ISSUE THREAD

**Issue by gitmalong** [leptos-rs/leptos#1737]
There is a tailwind class called `opacity-0` to make an element invisible. When running the example with `trunk serve --open` and using Chrome's dev console to add the class `opacity-0` to the button, the button remains visible.

Other tailwind classes work fine. I don't know what the issue is in here.

* https://tailwindcss.com/docs/opacity
* https://github.com/leptos-rs/leptos/tree/main/examples/tailwind_csr_trunk

**Comment by gbj** [comment]
Could you please provide an example of how you're using `opacity-0` in your code? You describe adding `opacity-0` in the console, but the Trunk hook being used here is just running `npx tailwindcss`, which means it's scanning your code for used classes. If you are only adding it in the browser, but not in your code, Tailwind will not detect it and will not add it to its stylesheet.

**Comment by gitmalong** [comment]
Sure!

This is in my app in which it does not work

```rust
{
    move ||
    match progress_sig.get() {
        Some(v) => {
            view! {cx,
                <progress
                    class:opacity-0=move || v == 100
                    class:bg-opacity-0=move || v == 100
                    class:text-opacity-0=move || v == 100
                    class="progress grow ml-4 mt-7 transition-opacity"
                    value=v
                    max="100" />
            }.into_view(cx)
        }
        None => {
            "".into_view(cx)
        }
    }
}
```

When using the example project it works when I do 
```rust
class="bg-amber-600 hover:bg-sky-700 px-5 py-3 text-white rounded-lg opacity-0"
```

**Comment by gbj** [comment]
I suspect `npx tailwindcss` doesn't do a good job of detecting the `class:opacity-0=` syntax. If you try `class=("opacity-0", v == 100)` does it work?

(I removed the closure because AFAICT `v` is not a reactive value, the reactivity is in the `progress_sig.get()` outside it)

**Comment by gitmalong** [comment]
> If you try class=("opacity-0", v == 100) does it work?

Yes, this makes it work :). Thank you @gbj !
