### ISSUE TITLE
Support for axum extractors directly

### ISSUE THREAD

**Issue by Beiri22** [leptos-rs/leptos#1755]
You are using macro magic to create server functions. I just wonder if it was possible to avoid an explicit `extract` function in favor of directly defining the extractors in the handler methode signature as axum does. Could that be possible?

**Comment by Beiri22** [comment]
I mean, it's just a proposal. If you ask me, the axum syntax of extractors is pretty neat.

> Well, here's the question: What does it look like to call, from the client, a server function that takes arguments that only exist on the server? Are they all `Option<_>` and when you call it from the client you pass `None` and they become `Some(_)` when received on the server? To me, that's much more magical and unpredictable.

As we are talking of macros, for the client there should be a wrapper so that the client calls the function as he does right now.

> Doing it inline would also significantly increase the amount of macro "magic" going on, i.e., would shift more of the logic into a proc macro instead of a function call.

That might be the result, you're right. But on the other hand it would reduce boilerplate in favor of a clear and understandable syntax. You would, of course, need a few lines in the book to make the user understand the principle.

**Comment by Beiri22** [comment]
As I see, the server macro is already a procedural macro. I'm unfortunately not too much into this topic; but is a procedural macro able to check if an argument is for example FromRequestParts?

**Comment by gbj** [comment]
> is a procedural macro able to check if an argument is for example FromRequestParts?

No, unfortunately not; all proc macros do is transform a stream of tokens into a different stream of tokens, and then run before the compiler does anything having to do with types, so they have no access to type information like this.

> But on the other hand it would reduce boilerplate in favor of a clear and understandable syntax.

Here's the current form
```rust
#[server(QueryExtract, "/api")]
pub async fn query_extract() -> Result<String, ServerFnError> {
    // these are just some imports, not boilerplate
    // putting them inside the server fn body means they don't need to be available for WASM
    use axum::{extract::Query, http::Method};
    use leptos_axum::extract;

    // uses the exact same syntax as Axum handlers/extractors: 
    // typed arguments in an async function
    extract(|method: Method, res: Query<MyQuery>| async move {
            format!("{method:?} and {}", res.q)
        },
    )
    .await
    // pretty sure this can just be `?`
    .map_err(|e| ServerFnError::ServerError("Could not extract method and query...".to_string()))
}
```
If changed it would be something like this
```rust
#[server(QueryExtract, "/api")]
pub async fn query_extract(
    // the types are inline here because having them in a `use` outside the
    // server function body would mean they need to be compilable for WASM
    #[extract] method: axum::http::Method,
    #[extract] axum::extract::Query
) -> Result<String, ServerFnError> {
    Ok(format!("{method:?} and {}", res.q))
}
```
I don't see this as a big improvement. Maybe this is just a difference of stylistic preference. In general I think functions are a lot easier to document and to use than macros.

***

But the main issue here is just the simple mental model of a server *function*. In the current form I can declare some function `query_extract`, and I can call it
1) from the client as `query_extract()`,
2) from the server during initial rendering as `query_extract()`,
3) or as a separate, later API call as `query_extract()`
This means I can do things like 
```rust
let data = create_resource(|| (), query_extract)
```
and it just works everywhere.

It's possible I'm doing a bad job of explaining why this is important (sorry), but adding additional arguments to the function that only exist in some places, or are somehow transformed, becomes a problem. I've tried implementing something like this in the past and it doesn't really work. 

I *think* it could work if the `#[extract]` version above just expands into the current version, but that feels like too much for me: it transforms a function definition with 2 arguments into a function definition with 0 arguments, and that has implications for things like support in different IDEs etc. For `#[component]`, we *need* to transform the arguments if we want to have named props in an XML-like syntax, because Rust doesn't have named function arguments. But server functions are usually called as functions, so having the arguments in the source correspond seems more important to me.

**Comment by Beiri22** [comment]
> I don't see this as a big improvement. Maybe this is just a difference of stylistic preference. In general I think functions are a lot easier to document and to use than macros.

Maybe it's a case of personal style. For me, the latter looks clearly better.

> I think it could work if the #[extract] version above just expands into the current version, but that feels like too much for me: it transforms a function definition with 2 arguments into a function definition with 0 arguments, and that has implications for things like support in different IDEs etc. For #[component], we need to transform the arguments if we want to have named props in an XML-like syntax, because Rust doesn't have named function arguments. But server functions are usually called as functions, so having the arguments in the source correspond seems more important to me.

Taking this approach one step to the side. Imaging a macro `extract` to be used like this:
```rs
#[server(QueryExtract, "/api")]
pub async fn query_extract(
) -> Result<String, ServerFnError> {
    (method, query) = extract!{axum::http::Method, axum::extract::Query<HashMap<String, String>>}
    Ok(format!("{method:?} and {}", res.q))
}
```
This macro would just transform this statement into
```rs
// I left out the full type paths for clarity.
extract(|method: Method, Query(query): Query<HashMap<String, String>>| async move { (method, query) } )
```

This would clear up the syntax for common use cases, but as it's not forced, it won't restrict the user.

**Comment by gbj** [comment]
A `macro_rules!` macro like that is a great idea, and should be fairly straightforward to implement. Would you like to try it?

**Comment by Beiri22** [comment]
I have made a few attempts. One problem I see with multiple arguments it the naming of variables. With only one argument I simply call it `x`, no problem. But with multiple arguments, how can i generate proper names?
```|x1: Method, Query(x2): Query<HashMap<String, String>>| async move { (x1, x2) }```

Is there some obvious solution that I do not see?

**Comment by gbj** [comment]
Great point. The good thing is that for both Actix and Axum, extractors always also support a tuple of extractors. So 
```rust
#[server]
async fn fetch_data() -> Result<String, ServerFnError> {
    use actix_web::dev::ConnectionInfo;
    use actix_web::web::Data;
    use leptos_actix::extract;

    let (data, connection) =
        extract(|fields: (Data<String>, ConnectionInfo)| async move { fields }).await?;
    todo!()
}
```
is totally valid.

This means you don't actually need field names, just an extractor type or tuple of types, and you should be good to go.

**Comment by Beiri22** [comment]
That is indeed nice. But you cannot use the destructuring trick like `Query(x2): Query<HashMap<String, String>>` to directly get the inner value, right?

**Comment by gbj** [comment]
Due to the awesomeness of Rust pattern matching, you actually can! (assuming that this is what you mean)
```rust
    let (data, Query(connection)) = extract(
        cx,
        |fields: (Method, Query<HashMap<String, String>>)| async move { fields },
    )
    .await
    .unwrap();
```

**Comment by Beiri22** [comment]
Focusing on the macro internals, I totally forgot about this place for destructuring.

**Comment by Beiri22** [comment]
So we got something like
```
macro_rules!extract{
    ($($x:ty),+) => ( leptos_axum::extract(|fields: ($($x),+)| async move { fields }).await );
}
```

Would you do 2 different macros, one for axum and one for actix?

**Comment by Beiri22** [comment]
I wonder how to include state. Just looking at your example in https://docs.rs/leptos_axum/0.5.0-rc2/leptos_axum/fn.extract_with_state.html I really don't get it. When you retrieve the state via `use_context::<crate::ServerState>()`, then you have the state right there; why do you then call `extract_with_state`? Also: The `extract_with_state`-call does not use any state, does it? I don't get the point of this example.

**Comment by gbj** [comment]
Here's a link to the PR but there's not much discussion there https://github.com/leptos-rs/leptos/pull/1275

Here's a link to the Discord discussion to which it refers https://discord.com/channels/1031524867910148188/1124201405486473267/1124201405486473267

> I want to use this with a `T: FromRequestParts<ServerState>`, am I out of luck or is there a work around?

I'm not sure the original context/need for an extractor that takes State, but maybe @sjud could give an example of an extractor that requires state, even though you have access to the state itself.

**Comment by Beiri22** [comment]
I don't find an example or detailed use case in the PR or Discord. Please, @sjud, can you help me understanding your use case?

**Comment by gbj** [comment]
@Beiri22 Do you want to complete this or should I take it over?

**Comment by Beiri22** [comment]
I would wait for more information; so better you do it. Have you looked at the menioned dioxus variant?

**Comment by gbj** [comment]
@lelgenio it's a nice design, although those examples seem like they're chosen to *not* need additional type info... I guess the type of `user` for the `Json` is inferred from elsewhere?

Here's the equivalent for us that I'm finishing right now.
```rust
let info = extract!(ConnectionInfo);
let Query(data) = extract!(Query<Search>);
let (info, Query(data)) = extract!(ConnectionInfo, Query<Search>);
```
This seems concise enough to me.

**Comment by gbj** [comment]
> ... but dioxus gets this done without macro ... 😏

This is not a helpful comment.

**Comment by Beiri22** [comment]
Sry, i couldn't resist. And thx for implementing the feature.

**Comment by Beiri22** [comment]
Do we close the issue right now or when merged?

**Comment by gbj** [comment]
Oh, it's okay — you pissed me off enough that I took ten minutes and implemented the same API as the Dioxus one. The hardest part was finding the `extract` function in the Dioxus docs.

```rust
#[server]
pub async fn data() -> Result<MyQuery, ServerFnError> {
    use axum::{extract::Query, http::Method};
    use leptos_axum::*;
    let Query(query) = extract2().await?;

    Ok(query)
}
```

This needs cleaning up w.r.t. docs and so on, and I'll add the same for Actix, but it's better than the macro version or the callback version, I think. I'm out of time to work on it more now, but I'll close the issue when I'm done with that.

This is a good example where actually getting extractors implemented for Axum in the first place was really hard and took me a while; it's easy to end up with tunnel vision and miss on small API things like this when you've been wrangling the compiler to get it to work.

**Comment by gbj** [comment]
P.S. @Beiri22 I hadn't eaten breakfast yet when I was a little rude this morning -- apologies, and I do have a sense of humor lol

Thanks for pushing me on this one and working through these ideas. This is a big win for every user, I think.

**Comment by Beiri22** [comment]
I also like the outcome and did not take any offense. :-)
