### ISSUE TITLE
Support wasm32 server by implementing a small change in `leptos_reactive`

### ISSUE THREAD

**Issue by 9oelM** [leptos-rs/leptos#1786]
**Is your feature request related to a problem? Please describe.**
I am trying to write an integration where SSR can be run in Cloudflare workers. This is a different backend then Actix, Axum, or Viz because Cloudflare workers are run in a very special environment - i.e. wasm32 target and limitations of the edge environment like no fs or threads. Also, at this point, the website can only be built and run with `wrangler`, meaning that `cargo-leptos` can't be used. Anyway, all that is to say is that this one is special and may require some changes in the existing codebase of leptos itself. 

The code on my side is mostly complete, but just needs a few refactors and fixes. If you are interested, you can have a look:

- https://github.com/9oelM/leptos-cf/blob/feat/ssr-crate/leptos-cf/src/lib.rs
- https://github.com/9oelM/leptos-cf/blob/feat/ssr-crate/worker/src/lib.rs

The main problem that I am experiencing is that code in `leptos_reactive` is not designed with wasm32 server in mind, so this error is presented when I am trying to use the current code at leptos-cf:

![image](https://github.com/leptos-rs/leptos/assets/22465806/61c18509-286c-4f44-b9c5-2e75f60fd662)

**Describe the solution you'd like**

AFAIK we just need to change the first `if` statement in the code below to `if #[cfg(target_arch = "wasm32")]`, because `tokio::task::spawn_local` in the third branch is simply not supported in wasm32 target environment:

![image](https://github.com/leptos-rs/leptos/assets/22465806/abd5dd32-b5bb-4988-9461-6704abb5504c)

And the solution is already seen and proven in https://github.com/leptos-rs/leptos/pull/1554/files#diff-a5ad10cf725eb78940bf4cc9772674f4896a3255da582bdefb37deda4ae55e94L79, where @seanaye was also trying to create a server that can be run in wasm32 although the objective of the PR was a lil bit different from what I am trying to do:

<img width="2347" alt="image" src="https://github.com/leptos-rs/leptos/assets/22465806/ebdcdf27-b74a-4750-b21f-f2e5b1746940">

**Describe alternatives you've considered**
The only solution that is available seems to be the best (and probably the only) one to my knowledge.

Lastly, it'd be fascinating if leptos SSR could also support Cloudflare workers as a backend, but I think it's got more polishing work to do if it were to be merged into this repository. For now I would just love to have leptos_reactive to support wasm32. I will create a PR for this.

**Comment by gbj** [comment]
I just merged #1554 (actually I thought I merged it over the weekend but apparently I was letting the CI run on a fixed error and forgot about it!) which makes the changes you're asking for here. I don't think there's anything else needed but let me know if I'm wrong.

**Comment by 9oelM** [comment]
@seanaye @gbj great!! Thank you so much guys!!
