### ISSUE TITLE
Why not make <Title>example</Title> as an alternative?

### ISSUE THREAD

**Issue by veniamin-ilmer** [leptos-rs/leptos#1792]
**Is your feature request related to a problem? Please describe.**
Some people might prefer to use <Title>example</Title>

**Describe the solution you'd like**
Allow <Title>example</Title>

**Describe alternatives you've considered**
This works - <Title text="example"/>

**Additional context**
Is there a particular reason why <Title>example</Title> is not currently an option?

**Comment by gbj** [comment]
Generally when a component takes `children` this means you can pass it any view. But this isn't the case with `Title`-- this should not be valid:
```
<Title><p>Oop</p></Title>
```

It would be possible to make `children` a `Box<dyn Fn() -> T: ToString>` or something here, and then try to deal with the optional generic; or to implement the same IntoChildren helper trait for TextProp that we do for a few other types. 

But I'm not sure I see the point of making this breaking change. Just so it's more similar to HTML?

**Comment by veniamin-ilmer** [comment]
Good point. HTML is broken! Use Leptos to fix HTML!
