### ISSUE TITLE
allow provide_context in generate_route_list function

### ISSUE THREAD

**Issue by beckend** [leptos-rs/leptos#1812]
**Is your feature request related to a problem? Please describe.**
```rust
use leptos_axum::generate_route_list;

  #[derive(Clone)]
  pub struct ConfigClient {
    pub base_url: String
  }

  let config_client = ConfigClient { base_url: "http://localhost" };

  let routes = generate_route_list({
    let config_client = config_client.clone();

    move || {
      provide_context(config_client);
      view! { <App/> }
    }
  });
```
1. Context seem to not work doing this, the app seem not to find the context.
2. this code is broken, the Fn tries to move config_client and complains about capturing parent context.

**Describe the solution you'd like**
It should work like `leptos_axum::render_app_to_stream_with_context`

**Additional context**
```rust
error[E0507]: cannot move out of `config_client`, a captured variable in an `Fn` closure
   --> src/ssr/app.rs:135:23
    |
132 |     let config_client = config_client.clone();
    |         ------------- captured outer variable
133 |
134 |     || {
    |     -- captured by this `Fn` closure
135 |       provide_context(config_client);
    |                       ^^^^^^^^^^^^^ move occurs because `config_client` has type `ConfigClient`, which does not implement the `Copy` trait
```

**Comment by gbj** [comment]
Hmm.... `generate_route_list` is really just there to extract routes. Does it need context because you're unwrapping a `use_context` somewhere during rendering, so it panics, or are you actually conditionally defining the routes based on context?

**Comment by beckend** [comment]
The application expect that context to exist across the tree.
We are attempting to render a whole application, it should be able to depend and expect things to exist to function properly.

**Comment by beckend** [comment]
And yes, I am doing pretty much a .expect() since that thing struct is used everywhere.

**Comment by beckend** [comment]
To clarify, it should not work like `render_app_to_stream_with_context`, but be able to provide context and capture variables doing it's thing extracting routes.

**Comment by gbj** [comment]
Got it. So, to clear the compile error you just need to `provide_context(config_client.clone())`-- this is just a normal Rust ownership error, as `generate_route_list` wants a `Fn` and `provide_context` wants an owned value, so you need to clone here. 

Obviously I don't know if that solves the underlying issue of context. If not, let me know and we can add a `generate_route_list_with_context` or whatever.

**Comment by beckend** [comment]
Ok, that worked, I didn't think I needed to clone it inside the closure as well, I suppose it wants a owned value, that means I had to clone it twice which was unexpected.
