### ISSUE TITLE
ci(leptos): run ci on change instead of check

### ISSUE THREAD

**Issue by agilarity** [leptos-rs/leptos#1815]
PROPOSED: _Let me know if you would like me to submit a PR_

**Is your feature request related to a problem? Please describe.**
Some breaking changes are detected only when the daily CI Examples workflow runs.

**Describe the solution you'd like**
- Run CI Examples when a leptos change is detected
- Do not run CI Examples when a leptos change is detected

**Describe alternatives you've considered**
1. Run Check Examples on leptos change (current behavior)
2. Run both Check Examples and CI Examples on leptos change
3. Run CI Examples on leptos change (proposed)

**Additional context**
- This change will provide earlier detection of breaking changes, making it easier to troubleshoot
- This change will minimize the number of breaking changes that make it into the `main` branch

**Comment by gbj** [comment]
Sorry for my delayed reply to this. Yes, I think this is a good idea, and I'd appreciate a PR very much.
