### ISSUE TITLE
Improvements for the book

### ISSUE THREAD

**Issue by obioma** [leptos-rs/leptos#1845]
**Issues with the book**
When reading the book - which is great btw, thanks for that - I encountered several discrepancies which confused me as beginner - I guess from recent changes. Here the list 

***1. Missing definition for length***
****Location****
https://leptos-rs.github.io/leptos/view/04_iteration.html
The fact that the list is static doesn’t mean the interface needs to be static. You can render dynamic items as part of a static list.
****Suggested change****
```rust
// create a list of N signals
let counters = (1..=length).map(|idx| create_signal(idx));

// each item manages a reactive view
// but the list itself will never change
let counter_buttons = counters
```
to

```rust
// create a list of N signals
let length = 5;
let counters = (1..=length).map(|idx| create_signal(idx));
....
```
or
```rust
// create a list of N signals
let counters = (1..=5).map(|idx| create_signal(idx));
....
```

***2. Old code in sandbox***
****Location****
https://leptos-rs.github.io/leptos/view/04_iteration.html
Check out the <DynamicList/> component below for an example.

Click to open CodeSandbox.
```rust
use leptos::*;

// Iteration is a very common task in most applications.
// So how do you take a list of data and render it in the DOM?
// This example will show you the two ways:
// 1) for mostly-static lists, using Rust iterators
// 2) for lists that grow, shrink, or move items, using <For/>

#[component]
fn App(cx: Scope) -> impl IntoView {
    view! { cx,
        <h1>"Iteration"</h1>
```
****Suggested change****
remove all occurrences of cx or cx: Scope,

Similar in other sandboxes.

***3. Old code in book text***
****Location****
// https://leptos-rs.github.io/leptos/view/04_iteration.html
Dynamic Rendering with the <For/> Component

The `<For/>` component is a keyed dynamic list. It takes three props:

`each`: a function (such as a signal) that returns the items T to be iterated over
`key`: a key function that takes &T and returns a stable, unique key or ID
`view`: renders each T into a view

`view` should be replaced with `children`

***4. Possible improvement for description for setting up nightly***
****Location****
// https://github.com/leptos-rs/leptos/blob/main/docs/book/src/02_getting_started.md

To use nightly Rust, you can run
```shell
rustup toolchain install nightly
rustup default nightly
```
might be changed to

To use nightly Rust, you can either change for all your rust projects by running
```shell
rustup toolchain install nightly
rustup default nightly
```
or only for your actual project
```shell
rustup toolchain install nightly
cd <into your actual development folder>
rustup override set nightly
```
for details kindly refer to https://doc.rust-lang.org/book/appendix-07-nightly-rust.html

**Comment by gbj** [comment]
The CodeSandboxes are unfortunately stuck on 0.4 for a little while — CodeSandbox has tight enough resource constraints that I've had a hard time updating them in place to a newer Rust compiler version and new Leptos version. I'll be continuing to do some work on replacing them over the next few weeks.

For the rest, would you consider making a PR or PRs to make those changes to the book? Your proposals sound good to me.

**Comment by obioma** [comment]
Did so, but then somehow closed it. Reopened again, hope this is fine.
