### ISSUE TITLE
Server Methods

### ISSUE THREAD

**Issue by smessmer** [leptos-rs/leptos#1860]
I'd like to keep some server side context when calling a server function that is pre-initialized on the server, but can be different for different calls. A way to think about it would be to have server functions be methods on objects (i.e. taking `&self`), and allow clients to call the server method on these objects, as long as the object was previously initialized on the server and handed to the client for calling.

Use case: I'm trying to write a webauthn plugin that implements a server<->client protocol.

1. The Webauthn plugin gets initialized and configured on the server
2. A button on the client triggers a protocol run.
3. The protocol triggered by that button needs to call several server functions, in the context of the previously initialized webauthn plugin.

The server function needs access to the plugin object that was previously initialized and configured on the server.

**Describe the solution you'd like**
I'd like to hide the whole protocol behind a minimal interface, i.e. users of the plugin shouldn't have to know about the server functions or how exactly it works. They should initialize a plugin instance on the server, and then can use that instance on the client to initiate the protocols:
```rust
lazy_static! {
   static ref webauthn_plugin = WebauthnPlugin::new();
}

#[component] fn LoginButton() -> impl IntoView {
  view! {
    <input on:click=move |_| webauthn_plugin::login() />
  }
}
```

Then, behind the scenes, the WebauthnPlugin could call a server method, something like this:
```rust
pub struct WebauthnPlugin {
  #[cfg(feature="ssr")]
  config: WebauthnPluginServerSideConfig,
}
impl WebauthnPlugin {
  #[server]
  pub fn login_server_method(&self) {...}

  pub fn login(&self) {
    self.login_server_method();
  }
}
```

**Describe alternatives you've considered**
The WebauthnPlugin `lazy_static` could be fully hidden inside of the plugin module. If there is only one instance of it globally, then there doesn't need to be a way for the client to call it as a method, a server function can just use the context of that one instance.

However, that gives users less flexibility. What if a user wants multiple instances of the plugin?

**Comment by gbj** [comment]
I'm a little confused. You define `login` as a method
```rust
pub fn login(&self) {
  self.login_server_method();
}
```
But you call it as an associated function
```rust
<input on:click=move |_| webauthn_plugin::login() />
```
I can't tell whether this is supposed to be `webauthn_plugin.login()` (accessing the `lazy_static` `webauthn_plugin`, which should probably be named `WEBAUTHN_PLUGIN`), or `WebauthnPlugin::login()`. I think it's the first of those two, right?

If you use a `lazy_static` on the server, that means you want the `WebauthnPlugin` instance to be shared across all users and all requests. If it only exists on the server side, it should be used inside server functions. If that's the case, then why wouldn't you just create the server functions you want to create, export them, and call them?

I'm confused about (library?) users using a `lazy_static` here, and then accessing it in a callback, because this implies it's supposed to exist on the client side... i.e., this will be compiled into the WASM binary.

The reason the server function API is the way that it is is that it allows you to call the function from either the client or the server, with the same function signature, but the server-only resources are only used on the server. Having it as a method implies that the object you're calling it on exists both on the server and in the browser, and I'm not sure how that works here.

**Comment by smessmer** [comment]
> I can't tell whether this is supposed to be webauthn_plugin.login() (accessing the lazy_static webauthn_plugin, which should probably be named WEBAUTHN_PLUGIN), or WebauthnPlugin::login(). I think it's the first of those two, right?

Ah yes, you're right of course. It should have been
```rust
lazy_static! {
   static ref WEBAUTHN_PLUGIN = WebauthnPlugin::new();
}

#[component] fn LoginButton() -> impl IntoView {
  view! {
    <input on:click=move |_| WEBAUTHN_PLUGIN.login() />
  }
}
```

> If you use a lazy_static on the server, that means you want the WebauthnPlugin instance to be shared across all users and all requests. If it only exists on the server side, it should be used inside server functions. If that's the case, then why wouldn't you just create the server functions you want to create, export them, and call them?

The `WebauthnPlugin` instance in my use case would be shared across all users and all requests. The reason for not wanting to just have it one global lazy_static is that there might be several instances of `WebauthnPlugin` and client code should get a choice which one to call. So for my use case, it would be used as a way to parameterize a server function into multiple function instances that have different (but server-defined) configurations. I haven't thought about making it even more dynamic, creating a new instance for each client and allow that client to call its own instance, and that probably wouldn't help my specific use case, but there might be use cases for that as well.

> I'm confused about (library?) users using a lazy_static here, and then accessing it in a callback, because this implies it's supposed to exist on the client side... i.e., this will be compiled into the WASM binary.

The `WebauthnPlugin` mostly exists on the server side, but part of it also exists to the client so the client can call methods on it. It would be a bridge object that has different implementations on the server and on the client. On the server, it holds its configuration and on the client it holds the necessary code to call that server instance. That's why the config itself is guarded with `cfg(feature="ssr")`. The reasoning is that I want the API to be as simple as possible and not have users of `WebauthnPlugin` to worry about what's server or client side. They just create an instance somewhere and then call that instance from the client, and behind the scenes the plugin will keep the right things server or client side and will handle the communication between those parts.

I'm not sure if the API I proposed is the best way to achieve this, it's just a first idea. There might be better ways to keep this kind of context for server calls.

**Comment by smessmer** [comment]
Hm thinking more about it, the variant having per-client objects sounds similar to sessions.

**Comment by smessmer** [comment]
I think this feature request might not be very actionable at the moment, since I now see multiple use cases and I think the design space is too open and needs more exploration. I'm not really sure anymore what the right approach is.

For the per-client variant, server methods could be useful to implement sessions and I think there can be an argument made for improving support for sessions and integrating them directly into Leptos. Server methods could achieve that (create a server object to create a session, then allow the client to call server methods on it), but it would need to be integrated with ssr and I'm not sure how exactly that would work.

For the plugin variant that I was describing with the WebauthnPlugin example, the benefit would be to allow plugins to work without storing global state inside the plugin. A plugin could define its own global context/plugin classes, and client code could instantiate it once (or multiple times, possibly through nested dependencies), and those plugin instances wouldn't interfere with each other because each instance would call the plugin server methods on their own instances of the plugin. But I'm not sure if that benefit by itself justifies an implementation of server methods or if there is a better way to achieve that.

**Comment by gbj** [comment]
Okay! I'm going to close this issue, in that case, but feel free to reopen in the future if you have a particular direction you'd like it to go in and think it should be added to the library.
