### ISSUE TITLE
Selector works in Firefox, not works in Chrome.

### ISSUE THREAD

**Issue by veta666** [leptos-rs/leptos#1884]
Hello!

First of all, thank you for your project!

I have an app on leptos and part of it works in Firefox, but not in Chrome/Chromium. This part contains of updating signal in selector with options.

MRE:

``` rust 
 
 let (b, set_bool) = create_signal(false);
 
 view! {
    <div>
            <table>
                <th>
                    <select>
                        <option
                            on:click=move |_| set_bool.update(|b| *b = true)
                        >
                            "True"
                        </option>
                        <option
                            on:click=move |_| set_bool.update(|b| *b = false)
                        >
                            "False"
                        </option>
                    </select>
                </th>
            </table>
            <p> { move || b.get() } </p>
    </div>
 }
```

I was trying to use different signal's getters (`b.get()`, `move || b.get()` and etc), cause of thinking that I am doing something wrong, but in all cases `b` was updated in Firefox and wasn't changed in Chrome.

Am I doing something wrong? Maybe I need some dependencies for wasm build for Chrome?

I couldn't give links for full project, cause of Company's Safety Policy. 

**Leptos Dependencies**

I work on stable channel.

```toml
leptos = { version = "0.5", features = ["csv"] }
leptos_router = { version = "0.5", features = ["csv"] }
```

**Comment by gbj** [comment]
I don't know, any chance Chrome doesn't fire `click` events when you select an `<option>`? No other errors in the browser?

**Comment by gbj** [comment]
Here's a vanilla JS reproducer. I don't think this has anything to do with Leptos, I think it's just a difference in the events the different browsers emit here.
```js
s = document.createElement("select");
s.innerHTML = `
<option
    onclick="console.log('True')"
>
    True
</option>
<option
    onclick="console.log('True')"
>
    True
</option>
<option
    onclick="console.log('False')"
>
    False
</option>
`;
document.body.appendChild(s);
```

**Comment by veta666** [comment]
Thank you for replay! 

Is it any option to unify these different behaviors in Leptos?
