### ISSUE TITLE
hackernews_js_fetch example fails ci

### ISSUE THREAD

**Issue by agilarity** [leptos-rs/leptos#1886]
**Describe the bug**

``` shell
error: could not compile `leptos_dom`
```
See [CI (examples/hackernews_js_fetch) / Run ci (nightly)](https://github.com/leptos-rs/leptos/actions/runs/6479643286/job/17593603880#logs) log.

**Leptos Dependencies**
N/A

**To Reproduce**
1. Go to **examples/hackernews_js_fetch**
2. Run `cargo make ci`
3. See compile error

**Expected behavior**
Running `ci` should succeed.

**Screenshots**
N/A

**Additional context**
The build has been failing for two weeks.

**Comment by gbj** [comment]
Thanks for pointing this out! I had mentally marked this as "need to merge the PR before releasing 0.5, the actual build works and I can fix `cargo make lint` for it later" and never did it. The fundamental issue was the existence of `.cargo/config.toml` setting the build target always to `wasm32-unknown-unknown`, but I cleaned up the other linting issues too. I think it should be fine now.
