### ISSUE TITLE
Anchor Tag missing target prop

### ISSUE THREAD

**Issue by lsproule** [leptos-rs/leptos#1892]
I think this would be an easy fix and I would love to help do it. I would just need a little help figuring out where this is.

Diagnostics:
1. no method named `target` found for struct `APropsBuilder` in the current scope
   method not found in `APropsBuilder<&str, ((&str,), (), (), (), (), (), (), ())>` [E0599]

**Comment by gbj** [comment]
https://github.com/leptos-rs/leptos/blob/17b33003517928a35fb50d74d56328cbf38dd7c2/router/src/components/link.rs#L65
