### ISSUE TITLE
Allow replace navigation option for forms

### ISSUE THREAD

**Issue by minijackson** [leptos-rs/leptos#1914]
**Is your feature request related to a problem? Please describe.**

Hello, and thanks for this amazing library!

I've implemented something very closed to the search page presented in the [Form tutorial](https://leptos-rs.github.io/leptos/router/20_form.html), with the form submitted on each input. One thing that surprised me is that the window history gets pushed with the new location on each key press, which I find to be a bit much.

**Describe the solution you'd like**

We can maybe add the `replace` property to `Form`, like we have for the `scroll` property. Or maybe we can allow specifying the whole `NavigationOptions`?

**Describe alternatives you've considered**

Not much, I've wondered if I could replace the history manually by overriding `on:submit` or `onsubmit`, but I haven't tried it.

**Comment by gbj** [comment]
> We can maybe add the `replace` property to Form, like we have for the `scroll`property. 

A PR adding this would be completely welcome.
