### ISSUE TITLE
Enable directly serving SSG output as a website

### ISSUE THREAD

**Issue by NiklasEi** [leptos-rs/leptos#1941]
**Is your feature request related to a problem? Please describe.**
I am trying to use Leptos as a static site generator. The output of running the project, should be a directory that can be served as a static website. But currently, Leptos adds `.static` to the html file names generated from static routes and a static route at `/` will be called `.static.html` instead of `index.html`.

For my own project, [I hacked together a solution](https://github.com/leptos-rs/leptos/commit/0d34e14217c1000f2814847195e3d3e3cf3b595a), but it probably breaks other usages.

**Describe the solution you'd like**
The files generated from static routes should be called `<last path part>.html`.

**Describe alternatives you've considered**
Generating a static website could have an additional step that "fixes" the file names.

**Comment by NiklasEi** [comment]
Just found #1594. Feel free to close this issue if you consider it included in the older one.

**Comment by gbj** [comment]
Thanks, yes — I think I will close this, as this is just not supported at the moment, but have summarized the point in #1594 so it doesn't get lost.

The feature at the moment basically supports static routes on the server, and is not yet a full-fledged static site generation tool, although it could be used as the basis for that.
