### ISSUE TITLE
`leptos_router::params_map!` remove from public API

### ISSUE THREAD

**Issue by ChristopherPerry6060** [leptos-rs/leptos#1971]
# Issue

`params_map!` macro is in public API but is broken when used outside of the defining crate.

It is used in unit tests. I would assume it got `macro_exported` for internal use and leaked into public API.

I am not sure if it is meant to be public. Secondly, the first match arm is a compiler error when called.

https://github.com/leptos-rs/leptos/blob/d7ca5f2e961caa7fba8175c58afdd7b1be24a13c/router/src/history/params.rs#L89

# Solution
I can submit a PR for any of the following

* Fix the macro for external use (not sure if anyone would benefit as this has seemingly gone under the radar for quite a while).
* [hide it from the documentation](https://docs.rs/leptos_router/latest/leptos_router/index.html#macros).
* Remove from public API

# Images

![image](https://github.com/leptos-rs/leptos/assets/89366859/0d997d9a-32d5-4774-853f-a6bc694351a6)

 
![image](https://github.com/leptos-rs/leptos/assets/89366859/f7889920-e3ce-46a7-ab8e-fb964ce0fd29)

![image](https://github.com/leptos-rs/leptos/assets/89366859/6cf99f44-2ec8-48ee-bc94-efb7bfa1feda)

**Comment by gbj** [comment]
PR welcome to fix it!
