### ISSUE TITLE
BUG: Unable to test the animated_show (first) example from the main branch when using the included `flake.nix`

### ISSUE THREAD

**Issue by saikatdas0790** [leptos-rs/leptos#1972]
**Describe the bug**
The `cargo make ci` doesn't compile in the example root folder. It is missing NodeJS. After adding NodeJS, it panics with the following.

**To Reproduce**
- Clone the repo and checkout the main branch
- `nix develop` to enter a nix shell with the dependencies specified in `flake.nix` installed
- `cd` into the examples/animated_show` folder
- `cargo make ci`
![image](https://github.com/leptos-rs/leptos/assets/7412443/85a636ed-be56-48b9-ada9-f3f23b4d9fb5)
- Add NodeJS to the dependencies in `flake.nix` like this:
![image](https://github.com/leptos-rs/leptos/assets/7412443/e855d12a-c185-4217-8179-4d0a7300aead)
- Rerun `cargo make ci`
- Panic
![image](https://github.com/leptos-rs/leptos/assets/7412443/0af81f19-e3a4-4251-ad9e-10ef7b26f211)

For the other examples in the same folder, I mostly keep getting this compilation error for `cargo make ci`
![image](https://github.com/leptos-rs/leptos/assets/7412443/eceadd3a-f50f-4885-b620-8242641cf8a3)

**Comment by gbj** [comment]
I am not familiar with Nix and not equipped to debug or fix Nix-related issues, but welcome a PR correcting this.

>  I mostly keep getting htis compilation error for cargo make ci

This reflects an out-of-date version of the Rust nightly compiler, and can be solved with `rustup update nightly` in most environments.

**Comment by saikatdas0790** [comment]
> I am not familiar with Nix and not equipped to debug or fix Nix-related issues, but welcome a PR correcting this.
> 
> > I mostly keep getting htis compilation error for cargo make ci
> 
> This reflects an out-of-date version of the Rust nightly compiler, and can be solved with `rustup update nightly` in most environments.

I was able to fix the above build issues by bumping Rust to the latest nightly toolchain in the included flake in the repo. I have created a pull request for it [here](https://github.com/leptos-rs/leptos/pull/1979).

However, running it locally I'm still running into this for some of the examples:
![image](https://github.com/leptos-rs/leptos/assets/7412443/de424d17-3630-41a1-ab3d-48e4eda86f1f)

I can confirm that the chrome driver was downloaded to that location so I'm a bit clueless why this is failing.
![image](https://github.com/leptos-rs/leptos/assets/7412443/220e13c0-f444-46eb-9a0d-5bfab7b04fe1)

Any ideas?

**Comment by benwis** [comment]
This should be closed by a recent PR. Feel free to reopen if not
