### ISSUE TITLE
Some component prop types lead to Javascript exceptions

### ISSUE THREAD

**Issue by UgnilJoZ** [leptos-rs/leptos#1988]
## Describe the bug
**No struct that contains a `time::OffsetDateTime` attribute can be used as a component prop.**

I am trying to use the type `OffsetTime` from the `time` crate in a component prop.

The following struct **works** when used as the type of a component prop:
```rs
pub struct EntryType {
    pub elevation: f64,
}

#[component]
fn Entry(e: EntryType) -> impl IntoView {
    view! {
        <p>
            {format!("ele: {}", e.elevation)}
        </p>
    }
}

fn main() {
    mount_to_body(|| view! { <Entry e=EntryType {elevation: 12.0 }/> })
}
```

This renders to the following HTML:
```html
<p>ele: 12</p>
```

This changes when I add an attribute of the type `time::OffsetDateTime` crate to my struct definition:

```rs
pub struct EntryType {
    pub elevation: f64,
    pub time: OffsetDateTime,
}
…
fn main() {
    mount_to_body(|| view! { <Entry e=EntryType {elevation: 12.0, time: OffsetDateTime::now_utc()}/> })
}
```

As a result, the component is not rendered and a Javascript exception appears on the browser console:
```
Uncaught (in promise) RuntimeError: unreachable executed
    __wbg_finalize_init http://127.0.0.1:8081/lepta-d72f58285d4ba638.js:385
    __wbg_init http://127.0.0.1:8081/lepta-d72f58285d4ba638.js:421
    async* http://127.0.0.1:8081/:12
lepta-d72f58285d4ba638_bg.wasm:565992:1
```

## Dependencies

```toml
[dependencies.leptos]
version = "0.5.2"
features = ["csr", "nightly"]

[dependencies.time]
version = "0.3.30"
```

## To Reproduce
Minimal steps to reproduce the behavior:

1. Define a struct that contains `time::OffsetDateTime`.
2. Create a component that uses the struct as property type

## Expected behavior

1. There is no JS exception happening.
2. The component is rendered as defined.

**Comment by gbj** [comment]
Not all features of every crate are supported in WebAssembly. Do you have the `wasm-bindgen` feature enabled on your `time` dependency? ([See `time` docs here](https://docs.rs/time/latest/time/) for feature list.)

**Comment by gbj** [comment]
Just ran it myself to confirm, and yes, this works as expected if you correctly set the `wasm-bindgen` feature on `time`:
```toml
time = { version = "0.3", features = ["wasm-bindgen"] }
```

**Comment by UgnilJoZ** [comment]
Of course, thank you. I knew I forgot something.
