### ISSUE TITLE
Error running hackernews-js-fetch example

### ISSUE THREAD

**Issue by kyeotic** [leptos-rs/leptos#1992]
**Describe the bug**
`trunk serve` produces an error when running the hackernews-js-fetch example

**Leptos Dependencies**

[Example Cargo.toml](https://github.com/leptos-rs/leptos/blob/main/examples/hackernews_js_fetch/Cargo.toml)

**To Reproduce**
1. Clone this repo
1. Cd into `examples/hackernews_js_fetch`
2. Copy of the `style.css` file from the `public` dir to root (something requires it here)
3. Run `trunk serve`

Output
```
    Finished dev [unoptimized + debuginfo] target(s) in 16.40s
2023-11-05T20:17:49.079340Z  INFO fetching cargo artifacts
2023-11-05T20:17:49.172793Z ERROR ❌ error
error from HTML pipeline

Caused by:
    0: error from asset pipeline
    1: cargo artifacts not found for target crate

```

**Expected behavior**
Trunk should build and serve the example

**Comment by kyeotic** [comment]
@gbj That commit does not fix the problem for me. The problem persist whether the css file is present, or if I remove that tag entirely.

**Comment by gbj** [comment]
@kyeotic Thanks. I had only looked at it quickly. This example is not set up for Trunk at all, and the README is erroneous -- the original contributor left it in by accident. This example is only for SSR in a JS-based WASM environment. See the regular `hackernews` example for a version that does work with CSR with trunk.

**Comment by kyeotic** [comment]
Is trunk only for CSR? I was definitely confused about that. I am looking for JS-based WASM (Deno Deploy). Does that only work with SSR?

**Comment by gbj** [comment]
> Is trunk only for CSR?

Correct. `trunk serve` runs a little dev server for you, but `trunk build` just outputs an empty `index.html` and the JS/WASM you need for client-side rendering, which can be served from any server.

>  I am looking for JS-based WASM (Deno Deploy). Does that only work with SSR?

I'm a little confused. This example is specifically for how to do server-side rendering in a JS-based WASM environment like Deno Deploy. If you are just trying to serve a SPA-style empty `index.html` with some JS/WASM, with all the rendering work done in the browser, you should just use `trunk build` on a CSR example, and you can deploy it however you want. If you want to render your app to HTML in Deno Deploy and serve it, you should use this example.

**Comment by kyeotic** [comment]
Sorry, what I was getting at was support for both. SSR with CSR+hydration.

"SSR in a JS-based WASM environment" is what I am after, since I specifically want to run this on Deno Deploy. You said the README was erroneous, and pointed to the other hackernewws example for CSR. That still leaves this example with no working instructions.

**Comment by gbj** [comment]
> Sorry, what I was getting at was support for both. SSR with CSR+hydration.
> 
> "SSR in a JS-based WASM environment" is what I am after, since I specifically want to run this on Deno Deploy. You said the README was erroneous, and pointed to the other hackernewws example for CSR. That still leaves this example with no working instructions.

I don't understand. The working instructions for this example are in the README:
```
deno task build
deno task start
```

**Comment by gbj** [comment]
There may be some other misunderstanding here. I said that the part of the README saying you can run a client-side-rendering-only version with Trunk (and no server-side rendering) was incorrect, deleted it, and pointed to the other hackernews example for CSR with Trunk, which is what you originally described.

The piece of the README that describes server-side rendering with Deno works, and has always worked. If that is what you want, the instructions to build and run the example with Deno are the correct ones.

**Comment by kyeotic** [comment]
Ah, ok, I thought you meant the whole README was wrong.

I am able to get a built version running from deno. Thank you :)

**Comment by kyeotic** [comment]
The dev loop for this is a bit painful: stop, rebuild, restart deno, repeat. A watch task would go a long way.
