### ISSUE TITLE
Type alias support for server functions return types

### ISSUE THREAD

**Issue by paul-hansen** [leptos-rs/leptos#1993]
To save some typing I wanted to make an alias for common server function return types that I use.
For example:
```rust
pub type FormResponse<T> = Result<FormResult<T>, ServerFnError>;

#[server(Test, "/api")]
pub async fn test() -> FormResponse<String> {}
```

Unfortunately the server macro doesn't like that, returning this error:
```
server functions should return Result<T, ServerFnError>
```
Even though FormResponse<T> is an alias for a type that does work.

This isn't a big deal, but if it's an easy fix for someone it'd be appreciated!

**Comment by gbj** [comment]
The main issue here is that proc macros don't have access to anything other than a stream of tokens, i.e., it has no way of knowing that you've defined a type alias and that information isn't actually determined until later in the compilation process.

So, it seems to me that we can either
1) remove this check from the server macro, which would allow you to use a type alias but possibly cause confusing compiler errors if people use an incorrect return type,
2) keep it and it's not possible to alias
3) provide our own type alias that the macro also recognizes, which would be shorter than typing out `Result<T, ServerFnError>` but still wouldn't cover your use case

**Comment by paul-hansen** [comment]
Hmm, I do like having the check and 3 doesn't seem like a very big win either. I think that answers it for me so I'll close this for now, feel free to reopen if you want to pursue something though.
