### ISSUE TITLE
Leptos Book Enhancement Proposals - for discussion

### ISSUE THREAD

**Issue by diversable** [leptos-rs/leptos#2007]
I've been reading through the docs, and I think there's a few items we could add/expand in the docs / book that I think would be helpful for newcomers to Leptos.

Specifically, what I would suggest adding to the book includes:

1. a section on the burgeoning ecosystem of crates / projects around Leptos, such as leptos-use, leptos-query, leptonic, leptos-i18n, etc. I think it would help make these projects more discoverable and help newcomers at the same time by including links and brief descriptions of the projects in the book, perhaps as the last chapter. 

2. possibly(?) a section on using Leptos as the UI along with the Tauri desktop/mobile app framework. Until the work on custom renderers is complete, Tauri might be the best way of producing non-web apps with Leptos (imho) - it would be nice to alert newcomers to this possibility, along with relevant links and perhaps even a 'quickstart with Leptos/Tauri' page to get users up and running quickly.

3. move the info from the appendix on DX into a new section that comes after the "getting started" section. You could call this new section "Getting Ready for Leptos Development" or something like that. Why? I think it would be helpful to surface DX improvements up front to help put Leptos' 'best foot forward' -  it'd be really nice for new users to benefit from better DX while they're initially getting started with Leptos

4. create a new section on "Contributing to Leptos" at the end of the book - providing users a few different options of how to meaningfully contribute to Leptos, such as feature and docs enhancements to Leptos itself, and including links to ecosystem crates that are looking for new contributors, might help take some pressure off the core maintainers. We could create subsections on Leptos internals in this section, which might include things like "How the Reactive System Works", and maybe how other internal modules work, which would be a great way of onboarding new maintainers to Leptos.

5. Move the section on "Optimizing WASM Binary Size" from an appendix into the section (or a subsection) of "Deployment", as that's where optimizing binary size is most relevant...

I'll leave it at just those suggestions for now, as the above represents a good chunk of work on the book already. 

I'd like to get some discussion going on this topic to see if there's any interest in making some modifications to the book, using the above as a starting point for discussions. Once the community has a chance to chime in to provide feedback and further direction, I can start implementing the requested changes.

**Comment by chrisp60** [comment]
I believe the largest chance for improvement and growth of the docs is just dealing with this in small chunks. This repo has a lot to cover and moves quickly, that leaves a lot of opportunity for docs to become a burden on maintainers.

I for one am a big advocate for docs with small word counts, powerful doctests, and meaningful examples. When I read docs with those attributes I tend to understand concepts in a more meaningful way.

**Anecdotes aside, before adding additional sections I would put effort into condensing, rewriting, and updating docs to reduce the area that needs to be maintained.** It is strange but sometimes less documentation can lead to much better documentation. Just my thoughts. Docs are something I plan and working on as my work schedule slows down.

**Comment by gbj** [comment]
> 1. a section on the burgeoning ecosystem of crates / projects around Leptos, such as leptos-use, leptos-query, leptonic, leptos-i18n, etc. I think it would help make these projects more discoverable and help newcomers at the same time by including links and brief descriptions of the projects in the book, perhaps as the last chapter.

Perhaps by including a link to [awesome-leptos](https://github.com/leptos-rs/awesome-leptos), which is linked in the README and contains references and short descriptions of all these libraries and more? 

> 2. possibly(?) a section on using Leptos as the UI along with the Tauri desktop/mobile app framework. [...]

Fine by me — I have no Tauri experience, open to contributions if someone wants to write a chapter.

> 3. move the info from the appendix on DX into a new section that comes after the "getting started" section. 

Fine by me.

> 4. create a new section on "Contributing to Leptos" at the end of the book [...]

Check out `ARCHITECTURE.md` and `CONTRIBUTING.md` in this repo and feel free to PR changes or additions to them, as well as linking them from the book.

> 5. Move the section on "Optimizing WASM Binary Size" from an appendix into the section (or a subsection) of "Deployment", as that's where optimizing binary size is most relevant...

Fine by me.

> I'm not sure if anyone's formally "in charge" of the docs right now

Just me!

> but I'd like to work with whoever is interested in improving the state of the documentation for the benefit of the whole community; if nobody's currently in charge of the book/docs, I'll step up and help myself. [...] I agree that the docs could be updated and re-written in areas which could make the docs more 'efficient' to read & make Leptos easier to understand and work with – @diversable 

> before adding additional sections I would put effort into condensing, rewriting, and updating docs to reduce the area that needs to be maintained. It is strange but sometimes less documentation can lead to much better documentation. – @chrisp60 

I'm very open to help with the docs. In general, at an early stage the creator of the framework is both the worst person to write the docs and the only person able to/interested in it. We're probably at a good point of transition now from that early stage to the medium stage where a docs team (informal or formal) would be useful.

I'm hearing from both of you a general felt need to edit some portions of the docs. It's not clear to me exactly what the specific concerns are.

From my perspective, the docs.rs docs and the examples in this repo should constitute "minimal viable docs" for the project, with the brief content and doctest examples that @chrisp60 describes. The guide is a much chattier, wordier intro to the framework. My hope is that if people read the book and respond "cut the crap, how do I use resources?" they will feel free to skip the chapter and go to docs.rs.

**Comment by blorbb** [comment]
i think one problem is discoverability - there are quite a few (mostly recent) features that were added but aren't included in the book (`#[prop(attrs)]`, `#[slot]`s, `<Portal>`, `slice!`, `Callback`, `TextProp`, `ViewFn`, `MaybeProp`, extra signal stuff (`batch`, `untrack`, `on_cleanup`)) that I think could be beneficial for people to _know of_. 

Maybe a full discussion of the features doesn't need to be included in the book, but simply mentioning that these exist could be helpful, so that people don't try to reinvent the wheel. For example, the [Components and Props](https://leptos-rs.github.io/leptos/view/03_components.html) section could mention (and briefly describe the use cases of) `#[slot]`s, the handy types like `Callback`, `TextProp`, `MaybeProp` and `ViewFn`, with links to the docs.rs pages. Same thing in the Reactivity section, the signal helper functions `batch` and `untrack` could be briefly mentioned.

Perhaps a more ambitious undertaking could be restructuring the leptos modules. Currently, pretty much everything is just re-exported in `leptos::*`, which makes it easy to use in code but difficult to navigate the docs. Maybe having more public modules (e.g. `components` for all the components provided by leptos, `props` for all the extra structs) but still re-exporting in the crate root could help. Maybe some functions like `batch` and `untrack` could be moved to be associated functions of the `Signal` type?

These are just my random thoughts and opinions, a different approach could be better so feel free to disagree. I wouldn't mind helping out with this task too.

**Comment by chrisp60** [comment]
One question I have is likely directed entirely towards @gbj is how much should this be dug into prior to 0.6? Do you expect most of the public API to remain the same, or are we looking at a general upheaval of previous concepts?

And by all means an "I don't know yet" is a very acceptable answer. I'm excited to see whatever you are cooking up and I believe most of the community is more than willing to be patient. Just genuinely curious on a timeframe / *signal* of what's to come. The whispers I have heard of `Send` sound exciting.

**Comment by chrisp60** [comment]
> Perhaps it's time to split the book out into its own repo under the `leptos-rs` org so that the book's issues don't clutter up the issues in the Leptos repo, and so that we can grant permissions to contributors to the book separately from contributors to the Leptos core codebase... what do you think, @gbj?

I think this is a really great first step and could help alleviate the burden falling entirely on one person's shoulders. At the end of the day, even just reviewing pull requests can become a mental workload all within itself.

> Understood, and agreed. The book has a 'personality' or 'voice' to it right now and I don't want to take that away.

I agree, I may have failed to separate my opinions on API docs Vs helper guides, but I do enjoy the more casual nature of the book.

**Comment by gbj** [comment]
I have had a busy month of work recently so have been a little quiet in this thread this week. Thank you all for the discussion so far!

@diversable and @chrisp60, this all makes sense to me. I think everyone is basically on the same page.

For now, I'd like to keep the book/docs in the same repo. Small changes are easy to review, and at least for now I should probably check the accuracy of anything substantive. It shouldn't ever be hard for me to review docs PRs within a few days.

I might not have much time coming up to do more writing for the docs so I really appreciate the contributions.

******

Re: 0.6 — Conceptually, there will not be any big departures. i.e., the relationship between signals, memos, and effects, the use of `move || /* whatever */` for reactivity, the "components run once to set things up" model, and so on are all still true. One of my goals for the release is for most normal component code to "just work" as written.

There will probably be changes around the edges of things like the naming of `create_local_resource`, the way Suspense works (by using `async` blocks!) and so on.

But I also don't have a precise timeline for this work. I feel like I've spent the last ~year fixing bugs and adding needed features to the point that 0.5 is usable and correct, and I'm taking my time making 0.6 amazing. 

So don't let the prospect of 0.6 slow down work on making 0.5 docs even better. I do not anticipate needing to throw out any new work described above.

**Comment by gbj** [comment]
Ok, sorry I haven't had much time to engage recently! As a starting point, I have created an empty repo at https://github.com/leptos-rs/book

I have not done anything yet to migrate the source for the book into that repo, or migrate the GitHub action to deploy the book into that repo. 

It can be used for issue tracking and discussion, and PRs to move the book over are very welcome if someone has time to get to it before I do.

**Comment by gbj** [comment]
Closing this issue as the https://github.com/leptos-rs/book repo now exists to track these
