### ISSUE TITLE
Possibly broken generics when using #[island]

### ISSUE THREAD

**Issue by gibbz00** [leptos-rs/leptos#2018]
```rust
trait SomeTrait {}

// Works
#[component]
pub fn TestComponent<S: SomeTrait>(_some_trait: PhantomData<S>) -> impl IntoView {}

// Errors
#[island]
pub fn TestIsland<S: SomeTrait>(_some_trait: PhantomData<S>) -> impl IntoView {}
```
```
error[E0412]: cannot find type `S` in this scope
  --> main.rs:26:58
   |
26 | pub fn TestIsland<S: SomeTrait>(_some_trait: PhantomData<S>) -> impl IntoView {}
   |                                                          ^ not found in this scope
   |
help: consider importing one of these items
   |
1  + use crate::views::html::S;
   |
1  + use leptos::html::S;
   |
```
Might be related to https://github.com/leptos-rs/leptos/pull/1636, that's what I used for reference.

**Leptos Dependencies**

(With `cargo update`)

leptos_axum = { git = "https://github.com/leptos-rs/leptos", features = ["experimental-islands"], optional = true }
leptos = { git = "https://github.com/leptos-rs/leptos", features = ["nightly", "experimental-islands"] }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", features = ["nightly"] }
leptos_router = { git = "https://github.com/leptos-rs/leptos", features = ["nightly"] }

**Comment by gbj** [comment]
I would not expect generics to work on an island. I can try to work on a better error message at some point. If you need a generic island you can use a generic component that's used by multiple concrete islands. But because each island needs to be separately callable from JS there isn't really a way for generics to work on them.

**Comment by gibbz00** [comment]
Got it, thanks!
