### ISSUE TITLE
Panic when using closure returning a signal in `inner_html` attribute.

### ISSUE THREAD

**Issue by titaniumtraveler** [leptos-rs/leptos#2023]
**Describe the bug**

Panic when returning a `ReadSignal` from a closure used in an attribute.

Minimal example:
```rust
use leptos::*;

fn main() {
    let text = create_rw_signal("123".to_string());
    mount_to_body(move || {
        view! {
            <div inner_html = move || { text }/>
        }
    })
}
```

**Leptos Dependencies**

`Cargo.toml`:
```toml
leptos = { version = "0.5.2", features = ["csr"] }
```

Other dependencies:
`trunk 0.17.5`
`wasm-bindgen 0.2.88`

**To Reproduce**
1. `git clone https://github.com/titaniumtraveler/leptos-test-1`
2. `trunk serve`
3. `firefox http://127.0.0.1:8080`
4. Panic in browser console when executing the wasm with following message:
    ```
    Uncaught (in promise) RuntimeError: unreachable executed
        __wbg_finalize_init http://127.0.0.1:8080/leptos-test-1-5c01ef5f7a5b7def.js:360
        __wbg_init http://127.0.0.1:8080/leptos-test-1-5c01ef5f7a5b7def.js:396
    leptos-test-1-5c01ef5f7a5b7def_bg.wasm:569714:1
    ```

**Expected behavior**

The panic not to happen and it to just work.

**Additional context**

It works fine when using `text.get()` instead of `text` in the closure body.

**Comment by gbj** [comment]
So, this is kind of a tough one.

On the one hand, you should never need to have a function that returns a signal (or another function) as an attribute value. Your example is better written as either
```
<div inner_html=move || text.get()/>
```
or simply
```
<div inner_html=text/>
```
either of which works.

On the other hand, panicking in this situation and forcing you to track down the bug is annoying.

The attached PR means your example does work, which is nice -- but it does some additional work to do it, so it's best to avoid this situation if possible.

**Comment by lpotthast** [comment]
Hey, would you like to add a `tracing::warn` event if this case is encountered? Like when calling a reactive accessor outside a tracking context?
Occurrences would otherwise go by (probably) completely unnoticed.

**Comment by titaniumtraveler** [comment]
> Hey, would you like to add a tracing::warn event if this case is encountered? Like when calling a reactive accessor outside a tracking context?
I definitely agree that that would be really helpful. Especially because when *not* using [`console_error_panic_hook`](https://github.com/rustwasm/console_error_panic_hook) the error message is impossible to understand, leading to a frustrating debug experience.

**Comment by gbj** [comment]
The actual panic is fixed in https://github.com/leptos-rs/leptos/commit/68c91a732d745fc441a7280b8188aa32051c9d48. I'm making a separate PR (#2045) to give a clearer warning in the working but less than ideal situation.
