### ISSUE TITLE
Leptos Book Enhancement Proposal: Add Spin serverless WASM/WASI framework as a deployment option for CSR apps

### ISSUE THREAD

**Issue by diversable** [leptos-rs/leptos#2032]
I've been exploring options for deploying Leptos apps, and one option that has seen some traction in prior issues (both in the Leptos issue tracker and the Spin issue tracker) has been deploying Leptos apps to Fermyon's Spin serverless WASM/WASI platform. 

~~This is currently only possible for Leptos CSR apps~~; I currently have a working CSR 'getting started' example now, and will develop an SSR example as well. 

The example repo can be found here: https://github.com/diversable/leptos-with-spin

So, I propose adding a small section to the "Deployment" chapter that opens up the possibility of deploying ~~CSR~~ apps to Spin. 

This could either 1) take the form of adding a link to the example repo I have, or 2) we could refactor the "Deployment" chapter into 2 sub-chapters - 1 sub-chapter dealing with deploying CSR apps, and 1 sub-chapter for deploying SSR apps. 

Does the community have any thoughts on which route we should take?

1) just post the link to the example repo
2) refactor the "Deployment" chapter to separate CSR app deployment from SSR app deployment
3) neither of the above

Please let me know!

**Comment by gbj** [comment]
I'm fine with either idea, given that 2 is probably better long term but 1 is very easy to do.

Feel free to make a PR for either one.

AFAIK Spin *should* now work with Leptos SSR but there's not an existing template or integration to do so.
