### ISSUE TITLE
Add a `Store` derive macro.

### ISSUE THREAD

**Issue by jquesada2016** [leptos-rs/leptos#2042]
**Is your feature request related to a problem? Please describe.**

I hadn't realized, because I hadn't read through the SolidJS's API before, but this issue would preempt #1635. 

**Describe the solution you'd like**

It's useful to be able to bundle many `create_signal` calls into a single one under a struct.

```rust
let (a, set_a) = create_signal(0);
let (b, set_b) = create_signal(0);
let (c, set_c) = create_signal(0);
```

The above can be re-written as

```rust
#[derive(Default, Store)]`
struct Bundle {
  a: u8,
  b: u8,
  c: u8
}

let (read, write) = Bundle::default().create_store();

assert_eq!(0, read.a());

write.b.set(7);

assert_eq!(7, read.b());
```

The macro can use 3 modes, one for `Signal`, one for `RwSignal`, and one for `StoredValue`.

**Describe alternatives you've considered**

Well, the alternative would be to continue trying to piggy back off the `create_slice` way of thinking about this problem.

**Additional context**
N/A

**Comment by gbj** [comment]
See the `Store` APIs in 0.7 and the [`stores`](https://github.com/leptos-rs/leptos/blob/main/examples/stores/src/lib.rs) example.
