### ISSUE TITLE
Notifying trigger in component breaks the trigger

### ISSUE THREAD

**Issue by PaulWagener** [leptos-rs/leptos#2048]
When calling `notify()` on a trigger directly in a component causes all subsequent `notify()` calls to silently fail.

In the below example the expected behavior is that the button keeps printing "Triggered" when clicked, but it does nothing instead.

A workaround is wrapping the notify call in a `queue_microtask()` call.

Tested in Leptos version 0.5.2

````rust
use leptos::*;
use leptos::logging::log;

fn main() {
    mount_to_body(|| view! { <App /> })
}

#[component]
pub fn App() -> impl IntoView {
    let trigger = create_trigger();

    create_effect(move |_| {
        trigger.track();
        log!("Triggered");
    });

    trigger.notify(); // This line breaks the trigger

    view! {
        <button on:click=move |_| trigger.notify()>Notify</button>
        <Child trigger=trigger />
    }
}

````

**Comment by PaulWagener** [comment]
While I agree that the minimal example is contrived and useless. I encountered the bug in a situation in which I needed a trigger that triggered on certain child components being added or removed (with the trigger itself being provided via context). Hence the notify call in the render code to signal that a child component was mounted.

**Comment by gbj** [comment]
... well, sometimes once you figure out what the heck is going on, sometimes it's easier than anticipated. 

#2059 should fix this (and also another issue with triggers #1948). Feel free to test your actual use case against that branch and let me know if it fixes it, but I think it will.

**Comment by PaulWagener** [comment]
Yep, that commit indeed fixes the problem. Thanks a lot for investigating and fixing it!
