### ISSUE TITLE
Would it be useful to add a step, about installing 'Trunk' to the examples/README.md file

### ISSUE THREAD

**Issue by hpepper** [leptos-rs/leptos#2055]
**Is your feature request related to a problem? Please describe.**
I had missed that I needed to install 'trunk' in order to build the examples.

**Describe the solution you'd like**
Would it be useful to add a step, about installing 'Trunk' to the examples/README.md file, in the Prerequisites section?

- [Trunk](https://github.com/thedodd/trunk)
  - Run `cargo install --locked trunk`

So it would look like this

## Prerequisites

Example projects depend on the following tools. Please install them as needed.

- [Rust](https://www.rust-lang.org/)
- Nightly Rust
  - Run `rustup toolchain install nightly`
  - Run `rustup target add wasm32-unknown-unknown`
- [Cargo Make](https://sagiegurari.github.io/cargo-make/)
  - Run `cargo install --force cargo-make`
  - Setup a command alias like `alias cm='cargo make'` to reduce typing (**_Optional_**)
- [Trunk](https://github.com/thedodd/trunk)
  - Run `cargo install --locked trunk`
- [Node Version Manager](https://github.com/nvm-sh/nvm/) (**_Optional_**)
- [Node.js](https://nodejs.org/)
- [pnpm](https://pnpm.io/) (**_Optional_**)

**Describe alternatives you've considered**
None considered.

**Additional context**
None.

**Comment by gbj** [comment]
I think that's a wonderful idea. Any chance you'd like to make a PR?

**Comment by hpepper** [comment]
PR create, thanks :-)
[Add instruction to install trunk to examples/README.md](https://github.com/leptos-rs/leptos/pull/2064)
