### ISSUE TITLE
server functions are a bit restrictive

### ISSUE THREAD

**Issue by dvc94ch** [leptos-rs/leptos#2062]
I'd like to be able to create a regular REST api using axum and derive the client side actions/resources. I realize I can do this manually using `create_local_resource` which I'll probably do for now, but would be nice to also integrate with ssr somehow.

**Comment by gbj** [comment]
There's nothing stopping you from doing this, is there? You can just create a REST API use it. If you use `create_resource`, you'll even get streaming data from the server and suspense support. In fact, server functions are just an abstraction over a REST API.

**Comment by dvc94ch** [comment]
ok thanks
