### ISSUE TITLE
Style display error when the style component specifies the ID

### ISSUE THREAD

**Issue by luoxiaozero** [leptos-rs/leptos#2070]
**Describe the bug**

When the style component specified the ID, there was a problem with the style display after the page was jumped.

**Leptos Dependencies**

For example:
```toml
leptos = { version = "0.5.2", features = ["csr"] }
leptos_meta = { version = "0.5.2", features = ["csr"] }
leptos_router = { version = "0.5.2", features = ["csr"] }
```

```rust
use leptos::*;
use leptos_meta::*;
use leptos_router::*;

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();
    view! {
        <Router>
            <Routes>
                <Route path="/" view=Home/>
                <Route path="/apple" view=Apple/>
            </Routes>
        </Router>
    }
}

#[component]
pub fn Home() -> impl IntoView {
    let navigate = use_navigate();

    let on_click = move |_| {
        navigate("/apple", Default::default());
    };
    view! {
        <button on:click=on_click>
            <Style id="red">
                "button { color: red }"
            </Style>
            "goto apple page"
        </button>
    }
}

#[component]
fn Apple() -> impl IntoView {
    let navigate = use_navigate();

    let on_click = move |_| {
        navigate("/", Default::default());
    };
    view! {
        <button on:click=on_click>
            <Style id="red">
                "button { color: red }"
            </Style>
            "goto home page"
        </button>
    }
}

fn main() {
    leptos::mount_to_body(App)
}
```

**To Reproduce**

Click the button repeatedly to jump to the page, and the font color is once red and once black.

**Expected behavior**

The font is always red.

**Screenshots**

**Additional context**

https://github.com/leptos-rs/leptos/blob/061213ca783ed352370b28dfaddd30eb67bcea97/router/src/components/routes.rs#L488

```rust
root.as_ref().map(|route| {
      let (outlet, disposer) = outlet((*route).clone());
      drop(std::mem::replace(
              &mut *root_disposer.borrow_mut(),
               Some(disposer),
      ));
      outlet
})
```

You should take the last disposer and drop it before executing the outlet function.

**Comment by luoxiaozero** [comment]
https://github.com/leptos-rs/leptos/blob/061213ca783ed352370b28dfaddd30eb67bcea97/router/src/components/outlet.rs#L56

There are also problems.

**Comment by gbj** [comment]
Thank you for the bug report, and especially for identifying the issue! That is very helpful. I believe PR #2071 addresses *both* of your points, but please let me know if it does not fix the issue for you.
