### ISSUE TITLE
module restructuring proposal

### ISSUE THREAD

**Issue by blorbb** [leptos-rs/leptos#2086]
The module structure of `leptos` is almost completely flat, making it hard to find certain items or add documentation about groups of items. I discussed this briefly in https://github.com/leptos-rs/leptos/issues/2007#issuecomment-1807411843

I suggest we restructure the modules such that there are clearer sections (e.g. reactive, dom, async, components etc.. get their own module), and switch to using a prelude for common imports (`use leptos::prelude::*;` over `use leptos::*;`)

Restructuring the modules is obviously a major breaking change, and would probably also cause a lot of merge conflicts with existing PRs too. Maybe this change could be done right before 0.6, when there are probably fewer ongoing PRs and all the changes can be made at once. For the majority of users, the only changes should be changing `use leptos::*;` to `use leptos::prelude::*;`, and maybe a few more imports for more uncommon items not included in the new prelude.

Below is my idea for a potential restructure; please add your own suggestions/feedback too! hopefully the half made-up syntax makes sense. I didn't include every single module / crate, only the most commonly used ones

```rust
crate leptos_reactive {
    // move `Callback` to `leptos` instead? it's not used anywhere internally,
    // just a helper type, not really reactive either.

    // make these `pub mod` instead of re-exporting at crate root
    pub mod hydration { ... }
    // renamed from `runtime`
    pub mod runtime_primitives { ... }
    pub mod macros { ... }

    pub mod reactive {
        // traits are accessible in `crate::reactive::*` or `crate::reactive::traits::*`
        pub mod traits { SignalGet, SignalDispose, SignalWith, IntoSignal, etc... }
        pub use traits::*;

        pub mod primitives { 
            // move these files from old modules over here
            crate::{diagnostics, trigger, node} 
        }

        signals, Memo, Effect, watch, slices, selector, MaybeSignal, MaybeProp, TextProp
        // should `batch`, `on_cleanup`, `untrack`, `untrack_with_diagnostics`
        // be moved from `crate::runtime` to here?
    }

    // better name? anything that is stored in the runtime but not reactive
    pub mod stores {
        context, StoredValue
    }

    // does this need to be its own module, or is `crate::Oco` fine?
    pub mod oco { Oco }

    // rename this? i don't like the look of the trailing _
    pub mod async_ {
        // not sure where `queue_microtask` should go, not exactly async but 
        // it's mainly used in Resources
        Resource, SuspenseContext, spawn_local, queue_microtask
    }

    pub mod prelude { ... }
}

// rename the folder `router` to `leptos_router`
crate leptos_router {
    // module tree looks fine: make everything `pub mod` and re-export in `prelude` instead.
}

crate leptos_dom {
    // modules look fine, but maybe move the stuff in `lib.rs` to separate file(s)
    // does this need a prelude?
}

// rename the folder `meta` to `leptos_meta`, otherwise looks fine, no need for a proper module tree
// should this have a prelude?
crate leptos_meta;

// i don't really use server functions much so I'm not sure what's used commonly/uncommonly
// seems like some of the stuff in `lib.rs` could be moved to a separate file though.
crate server_fn;

crate leptos {
    // re-export
    pub use leptos_reactive::*;
    // most of the `leptos_dom` re-exports should be moved to prelude
    pub use leptos_dom as dom;
    pub use leptos_macro as macros;

    // additional_attributes is deprecated, could remove in 0.6?

    pub mod components {
        Await, AnimatedShow, Show, Transition, Suspense, Provider, Portal, For, ErrorBoundary
    }

    #[doc(hidden)]
    pub mod component_builder {
        // all the stuff in lib.rs (except type AttributeValue)
        // could also move crate::children::ToChildren here
    }

    // move `crate::children::Children*` types here? remove `children.rs`

    // any other helpful types / structs
    pub mod helpers {
        ViewFn, Callback // (Callback moved from leptos_reactive)
        // maybe also `pub use leptos_reactive::reactive::{MaybeProp, TextProp}`
    }

    pub mod prelude { ... }

    // what does leptos_config do? no clue what to do with that.
}
```

This restructure would then make it a lot easier to add module documentation to provide higher-level overviews and improve the discoverability of features.

An alternative to this would just be adding all of this documentation in the leptos book instead, but that may make the book too large and it's easier to quickly read through docs within the IDE instead of the book.

**Comment by gbj** [comment]
For now I'll just say that switching to a `prelude` and restructuring exports/modules is very much on my agenda for 0.6, and I'm very open to thoughts on the most ergonomic way for that to be structured. Thanks for thinking through this. The ability to add module-level docs is great too.

**Comment by blorbb** [comment]
@gbj I've had a look through rustdoc to see the new module structure, and I'm really liking it so far! I have some thoughts, though these are very opinionated and minor, so feel free to disagree with many of them :)

In no particular order (numbered to make it easy to reference):

1. [`leptos::attr::Attribute::hydrate<const FROM_SERVER: bool>`](https://docs.rs/leptos/0.7.0-beta/leptos/attr/trait.Attribute.html#tymethod.hydrate) - the const generic here could be an enum instead, to make it clearer what `FROM_SERVER = false` means (does it mean it's from the client?)
2. Items in [`leptos::context`](https://docs.rs/leptos/0.7.0-beta/leptos/context/index.html) are suffixed with `_context` - maybe it could be nicer to use a qualified path instead? Similar to the std `mpsc::channel`, these could also be used as `context::provide()`, `context::get()` (renamed from `use_context()` since use is a keyword).
	1. It looks like `expect_context()` is missing (rename to `context::expect()`?)
	2. [`leptos::mount`](https://docs.rs/leptos/0.7.0-beta/leptos/mount/index.html) is similar, rename to `mount::{to_element, to_body, to_renderer}` (maybe remove `to_` as well?).
	3. If these changes are made, the prelude should probably just export `mount` and `context` instead of `mount::*` and `context::*`.
3. Should the leptos provided components (`Show`, `For`, `Suspense`, etc) be in modules based on its purpose (current), or just one big `components` module? Not sure which is better.
7. Is it possible to only export components but without their `*Props` struct too? `view!` doesn't need them to be public, and you could maybe add something to make it easy to build using builder pattern like `Suspense::builder()` instead of `leptos::component::component_props_builder(Suspense)`.
4. Rename [`leptos::spawn`](https://docs.rs/leptos/0.7.0-beta/leptos/spawn/index.html) to `leptos::task`
	1. `tick()` isn't really related to spawning futures, slightly more related to tasks ig
		1. Docs are missing for this function
	2. Could add `queue_microtask` into here as well?
	3. the qualified path `task::spawn()` sounds nice :)
5. Rename long re-exported crate names `leptos_dom` -> `dom`, `reactive_graph` -> `reactive`?
	1. Does [`leptos_dom`](https://docs.rs/leptos_dom/0.7.0-beta/leptos_dom/index.html) actually need to be completely re-exported? The macros are already exported in [`leptos::logging`](https://docs.rs/leptos/0.7.0-beta/leptos/logging/index.html), and [`leptos_dom::logging`](https://docs.rs/leptos_dom/0.7.0-beta/leptos_dom/logging/index.html) isn't really necessary with the macros. Perhaps `pub use leptos_dom::helpers as dom;` instead?
6. Does `tachys` need to be completely re-exported (in both `leptos::tachys` and `leptos::prelude::tachys`)? It seems like most of its contents are already re-exported individually.
	1. Why is re-exporting `tachys::html::event as ev` marked as [`#[doc(no_inline)]`](https://docs.rs/leptos/0.7.0-beta/src/leptos/lib.rs.html#264)?
	2. The crate re-exports should be marked as `#[doc(inline)]` so that it can be searched. It looks like re-exported *crates* are just shown under the re-exports section and they don't show up when searching, while inlined/module re-exports show it as if it's part of leptos.
8. It seems like many functions are re-exported in the prelude but nowhere else. This might also be because many crates are re-exported and their inner items don't show up when searched, so it looks like it's only available in the prelude.
	1. There are a lot of things in the prelude, many of which seem to be very niche. Since the modules are a better organised now, it might not be necessary to re-export so many things; just import them when we need it.
9. Rename the `EitherOf*` enums to just `Either*`?
10. Why are [`Either*Future`](https://docs.rs/either_of/0.1.0/either_of/enum.EitherOf3Future.html) variants in the form `A { inner: T }` instead of `A(T)`, like [`Either*`](https://docs.rs/either_of/0.1.0/either_of/enum.EitherOf3.html) are?
11. Rename the [`Writable`](https://docs.rs/leptos/0.7.0-beta/leptos/prelude/trait.Writeable.html) trait to `Write` to match the [`Read`](https://docs.rs/leptos/0.7.0-beta/leptos/prelude/trait.Read.html) trait (and general Rust conventions).
12. [`unwrap_signal!`](https://docs.rs/leptos/0.7.0-beta/leptos/prelude/macro.unwrap_signal.html) looks like it should be an internal thing (blanket re-exported from [`leptos::reactive_graph::unwrap_signal`](https://docs.rs/reactive_graph/0.1.0-beta/reactive_graph/macro.unwrap_signal.html), should probably be internal within `reactive_graph` too).
13. Re-exporting `reactive_graph::untrack` at the root seems odd, there's no other functions that are re-exported at the root of this crate. Maybe `reactive_graph::signal::untrack` is a better spot to put it.

Thanks for reading this long brain dump! Lmk your thoughts, I'm happy to implement any of these changes.

**Comment by gbj** [comment]
Thanks for this feedback @blorbb — I read through it initially and agree with most of it, I will go through and implement individual pieces but just have not had the time to do it as I have been focused on bugfixes and filling out missing features instead. I can also write a piece by piece response if that's helpful but I find those tend to end up being longer and longer comment chains.

For example things like
```
12. Why are [Either*Future](https://docs.rs/either_of/0.1.0/either_of/enum.EitherOf3Future.html) variants in the form A { inner: T } instead of A(T), like [Either*](https://docs.rs/either_of/0.1.0/either_of/enum.EitherOf3.html) are?
```
The answer here is something along the lines of "`pin_project_lite` macro doesn't support tuple structs."  If this level of individual detail is helpful I can take the time to write it out.

**Comment by blorbb** [comment]
Thanks @gbj, no need for a piece by piece response :) If you would like me to implement these just lmk which ones you agree with (/any variations) and I can have a go at most of these. Otherwise if you would like to implement them instead you can go ahead whenever you're free.

**Comment by benwis** [comment]
I think 3 should stay that way and 6 I suspect the shorter names are not available on crates.io

**Comment by gbj** [comment]
@blorbb So I've finally worked through these, and I have a few minutes to write down thoughts.

For context, the goal of the prelude in 0.7 is
1) to make the migration from leptos 0.0-0.6 (where nearly everything is exported as `leptos::*`) as easy as possible; if something is exported as `leptos::*`, for the most part I've tried to export it from `leptos::prelude::*`
2) without cluttering up the leptos root docs

So I'm not bothered about the prelude being a mess at the moment, even though it's worse than the prelude just having traits etc.

> 1. Rename the [`Writable`](https://docs.rs/leptos/0.7.0-beta/leptos/prelude/trait.Writeable.html) trait to `Write` to match the [`Read`](https://docs.rs/leptos/0.7.0-beta/leptos/prelude/trait.Read.html) trait (and general Rust conventions).

Yes.

> 2. Items in [`leptos::context`](https://docs.rs/leptos/0.7.0-beta/leptos/context/index.html) are suffixed with `_context` - maybe it could be nicer to use a qualified path instead? Similar to the std `mpsc::channel`, these could also be used as `context::provide()`, `context::get()` (renamed from `use_context()` since use is a keyword).

Yeah maybe. We can always add these in future and deprecate the old ones if we want, although the fact that `context::use()` isn't possible (keyword) is probably just more hassle than it's worth.

>    1. It looks like `expect_context()` is missing (rename to `context::expect()`?)

Have since added.

>    2. [`leptos::mount`](https://docs.rs/leptos/0.7.0-beta/leptos/mount/index.html) is similar, rename to `mount::{to_element, to_body, to_renderer}` (maybe remove `to_` as well?).

I can see the logic but `mount_to` is a better name than `to` for a function, and `to_element` is longer than `mount_to`. I don't have strong feelings on this.

> 3. Rename [`leptos::spawn`](https://docs.rs/leptos/0.7.0-beta/leptos/spawn/index.html) to `leptos::task`

Like it, done.

>    1. `tick()` isn't really related to spawning futures, slightly more related to tasks ig
>       1. Docs are missing for this function

Thanks.

> 4. Is it possible to only export components but without their `*Props` struct too? `view!` doesn't need them to be public, and you could maybe add something to make it easy to build using builder pattern like `Suspense::builder()` instead of `leptos::component::component_props_builder(Suspense)`.

Props are useful for docs, because they are where the props are best documented IMO. I'm fine with the latter ergonomics suggestion but I think it's out of the scope of this particular conversation.

> 5. Rename long re-exported crate names `leptos_dom` -> `dom`, `reactive_graph` -> `reactive`?

I like `leptos::reactive` as a reexport of `reactive_graph`. I think `leptos_dom` has been reexported as such forever, I don't think it's worth changing.

>    1. Does [`leptos_dom`](https://docs.rs/leptos_dom/0.7.0-beta/leptos_dom/index.html) actually need to be completely re-exported? The macros are already exported in [`leptos::logging`](https://docs.rs/leptos/0.7.0-beta/leptos/logging/index.html), and [`leptos_dom::logging`](https://docs.rs/leptos_dom/0.7.0-beta/leptos_dom/logging/index.html) isn't really necessary with the macros. Perhaps `pub use leptos_dom::helpers as dom;` instead?

It's not clear whether even having it as a separate package makes sense long term. It is definitely a relic of the pre-tachys structure. I'm open to more thoughts here.

> 6. Does `tachys` need to be completely re-exported (in both `leptos::tachys` and `leptos::prelude::tachys`)? It seems like most of its contents are already re-exported individually.

Agreed.

>    1. Why is re-exporting `tachys::html::event as ev` marked as [`#[doc(no_inline)]`](https://docs.rs/leptos/0.7.0-beta/src/leptos/lib.rs.html#264)?

This one's actually quite important: the current docs inline these by default, and it leads to some *very confusing* documentation.

<img width="584" alt="Screenshot 2024-09-30 at 9 41 33 PM" src="https://github.com/user-attachments/assets/343940a1-e3fe-4b41-8dc2-1eabb0ae9772">

These are the docs I get if I search `MouseEvent` in the 0.6 docs, which instruct me to activate the `MouseEvent` feature, which doesn't exist on `leptos` but exists on `web-sys`. These docs give no evidence that they're talking about web-sys. Avoiding inlining them means that the still show up in search, but just as a link to `web_sys::MouseEvent`, which is much better.

>    2. The crate re-exports should be marked as `#[doc(inline)]` so that it can be searched. It looks like re-exported _crates_ are just shown under the re-exports section and they don't show up when searching, while inlined/module re-exports show it as if it's part of leptos.


Thanks, this is really helpful and not something I knew! Works much better.

> 7. It seems like many functions are re-exported in the prelude but nowhere else. This might also be because many crates are re-exported and their inner items don't show up when searched, so it looks like it's only available in the prelude.
>    
>    1. There are a lot of things in the prelude, many of which seem to be very niche. Since the modules are a better organised now, it might not be necessary to re-export so many things; just import them when we need it.


> 8. [`unwrap_signal!`](https://docs.rs/leptos/0.7.0-beta/leptos/prelude/macro.unwrap_signal.html) looks like it should be an internal thing (blanket re-exported from [`leptos::reactive_graph::unwrap_signal`](https://docs.rs/reactive_graph/0.1.0-beta/reactive_graph/macro.unwrap_signal.html), should probably be internal within `reactive_graph` too).

The rules around `macro_rules` exports are baffling to me. For now I'm just making it `#[doc(hidden)]`.

> 9. Re-exporting `reactive_graph::untrack` at the root seems odd, there's no other functions that are re-exported at the root of this crate. Maybe `reactive_graph::signal::untrack` is a better spot to put it.

Agreed, I reexported this from `leptos::prelude` and left it in its own module.

> 10. Should the leptos provided components (`Show`, `For`, `Suspense`, etc) be in modules based on its purpose (current), or just one big `components` module? Not sure which is better.

I have limited opinion on this. They're trying to be organized logically for now.

> 11. Rename the `EitherOf*` enums to just `Either*`?

I have no opinion on this except that it's not something I've heard in the last few months of people using it. 

> 12. Why are [`Either*Future`](https://docs.rs/either_of/0.1.0/either_of/enum.EitherOf3Future.html) variants in the form `A { inner: T }` instead of `A(T)`, like [`Either*`](https://docs.rs/either_of/0.1.0/either_of/enum.EitherOf3.html) are?

This one is just because `pin_project_lite` doesn't support tuple enums, IIRC.

See #3050.

**Comment by blorbb** [comment]
Thanks so much for taking the time to make a response, I really appreciate it! I agree with all your thoughts :)

**Comment by gbj** [comment]
:tada: see, I always get to issues eventually :smile:
