### ISSUE TITLE
Need to pass context to server functions or use #[server] with struct methods

### ISSUE THREAD

**Issue by Vai3soh** [leptos-rs/leptos#2091]
I'm currently facing two issues when working with leptos and ```create_server_action```.

Firstly, I can't use the `#[server]` macro with methods defined in the `Core` struct. This limits my ability to organize my code and utilize `leptos` functionality.

```
pub struct Core {
	userRepo: Box<dyn UserRepository>,
       sessionRepo: Box<dyn SessionProvider>,
}

impl Core {
	#[server(Login, "/api")]
	pub async fn login(&self,
	username: String,
	password: String,
	remember: Option<String>,) -> Result<(), Box<dyn Error>> {

	}
}
```
Or i need to pass context (specifically, an instance of Core) to a server function defined using the #[server] macro. This is needed for handling authentication and authorization in my application.
```
#[server(Login, "/api")]
pub async fn login(core: Core,
     username: String,
     password: String,
     remember: Option<String>,) -> Result<(), ServerFnError> {

     core.login(username,password,remember)
}
```
However, it seems that `leptos` and `create_server_action` do not provide a straightforward way to pass additional context to server functions and use `#[server]` with struct methods. This creates difficulties when trying to implement things like authentication and authorization, and organize code by dividing it into layers (clean architecture).

It would be helpful to have the ability to pass additional context or state to server functions and use `#[server]` with struct methods. This could be implemented in various ways, such as through function arguments, global state, or changes in `leptos`.

I would appreciate any suggestions or recommendations on this issue.

**Comment by gbj** [comment]
You are correct: you cannot use the `#[server]` macro on struct methods in an impl block.

You *can* provide context to a server function, by providing it in your route handler and server function handler, for example with [`handle_server_fns_with_context`](https://docs.rs/leptos_axum/latest/leptos_axum/fn.handle_server_fns_with_context.html).

**Comment by Vai3soh** [comment]
Ok, i close. Many thanks!!!
