### ISSUE TITLE
Extend tree-sitter-rust grammar so it can correctly indent Leptos `view!` macro

### ISSUE THREAD

**Issue by aguynamedben** [leptos-rs/leptos#2108]
**Is your feature request related to a problem? Please describe.**

I'm struggling to adopt Leptos because indenting the HTML-ish elements inside "rsx" (`view!` macro) is incorrect with text editors. I realize I can run `leptosfmt` to run on every save, but that still doesn't help if I want to churn out a bunch of front-end code. Without having reliable indentation, I don't know if front-end engineers will/can contribute to a Leptos project. A lot of HTML is required to build a meaningful product, and people are used to HTML/JSX/etc indenting very reliably.

**Describe the solution you'd like**

Extend (or fork) the [tree-sitter-rust](https://github.com/tree-sitter/tree-sitter-rust) grammar so it understands content within the `view!` macro. The purpose of tree-sitter is to pattern match language syntax to assist editors with indention, highlighting, and AST-enabled movement. It's widely supported in many editors and editor extensions.

A more whack, undesirable idea is to keep `view!` but alter Leptos' design to somehow support .jsx, .erb, htmx, or other existing front-end "layout and a bit of logic" libraries. However, I like the design of Leptos, I just really wish indentation worked reliably.

**Describe alternatives you've considered**

leptosfmt - only fixes indentation after save, so I still have messy indentation before save

**Additional context**

This seems minor, but very much affects day-to-day developer experience, ability for people to evangelize the framework to front-end engineers, and affects if Leptos can be chosen for a general team project vs. the Rust-willing hardcores.

**Comment by aguynamedben** [comment]
Related request or yew's `html!` macro https://github.com/tree-sitter/tree-sitter-rust/issues/172

**Comment by gbj** [comment]
I'll link to https://github.com/bram209/leptosfmt/issues/96 to avoid having two separate conversations here.

The issue you linked regarding Yew suggests that the `tree-sitter-rust` team is explicitly *not* interested in support library-specific macros in their main grammar. So I guess the question is: Are you interested in maintaining a fork of `tree-sitter-rust` with Leptos support? I have never knowingly used tree-sitter and don't know the first thing about it, so this isn't something I'm going to take on right now but I'd be very open to that contribution.

Otherwise, just to clarify the difference between what you're asking for and `leptosfmt`: This is about indentation *as you type*, rather than formatting on save?

**Comment by aguynamedben** [comment]
@gbj Yes, I'm asking about indentation during editing—`leptosfmt` is doing a fine job at save time. Writing HTML-ish syntax ("rsx") for a front-end heavy-product is annoying if the indentation during editing is not right.

[JavaScript's tree-sitter grammar](https://github.com/tree-sitter/tree-sitter-javascript) also supports JSX, which due to the popularity of React is more-or-less required. ([TypeScript's tree-sitter grammar](https://github.com/tree-sitter/tree-sitter-typescript) also supports TSX).

I'm a tree-sitter user, but have never developed a grammar. I'm not heavily using leptos right now, so not yet inclined to spend time to make a tree-sitter grammar (never done it). I appreciate that this is open-source and PRs accepted, I was just curious if anybody was working on something like this. I'm considering leptos as a framework for projects, along with Next.js, SvelteKit, Rails, etc. and the editor support is something I factor in.

Since the RSX support in leptos is powered by [syn-rsx](https://github.com/stoically/syn-rsx), maybe they'd be more understanding of the request. It looks like someone took at stab at it here: https://github.com/tjdevries/tree-sitter-rsx.

**Comment by gbj** [comment]
It's [`rstml`](https://github.com/rs-tml/rstml), not syn-rsx — unfortunately the maintainer of syn-rsx passed away last year so that project is no longer maintainable and needed to be forked. 

This sounds like one of those chicken-and-egg issues that comes up in open source. For you, tree-sitter support is a blocker, but the fact that there's no pre-existing tree-sitter support makes it unlikely for you to get invested enough in the project to develop tree-sitter support. For the existing userbase, it doesn't seem to be an issue (or at least nobody's ever asked me about it before) so nobody's put any energy into developing the support.

I'll leave the issue open of course in case anyone comes along who wants to work on it.

**Comment by benwis** [comment]
I've thought about expanding/forking the tree-sitter grammar a little bit. I agree with Greg in that it's nice to have, but I don't know and probably don't have time to do it etiher

**Comment by bram209** [comment]
> I'll link to https://github.com/bram209/leptosfmt/issues/96 to avoid having two separate conversations here. 

Thanks : )

>  the tree-sitter-rust team is explicitly not interested in support library-specific macros in their main grammar.

Which is understandable. Proc macro's can take _any_ valid stream of tokens, so macro library owners can essentially create their own embedded syntax (rstml being an example of this). So if they start adding one embedded syntax, where does it end?).

I vaguely remember looking into the possibility of somehow using multiple grammars simultaneously, but this didn't seem to be supported (without having one parent grammer maintain the injected grammars). 

> This is about indentation as you type, rather than formatting on save?

I played around with having a `letpos-language-server` but ultimately decided against it. The syntax highighting and code completion that you get from `rust_analyzer` is decent enough and I was time constrained at the time.

I may continue the LSP implementation to add:
- Indentation (as you type)
- Folding HTML tags & code blocks

But frankly not sure if it is worth my time.

**Comment by kirawi** [comment]
I can't speak to the capabilities of other implementations, but Helix could handle this if there were a fork of HTML rather than Rust's tree-sitter library. We would just need to know which nodes are HTML and which are Rust, allowing us to:

- Parse the `view` macro syntax tree via this tree-sitter grammar
- Parse any Rust nodes as Rust
- Apply HTML queries to the rest of the syntax

**Comment by benwis** [comment]
I’d be happy to help with it if you can describe what you need it in. Although most of the files will be rust, we’d only expect html within a few macros and maybe a raw string or two.

**Comment by rayliwell** [comment]
I decided to take this on myself and created [tree-sitter-rstml](https://github.com/rayliwell/tree-sitter-rstml).

It's basically an extension of the `tree-sitter-rust` grammar with some extra rules for handling rstml nodes. It's seems close to perfect at parsing leptos code, but I'm sure there are probably some edge-cases arising from `rstml`/`leptos_macro` parsing quirks I'm not aware of.

The [Neovim support](https://github.com/rayliwell/tree-sitter-rstml?tab=readme-ov-file#neovim-experimental) does syntax highlighting, indentation, and folding of leptos macros inside of rust code. I'd really appreciate anyone who tries it and lets me know any issues they're having so I can get it merged into [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) soon 🙏.

I'd also appreciate a star on the repo if you like my work ♥️.

**Comment by benwis** [comment]
> I decided to take this on myself and created [tree-sitter-rstml](https://github.com/rayliwell/tree-sitter-rstml).
> 
> It's basically an extension of the `tree-sitter-rust` grammar with some extra rules for handling rstml nodes. It's seems close to perfect at parsing leptos code, but I'm sure there are probably some edge-cases arising from `rstml`/`leptos_macro` parsing quirks I'm not aware of.
> 
> The [Neovim support](https://github.com/rayliwell/tree-sitter-rstml?tab=readme-ov-file#neovim-experimental) does syntax highlighting, indentation, and folding of leptos macros inside of rust code. I'd really appreciate anyone who tries it and lets me know any issues they're having so I can get it merged into [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) soon 🙏.
> 
> I'd also appreciate a star on the repo if you like my work ♥️.

This is fantastic work, thanks for doing it! I've dropped it into the Leptos discord and I'll definitely be trying it out

**Comment by rayliwell** [comment]
> > I decided to take this on myself and created [tree-sitter-rstml](https://github.com/rayliwell/tree-sitter-rstml).
> > It's basically an extension of the `tree-sitter-rust` grammar with some extra rules for handling rstml nodes. It's seems close to perfect at parsing leptos code, but I'm sure there are probably some edge-cases arising from `rstml`/`leptos_macro` parsing quirks I'm not aware of.
> > The [Neovim support](https://github.com/rayliwell/tree-sitter-rstml?tab=readme-ov-file#neovim-experimental) does syntax highlighting, indentation, and folding of leptos macros inside of rust code. I'd really appreciate anyone who tries it and lets me know any issues they're having so I can get it merged into [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) soon 🙏.
> > I'd also appreciate a star on the repo if you like my work ♥️.
> 
> This is fantastic work, thanks for doing it! I've dropped it into the Leptos discord and I'll definitely be trying it out

Thanks! 

Hopefully this should make editing Leptos code more pleasant for others, as it does for me.

I've made a [project](https://github.com/users/rayliwell/projects/2) of everything I've got left to do. I should have rust and helix support ready too pretty soon.

**Comment by bram209** [comment]
> I decided to take this on myself and created [tree-sitter-rstml](https://github.com/rayliwell/tree-sitter-rstml).
> 
> It's basically an extension of the `tree-sitter-rust` grammar with some extra rules for handling rstml nodes. It's seems close to perfect at parsing leptos code, but I'm sure there are probably some edge-cases arising from `rstml`/`leptos_macro` parsing quirks I'm not aware of.
> 
> The [Neovim support](https://github.com/rayliwell/tree-sitter-rstml?tab=readme-ov-file#neovim-experimental) does syntax highlighting, indentation, and folding of leptos macros inside of rust code. I'd really appreciate anyone who tries it and lets me know any issues they're having so I can get it merged into [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) soon 🙏.
> 
> I'd also appreciate a star on the repo if you like my work ♥️.

Great work! starred your repo

**Comment by tobalsgithub** [comment]
> I decided to take this on myself and created [tree-sitter-rstml](https://github.com/rayliwell/tree-sitter-rstml).
> 
> It's basically an extension of the `tree-sitter-rust` grammar with some extra rules for handling rstml nodes. It's seems close to perfect at parsing leptos code, but I'm sure there are probably some edge-cases arising from `rstml`/`leptos_macro` parsing quirks I'm not aware of.
> 
> The [Neovim support](https://github.com/rayliwell/tree-sitter-rstml?tab=readme-ov-file#neovim-experimental) does syntax highlighting, indentation, and folding of leptos macros inside of rust code. I'd really appreciate anyone who tries it and lets me know any issues they're having so I can get it merged into [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) soon 🙏.
> 
> I'd also appreciate a star on the repo if you like my work ♥️.

This worked great for me!  I'm using dioxus, not leptos, but as far as I can tell it solved the indentation problem for me that was driving me crazy. Thank you for putting this together 🙇 ⭐

**Comment by benwis** [comment]
> > I decided to take this on myself and created [tree-sitter-rstml](https://github.com/rayliwell/tree-sitter-rstml).
> > It's basically an extension of the `tree-sitter-rust` grammar with some extra rules for handling rstml nodes. It's seems close to perfect at parsing leptos code, but I'm sure there are probably some edge-cases arising from `rstml`/`leptos_macro` parsing quirks I'm not aware of.
> > The [Neovim support](https://github.com/rayliwell/tree-sitter-rstml?tab=readme-ov-file#neovim-experimental) does syntax highlighting, indentation, and folding of leptos macros inside of rust code. I'd really appreciate anyone who tries it and lets me know any issues they're having so I can get it merged into [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) soon 🙏.
> > I'd also appreciate a star on the repo if you like my work ♥️.
> 
> This worked great for me! I'm using dioxus, not leptos, but as far as I can tell it solved the indentation problem for me that was driving me crazy. Thank you for putting this together 🙇 ⭐

Unless I'm mistaken, doesn't Dioxus use an entirely different templating language?

**Comment by rendivs925** [comment]
> I decided to take this on myself and created [tree-sitter-rstml](https://github.com/rayliwell/tree-sitter-rstml).
> 
> It's basically an extension of the `tree-sitter-rust` grammar with some extra rules for handling rstml nodes. It's seems close to perfect at parsing leptos code, but I'm sure there are probably some edge-cases arising from `rstml`/`leptos_macro` parsing quirks I'm not aware of.
> 
> The [Neovim support](https://github.com/rayliwell/tree-sitter-rstml?tab=readme-ov-file#neovim-experimental) does syntax highlighting, indentation, and folding of leptos macros inside of rust code. I'd really appreciate anyone who tries it and lets me know any issues they're having so I can get it merged into [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) soon 🙏.
> 
> I'd also appreciate a star on the repo if you like my work ♥️.

cool
