### ISSUE TITLE
The class display is inconsistent in some cases

### ISSUE THREAD

**Issue by luoxiaozero** [leptos-rs/leptos#2121]
**Describe the bug**

When `class` is of type Fn, updating class causes `class: ` or `class=("",...)` disappear. same as #773 .

**Leptos Dependencies**

```toml
leptos = { version = "0.5.4", features = ["csr"] }
```

```rust
#[component]
fn App() -> impl IntoView {
    let value = create_rw_signal("value");
    let is_thaw = create_rw_signal(true);

    view! {
        <div class=move || value.get() class:thaw=move || is_thaw.get() class=("thaw-button", move || true)>
            "value"
        </div>
        <button on:click=move |_| value.set("a")>
            "A"
        </button>
    }
}
```

**To Reproduce**

1. Run `trunk serve`. ( The value class is `value thaw thaw-button` )
2. Click A button. ( The value class is `a` )

**Expected behavior**

Click A button. The value class is `a thaw thaw-button`.

**Screenshots**

**Additional context**

I can think of two solutions.

When `class` type is Fn and `class: ` or `class=("",...)` exists:

1. Compile to dyn_classes instead of attr.
2. Add a new attribute dyn_classes. like [classList](https://www.solidjs.com/docs/latest/api#classlist)

**Comment by gbj** [comment]
This is working as designed. I'm open to suggestions for alternate approaches, but the correct way to do this currently is just with a format string and a single class:
```rust
class=move || format!(
  "thaw-button {} {}",
  value.get(),
  is_thaw.get().then_some("thaw").unwrap_or_default()
)
```
As far as I can tell there's no real downside to doing it this way; the performance cost is lower than the alternatives

**Comment by luoxiaozero** [comment]
You're right, I'm going to close this issue.
