### ISSUE TITLE
Use idiomatic, built-in From and Into traits instead of IntoView, IntoAttribure, etc.

### ISSUE THREAD

**Issue by SleeplessOne1917** [leptos-rs/leptos#2131]
Currently, leptos uses a few bespoke Into traits. While they get the job done, using the traits from [std::convert](https://doc.rust-lang.org/std/convert/index.html) would be more idiomatic, and I suspect it would make Leptos play nicer with other dependencies developers may use.

I'll work on this one.

**Comment by gbj** [comment]
For context: These separate traits come from the 0.4-and-earlier period when they required an additional `Scope` argument that is no longer used in 0.5, and they will likely not exist in the next meaningful version change. Feel free to experiment with something like implementing `From<T> for Attribute where T: IntoAttribute` or whatnot, but obviously removing the traits themselves would be a breaking change and replacing all the `-> impl IntoView` and so on with `-> impl Into<View>` is just churn. Having a separate `IntoView` trait in particular allows a lot of flexibility, as there is no `View` enum in the next version of the renderer.

**Comment by SleeplessOne1917** [comment]
@gbj I'll experiment with `Into<Attribute>`. I was banging my head against the wall trying to get `Into<View>` working, but will hold off on that since `View` is going away anyway.

Is there anywhere I can keep an eye on what's being done with the renderer you mentioned?

**Comment by gbj** [comment]
Sure. See my [comment](https://github.com/leptos-rs/leptos/issues/1830#issuecomment-1858410524) on the roadmap and the links to associated repos there.
