### ISSUE TITLE
Add `read_slice!()` and `write_slice!()` macros

### ISSUE THREAD

**Issue by mondeja** [leptos-rs/leptos#2140]
**Is your feature request related to a problem? Please describe.**

I'm always writing this kind of code:

```rust
let my_reactive_read_struct_field =
    create_read_slice(my_state, |state: &MyState| {
        state.my_struct_field.clone()
    });
let set_my_reactive_read_struct_field =
    create_write_slice(my_state, |state, new_value| {
        state.my_struct_field = new_value
    });
```

But when dealing with read/write slices, I don't spend so much time of my life thanks to the existence of the `slice!()` macro:

```rust
let (reactive_field, set_reactive_field) = slice!(my_state.my_struct_field);
```

**Describe the solution you'd like**

I would like to refactor the above using:

```rust
let my_reactive_struct_field = read_slice!(my_state.my_struct_field);
let set_my_reactive_struct_field = write_slice!(my_state.my_struct_field);
```

Or maybe some API like:

```rust
let my_reactive_struct_field = slice!(my_state.my_struct_field, "read");
let set_my_reactive_struct_field = slice!(my_state.my_struct_field, "write");
```

**Describe alternatives you've considered**

This, but shouldn't be as optimal. I'm wrong?

```rust
let (my_reactive_struct_field, _) = slice!(my_state.my_struct_field);
let (_, set_my_reactive_struct_field) = slice!(my_state.my_struct_field);
```

**Additional context**

Hopefully, these macros could take advantadge of the implementation on #2139.

**Comment by gbj** [comment]
I'll be honest and say I'm unlikely to implement these as they will probably be superseded by a proper Store type in the next release, and should be a short (4-5 line?) declarative macro in any case. But a PR would be welcome if you think it would be helpful for others too!
