### ISSUE TITLE
Inconstistency between debug and release on `if let Some(x)...`

### ISSUE THREAD

**Issue by nguiard** [leptos-rs/leptos#2143]
**Describe the bug**
I get different behavior between debug and release for this piece of code:
```rust
<p>
    "Your lucky number: " { move || 
    if let Some(num) = lucky_num() {
        view! { <>{num}</> }
    } else {
        view! { <>"loading..."</> }
    }}
</p>
```

**Leptos Dependencies**

```toml
leptos = { version = "0.5", features = ["nightly"] }
leptos_axum = { version = "0.5", optional = true }
leptos_meta = { version = "0.5", features = ["nightly"] }
leptos_router = { version = "0.5", features = ["nightly"] }
```
(latest releases at time of writing, checked)

**To Reproduce**
Can't do a minimal repro right now but I'll try soon. For context, I'm fooling around with a setup like this inside a component:
```rust
...
let (lucky_num, set_lucky_num) = create_signal(None::<u8>);

#[cfg(feature = "hydrate")]
spawn_local(async move {
    let mut rx = client
        .get_untracked()
        .lucky_num(())
        .await
        .unwrap()
        .into_inner();

    while let Ok(Some(item)) = rx.message().await {
        set_lucky_num(Some(item));
    }
});
...
```
Which is a tonic-web-wasm-client requesting a server-streaming endpoint, getting a new `u8` every few seconds. (I don't know if doing it like this is good or if there's a better way using `create_resource` maybe, but that's probably beside the point). `lucky_num` is initialised to `None` and quickly assigned a `Some` value.

In the view, I have two versions for rendering the same thing:
```rust
<p>
    "Your lucky number: " { move || 
    if let Some(num) = lucky_num() {
        //&format!("{}", num)
        view! { <>{num}</> }
    } else {
        view! { <>"loading..."</> }
    }}
</p>
<p>
    "Your lucky number: " { move || view! {
        <Show 
            when=move || lucky_num().is_some()
            fallback=|| view! { "loading..." }
        >
            { lucky_num().unwrap() }
        </Show>
    }}
</p>
```

Relevant example output in debug mode:
```
Your lucky number: 18
Your lucky number: 18
```
release mode:
```
Your lucky number: loading...239
Your lucky number: 239
```

**Expected behavior**
Even though the `Show` version works, I expected the `if let` version to behave the same in debug and release modes.

**Comment by gbj** [comment]
The fragments (`<>`) here are superfluous--does it work correctly if you use `num.to_string()` and `"loading...".to_string()`?

**Comment by nguiard** [comment]
Oh thanks for the quick reply! Yes, it works when using your suggestion.

**Comment by nguiard** [comment]
to be clearer:
```rust
<p>
    "Your lucky number: " { move || 
    if let Some(num) = lucky_num() {
        num.to_string()
    } else {
        "loading...".to_string()
    }}
</p>

This does not have the issue.
```

**Comment by nguiard** [comment]
Of these 4 versions:
```rust
<p>
    "Your lucky number: " { move || 
    if let Some(num) = lucky_num() {
        view! { <>{num}</> }
    } else {
        view! { <>"loading..."</> }
    }}
</p>
<p>
    "Your lucky number: " { move || 
    if let Some(num) = lucky_num() {
        num.to_string()
    } else {
        "loading...".to_string()
    }}
</p>
<p>
    "Your lucky number: " { move || 
    if let Some(num) = lucky_num() {
        view! { {num.to_string()} }
    } else {
        view! { {"loading...".to_string()} }
    }}
</p>
<p>
    "Your lucky number: " { move || view! {
        <Show 
            when=move || lucky_num().is_some()
            fallback=|| view! { "loading..." }
        >
            { lucky_num().unwrap() }
        </Show>
    }}
</p>
```

Only the first one exhibits the issue in release mode, but not debug.

**Comment by gbj** [comment]
Okay, thanks. I think this is fundamentally the same thing as #1223: fragments nested inside dynamic views in the current renderer are notoriously finicky. This is no longer the case in the next version of the renderer, although the "type erasure via fragments" pattern no longer works there. So I'd suggest any of the above working versions, and I'd suggest avoiding using fragments in this way, and I'm going to close this issue as partially solved and partially a duplicate.
