### ISSUE TITLE
examples: add `rust-toolchain.toml` files for examples

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#2151]
**Is your feature request related to a problem? Please describe.**
If a user tries to run an example that's built for `nightly` without `nightly`, it doesn't work and can give confusing errors, which is bad when you're starting out (See #2141)

**Describe the solution you'd like**
Adding the appropriate [`rust-toolchain.toml`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) file for each example.

**Describe alternatives you've considered**
Causing users ongoing pain.

**Comment by webmstk** [comment]
I had problems with some examples.

hackernews and hackernews_axum do not run with `trunk server`:

```
error from build pipeline

Caused by:
    0: error from asset pipeline
    1: found more than one target artifact: ["hackernews", "hackernews"]:
        * consider adding `<link data-trunk rel="rust" data-bin={bin} />` to the index.html to build only the specified binary
        * or adding `<link data-trunk rel="rust" data-target-name={artifact} />` to select the specific artifact by name
```

hackernews_islands_axum
```
listening on 0.0.0.0:8080
thread '<unnamed>' panicked at src/error_template.rs:7:9:
No Errors found and we expected errors!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /Users/webmstk/temp/leptos/integrations/axum/src/lib.rs:806:44:
called `Option::unwrap()` on a `None` value
```


session_with_axum
```
thread 'main' panicked at src/main.rs:64:14:
could not run SQLx migrations: VersionMismatch(20230226000000)
```

Also, I didn't check hackernews_js_fetch because I failed to run it with deno
