### ISSUE TITLE
leptos_router: Feature: Support for trailing slashes.

### ISSUE THREAD

**Issue by NfNitLoop** [leptos-rs/leptos#2154]
**Is your feature request related to a problem? Please describe.**

Relative URL resolution in plain HTML (`<a>`, not `<A>`) works by appending a relative path to the path in the URL bar, somewhat like when working with relative filesystem paths.  But in URLs the trailing `/` character is significant.  If it is present, the current URL is treated as a "directory", within which the URL is resolved. Otherwise, the last path part is treated as a "file" and is stripped before doing relative resolution.

So, without a trailing slash, visiting the URL `http://localhost:3000/foo`, an `<a href="bar.txt">` resolves to the URL `http://localhost:3000/bar.txt`.

But *with* a trailing slash, visiting the URL `http://localhost:3000/foo/`, the same link resolves as `http://localhost:3000/foo/bar.txt`.

So a trailing slash is a meaningful element of the route.  But leptos_router (or, maybe it's the actix implementation?) seems to be normalizing away trailing slashes.  Both `<Route path="/foo">` and `<Route path="/foo/">` end up serving the same path.

This is a problem because I'm hoping to gradually port an old codebase to Leptos. I want to keep the same URL structure for backward compatibility (i.e.: so I don't break old links). The relative links that I want to support are part of user input that can't be easily updated to use the `<A>` tags.

**Describe the solution you'd like**

SvelteKit has a nice way of handling trailing slashes.  See: <https://kit.svelte.dev/docs/page-options#trailingslash>

You can set a `trailingSlash` option that determines how the server and client handle trailing slashes.  You can configure this differently for different routes, and sub-routes inherit the parent behavior by default.

I'd love something similar in Router. Preferably I'd be able to set it once at the very top level on `<Router>` and just apply it to all of my routes by default.  Then I could override particular sub-routes w/ the same setting on `<Route>`.

**Describe alternatives you've considered**

1) Changing my URLs to have some `/foo/home` page instead of serving from `/foo/`.  

❌  Breaks link compatibility.
⚠️  Would still need to manually redirect from `/foo` to `/foo/home`.  If we could just redirect from `/foo` to `/foo/` that would be much better.

2) Forking Leptos router and adding this functionality for myself.  (😅)  

Not sure whether I can commit to doing it but if you'd like someone to help with this feature I might be interested enough to work on it.

**Comment by benwis** [comment]
Unfortunately your proposal is not possible, what happens to routes is governed by actix/axum. Being not an Actix user, a quick doc skim suggests that they do consider /foo and /foo/ to be different routes. See their middleware for one example of that: https://cseweb.ucsd.edu/classes/sp22/cse223B-a/tribbler/actix_web/middleware/struct.NormalizePath.html

Assuming actix is behaving how you want, it's possible the actix->leptos router conversion function doesn't handle that correctly. That can be found here: https://github.com/leptos-rs/leptos/blob/16cf3c4eafd660ab68a7a8dff1e06096f061ffea/integrations/actix/src/lib.rs#L941

**Comment by NfNitLoop** [comment]
> Unfortunately your proposal is not possible

It's possible, the implementation would just need to change.

I'll dig into actix integration and check what it's doing, but if:

> they do consider /foo and /foo/ to be different routes

… and I specify `<Route path="/foo/" trailingSlash="always" ...>`, then `generate_route_list()` could just add two routes:

 * `/foo`  is a route that just redirects the browser to `/foo/`
 * `/foo/` serves my Route view.

**Comment by gbj** [comment]
@NfNitLoop You are correct that the router's current behavior includes normalizing paths in a way that removes trailing `/`. 

@benwis You are also correct that there is a difference in behavior between Actix & Axum here. If you define a Route `/foo/`:
- Axum (or `leptos_axum`) matches `/foo` or `/foo/`, for initial render
- Actix (or `leptos_actix`) matches `/foo` only, not `/foo/`, for initial render
- Client-side routing always navigates to `/foo` if, for example, you click a link to `/foo/` or `/foo`

So the current behavior is perfectly consistent with itself, but not with all possible URL schemes (such as including trailing slashes). 

I haven't thought that much about what it would require to support trailing slashes, but I'm sure it's possible. If you'd be interested in making a PR I'd be happy to see it.

**Comment by skirsdeda** [comment]
I just hit this issue as well, but for me it is enough to fix client-side routing to retain trailing slash if it's there. So I fiddled with `leptos_router` a bit and it works now :) Just a bit ugly ATM. I changed `matching::resolve_path` to use a different `normalize` function that doesn't do `.trim_end_matches('/')`. `normalize` is also used by `join_paths` which depends on trailing slash removal though, so that breaks quite spectacularly if I just change `normalize` implementation.
Anyway, the version of `normalize` that I use in `resolve_path` looks like this:
```rust
fn normalize_for_resolve(path: &str, omit_slash: bool) -> Cow<'_, str> {
    let s = path.trim_start_matches('/');
    if s.is_empty() || omit_slash || begins_with_query_or_hash(s) {
        s.into()
    } else {
        format!("/{s}").into()
    }
}
```

**Comment by skirsdeda** [comment]
@gbj do you see any issues with this approach? Otherwise, I could open a PR once I tidy this up and add a few tests.

**Comment by NfNitLoop** [comment]
@skirsdeda While it doesn't address the full scope of this issue (I still would like support for redirecting to URLs with/without slashes), I'd definitely be interested in seeing your fix. It may unblock me for maintaining URL compatibility w/ my existing project, and I can just put in `/foo` → `/foo/` redirects manually for now.  

Did you account for not adding a redundant `/` when concatenating inner routes, now that they'er not being trimmed?

**Comment by skirsdeda** [comment]
@NfNitLoop there's also a workaround for links with current implementation. Just add non-empty query string or hash fragment and trailing slash is retained.

**Comment by NfNitLoop** [comment]
Learning Leptos codebase when testing @skirsdeda's changes in #2163. 

That's a good place to branch off of w/ an experimental implementation of my feature request.  
I think I'll offer a few options on `<Router>` and `<Route>`. 

* `TrailingSlash::Drop` -- default/legacy behavior, trailing slashes get stripped from path patterns. Route paths with a trailing slash are not possible.  

* `TralingSlash::Redirect` -- If the client/server receive a request that is off by just the trailing slash, issue a redirect/navigate to the correct URL. (My preferred user-friendly & SEO-friendly option. Maybe we can make this the default in a future major version?)

* `TrailingSlash::Exact` -- Keep the trailing slash (or lack thereof), and don't do any redirects to fix it up for users.

**Comment by NfNitLoop** [comment]
First pass at an implementation is up.  Let me know what you think!

Should I spend some more time to get this ready to be merged? Or am I going off in the wrong direction?

**Comment by benwis** [comment]
I believe we can close this one now that #2172 is merged. Feel free to comment if that's not so

**Comment by paul-hansen** [comment]
@benwis @gbj  since #2172 was reverted in 0.5.7 and isn't in 0.6.2 or main is it no longer planned? Just curious if I need to re-implement the workaround I had for this in my app.

Basing my assumption that it isn't in 0.6.2 from it not showing up in the docs: https://docs.rs/leptos_router/0.6.2/leptos_router/?search=leptos_router%3A%3ATrailingSlash

**Comment by gbj** [comment]
@paul-hansen Try against the branch for PR #2217.

**Comment by paul-hansen** [comment]
Ah I missed it thanks!
