### ISSUE TITLE
Use a cloneable type for ActionForm's error prop instead of Box<dyn Error>

### ISSUE THREAD

**Issue by SleeplessOne1917** [leptos-rs/leptos#2174]
**Describe the bug**
While working on [this PR](https://github.com/leptos-rs/leptos/pull/2110), I realized I couldn't get the error from the `ActionForm`'s error prop. To give a small snippet:

```rust
#[component]
fn Foo() -> impl IntoView {
    let error = RwSignal::new(None);

    Effect::new(move |_| {
        logging::log!("{:?}", error.get()); // This line will error because get cannot be called for signals with types that don't implement Clone
    });

    view!{
        <ActionForm action=some_action error=error>
               {/* Rest of form */}
        </ActionForm>
    }
}
```

The type of the error prop is `Option<RwSignal<Option<Box<dyn Error>>>>`. Since `Error` isn't constrained by `Clone`, the compiler will give an error when trying to call `get` on that `RwSignal`. Should signals even be able to be set with non-cloneable types in the first place? The `Clone` constraint exists on `SignalGet`, but not `SignalSet`, making it possible to set a value that cannot be gotten.

**Comment by gbj** [comment]
`.with()` can be called on any signal whose value isn't `Clone`, i.e.,
`error.with(|value| logging::log!("{value:?}"));`

We are probably slightly working across each other at this point, as the `error` signal is being removed on `ActionForm` in favor of simply using the `action`'s `.value()` signal, which it currently duplicates (i.e., the `Err` condition in that signal) https://github.com/leptos-rs/leptos/pull/2158

I need to reply to your comments in your PR and will do that soon.

**Comment by SleeplessOne1917** [comment]
Using value instead of error should simplify things for me quite a bit. Thanks for letting me know.
