### ISSUE TITLE
Transfer or remove Viz integration?

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#2177]
**Is your feature request related to a problem? Please describe.**
@fundon contributed a server integration for the [Viz](https://viz.rs/) framework last year. In the time since, it's been [maintained somewhat](https://github.com/leptos-rs/leptos/commits/main/integrations/viz) in parallel with the other server integrations, but has not been updated meaningfully. For example, the Axum integration was rewritten to be [less bad](https://github.com/leptos-rs/leptos/issues/811), but the same work was not done for Viz. Likewise, the current published version uses Viz 0.4.8, hyper 0.14, and http 0.2, while the current published version of Viz is 0.7.1 and uses hyper 1.0 and http 1.0.

With the ongoing [server function rewrite ](https://github.com/leptos-rs/leptos/pull/2158) as part of 0.6, the Viz integration is now broken. I don't have the knowledge or capacity to update the Viz integration to hyper/http 1, viz 0.7, and the new server functions.

**Describe the solution you'd like**
I think my preference would be for the `leptos_viz` crate to be handed off to @fundon to maintain. I don't think enough knowledge of the framework exists in the community for it to be maintained as part of this core repo.

**Describe alternatives you've considered**
An update PR to bring it into a working state would also be welcome as an alternative.

For now, I will just disable CI running on it, and not publish new versions.

**Comment by fundon** [comment]
Hi @gbj,

Thanks for the feedback, you can transfer `leptos_viz` to me. 
I'm happy to maintain it and keep up with leptos changes.
