### ISSUE TITLE
cargo leptos watch Error: compile sass/scss

### ISSUE THREAD

**Issue by butoften** [leptos-rs/leptos#2178]
I used following cmd:

```
cargo install cargo-leptos
cargo leptos new --git https://github.com/leptos-rs/start
cd start-project
cargo leptos watch
```
and it show error:
```
Error: compile sass/scss: style/main.scss -> @pkg/leptos_start.css at `/Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.5/src/compile/style.rs:52:18`
```

can you help me?
Am I missing any configurations?
thank you.

**Comment by gbj** [comment]
You haven't made any other changes to the template? You just ran those commands? In that case, I can't reproduce the issue.

**Comment by butoften** [comment]
I'll look for the reason again. And close it for now
