### ISSUE TITLE
0.7 attribute values

### ISSUE THREAD

**Issue by blorbb** [leptos-rs/leptos#2196]
**Is your feature request related to a problem? Please describe.**
How attribute values work is slightly inconsistent and rust-analyzer support isn't the best

**Describe the solution you'd like**
This was discussed briefly on discord:

**1. Require braces for attribute values** except for str/num/bool literals.

Right now you can do `attr=arbitrary.expression() + thing` - but this requires that the expression after the `=` is valid - if you write something like `arbitrary.`, the macro won't expand and you don't get any autocomplete suggestions after the `.`.

This change would require any non-literal expressions to be wrapped in braces, like `attr={arbitrary.expression() + thing}`. This makes it easier to parse (just take everything inside the `{}`), providing r-a support even in incomplete expressions.

**2. More consistent value shorthands**

On HTML attributes, the attribute `checked` is equivalent to `checked=true`, while on leptos components, it is `checked={checked}`.
Make this consistent by making `checked` always equivalent to `checked=true`, and `{checked}` equivalent to `checked={checked}`. 

Both of these changes are also what other frameworks like Svelte does.

**Describe alternatives you've considered**

staying with the current macro.

**Additional context**

My own view macro [leptos-mview](https://github.com/blorbb/leptos-mview) implements these requirements, and does have significantly better r-a support. Feel free to steal parts of my implementation for this change.

**Comment by jquesada2016** [comment]
I like this!

**Comment by JonahLund** [comment]
Yes, I would love a stricter/more consistent view macro aswell

**Comment by benwis** [comment]
I could see this in 0.7 if someone wants to PR it and we can get a migration aid.

**Comment by blorbb** [comment]
ill have a go at implementing this

**Comment by rakshith-ravi** [comment]
@blorbb just cleaning up some older issues, and wanted to check - has this been merged into main? Can this issue be closed?

**Comment by blorbb** [comment]
@rakshith-ravi the first point has, I'm not sure what the status of the second point is in 0.7

**Comment by gbj** [comment]
Point 1 is resolved, I disagree with point 2.

`{checked}` probably would have been a better syntax for components in the first place, but I think making breaking syntax changes is a losing proposition (you will always annoy at least as many people as you please) unless there is a particularly compelling reason (i.e., there's something that can't be achieved with syntax A and can only be achieved with syntax B).
