### ISSUE TITLE
server_fn crate docs.rs build failed v0.6.0-beta 

### ISSUE THREAD

**Issue by paul-hansen** [leptos-rs/leptos#2197]
The [docs](https://docs.rs/crate/server_fn/0.6.0-beta) for the [server_fn](https://github.com/leptos-rs/leptos/tree/v0.6.0-beta/server_fn) crate failed to build.

Build log is here: https://docs.rs/crate/server_fn/0.6.0-beta/builds/1092731

Couldn't find any existing discussions/issues about this so I thought I should let someone know.

It appears to be caused by lines like this:
https://github.com/leptos-rs/leptos/blob/8b5dd99d7fba5acca391810152f5538c741accf2/server_fn/src/client.rs#L36
which enable code when a feature is enabled OR when building the docs, I guess that it's trying to build the docs without the feature which causes the optional dependencies the feature enables to not be compiled so it fails when it tries to use them.

**Comment by paul-hansen** [comment]
Perhaps this is a better replacement for `#[cfg(any(feature = X, doc))]` ?

**Cargo.toml**
```toml
[package.metadata.docs.rs]
features = ["X", ]
# OR
# all-features = true
```
Documentation for this is here: https://docs.rs/about/metadata

Will need to update CI to test docs using the --all-features flag or something too if applicable.


Note that I haven't messed with the publishing end of docs.rs much myself so prefer the opinion of anyone with experience over mine.

**Comment by gbj** [comment]
Thanks -- added the docs.rs metadata section.
