### ISSUE TITLE
Incorrect route gets rendered

### ISSUE THREAD

**Issue by bokenator** [leptos-rs/leptos#2201]
Hi, I'm new to Leptos, so it's possible that I'm not defining the routes properly. I've also tried changing the `<Home />` route to `path=""` and the `<Post />` route to `path="/:id"` but they yield the same result.

**Describe the bug**
Given the following routes:
```
<Router trailing_slash={TrailingSlash::Drop} fallback={|| view! { <NotFound /> }}>                                                                                                  
      <nav>
            <A href="/">"Home"</A>
      </nav>
      <main>
            <Routes>                                                                                                                                                
                  <Route                                                                                                                                                                  
                        path="/"
                        view={|| view! { <Home /> }}
                  />
                  <Route
                        path=":id"
                        view={|| view! { <Post /> }}
                  />
            </Routes>
      </main>
</Router>
```
Expected behavior:
- `https://example.com` should render `<Home />`
- `https://example.com/123` should render `<Post />`

Actual behavior:
- `https://example.com` renders `<Post />`
- `https://example.com/123` renders `<Post />`

**Leptos Dependencies**

```toml
leptos = { version = "0.5", features = ["csr"] }
leptos_router = { version = "0.5", features = ["csr"] }
```

**Comment by gbj** [comment]
Your understanding of the expected behavior is correct. Unfortunately it looks like #2172 broke matching on `/` if there is a possible param at the same level. Thanks for raising this — I will need to fix this and likely yank the last two releases.
