### ISSUE TITLE
axum 0.7++ support

### ISSUE THREAD

**Issue by MinaMatta98** [leptos-rs/leptos#2204]
Hello,

If you have time, this would be much appreciated :)

**Comment by gbj** [comment]
Searching "Axum 0.7" in the repo yields results for:
- #2111 
- #2082 
- #2158 

You can use `0.6.0-alpha` or `0.6.0-beta` Leptos versions to support Axum 0.7.

**Comment by MinaMatta98** [comment]
My bad, should've checked.

Thanks!!

**Comment by gbj** [comment]
Sorry for my somewhat rude reply! I was frustrated about something completely unrelated and should've taken a minute before typing. I'm really happy that we're finally getting close to Axum 0.7 support -- for 95% of use cases using one of the 0.6 prereleases should work.

**Comment by MinaMatta98** [comment]
Nah. I've been working for quite a while, got tired and didn't think to check. 

Thank you for all your work.
