### ISSUE TITLE
Add server_fn_by_path() to 0.6.0-beta server_fn for external users

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#2212]
Working on updating the leptos-spin package to work with 0.6.0-beta, and I need to be able to match and retrieve server_fn_by_path() as we did in 0.5. Maybe behind a feature flag called generic?

EDIT: I think since we're moving Request/Response processing into the server_fns, we'll have to add Spin's IncomingRequest and OutgoingResponse types under a spin feature flag

**Comment by gbj** [comment]
This is similar to the conversation about Viz integration. For any integration that's not going to be maintained by us/in this repo, I think the most straightforward path is to do two things:
1. **Macro**: Provide a custom `#[server]` macro that injects the correct request/response types, so they are used in each server macro created. This is a simple matter of a proc-macro crate that adapts the following to replace `None` with `Some(/* the correct request or response type */)`. Only the two `None` lines need to change.
https://github.com/leptos-rs/leptos/blob/b450f0fd10e3cd8a3ecaefe461ef48003d24621b/leptos_macro/src/lib.rs#L947-L961
2. **Runtime**: At present, Actix and Axum are both handling the map of requests themselves, given their distinct request/response types. I would think most of the below could be adapted for the Spin integration.
https://github.com/leptos-rs/leptos/blob/b450f0fd10e3cd8a3ecaefe461ef48003d24621b/server_fn/src/lib.rs#L458-L537

I think both these things should live outside this repo, if fermyon is open to them living in the `leptos-spin` repo, for the sake of maintenance burden over time.

**Comment by benwis** [comment]
> I found both `Req` and `Res` traits need to be implemented. <img alt="Screenshot 2024-01-23 at 15 41 29" width="914" src="https://private-user-images.githubusercontent.com/27926/298847072-4e4e360f-750b-4fa0-86e8-c5ce6504c2da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzE1MzksIm5iZiI6MTcwNjAzMTIzOSwicGF0aCI6Ii8yNzkyNi8yOTg4NDcwNzItNGU0ZTM2MGYtNzUwYi00ZmEwLTg2ZTgtYzVjZTY1MDRjMmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE3MzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NTg2MzFmYTllZGFjZTViMTUwOTFhYzhiY2YwMzhjMjc3MzFjZjY3ZDNiNTg1ODMwN2YwNGZhZGViNDlkMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oXLsXdt-nGgsKgECwhWT97wvf9TTg6SEUgWQ8qZ8Two">

Yeah, if not using either http's or Actix's Request/Response types

**Comment by benwis** [comment]
Closing this one as well, seems like a fairly sane default for external users
