### ISSUE TITLE
leptos_axum extract parameters need to be `Debug`

### ISSUE THREAD

**Issue by maccesch** [leptos-rs/leptos#2219]
**Describe the bug**
In the `extract` function parameters are required to be `Debug`. I'm trying to use it with a library that has the `FromRequestParts` implemented but not `Debug`.

This is why the following code won't compile:

```rust
extract(|csrf_token: axum_csrf::CsrfToken| async move { 
   csrf_token
})
```

Looking at the code of `extract` it seems that this is really not necessary. Can we remove it?

**Leptos Dependencies**

```toml
leptos_axum = { version = "0.5", optional = true }
```

**Comment by gbj** [comment]
That seems totally reasonable. I was going to ask if you wanted to make a PR but this has actually already been fixed on main during the process of updating to Axum 0.7 and new server fns. I'm expecting to make a 0.6 release in the next week or so. Not sure there's further action on this other than patching it locally for your own use for right now.

**Comment by maccesch** [comment]
Awesome! Thanks!
