### ISSUE TITLE
Resource refetch effect

### ISSUE THREAD

**Issue by ycuk** [leptos-rs/leptos#2221]
**Describe the bug**
Resource `.refetch()` runs effect function.

I have two behaviors for my resource:
a. When click button load data from resource, append to vector, show reactive data.
b. When change url query params by external signal (i.e from top navbar), catch that by effect, clear vector, refetch resource, append to vector, show reactive data.

So, when I click button, I see "refetch effect" in console, because `.refetch()` runs effect function.

**Expected behavior**
Resource `.refetch()` should not run effect function.

Maybe provide `refetch_untracked()`?

**Leptos Dependencies**
```toml
leptos = { version = "0.5.7", features = ["csr", "nightly"] }
```

```rust
use leptos::*;
use leptos_router::{*};


pub async fn get_data_func(page: usize) -> Vec<String> {
    // let qs = use_location().search.get_untracked();
    // let url = format!("/api/data?page={}&{}", page, qs);
    // gloo_net::http::Request::get(&url).await

    vec![1, 2, 3, 4, 5].get(page).iter().map(|x| x.to_string()).collect()
}

#[component]
pub fn NavBar() -> impl IntoView {
    let (sort_example, set_sort_example) = create_signal(0usize);
    let (_, set_q_sort) = create_query_signal::<String>("sort");

    view! {
        <button on:click=move |_| {
            set_sort_example.set(sort_example.get_untracked() + 1);
            set_q_sort.set(Some(sort_example.get_untracked().to_string()));
        } type="button">Sort</button>
    }
}

#[component]
pub fn Page() -> impl IntoView {
    let (get_page, set_page) = create_signal(0usize);

    let objs = create_resource(move || get_page.get(), get_data_func);
    let (data, set_data) = create_signal(vec![]);

    create_effect(move |_| {
        match objs.get() {
            Some(mut objs) => {
                set_data.update(|data| data.append(&mut objs));
            }
            _ => {}
        }
    });

    let (get_q_sort, _) = create_query_signal::<String>("sort");
    create_effect(move |_| {
        log::debug!("here .refetch() runs effect instead of get_q_sort.get()");
        get_q_sort.get();
        set_data.set(vec![]);
        objs.refetch();
    });

    view! {
        <div>{ move || data.get().into_iter().map(|item| view! {
            <p>{item}</p>
        }).collect_view() }</div>

        <button on:click=move |_| {
            set_page.set(get_page.get_untracked() + 1);
        } type="button">More</button>
    }
}

#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <NavBar/>
            <Page/>
        </Router>
    }
}
```

**Comment by gbj** [comment]
The reproduction provided above doesn't compile, but I created a version that reproduced the issue, and the attached PR does fix it. However, could you test it to make sure that it now works as intended? What you're trying to do is a little unclear to me. 

I would add that your example here is, IMO, an antipattern: Rather than calling `.refetch()` in an effect that reads from `get_q_sort`, `get_q_sort` should be included in the source signal for the resource (so that it's `move || (get_page.get(), get_q_sort.get())`) But I understand that this may be a simplified form

**Comment by ycuk** [comment]
Ok, edited to reproduction. Sorry cant check your commit, it shows many errors on compile.
So the main issue is when click More button, it should **only** load next page from resource, then append loaded data to vector. Instead of this `.refetch()` touches effect and clear vector, that I dont expect.

**Comment by ycuk** [comment]
I think got your point, and will try other options. Anyway I guess it would be good to have `refetch_untracked()` in future for some cases. Thanks!

**Comment by gbj** [comment]
> Sorry cant check your commit, it shows many errors on compile.

Could you clarify what you mean here? For me, the new reproduction you provided above compiles and works against the branch in the PR I linked to. If there are errors for you could you provide a sample?

> Anyway I guess it would be good to have `refetch_untracked()` in future for some cases.

This shouldn't be necessary because `refetch()` should *always* be untracked. The fact that it currently tracks one thing (the source memo) is a bug, which the PR is supposed to fix.

**Comment by ycuk** [comment]
> Could you clarify what you mean here?

Mayme im wrong, but I use this
```toml
leptos = { git = "https://github.com/leptos-rs/leptos.git", rev = "ea6c957f3d982d31c52f3b50c7cf7224f57c1344", features = ["csr", "nightly"] }
```

```
   Compiling leptos v0.5.7
error[E0659]: `url` is ambiguous
  --> /Users/ycuk/.cargo/git/checkouts/leptos-2c8932a5258b3db6/ea6c957/server_fn/src/codec/mod.rs:40:9
   |
40 | pub use url::*;
   |         ^^^ ambiguous name
   |
   = note: ambiguous because of multiple potential import sources
   = note: `url` could refer to a crate passed with `--extern`
   = help: use `::url` to refer to this crate unambiguously
note: `url` could also refer to the module defined here
  --> /Users/ycuk/.cargo/git/checkouts/leptos-2c8932a5258b3db6/ea6c957/server_fn/src/codec/mod.rs:38:1
   |
38 | mod url;
   | ^^^^^^^^
   = help: use `self::url` to refer to this module unambiguously

error[E0562]: `impl Trait` only allowed in function and inherent method return types, not in trait method return types
  --> /Users/ycuk/.cargo/git/checkouts/leptos-2c8932a5258b3db6/ea6c957/server_fn/src/client.rs:33:10
   |
33 |     ) -> impl Future<Output = Result<Self::Response, ServerFnError<CustErr>>> + Send;
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #91611 <https://github.com/rust-lang/rust/issues/91611> for more information
   = help: add `#![feature(return_position_impl_trait_in_trait)]` to the crate attributes to enable
```
And so on large output report of errors...
