### ISSUE TITLE
Make LeptosRoutes/generate_route_list() more modular for 0.6

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#2223]
For serverless function implementations, it would be good to allow people to both manually define(or use a catchall) for Leptos routes and maybe seperate the serverl fn route generation into it's own function that can be called

**Comment by gbj** [comment]
I'm just cleaning up the issue track at the moment. If this hasn't already been accomplished during your work on the spin integration, feel free to open a new issue with some more specifics on what we need to implement.
