### ISSUE TITLE
CI: explore adding `cargo-semver-checks`

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#2229]
**Is your feature request related to a problem? Please describe.**
I'd like additional help from CI in identifying possible breaking API changes in PRs.

**Describe the solution you'd like**
Adding [`cargo-semver-checks`](https://lib.rs/crates/cargo-semver-checks) as part of CI won't catch every possible breaking change, but could be an extra layer of protection.

Open to other thoughts!

**Comment by agilarity** [comment]
They recommend pinning the nightly version.

I can add a workflow to run this after #2272 is merged. It pins the nightly version.

You may also want to run the `cargo-semver-checks` when a version tag is added.
