### ISSUE TITLE
leptos_axum::extract requires unused generic and example does not compile

### ISSUE THREAD

**Issue by paul-hansen** [leptos-rs/leptos#2234]
**Describe the bug**
Trying the example code given in the docs [here](https://docs.rs/leptos_axum/0.6.2/leptos_axum/fn.extract.html) returns this error:
```
error[E0283]: type annotations needed
    --> main.rs:112:24
     |
112  |     let Query(query) = extract().await?;
     |                        ^^^^^^^ cannot infer type of the type parameter `CustErr` declared on the function `extract`
     |
     = note: cannot satisfy `_: StdError`
note: required by a bound in `leptos_axum::extract`
    --> /home/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_axum-0.6.2/src/lib.rs:1779:14
     |
1775 | pub async fn extract<T, CustErr>() -> Result<T, ServerFnError>
     |              ------- required by a bound in this function
...
1779 |     CustErr: Error + 'static,
     |              ^^^^^ required by this bound in `extract`
help: consider specifying the generic arguments
     |
112  |     let Query(query) = extract::<axum::extract::Query<std::string::String>, CustErr>().await?;
     |                               ++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Leptos Dependencies**
```toml
leptos = { version = "0.6", features = ["tracing"] }
leptos_meta = { version = "0.6" }
leptos_router = { version = "0.6" }
leptos_axum = { version = "0.6" }
axum = { version = "0.7", features = ["macros"] }
```

**Expected behavior**
Expected the example code to compile.

**Additional context**
ServerFnError was changed in leptos 0.6 to have a custom error type. I don't think extract is handling this properly as it should either use and return the custom error used by the FromRequestParts implementation, or it should return NoCustomError. Instead it's creating a new ServerFnError with the type that's required by the signature but that ServerFnError is always ServerFnError::Server so the custom error type is never constructed.

**Comment by paul-hansen** [comment]
**Workaround for 0.6**
```rust
/// This is like `server_fn::error::NoCustomError` but implements Error so it can be passed to extract.
#[derive(Debug)]
pub struct NoCustomErrorErr {}
impl std::error::Error for NoCustomErrorErr {}
impl std::fmt::Display for NoCustomErrorErr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "")
    }
}

#[server]
pub async fn query_extract() -> Result<String, ServerFnError> {
    use axum::{extract::Query, http::Method};
    use leptos_axum::*;
    let Query(query) = extract::<_, _, NoCustomErrorErr>().await?;

    Ok(query)
}
```
**Other Thoughts**
There should probably be an example somewhere that uses this and is compiled so problems like this are caught in the future.

**Comment by gbj** [comment]
This has been fixed on main and was supposed to have been published as 0.6.2, but I seem to have published 0.6.2 from the branch before that change in the rush to fix it. 

Republishing as 0.6.3 and I'll yank 0.6.2.

You're right that an example would've caught this earlier, as would wider use during the alpha/beta period.

**Comment by paul-hansen** [comment]
Ah, no worries! Thanks for dealing with this. I should have reported this during the beta, but I wasn't understanding what was happening yet so I thought it was a me problem lol.

**Comment by gbj** [comment]
All good :smile: Should be all set on latest 0.6.3 now.
