### ISSUE TITLE
ActionForm does not send name-value pairs from type=submit inputs

### ISSUE THREAD

**Issue by haslersn** [leptos-rs/leptos#2265]
(Leptos v0.6)

The following ActionForm doesn't send the `"accept": "true"` key-value pair when clicking "Accept" and JS/WASM is loaded. When JS/WASM is not loaded, yet, it works.

```rust
use leptos::*;
use leptos_router::*;

#[component]
pub fn App() -> impl IntoView {
    let handle_consent = create_server_action::<HandleConsent>();

    view! {
        <ActionForm action=handle_consent>
            <button type="submit" name="accept" value="true">Accept</button>
        </ActionForm>
    }
}

#[server(HandleConsent)]
async fn handle_consent(accept: Option<String>) -> Result<(), ServerFnError> {
    println!("{:?}", accept);
    Ok(())
}
```

(Leptos v0.6)

**Comment by gbj** [comment]
Please include a reproducible example, rather than deleting the issue template. Thanks!

**Comment by haslersn** [comment]
Hi @gbj! I don't always have time to fill out these issue templates. However, I'd be happy to provide a reproducible example, if there's an easy way. Is there something like a codesandbox with a Hello-World example for leptos 0.6 and SSR? Then I could fork that and add the necessary code. (The playground linked on the website seems to use leptos 0.5 and CSR.) Or do you propose some other way to share leptos examples?

**Comment by rakshith-ravi** [comment]
Hi @haslersn - Perhaps you can take one of the examples in the repo and use that as a template? That would give you a starting point to give us a reproducible example that we can use to debug the issue at hand. It would certainly make things easier for us to just clone something and see the error pop up, if you don't mind.

Additionally, the issue templates are meant to help us categorize the issues and sort them, so if you could use that next time onwards, that would be super helpful for us, and would save us all a lot of time in sorting through the issues. Thanks for understanding!

**Comment by haslersn** [comment]
Steps to reproduce:

1. ```bash
   git clone -b issue-2265 git@github.com:haslersn/leptos-playground.git
   cd leptos-playground/
   nix develop # skip this if you already have the necessary dependencies installed
   cargo leptos serve
   ```
2. Go to http://127.0.0.1:3000
3. Click "Accept"

Depending on whether you have JS/WASM enabled and loaded, or not, the server will print `None` or `Some("true")`. The expected behavior is `Some("true")`.

When using the Network Monitor (Firefox Ctrl+Shift+E), you'll see that the POST requests sent by JS don't contain the `accept=true` body.

**Comment by gbj** [comment]
Thanks. For the sake of clarity all I mean by "reproducible example" is something like this, which can just be copied and pasted and compiles: https://github.com/haslersn/leptos-playground/commit/0c48ce6be15f3d4c9609f1902ab46267d550907c

The issue here is basically a quirk of the browser. If you construct a new `FormData` in JS from a `<form>` element (which we do [here](https://github.com/leptos-rs/leptos/blob/main/router/src/components/form.rs#L760-L761)), it appears not to include `<button>` name-value pairs, but if you submit the form without JS, it does not. (I have tested this with vanilla JS and it is true, it's nothing the framework is doing differently here.)

I guess it's possible to add a workaround to patch the browser's behavior here.  Do you have any interest in working on that?

**Comment by haslersn** [comment]
Not sure if it has something to do with the `<button>` tag. The same issue also occurs when replacing the button by

```
<input type="submit" name="accept" value="true"/>
```

so it seems more related to `type="submit"`.

**Comment by haslersn** [comment]
There can be multiple submit buttons. (This is actually the motivation for using values on the submit buttons, so the server knows which button was used.) The POST request should only contain the key/value pair from the submit button that was used.

When constructing the `FormData` [here](https://github.com/leptos-rs/leptos/blob/38bf73947fd87125b3ef0f2cafa631f7f86a2c06/router/src/components/form.rs#L760-L761), the framework probably doesn't know which submit button gets used, so not having any submit key/value pairs seems to be expected behavior.

We need to manually inject the key/value pair from the submit button that got used.

**Comment by haslersn** [comment]
I'm working on this.

**Comment by gbj** [comment]
> I'm working on this.

That is awesome! Thank you so much.

**Comment by haslersn** [comment]
See #2268
