### ISSUE TITLE
Server actions: redirect to different origin does not work in HTTPS scenario

### ISSUE THREAD

**Issue by haslersn** [leptos-rs/leptos#2269]
**Describe the bug**

When accessing a leptos app over HTTPS (via a TLS-terminating reverse proxy), redirects returned by server actions do not work, when the location points to a different origin. Instead of following the redirect, the following error is printed to the JS console:

```
Uncaught Error: `unwrap_throw` failed ([...]/leptos_router-0.6.5/src/history/mod.rs:124:18)
```

This seems to have to do with same origin policy.

In my limited experience, this error only happens when a `<Router>` component is involved.

**Leptos Dependencies**

```toml
leptos = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6", optional = true }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
```

**To Reproduce**

1. Run the following leptos component:
    ```rust
    use leptos::*;
    use leptos_meta::*;
    use leptos_router::*;
    
    #[component]
    pub fn App() -> impl IntoView {
        provide_meta_context();
    
        view! {
            <Stylesheet id="leptos" href="/pkg/leptos-playground.css"/>
            <Title text="Leptos Playground"/>
    
            <Router>
                <Routes>
                    <Route path="" view=MyForm/>
                </Routes>
            </Router>
        }
    }
    
    #[component]
    fn MyForm() -> impl IntoView {
        let redirect = create_server_action::<Redirect>();
    
        view! {
            <ActionForm action=redirect>
                <button type="submit">Redirect</button>
            </ActionForm>
        }
    }
    
    #[server(Redirect)]
    async fn redirect() -> Result<(), ServerFnError> {
        leptos_axum::redirect("https://example.com");
    
        Ok(())
    }
    ````
2. Set up a TLS-terminating reverse proxy
3. Access the app over HTTPS
4. Click "Redirect"

When WASM/JS is enabled and loaded, the server function is called via the `fetch()` API and the redirect is not followed. Instead the following error is printed in the JS console:

```
Uncaught Error: `unwrap_throw` failed ([...]/leptos_router-0.6.5/src/history/mod.rs:124:18)
```

Leptos tried to call the `pushState()` API with url `https://example.com` and that returned a `SecurityError` which got unwrapped using `unwrap_throw()`.

**Additional context**

The `<Router>` component seems to be necessary to reproduce the issue. Maybe, without it, leptos doesn't manage a Histroy object.

**Comment by gbj** [comment]
Thanks for reporting. This is my mistake. The redirect hook here needs to check whether it is redirecting to the same origin or not, and if it's a different origin, just use `window().location().set_href()`

https://github.com/leptos-rs/leptos/blob/38bf73947fd87125b3ef0f2cafa631f7f86a2c06/router/src/components/router.rs#L59-L69

Let me know if you'd like to make a PR to fix it, otherwise I will try to get to it relatively soon.

**Comment by haslersn** [comment]
I'm working on it.

**Comment by haslersn** [comment]
See #2271
