### ISSUE TITLE
CI failing due to `cargo hack` running clippy on dependencies

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#2272]
**Describe the bug**
CI is failing with a clippy issue inside `rkyv` on the latest nightly, which we can't address.

**Expected behavior**
We should probably do at least one of the following: 
1. run `cargo clippy --no-deps`, which will also save a huge amount of CI time by not running clippy over and over on dependencies shared between crates, which we don't control
2. pin clippy to a particular nightly so that PRs don't turn up clippy issues in already-committed code, due to new lints being added

@agilarity any interest in working on this?

**Comment by agilarity** [comment]
Yes, you can assign it to me.
