### ISSUE TITLE
Whitespace removed with variable

### ISSUE THREAD

**Issue by soundprojects** [leptos-rs/leptos#2277]
**Describe the bug**
When rendering a variable in an HTML tag, any additional whitespace is removed.

**Leptos Dependencies**

```
[dependencies]
leptos = { version = "0.5.6", features = ["csr"] }
leptos_meta = { version = "0.5.6", features = ["csr"] }
leptos_router = { version = "0.5.6", features = ["csr"] }
```

**To Reproduce**
1. Add a variable with some text
2. Like: 
`<div>{myvariable} km/h</div>`
4. Let's say myvariable is 10
5. Output will be 10km/h instead of 10 km/h

**Expected behavior**
I don't expect the spaces to be removed

**Comment by gbj** [comment]
This is working as designed, in line with limitations of whitespace in proc macros.

The default syntax is to wrap all text nodes in double quotes like `" km/h"`, with the nice ability to omit those double quotes in most (but not all cases).

i.e., simply use `<div>{myvariable} " km/h"</div>` in situations where you need to ensure this whitespace is preserved, not trimmed.

**Comment by soundprojects** [comment]
Thank you, this explains it all
