### ISSUE TITLE
tailwind_axum example css is not loaded

### ISSUE THREAD

**Issue by j00p34** [leptos-rs/leptos#2322]
**Describe the bug**
The tailwind_axum example works but the css file is empty so no styles show up. In the release version this is working correctly

**Leptos Dependencies**

**To Reproduce**
Run the example from the git source
**Expected behavior**

Css file on /pkg/tailwind_axum.css route is not empty

**Comment by gbj** [comment]
Thanks, this was my bad -- just a matter of fixing the CSS file name after another change. See #2324.
