### ISSUE TITLE
Server action's error value is not picked up after calling the action with JS/WASM disabled

### ISSUE THREAD

**Issue by haslersn** [leptos-rs/leptos#2325]
**Describe the bug**

The same bug as described in #2321 (`Ok` case) happens in case the server function returns an `Err`, even though the server could deserialize the error value from the query string that gets added during redirect.

Example:

```rust
use leptos::*;
use leptos_meta::*;
use leptos_router::*;

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    let action = create_server_action::<Identity>();
    let value = action.value();
    view! {
        <ActionForm action>
            <input type="text" name="x"/>
            <button type="submit">Submit</button>
        </ActionForm>
        {move || format!("{:?}", value.get())}
    }
}

#[server(Identity)]
async fn identity(x: String) -> Result<String, ServerFnError> {
    Err(ServerFnError::new(x))
}
```

In this example, when you submit "text", you get redirected to

```
/?__path=%2Fapi%2Fidentity3724951852840807129&__err=ServerError%7Ctext
```

but the server doesn't seem to pick up the value from the query and instead renders `None`.

**Leptos Dependencies**

I tested both leptos `v0.6.5` and leptos `main` @ 0f7b8841b2ee259a0d4776ac8321082c3766271a and got the same behavior.

**Comment by haslersn** [comment]
@gbj when trying to reproduce this in https://github.com/leptos-rs/leptos/issues/2321#issuecomment-1950058277, did you disable JS?

**Comment by gbj** [comment]
https://github.com/leptos-rs/leptos/assets/286622/93db0300-927f-474d-86c1-a83768a7b72e

**Comment by gbj** [comment]
Oh, I see. Your example doesn't use the `<Router>`.

**Comment by haslersn** [comment]
Indeed, in my small example, it didn't work because the Router is missing. But my actual application uses a Router.

It seems it also doesn't work when using a custom error type (Here: `String`):

```rust
use leptos::*;
use leptos_meta::*;
use leptos_router::*;

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    view! {
        <Router>
            <Routes>
                <Route path="" view=Component/>
            </Routes>
        </Router>
    }
}

#[component]
pub fn Component() -> impl IntoView {
    let action = create_server_action::<Identity>();
    let value = action.value();
    view! {
        <ActionForm action>
            <input type="text" name="x"/>
            <button type="submit">Submit</button>
        </ActionForm>
        {move || format!("{:?}", value.get())}
    }
}

#[server(Identity)]
async fn identity(x: String) -> Result<String, ServerFnError<String>> {
    Err(ServerFnError::from(x))
}
```

**Comment by gbj** [comment]
> Indeed, in my small example, it didn't work because the Router is missing. But my actual application uses a Router.
> 
> It seems it also doesn't work when using a custom error type (Here: String):

Could you clarify: is your actual application using a custom error type, or does "also" here mean this is an additional bug?

**Comment by haslersn** [comment]
> is your actual application using a custom error type, or does "also" here mean this is an additional bug?

My application uses a custom error type.
