### ISSUE TITLE
server fn call fails with empty `HashSet`

### ISSUE THREAD

**Issue by gitmalong** [leptos-rs/leptos#2337]
```rust
#[server(SettingsApi, "/api")]
pub async fn settings_api(settings: Settings) -> Result<(), ServerFnError> {
    // do something
    Ok(())
}
```

```rust
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Settings {
    pub currency: String,
    pub time_zone: String,
    /// Default valuation method
    pub valuation: ValuationMethod,
    /// Custom valuation methods
    pub valuations: HashSet<CustomValuationMethod>,
}
```

When calling `settings_api` from client side with a `Settings` struct that has a empty `valuations` `HashSet`(created via `Default::default()`) the call fails.

The browser sends only the following payload

```
year: 2021
settings[currency]: EUR
settings[time_zone]: Europe/Berlin
settings[valuation]: Fifo
```

As `valuations` is not an `Option<HashSet<CustomValuationMethod>>` value and it's therefore impossible to compile a program that does not set this field I consider this as a bug.

**Comment by gbj** [comment]
`valuations` should have the `#[serde(default)]` annotation added to it, and I think this will fix it. This is a quirk of `serde_qs`, the library we use for URL encoding form data.

**Comment by gitmalong** [comment]
I thought such a default annotation does not exist due to this comment: https://github.com/serde-rs/serde/issues/1098#issuecomment-451716088

However the serde default workaround works fine.

I found a related issue on `serde_qs`'s side https://github.com/samscott89/serde_qs/issues/78

Seems I was mistaken.

**Comment by gbj** [comment]
For future readers, this is documented [here](https://docs.rs/leptos/latest/leptos/attr.server.html#default-values-for-parameters).
