### ISSUE TITLE
Resource and timouts lacks any cancelation

### ISSUE THREAD

**Issue by gzp79** [leptos-rs/leptos#2339]
**Describe the bug**
Once a resource loading started or a set_timeout was created, they cannot be canceled, aborted.

**Leptos Dependencies**
```toml
leptos = { version = "0.6", features = ["csr"] }
leptos_meta = { version = "0.6", features = ["csr"] }
leptos_router = { version = "0.6", features = ["csr"] }
```

**To Reproduce**
```
#[component]
pub fn Sandbox() -> impl IntoView {
    log::info!("start component");

    let resource = create_local_resource(
        || (),
        move |_| async {
            log::info!("start resource loaded");
            leptos_ext::sleep(3_000).await;
            log::info!("pending resource loaded");
            Ok::<_, AppError>("resource".to_string())
        },
    );
    let resource = resource.error_bound();
    let navigate = use_navigate();

    set_timeout(
        move || {
            log::info!("timeout, navigating");
            navigate("/design/buttons", NavigateOptions::default());
        },
        Duration::from_secs(1),
    );

    on_cleanup(move || {
        log::info!("cleanup component");
    });

    view! {
        <div>
            {move || resource.get().map(|_| "loaded").unwrap_or("loading")}
        </div>
    }
}

```

In the above example:
- resource load is started, but after some timeout the page is navigated away.
- Issue1: without user interaction, the page is navigated to a new location, but resource is still loaded. If this is a fetch, the AbortController could be an option, but for a timeout this is not possible. 
- Issue2: If user navigates away before the set_timeout expires, it is still triggered and the user flow is broken again by navigating to an unwanted location

These are just a few examples, as during resource loading other "global" states could be set etc those are out of scope/context and the net result is that after mounting a new component, the old one may still interfere. It creates hard to find bugs.

It also breaks some common component/separation/etc. philosophy as for example the resource get cannot be "transparently" replaced to fetch, return data after timeout, return data immediately, etc.. The internal implementation detail of resource acquiring greatly effect the behavior of the component. (And I think in this case we are not talking about some small glitches, but a very different nature to anyone used to the rust async behavior)

I think a more general solution is required for these async object. It is just simple too common in an SPA to start multiple operation, fetches, etc,  but before they are completed, the user navigates away. When the cleanup is called the resources, timeouts etc. should be stopped and futures shall not be polled any more.

**Comment by gbj** [comment]
So, this issue raises two questions that are not actually related:
1. Canceling timeouts
2. Canceling resources

I will address them in that order.

**1. Canceling timeouts**

Leptos provides a small utility function for cancelable timeouts: [`set_timeout_with_handle`](https://docs.rs/leptos/latest/leptos/fn.set_timeout_with_handle.html). (The fact that this is separate from `set_timeout` was for backwards compatibility/being able to add it without a breaking change, when it was first added.) This returns a handle that can be used to cancel the timeout. 

So your timeout example is simply a question of:
```rust
    let handle = set_timeout_with_handle(
        move || {
            log::info!("timeout, navigating");
            navigate("/design/buttons", NavigateOptions::default());
        },
        Duration::from_secs(1),
    );

    on_cleanup(move || {
        log::info!("cleanup component");
        if let Ok(handle) = handle {
            handle.clear();
        }
    });
```

If you prefer a RAII/dispose-on-drop style, you can use [`gloo-timers`](https://docs.rs/gloo-timers/latest/gloo_timers/), which will cancel the timeout when its handle drops, and then `drop(handle)` in the `on_cleanup`.

**2. Canceling resources**

This is a difficult situation to solve in the general case. As far as I'm aware, neither Rust nor JavaScript have a general-purpose mechanism for canceling a Future/Promise. However, it's quite possible to race two Futures. You could, for example, use a oneshot channel — below is intended to show the concept, not compile, as I'm just typing into GitHub.

```rust
let (tx, rx) = futures::channel::oneshot::channel();

// on cleanup, send to the oneshot channel to cancel the Future
on_cleanup(move || tx.send(()));

create_local_resource(
  /* ... */, 
  |_| async move {
    // use futures::select to race the channel against the 
    select! {
      rx => None, 
      /* some other thing that loads data */
    }
  }
);
```

So you can also set this up for yourself, if needed. 

But it should be relatively rare that you actually need to do this: the `async` block in a resource is for loading data, not running arbitrary side effects. If you are running side effects (like navigating) in a resource's data loading, you should be using `create_effect` instead — and `create_effect` *will* be canceled. So for example "load this async data and then navigate" should be handled with a resource and an effect, not a cancelable resource.

**Why not do this by default?**

You might ask why these two cancellation patterns aren't just the default behavior. i.e., why doesn't `set_timeout` automatically cancel itself in an `on_cleanup`, and why doesn't `create_resource` automatically race against a oneshot channel that fires in `on_cleanup`?

The answer is pretty simple: doing this adds overhead for every user, when it usually isn't necessary and can be done in userland. You could even implement your own functions that do exactly this, and then use them in your application. That's the good thing about smaller, composable primitives.

**Comment by gzp79** [comment]
Thanks. I see. 
I assume in my case some CancelationList could be the solution with functions likes timeout, create_(local)_resource that encapsulates the mentioned options. Within the cancelation I can handle this one shot channel, timouthandles etc. and hence if resource etc is created through my "strategy" they are "auto" canceled. Do ypu think if it is posible to implement ? (There are not much such resources but I know if i have to manually handle each cancelation independently some will be forgotton)
