### ISSUE TITLE
Programmatically navigate [Suggestion]

### ISSUE THREAD

**Issue by peteringram0** [leptos-rs/leptos#234]
On the router example it would be good to provide an example on how to programmatically navigate. Thanks

**Comment by gbj** [comment]
Sure! The answer is [use_navigate](https://docs.rs/leptos_router/0.0.8/leptos_router/fn.use_navigate.html) if you're just looking for it for yourself, but I'll add it to the example.

**Comment by peteringram0** [comment]
Thanks @gbj for the help!! So when using use_navigate with the default navigateOptions the URL changes but the router does not update to reflect the changes that should be applied to the dom. Do i need to trigger something manually to get the dom to update as per the route? Thanks for your help.

**Comment by gbj** [comment]
Sounds like either a mistake or a bug. Can you provide an example to reproduce it?
