### ISSUE TITLE
SSR renders in the wrong order

### ISSUE THREAD

**Issue by maccesch** [leptos-rs/leptos#2349]
The two marked elements `(1)` and `(2)` in the screenshot below should be rendered inside of `table > tbody` but instead they are rendered before `table`.

<img width="779" alt="Screenshot 2024-02-22 at 01 19 13" src="https://github.com/leptos-rs/leptos/assets/380881/c9a6833c-80c9-4175-b0ec-c514aaaf9a12">

In CSR with trunk this works. I tried all SSR modes but it doesn't make a difference.

To reproduce please run [this example](https://github.com/Synphonyte/leptos-struct-table/tree/master/examples/serverfn_sqlx).

The relevant code [is in this file](https://github.com/Synphonyte/leptos-struct-table/blob/master/src/components/table_content.rs).

`(1)` is rendered here:
https://github.com/Synphonyte/leptos-struct-table/blob/7935378b09975dcd11b607f4d2f0ada1266a7554/src/components/table_content.rs#L471

`(2)` is rendered here:
https://github.com/Synphonyte/leptos-struct-table/blob/7935378b09975dcd11b607f4d2f0ada1266a7554/src/components/table_content.rs#L567

**Comment by gbj** [comment]
I don't think you can actually put divs inside a table like this.

If I simplify this to
```rust
#[component]
pub fn Component() -> impl IntoView {
    view! {
        <table>
            <div>"A"</div>
            <tr><td>"B"</td></tr>
            <div>"C"</div>
        </table>
    }
}
```
They appear `ACB`, even though the rendered HTML is
```html
<table data-hk="0-0-0-8">
  <div data-hk="0-0-0-9">A</div>
  <tr data-hk="0-0-0-10"><td data-hk="0-0-0-11">B</td></tr>
  <div data-hk="0-0-0-12">C</div>
</table>
```
Firefox tells me this is invalid HTML.

It's entirely possible it works in CSR mode even though it's invalid HTML — in my experience the DOM *does* allow you to manually construct trees of DOM elements that would be invalid/"fixed" by the browser if parsed from html.

**Comment by maccesch** [comment]
This might be the case, but it still should render the invalid html in the right order in SSR, no? I can change the two elements to `<tr>` and check again

**Comment by gbj** [comment]
Unless I'm mistaken about what's happening, Leptos renders the HTML as you intend it to, and the browser reorders the elements because that HTML is not valid. We can't stop the browser from doing that. 

Check "View Source" on the page rather than the DOM inspector to see whether Leptos renders the HTML in the correct order. If it doesn't then we can fix that.

**Comment by maccesch** [comment]
ohh!!! You're right, changing the placeholders to `<tr>` fixed it.

Thanks man, you're the best!
