### ISSUE TITLE
Route component without re-render its view

### ISSUE THREAD

**Issue by ycuk** [leptos-rs/leptos#2352]
**Describe the solution you'd like**
a. A new property in existing `<Route>` to disable cleanup (dispose) after first render.
b. A new component that never cleanups (disposes) after first render.
c. I'm not sure if new property is suitable for `<StaticRoute>`

**Additional context**
I have dashboard index page with statistic loading from `create_action` and don't want to reload data every time when I back to that page. It doesn't matter resource or action, I have buttons to reload data manually or change date range, so `action.dispatch()` more useful. So server-side cache is not really what I need. For now my data is small and its ok with re-render, so it looks like a flash. In future will be more data and more pages like this. Also in my other project, index page too, it is photo album root if tree page, many thumbnails.

**Comment by ycuk** [comment]
Your way is working, but I added pagination or infinite scroll and it resets pagination or scroll position.

**Comment by uberfig** [comment]
sad to see this isn't planned, I do like the idea of `<LeakRoute/>` and can definitely see uses for it like a social media app with a home feed and the ability to view a post and return to the feed without loosing the position in the feed. There are workarounds though and its not a huge deal

**Comment by gbj** [comment]
@uberfig The way to do this would be to create a resource that lives in the root of the app, to cache the data, and to provide it via context so it can be used by components anywhere.
