### ISSUE TITLE
Drop `PartialEq` requirement in `create_owning_memo`

### ISSUE THREAD

**Issue by zroug** [leptos-rs/leptos#2388]
**Is your feature request related to a problem? Please describe.**
`create_owning_memo` requires `T` to implement `PartialEq`. This is unnecessary because `f` returns a boolean that determines if the value has changed. It can also be confusing because it makes it unclear whether the equality is being used from `PartialEq` or from the boolean.

**Describe the solution you'd like**
Drop the requirement for `PartialEq`.

**Describe alternatives you've considered**
Use of a wrapper type that has a dummy implementation for `PartialEq`.

**Additional context**
`create_owning_memo` was added in the new 0.6.7 release.

**Comment by gbj** [comment]
Thanks, probably just left in accidentally in the initial PR to add it. Any interesting in making a PR to fix it?
