### ISSUE TITLE
`#[prop(attrs)]` support for slots

### ISSUE THREAD

**Issue by Stefanuk12** [leptos-rs/leptos#2401]
It seems that `#[prop(attrs)]` is not currently supported for slots. The following code snippet errors on the `attrs`:
```rs
#[slot]
pub struct SlotTest {
    #[prop(attrs)]
    attributes: Vec<(&'static str, Attribute)>,
}
```
```
supported fields are `optional`, `optional_no_strip`, `strip_option`, `default` and `into`
```

**Comment by gbj** [comment]
It is very odd the way timing works out sometimes: someone made PR #2396 *yesterday* to add this. Want to help test it out?

**Comment by benwis** [comment]
That PR was merged into git main in leptos if you want to try it @Stefanuk12

**Comment by Stefanuk12** [comment]
Will do, haven't had an opportunity to recently but I will 😁
