### ISSUE TITLE
Warning: unnecessary braces around block return value

### ISSUE THREAD

**Issue by VVishion** [leptos-rs/leptos#2405]
**Describe the bug**
The following line produces the warning `warning: unnecessary braces around block return value`
```rust
view! { {format!("See {}", "something"))} }
```

But without the brackets
```rust
view! { format!("See {}", "something")) }
```
the view macro will take it as a literal and renders `format!("See {}", "something")` instead of `See something`

**Expected behavior**
No such warning, because the brackets are necessary.

**Comment by VVishion** [comment]
Maybe this is not that important. It seems that you should always use the reactive system
```rust
view! { "See " {|| "something"} }
```
over the format macro.
Im still exploring leptos, so Im lacking the knowledge.

**Comment by gbj** [comment]
The view macro is unnecessary in both those cases. Just return the String.

**Comment by gbj** [comment]
> Maybe this is not that important. It seems that you should always use the reactive system
> 
> ```rust
> 
> view! { "See " {|| "something"} }
> 
> ```
> 
> over the format macro.

No, using a closure here would not be a good idea, unless you're reading something reactive (which is not the case in this example).

**Comment by VVishion** [comment]
Yes, these were dumb examples. I failed to demonstrate you may want to use e.g. a macro inside `view!`. For those cases the warning is misleading. Closing for now.
