### ISSUE TITLE
leptos_router still pulls gloo_net 0.2

### ISSUE THREAD

**Issue by ydirson** [leptos-rs/leptos#2411]
All other crates are at 0.5 and 0.2 has had no update in 1y.

Would have submitted a PR, but I don't really know what to do of some API changes, like `body()` now returning a `Result`, while it is called from `<Form>` component - and since I have not started using that component my testing would be limited.

**Comment by gbj** [comment]
I'm transferring this to the main repo, as I think it belongs there rather than in the book.

**Comment by ydirson** [comment]
oops sry :)

**Comment by gbj** [comment]
The first time I tried it I thought it would require a breaking change. It turns out I just can't read docs. See #2416.
