### ISSUE TITLE
Panic with nested `islands`

### ISSUE THREAD

**Issue by boyswan** [leptos-rs/leptos#2440]
Currently, rendering an island directly in another panics (ex: `OuterFailing`). The only way around this is to render via children (ex: `OuterWorking`). 

This can be problematic as it uses up the child prop, and the `slot` solution to this is incompatible with islands. As a workaround I have various "island wrappers" which wrap a component in an empty island component, but it can get quite messy.

Perhaps what I'm attempting is an anti-pattern and nesting islands should be best avoided?

```rust
use leptos::*;

#[island]
pub fn CommonIsland() -> impl IntoView {
    let val = RwSignal::new(0);
    view! {
        <div>
            {move || format!("CommonIsland value is {}", val.get())}
            <button on:click=move|_| val.update(|x| {*x += 1})>Click</button>
        </div>

    }
}

#[island]
pub fn OuterWorking(children: Children) -> impl IntoView {
    let val = RwSignal::new(0);
    view! {
        <>
            <div>
                {move || format!("outer value is {}", val.get())}
                <button on:click=move|_| val.update(|x| {*x += 1})>Click</button>
            </div>
            {children()}
        </>

    }
}

#[island]
pub fn OuterFailing() -> impl IntoView {
    let val = RwSignal::new(0);
    view! {
        <>
            <div>
                {move || format!("outer value is {}", val.get())}
                <button on:click=move|_| val.update(|x| {*x += 1})>Click</button>
            </div>
            <CommonIsland/>
        </>

    }
}
#[component]
pub fn Example() -> impl IntoView {
    view! {
        <OuterFailing/>

        <OuterWorking>
            <CommonIsland/>
        </OuterWorking>

        <CommonIsland/>
    }
}

```

**Comment by gbj** [comment]
(Oh I should add: It is likely this will be fixed in 0.7, which is where I'm spending most of my energy, as the hydration works completely differently. I will tag this with 0.7 to make sure it is closed in that version if not before.)

**Comment by boyswan** [comment]
Great! In the meantime I'll do a little digging and see if I can find anything. Will update on here if so.

**Comment by gbj** [comment]
Can confirm this no longer panics on 0.7/git main, and all buttons seem to work.
