### ISSUE TITLE
Deep vs. shallow signal trait implementations

### ISSUE THREAD

**Issue by Giovanni-Tably** [leptos-rs/leptos#2445]
This is a tracking issue for traits implemented on signal types, and whether they should be 'shallow' or 'deep', and whether they should be tracking or not.

- A 'shallow' implementation does not access the value of the signal.
- A 'deep' implementation accesses the value of the signal.
  - If the value is accessed, we can track the signal or not (call `.get()` or `.get_untracked()`).

Considerations:
- In general, in Rust, 'pointer-ish' containers use the internal value for comparisons and similar traits (or don't implement the trait at all).
- We can't always avoid a panic in the process of accessing a value, because the signal might be a plain closure which itself may access a disposed signal.
  - In theory we could `catch_unwind`, but that is problematic because of the risk of running some code midway through and unwinding doesn't work on wasm anyway (yet).
- A deep `Debug` implementation is *really* useful for debugging.
- Shallow trait implementations will make nested signals less ergonomic.
- In the case of a deep implementation, the signal is being 'accessed'. That makes it feel like it should subscribe (`if a == b {}` being equivalent to `if a.get() == b.get() {}`).
- If we have a deep implementation which subscribes, then collections which rely on the values themselves (`HashMap`, `BTreeMap`, ...) might subscribe to arbitrary value on each access.
  - For keys, stashing things with interior mutability in these collections is already something to be careful with. Values would not be accessed.
- Under what scenario for an end-user something like `a == b` should compare the 'pointers'?
- if `a == b` subscribes, then the reactive graph might be less explicit. Whether this is a positive or negative probably depends on personal preference.
- In terms of breakage, we switched to deep trait implementations in a fork and we didn't see it cause any breakage (though we also are not using all the API surface).
- A migration path could look like: add `PointerEq` trait or similar, then remove all instances of `PartialEq` on signals, then migrate any usage to `PointerEq`, then re-implement `PartialEq` with new semantics. A process like that would guarantee nothing in `leptos` proper breaks.

---

Some relevant traits:
- `Debug`
  - `Arc`, `Rc`, & `Box` forward to the inner values.
  - `RefCell` & `Mutex` do the same but print tags if the value is inaccessible.
- `PartialEq`
  - `Arc`, `Rc`, `Box`, `RefCell` forward to the inner values.
  - `Mutex` does not implement `PartialEq`.
  - `{Rc,Arc}::ptr_eq` are available.
- `PartialOrd`
  - `Arc`, `Rc`, `Box`, `RefCell` forward to the inner values.
  - `Mutex` does not implement `PartialOrd`.
- `Hash`
  - `Arc`, `Rc`, & `Box` forward to the inner values.
  - `RefCell`, & `Mutex` do not implement `Hash`.
- `Serialize` & `Deserialize`
  - This one essentially has to be deep to work. It is implemented by forwarding to the inner value for every type in `serde`.

Currently the signals all implement shallow versions of the traits above, with the exception of `Serialize` and `Deserialize`.

---

(This is a follow up to #2384)

**Comment by gbj** [comment]
Apologies for the slow response. Two main reasons I haven't written yet:
1) I don't have very strong feelings about it
2) Sometimes when I don't have a strong opinion, it's helpful not to prejudice whatever discussion others may want to have with my half-formed thoughts.

That said, here's a response now.

**Meta-response**: A few data points for consideration:
- AFAIK the way these traits are implemented now is the way they have always been
- This is the only time this question has been raised 
- There have been no reactions or replies to the issue

To me, this suggests that to the extent that people use these traits, they're generally happy with the current behavior. It's very hard to make an argument from silence; but I have a pretty good sense of conversations among the user base about what they'd like to see change, and these aren't on the list.

To me, this argues pretty strongly *against* making a breaking change to the behavior.

**Substantive response**: A few points here.

*Smart pointer vs. signal*: From my perspective, signals are not smart pointers. Specifically, they cannot be dereferenced to get their inner value, and accessing them does have side effects; whereas smart pointers can be (infallibly!) dereferenced to an inner value without side effects. 

A signal is not a way of saying "this is a thing that points to this value." It is a way of saying "this is a container with a stable identity over time, even as its value changes."

*Performance considerations*: It is very useful to be able to use a signal as (for example) a `HashMap` key in a `For` component. Implementing very cheap `PartialEq` and `Hash` operations (you're just comparing or hashing an integer signal ID) is very useful for this purpose. 

*Reduced "magic"*: "Magic" is always a handwavey and subjective term. But I don't agree, for example, that `a == b` should be the equivalent of `a.get() == b.get()`. I have found it helpful to be very explicit about signal access and signal updates; while marginally verbose they make it much clearer what's going on in your code. This is why, for example, we don't implement traits like `AddAssign` for signals: while it would *look* really cool to be able to just `set_count += 1`, I think it becomes really confusing when things that don't look like they're accessing or updating a signal do.

*User experience*: I spend a lot of time on Leptos support. I anticipate that making this change would cause many issues, both by breaking or changing the behavior of existing codebases in hard-to-detect ways (an effect suddenly runs much more often, etc.), and by introducing confusing behavior for new users (wait, where did I access this signal?)

*****

Given all of the above, and the lack of significant interest from the rest of the community in making this change, I am going to say this is "not planned."
