### ISSUE TITLE
Documentation and examples on how to manage global state

### ISSUE THREAD

**Issue by algoflows** [leptos-rs/leptos#245]
Documentation improvement:

- How to manage local and global state, patterns and best practices with examples.

**Comment by jclmnop** [comment]
@gbj 

I'm already planning on doing a small CSR project to get more acquainted with the leptos framework before I use it for a much larger one; judging by the very rough plan in my head right now, it will probably have some sort of global state anyway. 

Quite busy at the moment so not sure when I'll actually get round to it, but if that happens to be before someone else has started working on this issue I'm happy to pick it up. 

Only extra bit of work I'd need to do (other than making sure it's extra readable of course) is the documentation, but I figure that will also be a good way to reinforce my own learning.

**Comment by omie-lol** [comment]
I recently went through the [book in the docs](https://github.com/leptos-rs/leptos/tree/main/docs/book/src/view) and ended up with this repo 

https://github.com/omie-lol/leptos-tutorial

My plan is to basically do what @jclmnop was going to do and create a sort of playground/storybook/doc site

I also have some corrections and suggestions to improvements for the book on a branch that I was collecting. (mostly spelling fixes, grammar, formatting etc.) 

So far loving Leptos...

**Comment by gbj** [comment]
> I also have some corrections and suggestions to improvements for the book on a branch that I was collecting. (mostly spelling fixes, grammar, formatting etc.)
Oh that's awesome, thank you so much! It's all been one-pass drafts so far, so I appreciate the proofreading. Although please let me know if any examples are broken, of course. I'll take a PR for docs fixes at any point.

**Comment by gbj** [comment]
See new docs chapter here https://github.com/leptos-rs/leptos/blob/main/docs/book/src/15_global_state.md
