### ISSUE TITLE
leptos 0.7 version of Callback

### ISSUE THREAD

**Issue by luoxiaozero** [leptos-rs/leptos#2459]
**Is your feature request related to a problem? Please describe.**

Warning and conversion problems.

Related issue: #2041 #2142

Related PR: #1921

**Describe the solution you'd like**

1. Remove it in leptos 0.7.
2. Rewrite. (Ensure consistency in stable and nightly.)

**Describe alternatives you've considered**

**Additional context**

**Comment by gbj** [comment]
Is there a reason you're opening a separate issue in addition to #2041 and #2142?

**Comment by luoxiaozero** [comment]
What I want more to know is how to solve Callback-related issues in leptos0.7. (perhaps it would be more appropriate to turn this into a discussion)

**Comment by gbj** [comment]
Okay. I'm going to add the 0.7 milestone to those other two issues, and close this one so that we can keep the conversation in one place.

Baptiste's comment [here](https://github.com/leptos-rs/leptos/issues/2142#issuecomment-1963838013) is the closest I've seen to a solution so far.
