### ISSUE TITLE
Fix and reenable cargo-semver-checks

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#2472]
Re-enable cargo-semver-checks and update nightly version, as per:
https://github.com/leptos-rs/leptos/pull/2471#issuecomment-2028279903

**Comment by benwis** [comment]
Making this issue for you @agilarity, is this something you can do?

**Comment by agilarity** [comment]
@gbj already updated nightly.

I will add a PR to re-enable the semver checks.
