### ISSUE TITLE
Unused stored children causes hydration error. (ssr)

### ISSUE THREAD

**Issue by zakstucke** [leptos-rs/leptos#2482]
**Describe the bug**
`store_value(children())` causes hydration error if unused in component.

**Leptos Dependencies**
Verified bug occurs in both `counter_isomorphic` & `errors_axum` leptos standard examples.

**To Reproduce**
Add `<Parent/>` to the app:
```rust
#[component]
pub fn Parent() -> impl IntoView {
    view! {
        <Child>
            <div>Foo</div>
        </Child>
    }
}

#[component]
pub fn Child(children: Children) -> impl IntoView {
    let _children = store_value(children());
    view! { <div>Bar</div> }
}
```

Will cause `element with id 0-4-0-4 not found, ignoring it for hydration` (with whatever key).
If you comment out the `let _children = store_value(children());` line, error will disappear.

**Expected behavior**
No hydration error, instead e.g. `element with id 0-4-0-4 not found, ignoring it for hydration`

**Additional context**
This took a while to work out, I've been building out my first big leptos project and would sometimes hit confusing hydration errors that didn't make sense. I worked out the fix would usually be to hide the buggy component when not needed it, instead of unmounting it (obviously this is undesirable though, as means uneeded hidden components are being mounted for no reason). 
This is the root cause!

**Comment by gbj** [comment]
Is it actually an error (something is broken) or just the warning about ignored elements?

This is somewhere between "working as designed" and a limitation of the current system. It doesn't have to do with StoredValue in particular; any time you construct, but do not use, an element, it will be impossible to hydrate it (because it doesn't appear in the HTML). However, if it's not used, it should not cause an actual issue, because it's not used.

The solution is to only call the `children` function when you are actually using the children.

>  Verified bug occurs in both `counter_isomorphic` & `errors_axum` leptos standard examples.

I don't understand — Could you expand on this?

**Comment by zakstucke** [comment]
I originally assumed it was a bug, but after reducing it down to this, it makes sense it could be just a limitation of the current error system. 

> The solution is to only call the children function when you are actually using the children

As far as I understand this doesn't work. The reason I mention `store_value(children())` here is that's the root usage that causes the issue. When the children are *sometimes* needed, sometimes not, in circumstances where the children get moved and the compiler requires `store_value` as recommened in that case.

Concrete example I hit: a managed `<Btn />` component that automatically shows a loading spinner instead of the children based on some state. It hits this error in the circumstance loading is the state on first client hydrate, the only solution I've found currently is to wrap the children in `display: none` when not needed to get around, but it's far from ideal. 

Another one with modals: I really want to only mount my modal when it's been opened, but hits this bug leading to over a 1000 of these warnings:
![image](https://github.com/leptos-rs/leptos/assets/44890343/bf6003e7-3a70-47aa-bdcc-a8da10514095)
The only solution I currently have is hiding the modal, but when modals are added to 100s of elements, you can imagine the unnecessary dom load!


I've hit this implementing modals, tooltips, btns etc + less generic components in the last couple of weeks, and each time was very confused what the cause was (working around it each time as above).

Does that make more sense? 

> Verified bug occurs in both counter_isomorphic & errors_axum leptos standard examples.

Sorry, I meant I locally ran both those examples, copied the code block above in and hit the error, I just wanted to test this was actually the bug, and not something else causing it in my own project.

**Comment by zakstucke** [comment]
@gbj after thinking about what you've said and I've said, I've come up with this to only call `children()` if needed but still make it `Fn()`:

```rust
pub fn store_children_lazy(children: Children) -> Box<dyn Fn() -> Fragment> {
    let children_getter = create_rw_signal(Some(children));
    let lazy_children = create_rw_signal(None);
    Box::new(move || {
        if let Some(children) = lazy_children.get_untracked() {
            children
        } else {
            let children = children_getter
                .try_update_untracked(|c| c.take().unwrap()())
                .unwrap();
            lazy_children.set_untracked(Some(children.clone()));
            children
        }
    })
}
```

And use in component as `let children = store_children_lazy(children)` where was `let children = store_value(children())` prior.

This seems to work and avoids the performance hit of my prior, would you say this is the best solution? Or is there an easy internaly fix that could make this unnecessary?

**Comment by gbj** [comment]
It seems to me that the easiest way to do it would be to use something like the `Lazy` cell from `once_cell`, which makes it pretty trivial:
```rust
#[component]
pub fn AddSomething(children: Children) -> impl IntoView {
    let children = store_value(once_cell::unsync::Lazy::new(|| children()));
    move || if some_condition {
      children.with_value(|value| (*value).clone()))
    } else {
      // etc.
    }
}
```

**Comment by zakstucke** [comment]
Thanks! It's amazing how flexible leptos signals can be; `once_cell::unsync::Lazy` definitely simplified my `StoredValueLazy` implementation:

```rust
/// Like [`leptos::store_value`], but will only call the getter if needed.
pub fn store_value_lazy<T>(value_getter: impl FnOnce() -> T + 'static) -> StoredValueLazy<T> {
    StoredValueLazy::new(Box::new(value_getter))
}

#[derive(Debug)]
pub struct StoredValueLazy<T: 'static> {
    value: StoredValue<once_cell::unsync::Lazy<T, Box<dyn FnOnce() -> T>>>,
}

impl<T> Clone for StoredValueLazy<T> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<T> Copy for StoredValueLazy<T> {}

impl<T> StoredValueLazy<T> {
    pub fn new(value_getter: Box<dyn FnOnce() -> T>) -> Self {
        Self {
            value: store_value(once_cell::unsync::Lazy::<T, _>::new(value_getter)),
        }
    }

    pub fn with_value<R>(&self, cb: impl FnOnce(&T) -> R) -> R {
        self.value.with_value(|value| cb(value))
    }
}

impl<T: Clone> StoredValueLazy<T> {
    pub fn get_value(&self) -> T {
        self.with_value(|v| v.clone())
    }
}
```

So I'm happy with this lazy children approach as the solution if that's the way you want to support it right now. Feel free to close if you want to leave it there :)

**Comment by gbj** [comment]
Great! It's not just that the lazy solution is the way I want to support it right now — it is that it is the only solution that can work in any of the versions of the framework from 0.1 to 0.6.x, and fixing it more completely requires rewriting the whole framework... which is exactly what I'm already doing for 0.7! :smile:
