### ISSUE TITLE
DX regression in view macro for rust-analyzer 2024-03-18 (v0.3.1885) and newer

### ISSUE THREAD

**Issue by Ar4ys** [leptos-rs/leptos#2527]
- **Affected Leptos version:** [v0.6.11](https://github.com/leptos-rs/leptos/releases/tag/v0.6.11)
- **Affected Rust Analyzer version:** [2024-03-18 (v0.3.1885)](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-03-18) and newer
- **Related PR:** #2289 

In rust-analyzer [2024-03-18 (v0.3.1885)](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-03-18) they updated how they handle overlapping spans, which resulted in a degraded DX of #2289 (worse syntax highlighting, hover tooltips, go to definition etc.).

<details>
<summary><h3>Examples</h3></summary>

**Note:** This is not a full list of regressions

### Hover over items used inside `view!` macro
Working (rust-analyzer [2024-03-11 (v0.3.1877)](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-03-11)) | ![Screenshot of working tooltip](https://github.com/leptos-rs/leptos/assets/37052349/fc0979e0-f196-4564-8239-4f6db8a15091)
:---:|---
**Broken (rust-analyzer [2024-03-18 (v0.3.1885)](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-03-18))** | ![Screenshot of broken tooltip](https://github.com/leptos-rs/leptos/assets/37052349/fdb49fea-0005-4ddd-aacf-403628ae1dde)

### Component's syntax highlighting
Working (rust-analyzer [2024-03-11 (v0.3.1877)](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-03-11)) | ![Screenshot of working syntax highlighting](https://github.com/leptos-rs/leptos/assets/37052349/de173b53-e012-4dae-9b85-a3bad4e5fc46)
:---:|---
**Broken (rust-analyzer [2024-03-18 (v0.3.1885)](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-03-18))** | ![Screenshot of broken syntax highlighting](https://github.com/leptos-rs/leptos/assets/37052349/ca2ddb5d-0770-4b8d-9e9f-66163b9d7f70)

### Go to definition
Working (rust-analyzer [2024-03-11 (v0.3.1877)](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-03-11)) | ![Screenshot of good "go to definition"](https://github.com/leptos-rs/leptos/assets/37052349/5ccfd58e-9c51-4196-b56a-fbc96bb7ee4d)
:---:|---
**Broken (rust-analyzer [2024-03-18 (v0.3.1885)](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-03-18))** | ![Screenshot of bad "go to definition"](https://github.com/leptos-rs/leptos/assets/37052349/9df091c6-f6cd-4315-87c3-f2ab40e6e69c)

</details>

### Temporary workarounds

Until the issue is resolved, users can:
1. Downgrade to rust-analyzer [2024-03-11 (v0.3.1877)](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-03-11)
    - by following official installation guide [here](https://github.com/rust-lang/rust-analyzer/blob/master/docs/user/manual.adoc#rust-analyzer-language-server-binary) and using downloaded rust-analyzer binary in your IDE instead of a bundled one
    - in VSCode users can select "install another version" from the rust-analyzer context menu (thanks @zenlex for [suggestion](https://github.com/leptos-rs/leptos/issues/2527#issuecomment-2084303419))
2. Or use latest stable rustc version (`rustc 1.78.0 (9b00956e5 2024-04-29)` at the time of writing), instead on nightly

### Proposed solutions

I see two possible solutions to this issue:

1. Remove overlapping spans introduced in #2289. While this will fix the problem, it will also worsen error reporting in `view!` macro.
2. File an issue against rust-analyzer and try to fix the problem upstream.

**Comment by SeraphyBR** [comment]
I also had the same problem.. I tried some ways to ignore clippy (because when it hovers that's what appears), but I couldn't.

**Comment by zenlex** [comment]
same, didn't have much luck with any allow or config options and it also seemed to bork the syntax highlighting in vscode a tad too - primarily that the Component name lost it's coloration after rust-analyzer finished indexing leptos.

**Comment by gbj** [comment]
I don't know the first thing about how rust-analyzer works. Is there a reason to think this was an intentional decision by rust-analyzer, not a bug/regression? If it was an intentional decision to no longer support overlapping spans in this way, then I guess we should revert the changes made in #2289. If not, opening an issue there makes sense and @Ar4ys I'd appreciate it if you could do that, as you know what you're talking about more than I do!

**Comment by Ar4ys** [comment]
While trying to make a reproduction repository for my issue against rust-analyzer, I found out that DX regressions are not present when using latest stable rustc (`rustc 1.78.0 (9b00956e5 2024-04-29)` at the time of writing) instead of nightly. I added this as a possible workaround to the current issue. 

Still investigating why nightly breaks....

**Comment by chrisp60** [comment]
confirming downgrading rust-analyzer to `2024-03-11` is a valid workaround for Neovim `rustc 1.80.0-nightly (d84b90375 2024-05-19)`.

Regression present on `rust-analyzer@2024-05-20` `rustc 1.80.0-nightly (d84b90375 2024-05-19)`

Span shows on LSP hover:
```
unused_braces
___

unnecessary braces around an expression
```

Appreciate the workaround and notes on this
