### ISSUE TITLE
Allow custom derive for server_fns with custom encoding

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#2544]
**Is your feature request related to a problem? Please describe.**
I want to have my server functions use [bitcode](https://github.com/SoftbearStudios/bitcode/) encoding. For this I can implement IntoReq, FromReq, etc, but I noticed that the ServerFnInputType will always be `#[derive(Clone, serde::Serialize, serde::Deserialize)]` whereas I don't have a use for serde in this case and I actually want `#[derive(Clone, bitcode::Encode, bitcode::Decode)]` instead.

**Describe the solution you'd like**
have the `server` macro support parameters `input_derive` and `output_derive`

**Comment by gbj** [comment]
Seems reasonable. Any interest in making a PR?

These parameters would just feed into the logic here 

https://github.com/leptos-rs/leptos/blob/9353316947a6350b9fc54885e6681b8df4b0a616/server_fn_macro/src/lib.rs#L389-L411

**Comment by luxalpa** [comment]
Yes, I will make one. Just need to figure out why the scenario differs so much for the output type.

**Comment by luxalpa** [comment]
PR: https://github.com/leptos-rs/leptos/pull/2545
