### ISSUE TITLE
Add Trigger::dispose

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/leptos#2548]
**Is your feature request related to a problem? Please describe.**
I currently use RwSignal<()> as a trigger because it allows me to dispose it manually. I don't see a reason why we wouldn't want to have that same functionality on Triggers.

**Describe the solution you'd like**

```rs
impl<T> SignalDispose for Trigger {
    fn dispose(self) {
        _ = with_runtime(|runtime| runtime.dispose_node(self.id));
    }
}
```

**Describe alternatives you've considered**
Currently I'm using `RwSignal<()>`. To be fair I am not sure if there's any actual advantages of using Trigger over RwSignal<()>

**Additional context**
I'm using this to implement my global state in some kind of subscriber-system where signals are being created ad-hoc only for the elements that are visible on the page instead of for the entirety of the global state (which can have a large number of objects).

**Comment by stefnotch** [comment]
This will apparently be fixed in the next version of Leptos https://docs.rs/reactive_graph/0.1.0-gamma/reactive_graph/signal/struct.Trigger.html

**Comment by gbj** [comment]
Thanks for pointing this out. I've been keeping the issue tracker relative to the main branch, so I will close this as completed.
