### ISSUE TITLE
Notify crate (lib) not compiling when installing cargo-leptos

### ISSUE THREAD

**Issue by lzned** [leptos-rs/leptos#2596]
**Describe the bug**
An error that occurs when trying to install cargo-leptos.
When notify v4.0.17 is trying to compile, several errors occur:
e.g. unresolved imports, mismatched types, etc.

**Leptos Dependencies**
N/A

**To Reproduce**
1. Go to your console/terminal
2. Type 'cargo install cargo-leptos'
3. Wait
4. Eventually, a compilation error will occur.

**Expected behavior**
For cargo-leptos to be promptly installed.

**Additional context**

Operating System: Windows 11
IDE/Text Editor: Visual Studio Code.

**Comment by gbj** [comment]
See https://github.com/leptos-rs/cargo-leptos/issues/280 and https://github.com/leptos-rs/cargo-leptos/pull/274. For further `cargo-leptos` issue, you can use that repo rather than this one.
