### ISSUE TITLE
Boolean aria attribute values are not handled correctly

### ISSUE THREAD

**Issue by SleeplessOne1917** [leptos-rs/leptos#2605]
## Describe the bug
Currently, all true boolean attribute values are set to the name of the attribute when true. E.g., a disabled button ends up having the following HTML rendered:
```html
<button disabled="disabled" >
    Do Something
</button>
```
This behavior [comports with the HTML standard](https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML) for most attributes. However, ARIA attributes with boolean values are special snowflakes in this regard.

Here is a sampling of ARIA attributes that have boolean values:
- [`aria-busy`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-busy)
- [`aria-disabled`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled)
- [`aria-hidden`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden)
- [`aria-selected`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected)
- [`aria-required`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-required)

Notice that the valid value for true is `"true"` and not the attribute name. There are more, but I think I've made my point. I've already encountered a situation where this causes issues: [using ARIA with TailwindCSS](https://tailwindcss.com/docs/hover-focus-and-other-states#aria-states).     

## Leptos Dependencies

```toml
leptos = { version = "0.6" }
leptos_meta = { version = "0.6" }
leptos_router = { version = "0.6" }
leptos_actix = { version = "0.6", optional = true }
```

## To Reproduce
1. Create a simple Leptos UI (perhaps using one of the starter templates)
2. Put a boolean ARIA attribute, e.g. `aria-pressed`, on one of the elements and assign it `true`
3. Run `cargo leptos serve`
4. Open the served page
5. Open your browser's dev tools
6. Inspect the element you added the boolean ARIA attribute to

### Expected behavior
The attribute has the value `"true"`.

### Actual Behavior
The attribute has its own name as a value if true, e.g.
```html
<div aria-hidden="aria-hidden"/>
```

## Nice to have
While not causing any problems, it would be nice if non-ARIA boolean attributes only have the attribute present with no value when true, e.g.
```
<button disabled>
    Do Something
</button>
```

The amount of generated HTML would be marginally reduced this way, although I doubt it would be enough to make a difference in the vast majority of cases.

**Comment by gbj** [comment]
I think there's a confusion in terms here. `aria-busy="true"` is not a boolean attribute; it has a string value, which can either be `"true"` (the string, not the boolean) or `"false"` (the string, not the boolean)

HTML containing `aria-` attributes as boolean attributes is *not* parsed to these values:
```js
let x = document.createElement("div");
x.innerHTML = "<span aria-hidden>foo</span>";
console.log(x.firstElementChild.ariaHidden);
// logs '', not 'true'
```

Boolean values on attributes in Leptos mean "include this boolean attribute." From my perspective, the correct behavior here is to pass a string (`"true"` or `"false"`) or use `.to_string()` to convert a boolean to a `String`.

**Comment by gbj** [comment]
Just an added piece of context — I was double-checking myself on boolean attributes here and in fact the ARIA-style `="false"` is specifically *invalid* for actual boolean attributes. Per MDN on [Boolean attributes](https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML):
> If the attribute is present, it can have one of the following values:
> - no value at all, e.g. `attribute`
> - the empty string, e.g. `attribute=""`
> - attribute's name itself, with no leading or trailing whitespace, e.g. `attribute="attribute"`
> 
> Note: The strings `"true"` and `"false"` are invalid values. To set the attribute to `false,` the attribute should not be present in the element tag. Though modern browsers treat any string value as `true`, you should not rely on that behavior.

So for true boolean attributes, like `checked`, `checked="false"` is actually `true`, although not technically spec compliant. (It certainly isn't `false`.)

Gotta love the weirdness of the web.

**Comment by SleeplessOne1917** [comment]
> Just an added piece of context — I was double-checking myself on boolean attributes here and in fact the ARIA-style ="false" is specifically invalid for actual boolean attributes. Per MDN on Boolean attributes:

Funnily enough, I linked that same page in my original post.
