### ISSUE TITLE
add file upload

### ISSUE THREAD

**Issue by Polygons1** [leptos-rs/leptos#2616]
**Is your feature request related to a problem? Please describe.**
I am trying to build an app that requires file upload but there is not a method to get the files from an Input element

**Describe the solution you'd like**
add some sort of method to get the files from an input element

**Describe alternatives you've considered**
can't find any

**Additional context**

**Comment by gbj** [comment]
There's a [complete file uploading example](https://github.com/leptos-rs/leptos/blob/00a42daa63a696c98aeb45817c37c311f884184b/examples/server_fns_axum/src/app.rs#L397-L558) in the repo. If you want to do it without server functions, there's nothing the framework provides to help you but you can use all the normal Web APIs for file uploads through `web-sys`.

The [`files` method on `HtmlInputElement` in `web-sys`](https://docs.rs/web-sys/latest/web_sys/struct.HtmlInputElement.html#method.files) is the method to get files from an input element.
