### ISSUE TITLE
looks like "class" not work for 0.7 

### ISSUE THREAD

**Issue by PvlD** [leptos-rs/leptos#2636]
![image](https://github.com/leptos-rs/leptos/assets/10778065/c41825f7-e35e-4eed-8343-1d01de7e3e2f)

project from : https://github.com/leptos-rs/preview/

with 0.6 it is OK.

**Comment by gbj** [comment]
This is listed in [the PR](https://github.com/leptos-rs/leptos/pull/2607) in the list of not-yet implemented APIs as "global class support."
