### ISSUE TITLE
Resources with concrete default/fallback values

### ISSUE THREAD

**Issue by bugeats** [leptos-rs/leptos#2642]
When I reach for `create_resource_with_initial_value` it's because I have a local fallback value available that I can use while waiting for updates. However the getter for a resource is always `Option<T>`. This forces me to **always handle unwrapping** the maybe value wherever I use this resource. I makes more sense to me that such a resource is always able to provide a concrete value instead.

Of course, I can just derive a signal that falls back to a default, but then I lose all the utility of the Resource object.

The whole concept of an "initial value" maps cleanly onto the existing Rust convention of using the `Default` trait, and so feels like a redundant abstraction.

I propose a variation of Resource for types that impl Default. It always returns a concrete value. The "loading" state is orthogonal to the actual value on hand, and when loading completes the concrete value is updated. Perhaps the fetcher can avoid clobbering the value by intercepting a `Result<T>`.

**Comment by gbj** [comment]
Clarifying question: Are you intending this for use with server-side rendering, or with client-side rendering?

If you mean it for use with client-side rendering, then it's not clear to me how this would be different from an extension trait that just adds a method to do `.get().unwrap_or_default()`. 

If you mean it for use with server-side rendering, then it's not clear to me whether the server is supposed to return HTML with the default value for a resource, and then later fill it in on the client, or whether it's supposed to wait for it actually to load (as it currently does).

If you have reasonable default values then can I ask why you're using Resources/Suspense, in particular? Is it the shared fallbacks, access to a signal for loading state, server side rendering, or something else?
