### ISSUE TITLE
Add "scroll" prop to <A>

### ISSUE THREAD

**Issue by paul-hansen** [leptos-rs/leptos#2666]
**Is your feature request related to a problem? Please describe.**
I would like to have a table that has pagination buttons that are proper links and set the `?page=X` query parameter. Unfortunately this causes it to scroll to the top of the page when clicked. Because the table isn't at the top of the page, it's jarring and annoying to have to scroll down to the table again every time.

**Describe the solution you'd like**
I'd like to be able to pass `scroll=false` to Leptos' `<A>` component to tell it not to scroll to the top of the page when navigating. 

**Describe alternatives you've considered**
I've considered just using on:click and use_navigate but that's discouraged because it isn't as accessible according to the [Leptos book](https://book.leptos.dev/router/19_a.html?highlight=scroll#navigating-programmatically):

> You should almost never do something like `<button on:click=move |_| navigate(/* ... */)>`. Any `on:click` that navigates should be an `<a>`, for reasons of accessibility.

**Additional context**
I looked up how this was done in the React world for inspiration and here they have a `scroll` property on their `<link>` component: https://nextjs.org/docs/pages/api-reference/components/link#scroll

**Comment by paul-hansen** [comment]
I was looking into implementing this and it looks it does detect a `noscroll` attribute already. 
https://github.com/leptos-rs/leptos/blob/b3db094618eb8fbb9c1ffd34ee440f6616cf9cad/router/src/components/router.rs#L474

We probably should either document this somewhere or make a prop on `<A>` that sets it for us for more visibility. Happy to help with this.

**Comment by paul-hansen** [comment]
Looks like the noscroll attribute is missing in 0.7
![image](https://github.com/user-attachments/assets/c0d1a7f5-81b2-4778-8bab-533f427ca5da)

**Comment by gbj** [comment]
Ah. Probably because it's not an actual HTML attribute, and we do check those now.

I'm open to ideas. One easy one would be to support `data-noscroll` as an additional possibility, which you definitely *can* add.

**Comment by paul-hansen** [comment]
Yeah that makes sense, either that or take a component prop. Component prop would be more self documenting, but probably not worth much extra effort if a data attr is easier.

For my project I think I need to hold off on upgrading for a bit, so no rush from me. I've got some custom components I need to rework which will make upgrading easier in the future. I can work on a PR for this eventually if no one beats me to it.

**Comment by gbj** [comment]
I think I added a `scroll` prop straightforwardly enough in https://github.com/leptos-rs/leptos/pull/3333 but I'll admit I didn't really test it — want to try it out to see if it's suitable?

**Comment by paul-hansen** [comment]
Awesome! Busy today, not looking like I'll get a chance, but will give it a try tomorrow for sure!
