### ISSUE TITLE
server_fn depedency on gloo_net 0.5 causing duplicate inclusion of http library with different versions.

### ISSUE THREAD

**Issue by DylanRJohnston** [leptos-rs/leptos#2688]
Hey all, this isn't exactly a bug, but I was trying to reduce the number of duplicate packages in my project with different versions in an attempt to cut down on build times and binary sizes. I've noticed that `server_fns` depends on `gloo_net` v0.5, which in turn depends on http v0.2 when the rest of the ecosystem has moved onto http v1. We should bump gloo_net to a more recent version eg. 0.9 to help reduce the inclusion of http v0.2.

**Comment by paul-hansen** [comment]
The most recent version of gloo-net is 0.5.0 https://crates.io/crates/gloo-net/versions And it depends on http 1.0.
I think you are confusing the parent gloo (not gloo-net) crate version: https://crates.io/crates/gloo/versions

I also want to reduce the duplicated dependencies though.

**Comment by DylanRJohnston** [comment]
Ah apologies you are correct. It's still causing the inclusion of both http v0.2 and http v1.0 though right?

**Comment by DylanRJohnston** [comment]
According to crates.io gloo-net v0.5 depends on http v0.2.9 https://crates.io/crates/gloo-net/0.5.0/dependencies, but according to github it depends on http v1.0. It looks like they didn't bump the minor version or republish it after the change https://github.com/rustwasm/gloo/pull/407/files

**Comment by DylanRJohnston** [comment]
I open an issue on the upstream about it. https://github.com/rustwasm/gloo/issues/483

**Comment by paul-hansen** [comment]
Ah you're right 👍
