### ISSUE TITLE
Add a "create_server_resource" wrapper for server function

### ISSUE THREAD

**Issue by qchenqchen** [leptos-rs/leptos#2706]
**Is your feature request related to a problem? Please describe.**
It is rather strange why there is a wrapper for `create_action` but not `create_resource` for server functions.

**Describe the solution you'd like**
Adding a `create_server_resource` for server functions, and probably even things like `create_server_resource_with_initial_value` to the current API.

**Describe alternatives you've considered**
Probably just stay writing the boilerplate codes??

**Additional context**

**Comment by gbj** [comment]
The reason this does not currently exist is that resources take a source signal. If you only want to load the resource once, then as far as I can tell the proposed `create_server_resource` would be identical to `Resource::once(my_server_fn)`, so I don't think this requires a separate helper.
