### ISSUE TITLE
True async - Fix or Educate

### ISSUE THREAD

**Issue by VVishion** [leptos-rs/leptos#2722]
**Describe the bug**
If a function is not truly async we can hit bugs in the library. This can be fixed either for every impl which handles futures. In the executor of futures. Or left up to the caller (think of timeouts or something like [setImmediate()](https://nodejs.org/en/learn/asynchronous-work/understanding-setimmediate)). In the latter education is necessary.

**Comment by gbj** [comment]
This issue is too general to be acted on. If there are specific instances in which this is the case, please create issues with reproducible examples, following the issue template, or edit this issue to include an example.

**Comment by rakshith-ravi** [comment]
Just want to add - there's a `spawn_local` function available as well. Does this work for your use-case?

https://docs.rs/leptos/latest/leptos/fn.spawn_local.html
