### ISSUE TITLE
Bump MSRV to 1.8, so we can drop lazy_static

### ISSUE THREAD

**Issue by martinfrances107** [leptos-rs/leptos#2726]
To me this  is minor housekeeping, but I wanted to generate an issue, so this may  inform those  who are not focused on the detailed flow of PR's. But  want changes to Architecture (  or the to tool/infrastructure ).

I want to reduce the attack surface by droping the crate "lazy_static" as the functionality has now been stabilized in std  ( as of last weeks release of rust 1.8) 

**This issue has the awkward aspect that we must bump the MSRV to rust 1.8.** 

I plan to generate two PR for this isuse.. one for changes to the library only and one for changes to the examples.

For reference  see the  "Stabilized API" section of the release notes here 
[ release notes](https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-180-2016-04-14)

**Comment by rakshith-ravi** [comment]
Thanks for the PR @martinfrances107! If I may add my two cents here - Would it make sense to add this for 0.8? Might give people some time to upgrade

**Comment by rakshith-ravi** [comment]
Closing this since #2767 is merged. Feel free to reopen it in case I'm missing something
