### ISSUE TITLE
.leptos_routes() server fn routing should respect excluded routes

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#2735]
Right now it's impossible to manually implement a server fn route with leptos_routes() because it does not consider excluded routes, there should be a mechanism to do that, either through`generate_route_list_with_exclusions` or some other arg

**Comment by gbj** [comment]
Totally reasonable. I wonder whether this would just consist of adding a `leptos_routes_with_exclusions`? You start getting into combinatoric explosion (`leptos_routes`, `leptos_routes_with_context`, `leptos_routes_with_exclusions`, `leptos_routes_with_context_and_exclusions`) probably a better options is to switch the `LeptosRoutes` traits to have two methods:
1. `.leptos_routes`: calls `.leptos_routes_with_options` with default `LeptosRoutesOptions`
2. `.leptos_routes_with_options`: takes a `LeptosRoutesOptions`

If `LeptosRoutesOptions` has no `pub` fields but uses a builder, we can even add additional options without breaking changes in the future.

Thoughts?

**Comment by benwis** [comment]
We could do that, or we could make the server function registration consider the excluded routes passed to generate_route_list_with_exclusions. I’m not sure which is better to be honest
