### ISSUE TITLE
Never resolve Futures synchronously to prevent class of errors

### ISSUE THREAD

**Issue by VVishion** [leptos-rs/leptos#2736]
**Describe the bug**
```rust
async fn create_list(i: usize) -> Vec<String> {
    if i % 2 == 0 {
        log!("create even list");
        vec![
            String::from("Hello,"),
            String::from("Dave"),
            String::from("and"),
            String::from("the"),
            String::from("green"),
            String::from("World"),
        ]
    } else {
        log!("create uneven list");
        vec![String::from("Ehm")]
    }
}

#[server]
pub async fn create_server_list(i: usize) -> Result<Vec<String>, ServerFnError> {
    if i % 2 == 0 {
        log!("create even list");
        Ok(vec![
            String::from("Hello,"),
            String::from("Dave"),
            String::from("and"),
            String::from("the"),
            String::from("green"),
            String::from("World"),
        ])
    } else {
        log!("create uneven list");
        Ok(vec![String::from("Ehm")])
    }
}

#[component]
pub fn App() -> impl IntoView {
    let (counter, mut_counter) = signal(0);

    let list = LocalResource::new(move || async move { create_list(counter.get()).await });
    // let list = LocalResource::new(move || async move { create_server_list(counter.get()).await });

    view! {
        <div id="app">
            {move || counter.get()}
            <button on:click=move |_| {
                log!("click");
                mut_counter.update(|counter| {
                    *counter += 1;
                });
            }>"Click here!"</button>

            <Suspense>
                {move || list.get()}
            </Suspense>
        </div>
    }
}
```

<details><summary>panics with</summary><code>panicked at /home/emil/.cargo/git/checkouts/leptos-2c8932a5258b3db6/71c4437/tachys/src/renderer/mod.rs:85:38:
could not find parent element

Stack:

__wbg_get_imports/imports.wbg.__wbg_new_abda76e883ba8a5f@http://127.0.0.1:3000/pkg/leptos-test.js:445:13
console_error_panic_hook::Error::new::hd068f7ac0f16603f@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3829]:0x116d91
console_error_panic_hook::hook_impl::hfbec190b4fdeedc3@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[737]:0x8e69f
console_error_panic_hook::hook::h72aa3575a9db29c7@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4686]:0x123f71
core::ops::function::Fn::call::hc3b1d1d6db7fec49@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4125]:0x11becd
std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1700]:0xd3037
std::panicking::begin_panic_handler::{{closure}}::h24b0f4622f2766a5@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2262]:0xed844
std::sys_common::backtrace::__rust_end_short_backtrace::h19f35d272c126e7c@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[5633]:0x12d552
rust_begin_unwind@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4211]:0x11d4b6
core::panicking::panic_fmt::h87755523850ece9e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4603]:0x122e8c
core::option::expect_failed::h65a8ce8e046de7db@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3417]:0x10ebdc
core::option::Option<T>::expect::h63b3f4449aad64bf@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2978]:0x10444a
tachys::renderer::Renderer::mount_before::h1990bfbfdc40f62b@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1601]:0xcd8d5
tachys::view::iterators::<impl tachys::view::Render<R> for alloc::vec::Vec<T>>::rebuild::h6e94751ed2cfc1ba@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[90]:0xe5f2
tachys::view::either::<impl tachys::view::Render<Rndr> for either_of::Either<A,B>>::rebuild::hb53593cd2fecfc96@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[249]:0x46379
tachys::view::iterators::<impl tachys::view::Render<R> for core::option::Option<T>>::rebuild::h33bfa15d6782ee0e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1322]:0xbc9d1
tachys::reactive_graph::<impl tachys::view::Render<R> for F>::build::{{closure}}::h0fb8d0de11a3e369@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[557]:0x7a904
<alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h0f5e22053ddd468b@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2308]:0xef623
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::{{closure}}::{{closure}}::h5bfe6f0e2ec5b024@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2057]:0xe4a75
<reactive_graph::graph::subscriber::AnySubscriber as reactive_graph::graph::subscriber::WithObserver>::with_observer::h78a6a7fd8126ff70@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1755]:0xd5fa1
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::{{closure}}::h5ea7878e4a031555@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2373]:0xf1daf
reactive_graph::owner::Owner::with::hca34f6698718cab2@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2155]:0xe8fbe
reactive_graph::owner::Owner::with_cleanup::h2b87494958ed5b60@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4284]:0x11e6ad
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::h3c338f706a27a241@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[147]:0x27677
<core::pin::Pin<P> as core::future::future::Future>::poll::h8c643bafa4983baf@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2213]:0xeb7e8
wasm_bindgen_futures::task::singlethread::Task::run::h3014f4952bfdf91a@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[551]:0x79cbc
wasm_bindgen_futures::queue::QueueState::run_all::h3799444162cd0c81@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[350]:0x5b8bc
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hd7fdd2c2e2c4d1d0@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2600]:0xf9770
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h39db12a11a7ff3b3@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1772]:0xd6dea
__wbg_adapter_31@http://127.0.0.1:3000/pkg/leptos-test.js:228:6
real@http://127.0.0.1:3000/pkg/leptos-test.js:209:32
VoidFunction*__wbg_get_imports/imports.wbg.__wbg_queueMicrotask_481971b0d87f3dd4@http://127.0.0.1:3000/pkg/leptos-test.js:657:15
wasm_bindgen_futures::queue::queueMicrotask::h93fb41f41a731419@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3693]:0x1144e9
wasm_bindgen_futures::queue::Queue::schedule_task::hbe9a36afa581de9e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[742]:0x8ef96
wasm_bindgen_futures::queue::Queue::push_task::he405df74da83d7a5@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4313]:0x11edb2
wasm_bindgen_futures::task::singlethread::Task::force_wake::{{closure}}::h04b054958354cc60@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4312]:0x11ed75
std::thread::local::LocalKey<T>::try_with::h0d45dbbd6a418f1e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[817]:0x95e50
std::thread::local::LocalKey<T>::with::h6155969b056eea5e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2093]:0xe6450
wasm_bindgen_futures::task::singlethread::Task::force_wake::h2e731662d9e5e489@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3909]:0x1184a6
wasm_bindgen_futures::task::singlethread::Task::wake::h02a9a5f1428d5a2c@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1677]:0xd1c40
wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::h924b40ef1ab392f7@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4208]:0x11d3d8
core::task::wake::Waker::wake::ha288f43c02407a62@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3288]:0x10be16
futures_core::task::__internal::atomic_waker::AtomicWaker::wake::h1ce2a52b7c3dd60d@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[946]:0xa0fe0
reactive_graph::channel::Sender::notify::h34142444ca9b1195@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2686]:0xfc101
reactive_graph::effect::inner::<impl reactive_graph::graph::node::ReactiveNode for std::sync::rwlock::RwLock<reactive_graph::effect::inner::EffectInner>>::mark_dirty::hd0e4bf6a04a9e33e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1794]:0xd801a
<reactive_graph::graph::subscriber::AnySubscriber as reactive_graph::graph::node::ReactiveNode>::mark_dirty::h143bc2babc43c903@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[661]:0x86c37
reactive_graph::computed::async_derived::arc_async_derived::ArcAsyncDerived<T>::new_unsync_with_initial::{{closure}}::h065e7debee453384@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[81]:0x56c9
<core::pin::Pin<P> as core::future::future::Future>::poll::h8c643bafa4983baf@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2213]:0xeb7e8
wasm_bindgen_futures::task::singlethread::Task::run::h3014f4952bfdf91a@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[551]:0x79cbc
wasm_bindgen_futures::queue::QueueState::run_all::h3799444162cd0c81@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[350]:0x5b8bc
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hd7fdd2c2e2c4d1d0@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2600]:0xf9770
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h39db12a11a7ff3b3@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1772]:0xd6dea
__wbg_adapter_31@http://127.0.0.1:3000/pkg/leptos-test.js:228:6
real@http://127.0.0.1:3000/pkg/leptos-test.js:209:32
VoidFunction*__wbg_get_imports/imports.wbg.__wbg_queueMicrotask_481971b0d87f3dd4@http://127.0.0.1:3000/pkg/leptos-test.js:657:15
wasm_bindgen_futures::queue::queueMicrotask::h93fb41f41a731419@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3693]:0x1144e9
wasm_bindgen_futures::queue::Queue::schedule_task::hbe9a36afa581de9e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[742]:0x8ef96
wasm_bindgen_futures::queue::Queue::push_task::he405df74da83d7a5@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4313]:0x11edb2
wasm_bindgen_futures::task::singlethread::Task::force_wake::{{closure}}::h04b054958354cc60@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4312]:0x11ed75
std::thread::local::LocalKey<T>::try_with::h0d45dbbd6a418f1e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[817]:0x95e50
std::thread::local::LocalKey<T>::with::h6155969b056eea5e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2093]:0xe6450
wasm_bindgen_futures::task::singlethread::Task::force_wake::h2e731662d9e5e489@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3909]:0x1184a6
wasm_bindgen_futures::task::singlethread::Task::wake::h02a9a5f1428d5a2c@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1677]:0xd1c40
wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::h924b40ef1ab392f7@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4208]:0x11d3d8
core::task::wake::Waker::wake::ha288f43c02407a62@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3288]:0x10be16
futures_core::task::__internal::atomic_waker::AtomicWaker::wake::h1ce2a52b7c3dd60d@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[946]:0xa0fe0
reactive_graph::channel::Sender::notify::h34142444ca9b1195@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2686]:0xfc101
reactive_graph::computed::async_derived::inner::<impl reactive_graph::graph::node::ReactiveNode for std::sync::rwlock::RwLock<reactive_graph::computed::async_derived::inner::ArcAsyncDerivedInner>>::mark_dirty::h59648a0f4ced00cf@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1793]:0xd7f4f
<reactive_graph::graph::subscriber::AnySubscriber as reactive_graph::graph::node::ReactiveNode>::mark_dirty::h143bc2babc43c903@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[661]:0x86c37
reactive_graph::signal::subscriber_traits::<impl reactive_graph::graph::node::ReactiveNode for std::sync::rwlock::RwLock<reactive_graph::graph::sets::SubscriberSet>>::mark_subscribers_check::h5bc2882ff2820454@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[567]:0x7be7e
reactive_graph::signal::subscriber_traits::<impl reactive_graph::graph::node::ReactiveNode for std::sync::rwlock::RwLock<reactive_graph::graph::sets::SubscriberSet>>::mark_dirty::h279cdb78b52df686@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4958]:0x1276d0
<reactive_graph::signal::arc_write::ArcWriteSignal<T> as reactive_graph::traits::Trigger>::trigger::h3739fa1ac0029f7d@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3866]:0x117859
<reactive_graph::signal::write::WriteSignal<T,S> as reactive_graph::traits::Trigger>::trigger::h8e9f4619ce95f791@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[659]:0x86906
<reactive_graph::signal::guards::WriteGuard<S,T> as core::ops::drop::Drop>::drop::hfe85a490443a1b22@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1832]:0xd9f76
core::ptr::drop_in_place<reactive_graph::signal::guards::WriteGuard<reactive_graph::signal::write::WriteSignal<usize>,guardian::ArcRwLockWriteGuardian<usize>>>::h3ea03da33952f2bc@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3925]:0x118910
core::mem::drop::h602fcc592644106e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[5619]:0x12d4d2
<T as reactive_graph::traits::Update>::try_maybe_update::h3ae8ec99cc631e92@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[266]:0x4a7d7
reactive_graph::traits::Update::try_update::he6f4e84ba903ba52@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3869]:0x11791c
reactive_graph::traits::Update::update::ha1b1bfa97fa14380@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4396]:0x1200b8
app::__App::{{closure}}::hdab2e215a0f692a8@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1539]:0xc9fa7
<F as tachys::html::event::EventCallback<E>>::invoke::h6183fdfcb1ef8b12@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3828]:0x116d66
tachys::html::event::On<E,F,R>::attach::{{closure}}::hd181d0a83938ce01@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3180]:0x10959d
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h39db12a11a7ff3b3@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1772]:0xd6dea
__wbg_adapter_31@http://127.0.0.1:3000/pkg/leptos-test.js:228:6</code></details>

Does not panic when server fn is used (commented line)

**Leptos Dependencies**

```toml
leptos = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
leptos_axum = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
```
commit 71c4437

**To Reproduce**
Does not render the list, initially.
Click the button to panic.

**Expected behavior**
Render the list. Alternating list on button click.

**Additional context**
This is an arbitrary example for a class of errors where async function resolve synchronously.

If we take a look at the js async primitive, then it always resolves after synchronous code, which eliminates this class of errors.
```js
new Promise((r) => { console.log("execute promise"); r(); }).then(() => console.log("resolving promise"));
console.log("synchronous"); 
```

Im therefore arguing we should do the same if it is a possibility to modify the future executor in a way to prevent this class of errors.

**Comment by gbj** [comment]
>  This is an arbitrary example for a class of errors where async function resolve synchronously.

Just to be specific: As I understand it, this should *only* be a problem when you are using a `LocalResource` that resolves immediately, in `Suspense`: Because the `Suspense` sees that it is already ready, it thinks that it will have been server rendered, but of course this is not the case for `LocalResource`. 

Correct me if this happens in other cases.

> Im therefore arguing we should do the same if it is a possibility to modify the future executor in a way to prevent this class of errors.

It's possible to do this in `LocalResource` itself, and not modify the executor or other code, which is good.

*****

In general this is an anti-pattern — Having async code that resolves synchronously, such as the example above, is strictly worse than just doing this synchronously. However this is a reasonable edge case for things like conditionals, where branch A is synchronous and branch B actually does async, i.e., things that *sometimes* but not always are resolved immediately.

For the actual example this should just not be async, but I understand that it's just an example for the sake of the issue!

**Comment by VVishion** [comment]
I still think this is a reasonable approach to prevent those errors from occurring even in userland code. I didnt experience other cases, yet. And it probably has marginal impact in userland. So I understand this has no relevancy.
