### ISSUE TITLE
Nesting ErrorBoundary in Suspense panics on hydration

### ISSUE THREAD

**Issue by VVishion** [leptos-rs/leptos#2738]
**Describe the bug**
```rust
#[component]
pub fn App() -> impl IntoView {
    let (a, mut_a) = signal(Result::<String, Error>::Err(Error("Error A".into())));

    let fallback = move |errors: ArcRwSignal<Errors>| {
        errors
            .get()
            .into_iter()
            .map(|(_, error)| view! { <div>{format!("{}", error)}</div> })
            .collect::<Vec<_>>()
    };

    view! {
        <Suspense fallback=move || view! { <div>"Loading..."</div> }>
            <ErrorBoundary fallback>
                {move || a.get()}
            </ErrorBoundary>
        </Suspense>
    }
}
```

<details><summary>panics with</summary><code>panicked at /home/emil/.cargo/git/checkouts/leptos-2c8932a5258b3db6/71c4437/tachys/src/hydration.rs:94:14:
could not convert current node into marker node

Stack:

__wbg_get_imports/imports.wbg.__wbg_new_abda76e883ba8a5f@http://127.0.0.1:3000/pkg/leptos-test.js:441:13
console_error_panic_hook::Error::new::hd068f7ac0f16603f@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3148]:0xdff5c
console_error_panic_hook::hook_impl::hfbec190b4fdeedc3@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[582]:0x6d81f
console_error_panic_hook::hook::h72aa3575a9db29c7@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3882]:0xeb248
core::ops::function::Fn::call::hc3b1d1d6db7fec49@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3390]:0xe41b3
std::panicking::rust_panic_with_hook::h1e6ac5d404b8e31b@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1394]:0xa7eb2
std::panicking::begin_panic_handler::{{closure}}::h24b0f4622f2766a5@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1858]:0xbdcdf
std::sys_common::backtrace::__rust_end_short_backtrace::h19f35d272c126e7c@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[4677]:0xf2e70
rust_begin_unwind@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3464]:0xe5483
core::panicking::panic_fmt::h87755523850ece9e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3805]:0xea29b
core::option::expect_failed::h65a8ce8e046de7db@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2820]:0xd9832
core::option::Option<T>::expect::h5c282202bbbda3b8@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2456]:0xd0d80
tachys::hydration::Cursor<R>::next_placeholder::h0aba179ad39cfba3@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1324]:0xa4143
tachys::view::tuples::<impl tachys::view::RenderHtml<R> for ()>::hydrate::h8d3c8f2f170a5240@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3416]:0xe482b
tachys::view::error_boundary::<impl tachys::view::RenderHtml<R> for core::result::Result<T,E>>::hydrate::hd3abddf9dbc23f67@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[234]:0x3c837
tachys::reactive_graph::<impl tachys::view::RenderHtml<R> for F>::hydrate::{{closure}}::hd7e97e45e3c616e9@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[272]:0x44007
<alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h0983d66d4bfc407c@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1175]:0x9b39e
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::{{closure}}::{{closure}}::h878abd01544e736d@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[646]:0x7384d
<reactive_graph::graph::subscriber::AnySubscriber as reactive_graph::graph::subscriber::WithObserver>::with_observer::h34720eaf96b89c46@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1438]:0xaa4c1
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::{{closure}}::hb37f4ad197244e27@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[895]:0x88303
reactive_graph::owner::Owner::with::h34209b920acf1bb3@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1772]:0xba282
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::h743cebaeaee41f15@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1158]:0x9a2c7
core::bool::<impl bool>::then::h705bc609728af5e1@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[453]:0x5f711
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::hfd39bd8d56bb0134@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[92]:0x12ac3
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::ha393775406eb52f2@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1599]:0xb252b
reactive_graph::effect::render_effect::RenderEffect<T>::new::h9442df1fa08d2b73@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2363]:0xce52a
tachys::reactive_graph::<impl tachys::view::RenderHtml<R> for F>::hydrate::hfa6a8d5d4239c3bc@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1206]:0x9d2a4
<leptos::into_view::View<T> as tachys::view::RenderHtml<tachys::renderer::dom::Dom>>::hydrate::hece653e12c56c36c@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1844]:0xbd393
<leptos::error_boundary::ErrorBoundaryView<Chil,FalFn,Rndr> as tachys::view::RenderHtml<Rndr>>::hydrate::{{closure}}::hc283592809004102@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[71]:0x8122
<alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h1520fd617a548b4a@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1843]:0xbd30b
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::{{closure}}::{{closure}}::h4581b20e44f54f1e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1021]:0x91426
<reactive_graph::graph::subscriber::AnySubscriber as reactive_graph::graph::subscriber::WithObserver>::with_observer::h1d44ba77bf588754@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1437]:0xaa3f5
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::{{closure}}::h2b841cf3d94dca1b@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1127]:0x98270
reactive_graph::owner::Owner::with::h429bd3385ddcc225@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1775]:0xba495
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::h30427572a3e56c97@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1819]:0xbc312
core::bool::<impl bool>::then::h853f85193e33125b@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[520]:0x67466
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::h6c79d70a8e4e48a1@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[109]:0x194b0
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::h2ff1116ab302da11@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[807]:0x81483
reactive_graph::effect::render_effect::RenderEffect<T>::new::h61dc4d830bc4d0a8@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2571]:0xd3c68
<leptos::error_boundary::ErrorBoundaryView<Chil,FalFn,Rndr> as tachys::view::RenderHtml<Rndr>>::hydrate::h278c8a5bedb98da8@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[497]:0x64c40
<leptos::into_view::View<T> as tachys::view::RenderHtml<tachys::renderer::dom::Dom>>::hydrate::h713d6fbea679f5e3@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[686]:0x770dd
<tachys::view::either::EitherKeepAlive<A,B> as tachys::view::RenderHtml<Rndr>>::hydrate::{{closure}}::h67e2f28972cf210e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1453]:0xab0db
core::option::Option<T>::map::he8faba5b5fc01c42@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[233]:0x3c5f9
<tachys::view::either::EitherKeepAlive<A,B> as tachys::view::RenderHtml<Rndr>>::hydrate::h73704d28fb2979ce@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[201]:0x35257
<tachys::reactive_graph::owned::OwnedView<T,R> as tachys::view::RenderHtml<R>>::hydrate::{{closure}}::h93413a215ecf27ee@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2877]:0xdab17
reactive_graph::owner::Owner::with::h37298350920d0793@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1773]:0xba333
<tachys::reactive_graph::owned::OwnedView<T,R> as tachys::view::RenderHtml<R>>::hydrate::h1297e402dedc7cbf@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1071]:0x948f8
<leptos::suspense_component::SuspenseBoundary<_,Fal,Chil> as tachys::view::RenderHtml<Rndr>>::hydrate::{{closure}}::hb6574ce182172620@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[108]:0x19198
<alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h51113b27281f031d@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2616]:0xd4df3
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::{{closure}}::{{closure}}::h19a03742c741ea96@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2284]:0xcc121
<reactive_graph::graph::subscriber::AnySubscriber as reactive_graph::graph::subscriber::WithObserver>::with_observer::ha7abf770ee664fa6@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1440]:0xaa659
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::{{closure}}::h7bf33e608432096d@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1726]:0xb82a0
reactive_graph::owner::Owner::with::h3a41f3dc5626c148@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1774]:0xba3e4
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::{{closure}}::h7b4c49cb570dd3e5@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2528]:0xd2b2b
core::bool::<impl bool>::then::hd3b52e173672dec8@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1317]:0xa3aaf
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::erased::h90e7fb9d4dc57976@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[132]:0x214c1
reactive_graph::effect::render_effect::RenderEffect<T>::new_with_value::hf0a3fd943055decc@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2162]:0xc8742
reactive_graph::effect::render_effect::RenderEffect<T>::new::h7f02b5ac16ed08d6@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2572]:0xd3ccc
<leptos::suspense_component::SuspenseBoundary<_,Fal,Chil> as tachys::view::RenderHtml<Rndr>>::hydrate::h1082496a6d120817@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[114]:0x1b519
<tachys::reactive_graph::owned::OwnedView<T,R> as tachys::view::RenderHtml<R>>::hydrate::{{closure}}::h7b06eae06819e47a@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2073]:0xc59da
reactive_graph::owner::Owner::with::h72d2696170d1fd50@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1350]:0xa57f5
<tachys::reactive_graph::owned::OwnedView<T,R> as tachys::view::RenderHtml<R>>::hydrate::h88d2817e99db9aee@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1050]:0x932da
<leptos::into_view::View<T> as tachys::view::RenderHtml<tachys::renderer::dom::Dom>>::hydrate::h0f05fc66afb38b3e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2875]:0xdaa69
leptos::mount::hydrate_from::{{closure}}::hec8092b6dadea24e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1381]:0xa7322
reactive_graph::owner::Owner::with::h8339a260acc60162@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1508]:0xade12
leptos::mount::hydrate_from::h07807f6b5f31e9a2@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[192]:0x32efa
leptos::mount::hydrate_body::h8f39f5a2859a6267@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2710]:0xd7116
client::hydrate::{{closure}}::h3ddcb57e064b79d6@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1630]:0xb3c9c
client::_::__wasm_bindgen_generated_hydrate::{{closure}}::h73988259efc49a01@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[460]:0x604e0
wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::haafff30188ec382b@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[196]:0x33db7
wasm_bindgen_futures::task::singlethread::Task::run::h3014f4952bfdf91a@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[440]:0x5dc23
wasm_bindgen_futures::queue::QueueState::run_all::h3799444162cd0c81@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[280]:0x45735
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hd7fdd2c2e2c4d1d0@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2155]:0xc83ca
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h39db12a11a7ff3b3@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1449]:0xaade6
__wbg_adapter_24@http://127.0.0.1:3000/pkg/leptos-test.js:224:6
real@http://127.0.0.1:3000/pkg/leptos-test.js:209:32
VoidFunction*__wbg_get_imports/imports.wbg.__wbg_queueMicrotask_481971b0d87f3dd4@http://127.0.0.1:3000/pkg/leptos-test.js:614:15
wasm_bindgen_futures::queue::queueMicrotask::h93fb41f41a731419@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3037]:0xdde29
wasm_bindgen_futures::queue::Queue::schedule_task::hbe9a36afa581de9e@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[587]:0x6e115
wasm_bindgen_futures::task::singlethread::Task::spawn::{{closure}}::h28a5b2cabf53dfac@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[3556]:0xe6b00
std::thread::local::LocalKey<T>::try_with::h04110f94c3274f63@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[659]:0x7499b
std::thread::local::LocalKey<T>::with::h59be44633dfc15d9@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1720]:0xb7e10
wasm_bindgen_futures::task::singlethread::Task::spawn::h399a26d6a5a007fb@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[279]:0x45485
wasm_bindgen_futures::spawn_local::h2ec370abf616b7a2@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2039]:0xc47d2
wasm_bindgen_futures::future_to_promise::{{closure}}::h31de48b83af08164@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1383]:0xa750f
wasm_bindgen::convert::closures::invoke2_mut::h2f8c2e0fcc935a17@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1429]:0xa9d10
__wbg_adapter_116@http://127.0.0.1:3000/pkg/leptos-test.js:243:6
cb0@http://127.0.0.1:3000/pkg/leptos-test.js:655:8
__wbg_get_imports/imports.wbg.__wbg_new_81740750da40724f@http://127.0.0.1:3000/pkg/leptos-test.js:660:13
js_sys::Promise::new::hda5d75e660ee7100@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1797]:0xbb438
wasm_bindgen_futures::future_to_promise::h40e21201d325b9df@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[1919]:0xc03fc
hydrate@http://127.0.0.1:3000/pkg/leptos-test.wasm:wasm-function[2242]:0xcad6f
hydrate@http://127.0.0.1:3000/pkg/leptos-test.js:231:18
@http://127.0.0.1:3000/:28:9
promise callback*@http://127.0.0.1:3000/:27:57
promise callback*@http://127.0.0.1:3000/:26:4
@http://127.0.0.1:3000/:31:3</code></details>

https://github.com/leptos-rs/leptos/blob/71c4437b478f33cbb886073577303bdf69206b0b/tachys/src/hydration.rs#L94

**Leptos Dependencies**

```toml
leptos = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
leptos_axum = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
leptos_meta = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
leptos_router = { git = "https://github.com/leptos-rs/leptos.git", branch = "leptos_0.7" }
```

commit 71c4437b478f33cbb886073577303bdf69206b0b

**To Reproduce**
Panics on load

**Expected behavior**
hydrate without panicking

**Comment by gbj** [comment]
Thanks. I have tested d541fc3 in both directions and things seem to work fine with either nesting order, due to the way Suspense is currently scheduled, even without the "sealing" mechanism I've now removed.

As always, feel free to open an issue if you encounter a case that's still broken.
```rust
    view! {
        <Suspense fallback=move || {
            view! { <div>"Loading..."</div> }
        }>
            <ErrorBoundary fallback>"Success" {move || b.get()}</ErrorBoundary>
        </Suspense>
        <ErrorBoundary fallback>
            <Suspense fallback=move || {
                view! { <div>"Loading..."</div> }
            }>"Success" {move || b.get()}</Suspense>
        </ErrorBoundary>
    }
```
