### ISSUE TITLE
Policy change: Add a github/workflow for 'Cargo fmt'?

### ISSUE THREAD

**Issue by martinfrances107** [leptos-rs/leptos#274]
This a controversial,  everyone has their IDE setup slightly differently. This leads to  PR's  having slightly different tabs and spacing 

RUST being a new-ish language has 

```cargo fmt```

"love a rule" or "hate a rule"... is does not matter 
all discussions end with "is that standard or not?"  

I too have loves and hates BUT I like it only because it settles needless discussion

When I look at the code-base today, running "cargo fmt" creates a moderately sized PR/patch.

I propose a one time PR that fixes all the non-standard issues. 
A one time patch accompanied with a pre-commit hook that enforce the standard 

Nothing fancy just something of the form

[sample pre commit  hook](https://gist.github.com/hryniuk/e3f4ae34e37947d0ff55a3f63add90f8)

Anyway I thought I had better make this an issue, so others can express an opinion. I am new to this code-base .. and I don't to make waves..

As a discussion point against my proposal ... a PR of this form is bad for anyone using "git Blame". it means that they will have to iterate a little....that is why I want to make this a one time thing.

Separately, the discussion  in sample pre-hook gist, talks about including cargo clippy, my own view on this is Not to do it. Clippy has saved me several times but that is a step too far.

I will create a speculative PR so people can see what is what.

**Comment by martinfrances107** [comment]
As a change to what I said above 

pure git hooks are problematic on github.

We can get the same effect with "github/workflows".

**Comment by Gentle** [comment]
I would opt for running `cargo fmt --check` in CI so Pull Requests will show that formatting is off, but as you said commit hooks are too restrictive during active development in branches

**Comment by martinfrances107** [comment]
This is stage 2 #294

**Comment by gbj** [comment]
Thanks, this is done.
