### ISSUE TITLE
Extracting body information from request does not work.

### ISSUE THREAD

**Issue by CoolSlimbo** [leptos-rs/leptos#2741]
**Describe the bug**
When using the `extract` function to extract data from a request, it gives a blank body for all functions.
Only determined on Actix, unsure of Axum.

**Leptos Dependencies**
```
leptos = { version = "0.6" }
leptos_meta = { version = "0.6" }
leptos_actix = { version = "0.6", optional = true }
leptos_router = { version = "0.6" }
```

**To Reproduce**
1. Create a new Leptos SSR project, using Actix.
2. Add the following code into the `app.rs`:
```rs
#[server(name = TestServerFunction, prefix = "/api", endpoint = "test")]
pub async fn test_func() -> Result<(), ServerFnError> {
    use actix_web::web::Bytes;

    let test = match extract::<Bytes>().await {
        Ok(f) => f,
        Err(e) => {
            logging::error!("{:?}", e);
            return Err(e.into());
        }
    };

    logging::log!("{:?}", test);

    Ok(())
}
```
3. Call the endpoint (e.g. `curl -v --request POST --url http://127.0.0.1:3000/api/test --data "Hi"`)
4. Console logs `b""`

**Expected behavior**
Expecting the log of `b"Hi"` in the console.

**Comment by gbj** [comment]
This is working as designed, on all platforms. 

The body of a request can only be consumed once. Server functions use the body to communicate their arguments. In your case, you're creating a server function that expects a POST request with a  URL-encoded body that includes the arguments to the server function (although in this case, there are none). 

If you have no arguments but need to extract bytes from the body, you can either create a custom encoding or, more likely, just create a normal Actix route to handle the request. 

(After all, it would not actually be possible to *call* the server function from the client as it is written and pass anything in the body.)
