### ISSUE TITLE
Can some documentation regarding web components be added?

### ISSUE THREAD

**Issue by slalomzacharyd** [leptos-rs/leptos#2752]
I'm always frustrated when I'm looking through the documentation and I don't see mention of if webcomponents are usable in the framework.   

**Describe the solution you'd like**
Can a section please be added to explain the current support status?  Can existing web components be used?  Can this library be used to create web components?

**Additional context**
I like the basics of the framework and I am planning to delve deeper in.  Thank you for your work on this.

**Comment by gbj** [comment]
**Using web components** Just curious: Did you try? Web components can be used exactly like any other normal HTML elements, following the syntax of other elements in the `view` macro, etc.

**Creating web components** The framework does not provide any particular tools for creating web components.

**Comment by slalomzacharyd** [comment]
I can give some more feedback as I poke.  I might try going the declarative dom route because it straddles the SSR line relatively well.  The reason why I am tip-toeing is because the non-macro syntax makes me wonder if there might be typing problems or problems with using the name of a web component.  (I assume it would be camel case?)

<img width="813" alt="Screenshot 2024-08-02 at 9 57 40" src="https://github.com/user-attachments/assets/053c6551-a1d9-448d-8217-2e5c840a1186">

**Comment by gbj** [comment]
Here's an example using the builder syntax for a custom element in 0.6:
```rust
use html::Custom;
use leptos::{
    html::{custom, p},
    *,
};

#[component]
pub fn App() -> impl IntoView {
    custom(Custom::new("foo-bar")).child((
        ("I'm a text node inside a custom element"),
        p().child("Hello, I'm in a custom element"),
    ))
}
```

Here's an example in 0.7:
```rust
use leptos::html::{custom, p};
use leptos::prelude::*;

#[component]
pub fn App() -> impl IntoView {
    custom("foo-bar").child((
        ("I'm a text node inside a custom element"),
        p().child("Hello, I'm in a custom element"),
    ))
}
```

In either case, the equivalent with the view macro follows expected HTML syntax:
```rust
view! {
  <foo-bar>/* etc */</foo-bar>
}
```

See #2702 for a similar question and conversation. I'll close this one as a duplicate.

**Comment by slalomzacharyd** [comment]
That's exactly what I was looking for. Thank you!
