### ISSUE TITLE
`leptos_axum::redirect` fails if there is a delay issuing it inside a server function

### ISSUE THREAD

**Issue by metatoaster** [leptos-rs/leptos#2789]
**Describe the bug**

Given the following server function:

```rust
#[server] 
pub async fn goto_target() -> Result<String, ServerFnError> {
    tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    leptos_axum::redirect("/target");
    Ok("/target".to_string())
}
```

The sleep is there to emulate a fetch from some database; in my use case it determines whether or not to redirect the request to a different route set up directly on the underlying `axum::Router`.

Using the above in the following component:

```rust
#[component]
pub fn DemoPage() -> impl IntoView {
    let target = Resource::new(|| (), |_| async move { goto_target().await });
    
    view! {
        <Suspense fallback=move || view! { <p>"Loading..."</p> }>
            <span>"Redirecting to "{target}</span> 
        </Suspense>
    }   
}   
```

The above is setup inside a `<Routes>` at the root level with a `<Route path=StaticSegment("demo") view=DemoPage />`.

Issuing the following curl command will not result in the expected redirect. Note the `200 OK` and the lack of `location` header.

```shell
$ curl -H "Accept: text/html" -v http://127.0.0.1:4000/demo
*   Trying 127.0.0.1:4000...
* Connected to 127.0.0.1 (127.0.0.1) port 4000 (#0)
> GET /demo HTTP/1.1
> Host: 127.0.0.1:4000
> User-Agent: curl/8.0.1
> Accept: text/html
> 
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< transfer-encoding: chunked
< date: Wed, 07 Aug 2024 04:56:47 GMT
... rest of output snipped ...
```

Commenting out the `sleep` will result in the expected behavior, i.e. the `302 Found` is set along with the `location` header:

```shell
$ curl -H "Accept: text/html" -v http://127.0.0.1:4000/demo
*   Trying 127.0.0.1:4000...
* Connected to 127.0.0.1 (127.0.0.1) port 4000 (#0)
> GET /demo HTTP/1.1
> Host: 127.0.0.1:4000
> User-Agent: curl/8.0.1
> Accept: text/html
> 
< HTTP/1.1 302 Found
< location: /target
< content-type: text/html; charset=utf-8
< transfer-encoding: chunked
< date: Wed, 07 Aug 2024 05:13:22 GMT
```

Moreover, navigating to the `/demo` page via CSR will not result in a redirect because the redirect headers are also set on the server function, and only with the following modifications to the component that I got the expected behavior (but again only under CSR):

```rust
#[component]
pub fn DemoPage() -> impl IntoView {
    let target = Resource::new(|| (), |_| async move { goto_target().await });
    
    view! {
        <Suspense fallback=move || view! { <p>"Loading..."</p> }>
            <span>"Redirecting to "{
                move || target.get().map(|target| { target.map(|target| {
                    view! {
                        {target.clone()}
                        <Redirect
                            path=target
                            options=leptos_router::NavigateOptions { replace: true, ..Default::default() }
                            />
                    }
                })})
            }</span>
        </Suspense>
    }
}
```

This would "fix" the redirect issue but only from a browser with scripting on, and when **navigating** to the page (redirect still won't work if `http://127.0.0.1:4000/demo` is opened directly if the delay on the server function is turned back on).  With scripting off the redirect naturally won't work.  This slight gotcha may be explained via documentation but I thought to leave a note with this issue while on the topic.

**Leptos Dependencies**

This was tested under the current main branch, i.e. `0.7-beta`.

**To Reproduce**

Checkout my [axum_redirect_demo](https://github.com/metatoaster/leptos/tree/axum_redirect_demo) branch, go to `examples/axum_redirect_demo` (edit: changeset ac167b6, forgot to `git add` correctly after repeating my tests locally), run `cargo leptos watch`, then open `http://localhost:4000` in a browser that has scripting enabled.  From there, do the following:

1. Copy the link and use it with `curl` as per demonstration above (and find that the redirect isn't done)
2. Open that link in a new browser tab/window, and also see that the redirect fail within the browser (as neither the correct HTTP headers nor the `<Redirect/>` component work).
3. Back to the initial page, navigate to the link normally and see that the redirect does work via the `<Redirect/>` component.
4. Only when the sleep is commented out the redirects in 1 and 2 work as expected, but this is not a realistic use case as the sleep merely replaces real-world database usage.

**Additional context**

A superficial look at how this bug came to be may be due to the way `ExtendResponse::from_app` will call [`res.extend_response(&res_options)`](https://github.com/leptos-rs/leptos/blob/208ab97/integrations/utils/src/lib.rs#L66) before all the server functions are called.  Perhaps a fix is to ensure the server functions to be called are pending somehow so that the [wait loop](https://github.com/leptos-rs/leptos/blob/208ab97/integrations/utils/src/lib.rs#L44-L47) will be able to wait for them?  I am not knowledgeable with the entirety of the framework so I can't answer this question myself.

**Comment by metatoaster** [comment]
Okay, this might actually be an issue that could be improved in the handbook, that context I found actually nudged me to look deeper into how all this works, and it lead me to the `Resource::new_blocking` (or the old `leptos::create_blocking_resource`).  I will note that the documentation for that function is sufficient as it did mention the header, but it would be useful to include this detail in the documentation for [`leptos_axum`](https://docs.rs/leptos_axum/latest/leptos_axum/fn.redirect.html).  I supposed I can take a stab at writing something for that.

However, this is still not as straightforward because even with just that change is insufficient, because this happened:

```
thread 'tokio-runtime-worker' panicked at leptos/reactive_graph/src/computed/async_derived/future_impls.rs:80:29:
At leptos/examples/axum_redirect_demo/src/landing.rs:71:22, you tried to access a reactive value which was defined at src/landing.rs:68:18, but it has already been disposed.
```

Only by changing the route to the following:

```
<Route path=StaticSegment("demo") view=DemoPage ssr=SsrMode::Async />
```

Before this worked as expected.

I supposed this is essentially resolved, but the current solution to also need the `<Redirect />` component for CSR still feels clunky, but this feature does work.  Please let me know if the example written is desired, and whatever needs to be done to workshop that into a proper example for doing SSR/CSR redirect for inclusion into the project if that's the case.

**Comment by gbj** [comment]
This needs to be a blocking resource, as it sets headers.

I did not read through your whole issue but try that and let me know if it resolves it, and it not, I'll dig in more.

**Comment by metatoaster** [comment]
Yeah, I did figure out the need to use blocking resources, the issue becomes spurious panic until a change of ssr mode as per the subsequent comment.  The issue now is mostly in the form of documentation, such as:

1. The relevant section of the handbook should make it clear that blocking resource is required.
2. Documentation on redirect should include an explanation on this (moreover, [Loading Data with Resources](https://book.leptos.dev/async/10_resources.html#loading-data-with-resources) lacks reference to blocking resource, it could use a reference to this [later section](https://book.leptos.dev/ssr/23_ssr_modes.html#blocking-resources)).
3. Maybe further examples are needed for the manipulation of headers (e.g. setting redirect, setting correct response codes) in server function and how it needs to be inside a blocking resource.

When I find some additional time I might be able to work on documentation and put something together.
