### ISSUE TITLE
`ActionForm` with complex args does not work with javascript disabled

### ISSUE THREAD

**Issue by spencewenski** [leptos-rs/leptos#2790]
**Describe the bug**
`ActionForm` with complex args does not work with javascript disabled. It appears that the `[` and `]` from the form names are being url encoded. When javascript is enabled, the request is sent to the server as `request[foo]=foo&request[bar]=bar`, but when JS is disabled, the request is sent as `request%5Bfoo%5D=foo&request%5Bbar%5D=bar`.

I assume the parsing of the args occurring on the server side? If so, maybe the parsing could be updated to handle url-encoded `[` and `]`?

**Leptos Dependencies**

Minimal example: https://github.com/spencewenski/action-form-complex-arg

Specific commit: https://github.com/spencewenski/action-form-complex-arg/commit/e4b19abe956262c7d365f24eb52ba29077b83d3b

**To Reproduce**
1. Disable Javascript in your browser ([Firefox instructions](https://www.lifewire.com/disable-javascript-in-firefox-446039))
2. Run the [minimal example](https://github.com/spencewenski/action-form-complex-arg) using `cargo leptos watch`
3. Open the app in your browser (at `localhost:3000`)
4. Enter values into the form
5. Submit the form

**Expected behavior**
Values are passed into the complex `FooRequest` struct and the server fn is called.

**Actual behavior**
Values are not properly passed into the `FooRequest` struct and the server fn isn't called. Instead, the app redirects with an error in the address bar: `http://localhost:3000/?__path=%2Fapi%2Ffoo17492837785527282375&__err=Args%7Cmissing+field+%60request%60`

**Screenshots**
Expected behavior:
<img width="1249" alt="Screenshot 2024-08-07 at 12 14 19 AM" src="https://github.com/user-attachments/assets/bed3d98b-8d72-4c14-b0b6-940e8901c48f">

Actual behavior:
<img width="1249" alt="Screenshot 2024-08-07 at 12 13 46 AM" src="https://github.com/user-attachments/assets/740b9d60-bebe-4143-825c-2a4a64dc3c2f">

**Additional context**

**Comment by gbj** [comment]
PR #2792 fixes this on the main branch/0.7. Your example is for 0.6, and I've made the same change on the `leptos_0.6` branch in 0388903.

**Comment by spencewenski** [comment]
Awesome, thanks for the quick fix, @gbj!
