### ISSUE TITLE
use:directive syntax doesn't work with generic params in Leptos 0.7

### ISSUE THREAD

**Issue by brofrain** [leptos-rs/leptos#2808]
**Describe the bug**

Directives defined with a generic parameter don't seem to be properly handled by the `view!` macro. Using such causes an error:

```
type annotations needed
cannot satisfy `_: MyTrait`
the trait `MyTrait` is implemented for `MytStruct`
```

![image](https://github.com/user-attachments/assets/5b88cd72-37c5-4eef-9eab-8b898f99c394)

It is not possible to manually add the type annotations in `view!` either.

**To Reproduce**

The code below modifies [src/lib.rs](https://github.com/leptos-rs/leptos/blob/main/examples/counter/src/lib.rs) of the counter app example. Tested on `main` branch, commit `6938614`.

```rust
use leptos::prelude::*;
use leptos::web_sys::Element;

trait MyTrait {}

#[derive(Default, Clone)]
struct MyStruct {}

impl MyTrait for MyStruct {}

fn my_trait_directive(_el: Element, _my_trait: impl MyTrait) {}

fn my_trait_directive2<T>(_el: Element, _my_trait: T)
where
    T: MyTrait,
{
}

fn my_struct_directive(_el: Element, _my_struct: MyStruct) {}

/// A simple counter component.
///
/// You can use doc comments like this to document your component.
#[component]
pub fn SimpleCounter(
    /// The starting value for the counter
    initial_value: i32,
    /// The change that should be applied each time the button is clicked.
    step: i32,
) -> impl IntoView {
    let (value, set_value) = signal(initial_value);

    view! {
        <div use:my_trait_directive=MyStruct::default()>
            <button on:click=move |_| set_value.set(0)>"Clear"</button>
            <button on:click=move |_| *set_value.write() -= step>"-1"</button>
            <span>"Value: " {value} "!"</span>
            <button on:click=move |_| set_value.update(|value| *value += step)>"+1"</button>
        </div>
    }
}
```

Using both `<div use:my_trait_directive=MyStruct::default()>` and ``<div use:my_trait_directive2=MyStruct::default()>`` produces the error. `<div use:my_struct_directive=MyStruct::default()>` works just fine.

**Expected behavior**

I assume that using generics should just work 😄 

~~I'm not sure here, but automatically converting params using `Into` trait may also be the expected behavior.~~ (EDIT: nvm that works). This code snippet doesn't work due to the same problem:

```rust
use leptos::prelude::*;
use leptos::web_sys::Element;

#[derive(Default, Clone)]
struct MyStruct1 {}

#[derive(Default, Clone)]
struct MyStruct2 {}

impl From<MyStruct1> for MyStruct2 {
    fn from(_: MyStruct1) -> Self {
        MyStruct2 {}
    }
}

fn my_trait_directive(_el: Element, _my_trait: impl Into<MyStruct2>) {}

/// A simple counter component.
///
/// You can use doc comments like this to document your component.
#[component]
pub fn SimpleCounter(
    /// The starting value for the counter
    initial_value: i32,
    /// The change that should be applied each time the button is clicked.
    step: i32,
) -> impl IntoView {
    let (value, set_value) = signal(initial_value);

    view! {
        <div use:my_trait_directive=MyStruct1::default()>
            <button on:click=move |_| set_value.set(0)>"Clear"</button>
            <button on:click=move |_| *set_value.write() -= step>"-1"</button>
            <span>"Value: " {value} "!"</span>
            <button on:click=move |_| set_value.update(|value| *value += step)>"+1"</button>
        </div>
    }
}
```

**Comment by gbj** [comment]
If you expand the macro you can see that this is because `use:` automatically adds an `Into::into()` call to the param. This means that generics can't be inferred. This is not just in 0.7 but has been true since the original commit https://github.com/leptos-rs/leptos/commit/c87328f5cfb1884fc72635e84d7703b88a3bb744

@maccesch how important do you think the implicit `.into()` is here for directive params, given that it breaks the ability to use generics?

**Comment by maccesch** [comment]
@gbj I think you're right, let's get rid of the `into()`.

**Comment by brofrain** [comment]
I can confirm 478229c553da36fc00866b1226e38bfdc677f02a fixes the issue. Thanks very much!
