### ISSUE TITLE
GTK example doesn't build on latest main

### ISSUE THREAD

**Issue by sn99** [leptos-rs/leptos#2820]
**Describe the bug**
[GTK example](https://github.com/leptos-rs/leptos/tree/main/examples/gtk) doesn't build on latest main

**To Reproduce**
`cargo run --features gtk`

**Expected behavior**
For example to run

I tried to fix it but it seems there are multiple different compilation errors,

**Comment by rakshith-ravi** [comment]
I believe our 0.7 release is still in progress on the main branch. Would recommend trying the [0.6.13 tag](https://github.com/leptos-rs/leptos/tree/v0.6.13)

**Comment by gbj** [comment]
(This is fine and I will update it -- I think we removed `examples/gtk` from CI at some point so I didn't notice that it needs an update. The version in the repo is also a weird hybrid I created for a demo, IIRC -- I will probably restore it to a purer GTK form.)
