### ISSUE TITLE
template projects fail to build in version 0.6.14

### ISSUE THREAD

**Issue by c0per** [leptos-rs/leptos#2833]
**Describe the bug**
A newly created leptos project (using `cargo leptos new --git leptos-rs/start-axum`) fails to compile.

**To Reproduce**
1. Run `cargo leptos new --git leptos-rs/start-axum` and choose not to use nightly features. (I haven't tested if the nightly fails too)
2. Go to the newly created project and run `cargo leptos watch`
3. See the error

**Expected behavior**
It runs correctly.

**Screenshots**
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/97af81e8-94c8-4590-a42f-00681c5c3faf">

**What seems to be the problem**
The newly merged PR #2828 seems to be the problem. It updates web-sys from 0.3.69 to 0.3.70. To silence some deprecation warnings, it use some newly added api of web-sys 0.3.70 and correctly update web-sys dependency.

But the 0.6 branch has a problem, PR #2830 intend to do the same thing, but it forget to update web-sys dependency of server-fn.
So the 0.6.14 version resolves to use web-sys 0.3.69, which fails to compile.

**Comment by gbj** [comment]
I've updated the templates so will close this, it should work.
