### ISSUE TITLE
Provided context not available inside `on:click`

### ISSUE THREAD

**Issue by mondeja** [leptos-rs/leptos#2852]
**Describe the bug**

When I try to use a context inside an event it is not available with latest main branch.

```rust
use leptos::prelude::*;

#[derive(Clone)]
struct Foo(());

#[component]
pub fn App() -> impl IntoView {
    let foo = Foo(());
    provide_context::<Foo>(foo);

    view! { <Child/> }
}

#[component]
pub fn Child() -> impl IntoView {
    view! {
        <div on:click=|_| { expect_context::<Foo>(); }>"CLICK ME!"</div>
    }
}
```

When I click the div it panics:

```
leptos-fluent-csr-co…23653eaab88f.js:652 panicked at /.../reactive_graph-0.1.0-beta2/src/owner/context.rs:229:9:
Location { file: "/.../context-bug/src/lib.rs", line: 17, col: 28 } expected context of type "leptos_fluent_csr_context_bug::Foo" to be present
```

**Leptos Dependencies**

```toml
[dependencies]
leptos = { version = "0.7.0-beta2", features = ["csr"] }
console_error_panic_hook = "0.1"
```

**To Reproduce**
Just create a minimal CSR app and run `trunk serve`. 

**Expected behavior**
Context is available.

**Additional context**
It seems that only happens inside events, although I have not tried other events.

**Comment by gbj** [comment]
Working as designed since 0.5, unless I'm mistaken. Context is not available in event handlers because they are outside the ownership tree. Access context in the component body and move it into the closure.

**Comment by mondeja** [comment]
Oh, I see, `Copy` was hidden this...

**Comment by mondeja** [comment]
Oh, I see, `Copy` was being hidden this...

**Comment by mondeja** [comment]
Oh, I see. `Copy` was being hiding this...

**Comment by mondeja** [comment]
I can confirm that works with v0.6.14.

**Comment by gbj** [comment]
Your 0.6 version only happens to work when the context is both provided and used outside the reactive ownership tree, but does not work if it's used anywhere else in the application. This panics, for example:
```rust
#[component]
pub fn App() -> impl IntoView {
    view! {
        <Show when=|| true>
            <Child/>
        </Show>
    }
}

#[component]
pub fn Child() -> impl IntoView {
    let foo = Foo(());
    provide_context::<Foo>(foo);
    view! {
        <div on:click=|_| {
            expect_context::<Foo>();
        }>"CLICK ME!"</div>
    }
}
```

I would say that the fact that the 0.6 example currently works is unintended, and that the 0.7 version is consistent no matter where you try to use the pattern.
