### ISSUE TITLE
Implement `ToHref` for `Rc<str>`

### ISSUE THREAD

**Issue by SleeplessOne1917** [leptos-rs/leptos#2855]
## Is your feature request related to a problem? Please describe.
It can be annoying when I try to pass an `Rc<str>` to the `href` prop on the `A` component only to get a compiler error.

## Describe the solution you'd like
Implement `ToHref` for `Rc<str>`.

## Describe alternatives you've considered
Always converting the Rc into a string or similar object before passing it to the prop.

## Additional context
I can tackle this myself if the code I have in mind is correct:

```rust
impl ToHref for Rc<str> {
    fn to_href(&self) -> Box<dyn Fn() -> String + '_> {
        let s = Rc::clone(self);
        Box::new(move || Rc::clone(&s).to_owned())
    }
}
```

There are 2 reasons I made this issue instead of just directly opening a PR:
1. I am unsure if this would collide with any of the work being done on v0.7
2. I don't know if my idea for an implementation is correct. Looking at a similar one, say the one for `Oco`:

```rust
impl ToHref for Oco<'_, str> {
    fn to_href(&self) -> Box<dyn Fn() -> String + '_> {
        let s = self.to_string();
        Box::new(move || s.clone())
    }
}
```

I'm not sure if my implementation should be more like:

```rust
impl ToHref for Rc<str> {
    fn to_href(&self) -> Box<dyn Fn() -> String + '_> {
        let s = self.to_owned();
        Box::new(move || s.clone())
    }
}
```

Generally, I'm not sure of the correct way to handle cloning for this.

**Comment by gbj** [comment]
Rather, it should be implemented for `Arc<str>` as `Rc<str>` can't be used in the view in 0.7, since it is `!Send`.

Feel free to make a PR. 

```rust
impl ToHref for Rc<str> {
    fn to_href(&self) -> Box<dyn Fn() -> String + '_> {
        let s = Rc::clone(self);
        // there is no point to the additional `Rc::clone()` here
        Box::new(move || Rc::clone(&s).to_owned())
    }
}
```

**Comment by gbj** [comment]
Oh, ignore my note about `Arc<str>` — given that they're all converted to strings anyway, it really doesn't matter at all.
