### ISSUE TITLE
The number of children of the ParentRoute component

### ISSUE THREAD

**Issue by luoxiaozero** [leptos-rs/leptos#2863]
**Describe the bug**

The number of children of the ParentRoute component cannot exceed 16.

**Leptos Dependencies**

main branch

**To Reproduce**

```rust
view! {
      <ParentRoute path=path!("/guide") view=ComponentsPage>
             "<Route /> * 16"
              /// Add the 17th Route component and errors will start to appear.
              <Route path=path!("/installation") view=InstallationMdPage/>
      </ParentRoute>
}
```

**Expected behavior**

**Screenshots**

**Additional context**

The reason for the error in the ParentRoute component comes from here: https://github.com/leptos-rs/leptos/blob/b932bd5e043bb211b3a4d5698d185faa197d8466/router/src/matching/choose_view.rs#L143

HTMLElement also has this problem, the number of children cannot exceed 26. 

https://github.com/leptos-rs/leptos/blob/b932bd5e043bb211b3a4d5698d185faa197d8466/tachys/src/html/element/mod.rs#L58  ->   https://github.com/leptos-rs/leptos/blob/b932bd5e043bb211b3a4d5698d185faa197d8466/next_tuple/src/lib.rs#L35

**Comment by luoxiaozero** [comment]
The solution I currently use is as follows:

```rust
view! {
      <ParentRoute path=path!("/guide") view=ComponentsPage>
             "<Route /> * 16"
      </ParentRoute>
      <ParentRoute path=path!("/guide") view=ComponentsPage>
             "<Route /> * 16"
      </ParentRoute>
      <ParentRoute path=path!("/guide") view=ComponentsPage>
             "<Route /> * 16"
      </ParentRoute>
}
```

But there is one annoying problem.  When I add a child to one of the ParentRoute components, I always have to check whether the number of children of the current component exceeds 16.

**Comment by gbj** [comment]
Of course these are both classic "Rust needs variadic generics" issues, where we need to use a macro to manually implement traits on tuples of up to N members and then it errors if you go higher. 

Do you have suggestions for reasonable max numbers? 16 seems like an unusually high but not unreasonable number of distinct subroutes. It's harder with elements as they are usually < 10 but can easily go very large.

**Comment by luoxiaozero** [comment]
I can accept keeping the number at 16, but allowing an unlimited number gives a better development experience.

----

```rust
view! {
      <ParentRoute path=path!("/guide") view=ComponentsPage>
             "<Route /> * 16"
      </ParentRoute>
      <ParentRoute path=path!("/guide") view=ComponentsPage>
             "<Route /> * 16"
      </ParentRoute>
}
```

In addition, I found a bug that when switching routes in the same ParentRoute component, the ComponentsPage components will be reused, which is good, but when switching routes in different ParentRout components, the ComponentsPage components will not be reused.  This will cause some scroll bar confusion.

**To Reproduce**

https://thawui.vercel.app/components/progress-bar

Open this link, click `Popover` in the left navigation bar, and then click `Radio`.

**Comment by gbj** [comment]
> allowing an unlimited number gives a better development experience.

This is my point, because Rust doesn't have variadic generics we cannot allow an unlimited number. It needs to be some specific number and we need to add macro expansions up to that number.

> In addition, I found a bug that when switching routes in the same `ParentRoute` component, the `ComponentsPage` components will be reused, which is good, but when switching routes in different `ParentRoute` components, the `ComponentsPage` components will not be reused.

This is working as intended, it's just not intended that you need to use multiple different `ParentRoute`s for what is actually the same parent route. The workaround for the above just breaks it.

**Comment by luoxiaozero** [comment]
What should I do if I cannot predict the number of routes?  For example, in a management system, there is a navigation bar on the left and a content area on the right.  As the business develops, the number of routes in the navigation bar may increase.  Maybe 50 is enough, or 100, or even more.

**Comment by gbj** [comment]
I'm saying the library needs to pick a higher number than sixteen.

It's likely there will always be a need for a workaround in more extreme cases. However, there's a better workaround than the multiple-`ParentRoute` one: using multiple `view!` sets of routes under a single parent:
```rust
{view! {
    <Route path=path!("a") view=|| ()/>
    <Route path=path!("b") view=|| ()/>
    <Route path=path!("c") view=|| ()/>
    <Route path=path!("d") view=|| ()/>
    <Route path=path!("e") view=|| ()/>
    <Route path=path!("f") view=|| ()/>
    <Route path=path!("g") view=|| ()/>
    <Route path=path!("h") view=|| ()/>
    <Route path=path!("i") view=|| ()/>
    <Route path=path!("j") view=|| ()/>
    <Route path=path!("k") view=|| ()/>
    <Route path=path!("l") view=|| ()/>
    <Route path=path!("m") view=|| ()/>
    <Route path=path!("n") view=|| ()/>
    <Route path=path!("o") view=|| ()/>
    <Route path=path!("p") view=|| ()/>
}
    .into_inner()}

{view! {
    <Route path=path!("a2") view=|| ()/>
    <Route path=path!("b2") view=|| ()/>
    <Route path=path!("c2") view=|| ()/>
    <Route path=path!("d2") view=|| ()/>
    <Route path=path!("e2") view=|| ()/>
    <Route path=path!("f2") view=|| ()/>
    <Route path=path!("g2") view=|| ()/>
    <Route path=path!("h2") view=|| ()/>
    <Route path=path!("i2") view=|| ()/>
    <Route path=path!("j2") view=|| ()/>
    <Route path=path!("k2") view=|| ()/>
    <Route path=path!("l2") view=|| ()/>
    <Route path=path!("m2") view=|| ()/>
    <Route path=path!("n2") view=|| ()/>
    <Route path=path!("o2") view=|| ()/>
    <Route path=path!("p2") view=|| ()/>
}
    .into_inner()}
```

The reason that this works is that the appropriate trait is implemented for tuples up to 16 (can be bumped higher, will do), but it is also implemented for tuples of tuples, etc.

So this basically gives you `((A, B, C, ... P), (A2, B2, C2, ... P2))`, which compiles while `(A, B, C, ... P2)` as a single tuple doesn't. `.into_inner()` just removes the "view marker" that's used for hot-reloading.

This does *not* cause the `ParentRoute` to rerender when navigating from, say, `/a` to `/p2`.

I will increase the size of the tuple in any case, but this workaround will work for any size.
