### ISSUE TITLE
Bug Report: "NotFound" Error When Running `cargo leptos serve` on Workspace Example

### ISSUE THREAD

**Issue by neotheprogramist** [leptos-rs/leptos#2867]
**Describe the bug**

When running `cargo leptos serve` and opening the browser at `localhost:3000`, the following error is encountered:

```
Errors: [
    NotFound,
]
```

This error is printed in [error_template.rs, line 45](https://github.com/neotheprogramist/leptos-playground/blob/main/app/src/error_template.rs#L45), and it is unclear why this error appears.

**Leptos Dependencies**

```toml
leptos = { version = "0.6.14" }
leptos_meta = { version = "0.6.14" }
leptos_router = { version = "0.6.14" }
leptos_axum = { version = "0.6.14" }
```

**To Reproduce**

1. Clone the repository from [leptos-playground](https://github.com/neotheprogramist/leptos-playground).
2. Ensure the setup is unmodified and based on the [workspace example](https://github.com/leptos-rs/start-axum-workspace).
3. Run `cargo leptos serve`.
4. Open a browser and navigate to `localhost:3000`.
5. Observe the "NotFound" error in the logs.

**Expected behavior**

The server should start without errors, and the application should be accessible via `localhost:3000` without encountering the "NotFound" error.

**Screenshots**

N/A

**Additional context**

The issue occurs in a repository with a minimal example available [here](https://github.com/neotheprogramist/leptos-playground). The setup is essentially the workspace example without any modifications from [leptos-rs/start-axum-workspace](https://github.com/leptos-rs/start-axum-workspace).

**Comment by gbj** [comment]
Cloned your repo and ran `cargo leptos serve`. I don't see any errors or logs.

Could you clarify which `cargo leptos --version` you are using?

**Comment by benwis** [comment]
> Cloned your repo and ran `cargo leptos serve`. I don't see any errors or logs.
> 
> Could you clarify which `cargo leptos --version` you are using?

Guessing this is happening because you've enabled hashed file output, which is currently having issues in workspaces

**Comment by neotheprogramist** [comment]
@gbj @benwis 
Hi, thank you for replies, I'm using `cargo-leptos 0.2.19` on mac os and using Chrome to open it.
Error appears in console in which you run `cargo leptos serve` randomly - whole website works but we get this messages.
I think it has something to do with Router
