### ISSUE TITLE
Use the "correct" version of dependencies.

### ISSUE THREAD

**Issue by carloskiki** [leptos-rs/leptos#2868]
Dependencies in `leptos`'s crates are defined too broadly. For example, the `server_fn` crate specifies a requirement for `bytes = "1"` but in reality, it uses features from `bytes = "1.2"`. This can sometimes cause dependents to not compile. For example:

If someone depends on `bytes = "<1.2"` and on `leptos = "0.6.14"`, then cargo will use a version of `bytes` that is not compatible with leptos, which will make the project not compile.

We could solve this issue by adding a [CI test that checks for `minimal-versions`](https://github.com/jonhoo/rust-ci-conf/blob/5ed5ed26c75685740abb4af25c17b18cc091edcf/.github/workflows/test.yml#L46).

**Comment by gbj** [comment]
PR welcome to update dependencies, or to add it to CI, although note that the specific issue you mention has already been fixed

https://github.com/leptos-rs/leptos/blob/main/server_fn/Cargo.toml#L51

And in general the same policy has been applied to all dependencies in #2765

**Comment by carloskiki** [comment]
Oh great! I was not aware of that.

I will add it to CI when I find the time.
