### ISSUE TITLE
`Cargo.lock`

### ISSUE THREAD

**Issue by sabify** [leptos-rs/leptos#2881]
By introducing cargo lockfile to the project and examples, we will:

- Make `Dependabot` work. As you may notice, we don't have any PRs from `Dependabot` even though we had some dependency updates.
- Have the best working snapshot via the lockfile. We've seen that some dependencies like `wasm-bindgen` do not strictly follow semver semantics and somehow introduce breaking changes in patches. (cargo command with `--locked` feature switch can put us in a working snapshot)

**Comment by gbj** [comment]
For some added context, the guidance on including lockfiles in libraries has [changed](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html) during the lifetime of this project, from "don't include lockfiles for libraries" to "maybe include lockfiles for libraries."

I think this is probably a good suggestion.
