### ISSUE TITLE
[Actix-web integration] Router for known paths should return 200 on HEAD requests

### ISSUE THREAD

**Issue by adundovi** [leptos-rs/leptos#2885]
**Describe the bug**
As I pointed our [here](https://github.com/leptos-rs/start-actix/issues/51), it is strange that Leptos with the Actix integration returns 404 on a HEAD request (e.g. `curl --head  http://127.0.0.1:3000`) while it should return 200. Why is this relevant? Services like [UptimeRobot](https://uptimerobot.com/) reports status "down" for such websites although they are not down. Also the Axum integration works fine, i.e., is inconsistent with the Actix one.

**Leptos Dependencies**
It can be reproduced with the current `leptos-rs/start-actix` repo (commit `54b5fb1`).

**To Reproduce**
1. Clone, compile and run `leptos-rs/start-actix`
2. Run `curl --head  http://127.0.0.1:3000`
3. `HTTP/1.1 404 Not Found` is returned

**Expected behavior**
`200 OK` should appear.

**Comment by adundovi** [comment]
It looks like an Actix-web issue: actix/actix-web#2702.

**Comment by luckynumberke7in** [comment]
Just checking the age of that thread does not give one hope. I'm glad I am
going with axum if only for this reason..
