### ISSUE TITLE
File hashing not implemented for 0.7

### ISSUE THREAD

**Issue by mrvillage** [leptos-rs/leptos#2893]
**Is your feature request related to a problem? Please describe.**
Currently file hashing is not implemented in the 0.7 beta, making it very annoying to deploy a Leptos app behind a CDN or caching layer of any kind.

**Describe the solution you'd like**
For file hash resolution to be reimplemented.

**Comment by gbj** [comment]
If it's not too much work, could you please share a small example of what doesn't work and how it should work? I didn't implement the original feature and haven't used it but will likely be the one implementing it for 0.7 -- whether it's me or someone else having a test case would be great to ensure it's working as intended.

**Comment by mrvillage** [comment]
I'm not sure the best way to show an example, but essentially `cargo-leptos` outputs a `hash.txt` file in the server's target directory (so like `target/release`) that then gets read in when creating the HTML and replaces `crate.css/js/wasm` with `crate.hash.css/js/wasm`.

I also should have some time today to implement it if you'd like! Prolly going to take some screwing around to sort out the 0.7 render process compared to 0.5/0.6 but yeah!

**Comment by gbj** [comment]
Ah okay should be pretty simple: 0.6 has this function
https://github.com/leptos-rs/leptos/blob/3aef9e2d21fc418346ea36e834a7c45c16e20496/integrations/utils/src/lib.rs#L150-L156

Which feeds in here
https://github.com/leptos-rs/leptos/blob/3aef9e2d21fc418346ea36e834a7c45c16e20496/integrations/utils/src/lib.rs#L112-L117

0.7 has `HydrationScripts`
https://github.com/leptos-rs/leptos/blob/ceff827a7791cc49c859ed56ecf806e6ec27635b/leptos/src/hydration/mod.rs#L37-L47

I think the 0.6 "find and replace in `<head>`" looks a little awkward, maybe can be done better now that the shell lives in userland, not sure

**Comment by mrvillage** [comment]
Sweet! I'll take a look sometime this afternoon or evening then, thank you! :)

**Comment by mrvillage** [comment]
Added in #2984.
