### ISSUE TITLE
Optional param segments unrecognized by path! macro in 0.7 beta 2

### ISSUE THREAD

**Issue by Houski** [leptos-rs/leptos#2896]
Something I noticed converting from 0.6 -> 0.7

```path!("/property/:country_abbreviation?/:province_abbreviation?/:city?/:community?")```

This will return the error of " Invalid param segment: country_abbreviation? ".

So missing routing parity to 0.6 with the path! macro.

**Comment by gbj** [comment]
Oh yeah I have not implemented optional param segments at all, not just in the macro. Thanks for the reminder.

**Comment by rakshith-ravi** [comment]
*one quick look later*

Is this still necessary, especially since we have wildcard segments? Cuz I'm not sure how the implementation will differ from how wildcard segments work
