### ISSUE TITLE
`<A/>` navigation in `island` nested route `#[component(transparent)]` 

### ISSUE THREAD

**Issue by tetuaoro** [leptos-rs/leptos#2914]
**Describe the bug**
`<A/>` component does not return the correct nested path :

**To Reproduce**

### config.rs
```rust
...
pub(crate) const URI_DASHBOARD: &str = "/dashboard";
pub(crate) const URI_DASHBOARD_INDEX: &str = "/"; // nested /dashboard/
pub(crate) const URI_DASHBOARD_SETTING: &str = "/setting"; // nested /dashboard/setting
...
```

### app.rs
```rust
...
<Routes>
    ...
    <Route path=URI_DASHBOARD view=DashboardProtectedRoute ssr=SsrMode::Async>
        <RouteDashboardIndexPage/>
        <RouteDashboardSettingPage/>
    </Route>
</Routes>
...
```

### nav.rs
```rust
<nav>
    <A href=URI_DASHBOARD_INDEX>"Dashboard"</A>
    <A href=URI_DASHBOARD_SETTING>"Setting"</A>
</nav>
```

### setting.rs
```rust
...

#[component(transparent)]
pub fn RouteDashboardSettingPage() -> impl IntoView {
    view! { <Route path=URI_DASHBOARD_SETTING view=SettingPage/> }
}

#[component]
fn SettingPage() -> impl IntoView { ... }
```

**Expected behavior**
Nested components and `<A/>` should return `/dashboard` and `/dasboard/setting` but they return `/` and `/setting`.

**Additional context**
- `island` mode
- leptos v`0.6.14`

**Comment by gbj** [comment]
Okay, I tried to reproduce this to understand but I cannot quite figure out what you mean. Your example does not show wher e the `<nav>` appears.

Here is my attempt at a reproduced structure, based on the current main branch (I understand that you are using 0.6 but the principles should be the same)
```rust
pub(crate) const URI_DASHBOARD: &str = "/dashboard";
pub(crate) const URI_DASHBOARD_INDEX: &str = "/"; // nested /dashboard/
pub(crate) const URI_DASHBOARD_SETTING: &str = "/setting"; // nested /dashboard/setting

#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <nav>
                <A href=URI_DASHBOARD_INDEX>"Dashboard"</A>
                <A href=URI_DASHBOARD_SETTING>"Setting"</A>
            </nav>
            <Routes fallback=|| ()>
                <ParentRoute path=path!("/dashboard") view=|| view! { <Outlet/> }>
                    <Route path=path!("/setting") view=SettingPage/>
                </ParentRoute>
            </Routes>
        </Router>
    }
}

#[component]
fn SettingPage() -> impl IntoView {}
```

If it is structured like this, then the routes are supposed to resolve to `/` and `/setting`, because they appear at the root level, and are relative to the root. 

Could you please clarify what you mean, in a single, complete example?

**Comment by tetuaoro** [comment]
Ah thank you. This is solved using `path!` helpers. Yes I left out a lot components in my example and it's exactly the same as yours.
