### ISSUE TITLE
`Owner::current()` is `None` in event handler.

### ISSUE THREAD

**Issue by maccesch** [leptos-rs/leptos#2932]
I have a component with a click handler closure like the following. It doesn't work anymore with Leptos 0.7.

```rust
let on_click = move |_| {
    // This panics because it doesn't find the context because there's no owner.
    let ctx = expect_context::<SomeCtx>();

    // is None
    let owner = Owner::current(); 
}

view! {
    <button on:click=on_click>
        My Button
    </button>
}
```

Is this on purpose? It didn't use to be like that in 0.6.

The workaround is easy obviously. Just expect the context outside the closure and move it in. But it makes some things a bit less elegant.

**Comment by gbj** [comment]
This is true on 0.7, and it *was* true in every situation except at the very root level in 0.6.

Accessing context outside the event handler, in the body of the component, is the recommended approach in either case.

**Comment by maccesch** [comment]
Ah yes in my app it is at the root level. That's why it worked before.

Ok thanks!
