### ISSUE TITLE
Navigating in/out of `Route` nested in `ParentRoute`s triggering superfluous/duplicate invocation of closures for `Suspense`/`Suspend`.

### ISSUE THREAD

**Issue by metatoaster** [leptos-rs/leptos#2937]
**Describe the bug**
I have a set of routes that is structured like so:

```rust
<ParentRoute path=StaticSegment("/item") view=ItemRoot>
    <Route path=StaticSegment("/") view=ItemListing/>
    <ParentRoute path=ParamSegment("id") view=ItemTop>
        <Route path=StaticSegment("/") view=ItemOverview/>
        <Route path=WildcardSegment("path") view=ItemInspect/>
    </ParentRoute>
</ParentRoute>
```

`ItemRoot` and `ItemTop` provides the context to the Resource which `ItemListing`, `ItemOverview` and `ItemInspect` may use. A fully complete `app.rs` that would export the `shell` and `App` is provided in [this gist](https://gist.github.com/metatoaster/2798451bd9bc99d57b73c46d7cc8ca9a) which may be imported into a `main.rs` to be served using `axum` (is what I tested on) with the standard `lib.rs` for `hydrate` that calls `hydrate_body(App)`.

**Leptos Dependencies**

Tested using `leptos-0.7.0-beta4`

**To Reproduce**

1. Start at the home page of the app, with the network and console opened under browser developer tools - clear logs to help make the issue more visible
2. Navigate to `Item Listing` - should see one `POST` to `list_items...` (normal)
3. Navigate to `Item #` (any will do) - should see a `POST` to `get_item...` (again, normal)
4. Navigate to `Inspect Path#` - You will see `POST` `inspect_item...` happen twice, and sets of console logs related to `inspect_view` being done in triplicate and `res_inspect - inspect_item().await` (logging inside the `Resource`) happen twice.  You may also see `get_item...` being done in duplicate also, which the first one _may_ be due to departure from the `ItemOverview` component and then the second one being triggered by `ItemInspect` (despite the underlying parameter haven't changed).
5. Use the browser's navigation back (and forward) and see how navigating away from the component will also trigger the API call for the component that just got "unmounted" (thus superfluous).
6. Finally, for a "clean" test, from the home page, go directly into `Demo target`, which should give a cleaner listing of API calls (which will still show `inspect_item...` being accessed twice. Note that `list_items` being accessed despite it only having been just defined and put into a context and not having been used at that point since `itemListing` shouldn't have been invoked as a component (though I am not sure if this last sentence describes a bug).

**Expected behavior**
The server functions shouldn't need to be called in duplicate and shouldn't need to be called when the component using it is being "unmounted"

**Comment by gbj** [comment]
This was an interesting bug! The problem was that Resources were tracking other Resources, inside the async block -- which caused the second Resource actually to rerun when the first one resolved. This is obviously not the way it should work: it's already running, and just waiting for the second one to resolve to continue running.

I tested against the example and it looks like #2941 fixes both cases, feel free to reopen of course if it doesn't fix the real thing. It was super satisfying to navigate around and see it only making one request for each of them, I have to say...

**Comment by metatoaster** [comment]
It does fix that problem, but it turns out my implementation of having reactive changes done in subpath (i.e. the `WildcardSegment("path")`) being dependent on that erroneous `Resource` behavior rather than the signal that should have been generated when the param (`<Memo<Result<ItemInspectParams, ParamsError>>>`) updates, as navigation _between_ different values for `path` wildcard segments isn't actually reactive as expected.

To show what I mean, I've updated the gist to include additional links that would trigger this behavior. Follow the original steps 1 to 4, but now selecting the new set of links such as `Inspect path1/ Attr1` in the updated example doesn't actually change what's being inspected. Select `Attr2` and `Attr3` for good measure, and now refresh.

Refreshing for the SSR rendering at the `Attr3` location will show a different rendering (`Item { id: 1, path: "Item 1:path1/" }` vs the expected SSR rendering `Inspecting Item { id: 1, path: "Item 1:path1/attr3" }` given that CSR wasn't reactive), but now strangely the previous duplicate `get_item...` misbehavior returns while _not_ updating the view when navigating back using the browser, and worse, a couple panics happen simultaneously, as our expected `Resource<Result<Item, AppError>>` isn't present and `wasm-bindgen-futures-0.4.43/src/task/singlethread.rs:102:37:
already borrowed: BorrowMutError`.

This behavior will also happen if we directly open the browser at `/item/1/path1/` and click on any of the `Attr` links, so somehow the context for the `Resource` is completely absent, and not to mention `get_item...` will not be called in duplicate as per the Network tab, which was unlike how it would have happened if we simply navigate to that point from the site root (it would not trigger any additional network request because the resource wasn't reacting to the change of the wildcard `path` parameter, or rather, it's not propagating that it got changed).

**Comment by gbj** [comment]
I've looked at the new version.

There are two separate issues I see here:
1. Access context in the body of the component, not in the `async` block, and then move the resource in. That is:
```rust
#[component]
fn ItemInspect() -> impl IntoView {
    let params = use_params::<ItemInspectParams>();
    let res_overview = expect_context::<Resource<Result<Item, AppError>>>();
    let res_inspect = Resource::new(
        move || params.get().map(|p| p.path),
        move |p| async move {
```
That was the cause of the panics.

2. Yes, there does seem to be a separate issue here in which a resource notifying in Suspend causes itself to be run again. I've spent a while looking at it, will fix later.

**Comment by gbj** [comment]
Ok, #2948 should fix this so that resources run the correct number of times. But of course let me know if it is still broken.

**Comment by metatoaster** [comment]
Thanks! Good catch on that wrong context access, I had done this correctly for another location but not the one that I ultimately replicated in the MVRE in the gist (missed this for whatever reason).  That said, 48c21485 on the corrected version of the linked gist will exhibit the broken behavior where the param change didn't seem to notify the resource also (plus the double suspense invocation if the SSR started at the nested path and hydration from there triggers this - it's somewhat amusing to me because the loading shifted to work twice on this end and not from that other end).

827cc0bdfa definitely fixed **both** of these issues and I think it's safe to say this particular issue is now fully resolved.  I also backtracked to putting the `expect_context` inside the closure and that actually didn't cause any panic whatsover again and the expected behavior actually does work, so it turns out where the context was accessed (being inside the `async` block) actually didn't matter, interestingly enough.  Once again thank you so much for looking into this, I wouldn't have been able to fix this issue at the speed you did.

As an aside, do you think that I should tidy up the MVRE and put this in as an example with e2e testing to as a way to prevent regression with this aspect of the reactive system?  If so I can find some time to get this done over the next week or two.

**Comment by gbj** [comment]
> [827cc0b](https://github.com/leptos-rs/leptos/commit/827cc0bdfaae22b86133907f06d057a70c760bbd) definitely fixed **both** of these issues and I think it's safe to say this particular issue is now fully resolved.

Excellent! :tada: Thanks for confirming.

> I also backtracked to putting the `expect_context` inside the closure and that actually didn't cause any panic whatsover again and the expected behavior actually does work, so it turns out where the context was accessed (being inside the `async` block) actually didn't matter, interestingly enough.

Oh yeah, I fixed this one again en route -- my earlier fix had broken the ownership chain there, so I restored it.

> As an aside, do you think that I should tidy up the MVRE and put this in as an example with e2e testing to as a way to prevent regression with this aspect of the reactive system? 

This would be *awesome*. A good way to start would be adding it to the `suspense_tests` example, since that already has e2e set up as part of our CI and it's thematically the same. A good bug report and an offer to add a regression test... :heart:
