### ISSUE TITLE
[0.7] Store field getters should inherit `pub` modifier from their respective fields

### ISSUE THREAD

**Issue by brofrain** [leptos-rs/leptos#2946]
**Is your feature request related to a problem? Please describe.**
Currently, getters for store fields are always public, which prevents hiding them outside their modules.

**Describe the solution you'd like**
Whether a getter is `pub` or not should be copied from the original field

**Comment by gbj** [comment]
Ah right ok, so I just opened this up to see — The reason that this is not so straightforward is that currently the implementation uses an extension trait so that it can generate implementations for foreign types
```rust
trait TodosStoreFields<AnyStoreField>
where
    AnyStoreField: reactive_stores::StoreField<Value = Todos>,
{
    fn user(self) -> reactive_stores::Subfield<AnyStoreField, Todos, String>;
    fn todos(self) -> reactive_stores::Subfield<AnyStoreField, Todos, Vec<Todo>>;
}

impl<AnyStoreField> TodosStoreFields<AnyStoreField> for AnyStoreField
where
    AnyStoreField: reactive_stores::StoreField<Value = Todos>,
{
    fn user(self) -> reactive_stores::Subfield<AnyStoreField, Todos, String> {
        reactive_stores::Subfield::new(
            self,
            0usize.into(),
            |prev| &prev.user,
            |prev| &mut prev.user,
        )
    }
    fn todos(self) -> reactive_stores::Subfield<AnyStoreField, Todos, Vec<Todo>> {
        reactive_stores::Subfield::new(
            self,
            1usize.into(),
            |prev| &prev.todos,
            |prev| &mut prev.todos,
        )
    }
}
```

Rust does not allow us to directly implement methods on, say, `Store<Todos>` — it needs to be done either with a local newtype or with an extension trait. The extension trait seems far preferable here.

But the problem is that trait methods share the visibility of the trait, and cannot be set individually. So this is not really possible to do with the current design.

**Comment by brofrain** [comment]
Hmm
Would it be possible to generate a separate trait for each field?
So something like this:

```rust
trait TodosStoreUserField<AnyStoreField>
where
    AnyStoreField: reactive_stores::StoreField<Value = Todos>,
{
    fn user(self) -> reactive_stores::Subfield<AnyStoreField, Todos, String>;
}

impl<AnyStoreField> TodosStoreUserField<AnyStoreField> for AnyStoreField
where
    AnyStoreField: reactive_stores::StoreField<Value = Todos>,
{
    fn user(self) -> reactive_stores::Subfield<AnyStoreField, Todos, String> {
        reactive_stores::Subfield::new(
            self,
            0usize.into(),
            |prev| &prev.user,
            |prev| &mut prev.user,
        )
    }
}

trait TodosStoreTodosField<AnyStoreField>
where
    AnyStoreField: reactive_stores::StoreField<Value = Todos>,
{
    fn todos(self) -> reactive_stores::Subfield<AnyStoreField, Todos, Vec<Todo>>;
}

impl<AnyStoreField> TodosStoreTodosField<AnyStoreField> for AnyStoreField
where
    AnyStoreField: reactive_stores::StoreField<Value = Todos>,
{
    fn todos(self) -> reactive_stores::Subfield<AnyStoreField, Todos, Vec<Todo>> {
        reactive_stores::Subfield::new(
            self,
            1usize.into(),
            |prev| &prev.todos,
            |prev| &mut prev.todos,
        )
    }
}
```

Then, if the struct is pub and the field is pub, the trait would also be generated as pub.

**Comment by gbj** [comment]
Hm that's interesting. It is possible to create a trait per field. That would require you to import a *lot* of traits to use a store from a different module, though.

**Comment by brofrain** [comment]
After a moment of thought, I think I've greatly overcomplicated things. `#[derive(Store)]` is basically a generator of getters like [getset](https://crates.io/crates/getset) or [derive_setters](https://crates.io/crates/derive_setters), so we can adapt similar patterns here. I would expect such a syntax to be more intuitive for fellow rustaceans.

Mixing `pub` and non-`pub` fields isn't really a common pattern anyway and it can even be restricted via a [Clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#/clippy::partial_pub_fields).

I've submitted a simple `#[store(skip)]` implementation that I believe solves the issue here: https://github.com/leptos-rs/leptos/pull/2958/files

**Comment by gbj** [comment]
Oh nice, good idea. I agree that giving the ability to skip store fields is the best way. Thanks for the PR.
