### ISSUE TITLE
Double fetch when starting at `ParamSegment` at some route belonging to `ParentRoute`, navigate to parent and back down

### ISSUE THREAD

**Issue by metatoaster** [leptos-rs/leptos#2961]
**Describe the bug**

Initially thought to be only applicable to changes introduced in #2959, I've retested my reproduction steps below against 827cc0bdfa (which was thought to fix everything related to #2937) and the double fetch is in fact reproducible.

I've updated the [same gist once more](https://gist.github.com/metatoaster/2798451bd9bc99d57b73c46d7cc8ca9a/2bf0d782ef513e17ecd62b4f22dc13cec2058c6a) as I've been workshopping that into a fully standalone base for the regression test I've mentioned previously.

**To Reproduce**
1. Keep the Network developer tool open for the browser
1. Ensure that the page is hydrated while under `Target 3##` (i.e. `/item/3/`)
2. Navigate to `Item Listing` via the link to get CSR rendering
3. Navigate to `Target 4##` via the link
4. See that `get_item` is fetched twice.
5. Similar behavior will occur when starting from `Target 41#`, navigate to `Target 4##`, then `Target 42#`, and this would double fetch `inspect_item`.  Since the logging is instrumented more thoroughly for this component, this reproduction step may provide additional hints of what happened.
6. This is only triggered if the parameter has changed from the initial condition, that is, starting at `Target 42#`, go to `Target 4##` then back to `Target 42#` will _not_ trigger the double fetch, but once it hits `Target 41#` (being different to the start) then the double fetch behavior will continue until the root `ParentRoute` is fully unmounted (that is, going back to Home).
7. This also only affect the same component, that is, if you start at `Target 3##`, then `Item Listing` then `Target 4##`, going to `Target 41#` will not trigger the double fetch. Navigating back to `Target 3##` or `Target 4##` will once again trigger the double fetch.

**Comment by metatoaster** [comment]
Now that I finally have some free time this weekend to work on the regression tests, I've found that the reproduction steps documented above no longer reproduces the duplicate fetch.  I ran `git bisect` and found that 36df36e16cf055afae62642b15652dfaec9fec3d provided by #2966 is in fact responsible for fixing this somehow.  I don't exactly understand how that seemingly unrelated fix also managed to fix this issue, but given that the example I am using to test this does use Params, the changes to make this work more precisely may have helped in making the reactivity more precise which is what's needed here I guess? Hopefully this issue won't come back in a different way. I'll also be testing the new changes with the actual application I am building to see if there are other conditions that will trigger this double read, but I'll worry about that tomorrow.

Anyway I will try to wrap the testing example up soon, if my toddler will behave better during the upcoming weekends or any other scarce spare time that I might have...

**Comment by gbj** [comment]
Fair enough! I think this would have been a fairly difficult issue to pin down, so if both the original application and the MRE are fixed I don't see any reason to keep it open. I'm sure I could spend some time digging into and trying to explain the mechanism by which 36df36e fixes this, but it's probably not worth it -- "PR to make param behavior more sensible fixed odd param-related bug" seems fair enough to me. Thanks for following up!
