### ISSUE TITLE
Upgrade Lepros rkyv integration to support rkyv 8

### ISSUE THREAD

**Issue by thestarmaker** [leptos-rs/leptos#3006]
Hello, currently Leptos server fns suport rkyv 7. Rkyv 8 has been recently released. Please consider upgrading to 8. 

Word of caution: v8 is not backwards compatible with 7, it will end up being a breaking change; this is a good opportunity to move to rkyv 8 with Leptos 0.7.

**Comment by benwis** [comment]
Like most things, it's all a matter of time. PRs are welcome of course
