### ISSUE TITLE
template macro page shows view macro page content

### ISSUE THREAD

**Issue by vibrantsparrow** [leptos-rs/leptos#3007]
The template macro page at https://docs.rs/leptos/latest/leptos/macro.template.html seems to be the same for the most part as the view macro page at https://docs.rs/leptos/latest/leptos/macro.view.html.

**Comment by gbj** [comment]
Fair enough. I have updated the docs for 0.7 (main) already, and have tended to close issues relative to main, not relative to the `leptos_0.6` branch. The `template` macro supports most of the same syntax as the `view` macro: I'm happy to help with any differences but updating docs for 0.6 is a pretty low priority for me at the moment.
