### ISSUE TITLE
Issues in todo_app_sqlite

### ISSUE THREAD

**Issue by Bechma** [leptos-rs/leptos#303]
I located a couple of issues when running the example https://github.com/leptos-rs/leptos/tree/main/examples/todo_app_sqlite with `cargo leptos serve`:
When you add an item:
`error deserializing server function results Semantic(None, "invalid type: string, expected map")`

When you delete an item looks fine.

When I check the requests in the network tab I can see:
![image](https://user-images.githubusercontent.com/19294519/211930379-1ccd25f6-48a1-48cd-a32d-a55d70828add.png)

There's a reference to wasm that doesn't exist in the server: http://localhost:3000/pkg/todo_app_sqlite_bg.wasm

I would love to fix them, but I'm still learning how the system works...

**Comment by benwis** [comment]
@gbj is right, in the most recent cargo-leptos release paired with the latest leptos on git, we changed the variable name from `OUTPUT_NAME` to `LEPTOS_OUTPUT_NAME`. cargo-leptos should set this env var, and if it doesn't it assumes you are using wasm-pack. You should be able to fix this by using a git dependency for leptos, and I'll see if we can get a new release to bring things back into sync.

**Comment by Bechma** [comment]
With latest git version and updated cargo leptos(I had 0.1.0, but after upgrading to 0.1.2) this issue is no longer reproduced.

So my bad, I was using an outdated cargo leptos :|

**Comment by gbj** [comment]
Okay, awesome!
