### ISSUE TITLE
<link> elements cannot use the `as` attribute.

### ISSUE THREAD

**Issue by LennDG** [leptos-rs/leptos#3049]
**Describe the bug**

I am trying to avoid a  FOUC (flash of unstyled content) when rendering a page by using the `preload` attribute on my stylesheet like this:
```html
<link rel="preload" href="/main.css" as="style" onload="this.rel='stylesheet'">
```
The problem here is that `as` is a Rust keyword. Searching around I discovered that you can use `$` to avoid parsing the token: `$as`, but then the `view!` macro fails because it does not recognize that as a valid tag name or attribute key.

**Leptos Dependencies**

```toml
leptos = { version = "0.7.0-beta7", features = [
    "nightly",
] }
```

**To Reproduce**

```rust
#[component]
fn link_issue() -> impl IntoView {
    view! {
        <link rel="preload" href="/main.css" as="style" onload="this.rel='stylesheet'">
    }
}
```

A larger example (my actual case)
```rust
#[component]
pub fn Page(children: Children) -> impl IntoView {
    view! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <title>"Pick The Day!"</title>


                <link rel="preload" as="style" type="text/css" href="/main.css" />
                // <link rel="stylesheet" type="text/css" href="/main.css"/>

                <script src="https://unpkg.com/htmx.org@1.9.2/dist/htmx.min.js" defer/>
                <script src="https://unpkg.com/alpinejs@3.14.1/dist/cdn.min.js" defer/>

                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                <meta charset="utf-8"/>

                <base href="/"/>
            </head>

            <body class= "container relative mx-auto bg-slate-800">
                <main class="container text-white text-center pt-16">
                    {children()}
                </main>
            </body>
        </html>
    }
}
```

**Expected behavior**
Recognizing the `as` correctly as an attribute, potentially with the `$` escaoe character.

**Comment by gbj** [comment]
Strangely, it seems to work as long as `as` is the first attribute. In any case, using raw identifiers (`r#as`) is the way to we get around this and works for any of the other suspects: i.e., `<link rel="preload" href="/main.css" r#as="style" onload="this.rel='stylesheet'">`  produces the correct HTML output with `as=`.

(`as`, `async`, `loop`, `for`, and `type` are all valid HTML attributes for different elements, and also Rust keywords, but `as` is the only keyword that seems to trigger this behavior. It's possibly a bug in `rstml`, but is certainly a low priority here given the easy workaround of raw identifiers.)

**Comment by LennDG** [comment]
With some additional investigation together with the fine folks in the Discord we discovered some additional quirks:

In my second example (where the DOCTYPE is defined), escaping the string with `r#as` does not work. The rendered HTML also contains `r#as` instead of `as`.

However, when you define a component like:
```rust

#[component]
fn StyleSheetLink() -> impl IntoView {
    view! { <link rel="preload" href="/main.css" type="text/css" r#as="style" onload="this.rel='stylesheet'" /> }
}
```

and include that instead of the `<link>` element it *does* work! This might have something to do with the fact that my original component acts somewhat like `shell`, but I haven't looked into that much further.

In any case, the rendered HTML is now correct with the additional component, but the FOUC is still there so I haven't been able to fix the issue I had in the first place ¯\\\_(ツ\)_/¯

**Comment by gbj** [comment]
Thanks. The case in which `r#as` was rendered into HTML was a bug in the `InertHtml` optimization, see linked PR. Specifically the difference here was "is this the top-level element in the `view` or not?" It's not something you should have to think about, so definitely report any discrepancies like that.
