### ISSUE TITLE
Islands - Using components that rely on context such as <A>

### ISSUE THREAD

**Issue by NCura** [leptos-rs/leptos#3051]
Hello,

After some experimentation with the islands feature in my project, I found an issue. I've recreated it using the axum starter template:

- Create a new project using `cargo leptos new --git leptos-rs/start-axum`.
- Enable islands feature:
   - In `Cargo.toml`, add the `"experimental-islands"` feature to `leptos` and `leptos_axum.`
   - In `src/lib.rs`, replace `leptos::mount_to_body(App);` with `leptos::leptos_dom::HydrationCtx::stop_hydrating();`.
- In `src/app.rs`, replace `#[component]` with `#[island]` for the `HomePage` function.
- Run `cargo leptos watch` and open the website: everything works, and the counter increases when pressing the button.
- Modify `src/app.rs` by adding `<A href="/">"Test"</A>`.
- Revisit the website, and in the browser console, the following error appears, and the button no longer works:

```
Uncaught (in promise) RuntimeError: unreachable
  at islands.wasm.__rust_start_panic (islands.wasm:0x197ce0)
  at islands.wasm.rust_panic (islands.wasm:0x197a27)
  at islands.wasm.std::panicking::rust_panic_with_hook::ha341c5804a6857f6 (islands.wasm:0x137153)
  at islands.wasm.std::panicking::begin_panic_handler::{{closure}}::h524485e2965b4eec (islands.wasm:0x15379c)
  at islands.wasm.std::sys::backtrace::__rust_end_short_backtrace::ha5ddc19ab2c19caa (islands.wasm:0x197c6f)
  at islands.wasm.rust_begin_unwind (islands.wasm:0x17ad6b)
  at islands.wasm.core::panicking::panic_fmt::ha6fe70f94f343704 (islands.wasm:0x17edb6)
  at islands.wasm.leptos_router::hooks::use_router::hdb88240bfe9a72d6 (islands.wasm:0xe46d5)
  at islands.wasm.leptos_router::hooks::use_route::{{closure}}::hd5038b36d49864f2 (islands.wasm:0x1671dc)
  at islands.wasm.core::option::Option<T>::unwrap_or_else::h28ba4f26ec91962f (islands.wasm:0x15dab7)
```

Additional Information: The Leptos book suggests using `leptos::leptos_dom::HydrationCtx::stop_hydrating();`, but in the `hackernews_islands_axum` example, they use `leptos::mount::hydrate_islands();`. However, when I try that, the compiler gives the following error: `could not find 'mount' in 'leptos'`

**Comment by gbj** [comment]
`<A>` uses context provided by the router, which does not exist on the client unless the router itself is an island. This will explode the size of your binary pretty significantly: you can do it but I would recommend just using `<a>`.

> The Leptos book suggests using leptos::leptos_dom::HydrationCtx::stop_hydrating();, but in the hackernews_islands_axum example, they use leptos::mount::hydrate_islands();

The book is written for 0.6 and earlier; the main branch of the repo is now what 0.7 is. You can look at the `leptos_0.6` branch for the current state of 0.6.

**Comment by NCura** [comment]
Thank you very much for your quick reply, as always!

Apologies for the confusion—I was looking at the main branch instead of the 0.6 branch. Lesson learned, and I'll make sure not to repeat that mistake!

- Regarding the use of `<A>` and `<a>`, just to confirm, I should aim to use `<A>` as much as possible, except inside islands where I should switch to `<a>`. Is that correct?

- On the topic of islands, is there any reason to nesting one island component inside another? Or does it not make a difference since the outer island already wraps everything inside a `<leptos-island>`?

- I'm using `leptos_fluent` to handle all text translations across my site with the `move_tr!` macro. How would you recommend handling this within an island? For example, if I have a translated button like this:

```rust
#[island]
fn HomePage() -> impl IntoView {
    let (count, set_count) = create_signal(0);
    let on_click = move |_| set_count.update(|count| *count += 1);

    view! {
        <button on:click=on_click>{move_tr!("click-me")}" "{count}</button>
    }
}
```

I’m encountering the same error I initially described, which makes me think `move_tr!` can’t be used inside an island. How could I translate the button text while still keeping the button interactable?

Thanks again for your guidance, and I really appreciate the help!

**Comment by gbj** [comment]
> * Regarding the use of `<A>` and `<a>`, just to confirm, I should aim to use `<A>` as much as possible, except inside islands where I should switch to `<a>`. Is that correct?

I'd put this the other way around. You should aim to use `<a>` as much as possible, except in the specific cases where you need one of [the two additional features that `<A/>` provides](https://docs.rs/leptos_router/0.6.0/leptos_router/fn.A.html). Note that `<a>` does work with client-side routing when client-side routing is enabled, so unless you're using one of those two features (relative nested routing or marking the active URL) `<a>` should be preferred.

> * On the topic of islands, is there any reason to nesting one island component inside another? Or does it not make a difference since the outer island already wraps everything inside a `<leptos-island>`?

There are two things that you could mean by nesting islands:
1) Using an island in the `children` that you pass to another island
2) Using an island inside the `view` that you return from an island

EIther is fine, although 2 is (IIRC) bugged in 0.6 and fixed in 0.7. You can [read more here](https://book.leptos.dev/islands.html#unlocking-superpowers).

> * I'm using `leptos_fluent` to handle all text translations across my site with the `move_tr!` macro. How would you recommend handling this within an island? For example, if I have a translated button like this:
> 
> ```rust
> #[island]
> fn HomePage() -> impl IntoView {
>     let (count, set_count) = create_signal(0);
>     let on_click = move |_| set_count.update(|count| *count += 1);
> 
>     view! {
>         <button on:click=on_click>{move_tr!("click-me")}" "{count}</button>
>     }
> }
> ```
> 
> I’m encountering the same error I initially described, which makes me think `move_tr!` can’t be used inside an island. How could I translate the button text while still keeping the button interactable?

I'm not sure for this library in particular, sorry. In general, I'd say that creating an island that wraps the rest of your app, taking `children` and providing the context that `leptos_fluent` needs, is the way to support libraries that rely on context.

**Comment by NCura** [comment]
> I'm not sure for this library in particular, sorry

For anyone interested in this particular library, I've opened an [issue](https://github.com/mondeja/leptos-fluent/issues/245) on the `leptos_fluent` repo.

>You should aim to use `<a>` as much as possible, except in the specific cases where you need one of [the two additional features that `<A/>` provides](https://docs.rs/leptos_router/0.6.0/leptos_router/fn.A.html).

Oh, when I read the book, I had the impression that `<A>` was a direct improvement over `<a>`, so I’ve used it everywhere on my website instead of `<A>`. From now on, I will only use it when needed.
___
For the nesting islands, I meant the following. If you having something like this:

```rust
#[component]
pub fn App() -> impl IntoView {
    ...

    view! {
        ...
        <Router fallback=|| {...}>
            <Routes>
                <Route path="" view=View1>
                    <Route path="" view=View2/>
                    ...
                </Route>
            </Routes>
        </Router>
    }
}

#[component]
pub fn View1() -> impl IntoView {
    view! {
        <HeaderView/>
        <main>
            <Outlet/>
        </main>
        <FooterView/>
    }
}

#[component]
pub fn View2() -> impl IntoView {
    view! {
        ...
    }
}

```

If I make `View1` an island, I will get a `leptos-island` HTML element wrapping the content of the view, and all subsequent HTML elements that I create inside the `Header`, any `Outlet`, or the `Footer` will be marked for hydration. So my question was: is there any point in making those components islands since they are already inside a parent island?

> In general, I'd say that creating an island that wraps the rest of your app...

If, instead of marking `View1` as an island, I directly mark `App` as an island, everything will be marked for hydration. So, what would be the point of the islands? At least with `View1` as an island, I can gain some small size reduction.

In the [Unlocking Superpowers](https://book.leptos.dev/islands.html#unlocking-superpowers) section of the book, there are 3 key facts mentioned:

> 1. Code inside `#[component]` functions now _only_ runs on the server.
> 2. Children and props can be passed from the server to islands, without being included in the WASM binary.
> 3. Context can be passed between otherwise-independent islands.

Maybe the point of using islands in this case is that, even if everything is marked for hydration, any `#[component]` that is a child of an island only runs on the server. Or perhaps it’s that I can create nested islands, as mentioned earlier, and pass context between them?

**Comment by gbj** [comment]
> If I make `View1` an island, I will get a `leptos-island` HTML element wrapping the content of the view, and all subsequent HTML elements that I create inside the `Header`, any `Outlet`, or the `Footer` will be marked for hydration. 

First: You really don't want to do this, or there is no benefit to islands. The goal with islands is to make the island as small as possible. Anything that does not need to be interactive should not be included in the island. If you mark a whole route as an island then yes, everything will be compiled into the WASM binary: `HeaderView`, and `FooterView`, and also the `Outlet`. (Which may actually have issues because there is no router available)

Instead, mark specific, small parts of the page as islands.

> So my question was: is there any point in making those components islands since they are already inside a parent island?

In that case, no.

> > In general, I'd say that creating an island that wraps the rest of your app...
> 
> If, instead of marking `View1` as an island, I directly mark `App` as an island, everything will be marked for hydration. So, what would be the point of the islands? At least with `View1` as an island, I can gain some small size reduction.

That's not what I meant. All of the benefit is in projecting other islands through the `children` of an island, as described in the ["passing server children to islands" section](https://book.leptos.dev/islands.html#passing-server-children-to-islands).

Here's what I meant:

```rust
#[component]
fn App() -> impl IntoView {
  // none of this is included in the WASM
  view! {
    <HeaderView/> // not sent to client
    <main>
      <SomeProvider>
        /* a bunch more non-client HTML */
        <SomeConsumer/>
        /* a bunch more non-client HTML */
      </SomeProvider>
    </main>
    <FooterView/> // not sent to client
  }
} 

#[island]
fn SomeProvider() -> impl IntoView {
  provide_context(42i32);
  children()
} 

#[island]
fn SomeConsumer() -> impl IntoView {
  let value = use_context::<i32>();
  view! {
    <button on:click=|_| log!("value is {value:?}")>"Click me"</button>
  }
} 
```

In this, *only* the two islands are sent to the client. This is the way to do things: create small islands, project server content "through" the children of an island, and possibly pass other islands through the children of an island.

> > 1. Code inside `#[component]` functions now _only_ runs on the server.
> ...
> Maybe the point of using islands in this case is that, even if everything is marked for hydration, any `#[component]` that is a child of an island only runs on the server. 

This is a miscommunication on my part. `#[component]` functions only run on the server, unless you compile them into the body of an island. There are not really "client components" and "server-only components," there are "client components" (islands) and "shared components" (can be used on either client or server, but will only be in the WASM binary if they are used

**Comment by NCura** [comment]
Thank you for the clarifications. I realized that part of my confusion came from the fact that I haven't used `children()` in any of my projects. Instead, I relied on nesting components, which has worked for my use cases so far. In your example:

```rust
<SomeProvider>
  <SomeConsumer/>
</SomeProvider>
```

I would have approached it like this:

```rust
<SomeProvider/>
```

And then:
```rust
#[island]
fn SomeProvider() -> impl IntoView {
  view! {
    <SomeConsumer/>
  }
}
```

This led to my question about nesting islands and why `SomeConsumer` needed to be an island if it was already inside `SomeProvider`, which is an island itself. Your example cleared this up for me, and I'll be more mindful of using `children()` where appropriate.

I really appreciate the thorough explanation.
