### ISSUE TITLE
[0.7.0-gamma2] script tag body escaping characters (e.g. `&` -> `&amp;`)

### ISSUE THREAD

**Issue by BakerNet** [leptos-rs/leptos#3078]
**Describe the bug**

script tags which previously rendered unescaped JS are now having characters escaped - as if being rendered as text node

**Leptos Dependencies**

All `0.7.0-gamma2`

**To Reproduce**

Put a script tag in head of the shell with `&` in it - check the resulting HTML

**Expected behavior**

`&` is rendered instead of `&amp;`

**Screenshots**

![image](https://github.com/user-attachments/assets/05c191f2-c80e-418f-b875-af2cbce85c30)

**Additional context**

This was not happening in `-gamma`

**Comment by gbj** [comment]
Thanks. Should be fixed by #3079.

(In the future if you have a bug report, for this or any project, copied-and-pasted text is much easier than screenshots! This one was obvious enough to me that I didn't have to re-type everything, luckily.)

**Comment by BakerNet** [comment]
> Thanks. Should be fixed by #3079.
> 
> (In the future if you have a bug report, for this or any project, copied-and-pasted text is much easier than screenshots! This one was obvious enough to me that I didn't have to re-type everything, luckily.) 

The screenshot was included as "evidence this is happening" not meant to be used for recreating the issue.

But I'll include a full code example in the text next time.
