### ISSUE TITLE
Multiple query signals cancel each other out

### ISSUE THREAD

**Issue by TheToddmeister** [leptos-rs/leptos#3095]
Problem
Short:
https://github.com/TheToddmeister/leptos_params_test
The example is in xxxx/test and is using gamme2

I expect that when a new signal is set it adds itself to the url.
If if already exists it overwrites what is in that key's value.
if it is set to none it removes itself.
What i see happening is that if multiple signal are set sequentially only the last signal is persisted.
When the same signal sequence is submitted multiple times, that last signal is appended to the url instead of replacing the key.
In my example using 0.7.0-gamma2 i expect: to get something like this on submission:
0) http://127.0.0.1:3000/test -> 1) /test?river=a,b,c&activity=true&nation=A%2CB%2CC%2CD
-> 2) identical to 1

However in my test im getting:
0) http://127.0.0.1:3000/test
-> 1) /test?nation=A%2CB%2CC%2CD&nation=A%2CB%2CC%2CD
-> 2) /test?nation=A%2CB%2CC%2CD&nation=A%2CB%2CC%2CD&nation=A%2CB%2CC%2CD

if i add a preexisting parameter that parameter is persisted on updates as expected:
0) 127.0.0.1:3000/test?gibberish=true -> 1) ... -> 2) /test?gibberish=true&nation=A%2CB%2CC%2CD&nation=A%2CB%2CC%2CD

Long:
Expected behaviour:
When params are listed you can either represent that param as a list of repeated named params as shown with "location" below:
A) https://www.finn.no/realestate/leisuresale/search.html?leisure_situation=2&lifecycle=1**&location=0.20061&location=0.20012&location=0.20018&location=0.20015**

or "location" could have been represented as a list with or without [ ].
B) https://www.finn.no/realestate/leisuresale/search.html?leisure_situation=2&lifecycle=1&**location[0.2, 0.4, 0.54]**

As per this thread there doesnt seem to be a unviversal standard on this.

This is what the query signal says it does:
/// The function creates a bidirectional sync mechanism between the state encapsulated in a signal and a URL query parameter.
/// This means that any change to the state will update the URL, and vice versa, making the function especially useful
/// for maintaining state consistency across page reloads.
///
/// The key argument is the unique identifier for the query parameter to be synced with the state.
/// It is important to note that only one state can be tied to a specific key at any given time.
///
/// The function operates with types that can be parsed from and formatted into strings, denoted by T.
/// If the parsing fails for any reason, the function treats the value as None.
/// The URL parameter can be cleared by setting the signal to None.

I expect that when a new signal is set it adds itself to the url.
If if already exists it overwrites what is in that key's value.
What i see happening is that if multiple signal are set sequentially only the last signal is persisted.
When the same signal sequence is submitted multiple times, that last signal is appended to the url instead of replacing the key.
In my example using 0.7.0-gamma2 i expect: to get something like this on submission:
0) http://127.0.0.1:3000/test -> 1) /test?river=a,b,c&activity=true&nation=A%2CB%2CC%2CD
-> 2) identical to 1

However in my test im getting:
0) http://127.0.0.1:3000/test
-> 1) /test?nation=A%2CB%2CC%2CD&nation=A%2CB%2CC%2CD
-> 2) /test?nation=A%2CB%2CC%2CD&nation=A%2CB%2CC%2CD&nation=A%2CB%2CC%2CD

if i add a preexisting parameter that parameter is persisted on updates as expected:
0) 127.0.0.1:3000/test?gibberish=true -> 1) ... -> 2) /test?gibberish=true&nation=A%2CB%2CC%2CD&nation=A%2CB%2CC%2CD

**Comment by gbj** [comment]
You say that you are testing this against `gamma2`, which does not include the fix in https://github.com/leptos-rs/leptos/commit/e2f0b4deebba8ecce2079efc908bcd0869b2df87. When I tested it against current git main, it appears to work as expected. Could you confirm whether that is the cast?
