### ISSUE TITLE
ArcSignal With requires T:Clone

### ISSUE THREAD

**Issue by stefnotch** [leptos-rs/leptos#3106]
**Describe the bug**
Is there any reason for the `Clone` bound to be applied here? I attempted to remove it, and it still seems to compile
https://github.com/leptos-rs/leptos/blob/547442243b71a084a65fcdd866eb61c4ad7e0599/reactive_graph/src/wrappers.rs#L288-L291

**Leptos Dependencies**

Latest master from GitHub

**To Reproduce**
1. Go to https://github.com/leptos-rs/leptos/blob/547442243b71a084a65fcdd866eb61c4ad7e0599/reactive_graph/src/wrappers.rs#L288-L291
2. Remove the `Clone` bound
3. Should still work?

**Expected behavior**
I expected the code to not have that bound.

**Comment by gbj** [comment]
It looks like it was added accidentally during #3031 and not caught. Please feel free to just make PRs directly for things like "This trait bound doesn't need to be here" without opening a separate issue. It

**Comment by zakstucke** [comment]
Sorry, I think this should already be fixed in my next PR #3076 which gets rid of the manual `With` implementations.

**Comment by stefnotch** [comment]
Sounds good, I'll directly open PRs for reasonably straightforward fixes in the future!

And nice, #3076 has been merged. So I can close this :)
