### ISSUE TITLE
Idea for <ErrorBoundary/>

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#311]
I just realized that I think we could implement `IntoView` for `Result<impl IntoView, Error>` by creating an `<ErrorBoundary/>` component, which provides a context with a `Signal<Box<dyn Error>>`... any time you try to render `Ok`, it renders, and any time you try to render `Err`, it renders `()` and triggers the error boundary.

**Comment by benwis** [comment]
I like this idea! I think this is a great way to handle Errors returned from server functions and components. Coupled with error handling in Actix/Axum, that's the entire error handling story!

**Comment by gbj** [comment]
Done in #338. Thanks @benwis!
