### ISSUE TITLE
Need a way to get the base mount point of a `Route`

### ISSUE THREAD

**Issue by rakshith-ravi** [leptos-rs/leptos#3124]
**Is your feature request related to a problem? Please describe.**
Let's say I'm mounting a component (that has sub routes in it), into different parts of an app. There's no way for me to know where the component is being mounted. Example:

```
<Route path="/first">
    <MyComponent />
</Route>

<Route path="/second">
    <MyComponent />
</Route>
```

(Assume `MyComponent` has sub-routes in it, which is why it is being mounted as children.)

There's no way for `MyComponent` to know if it's currently running inside `first` or `second`. This is usually needed for "back" / "close" buttons to know where to redirect back to once a component has finished it's job.

**Describe the solution you'd like**
The ideal solution would be this:

```
let base_path = leptos_router::use_base_path(); // I'm sure a better name would be ideal
```

**Describe alternatives you've considered**
I tried using context shadowing but that isn't allowed in `Route` children, so :(

**Additional context**
Would be happy to implement this in 0.7 if you can tell me where I can get that information from

**Comment by gbj** [comment]
A form of this is already implemented internally, so I've opened #3126 to simply expose that as `use_matched()`. This returns a memo that should include the path that the router matched to render the current `Route`. Let me know if that works for your use case.

**Comment by rakshith-ravi** [comment]
Thanks a lot for this!

I tried it out with an example template. I noticed that `leptos_router` doesn't support child routes inside a `Route` component anymore, so I assumed that I was to use `ParentRoute` (please correct me if I'm wrong). This is my current code:

```
<Routes fallback=|| "Page not found.".into_view()>
    <ParentRoute path=StaticSegment("first") view=Outlet>
        {
            // Ideally this is where I would pass the `use_matched` value as a prop
            println!("{}", use_matched().get_untracked());
        }
        <Route path=StaticSegment("") view=HomePage/>
    </ParentRoute>
    <ParentRoute path=StaticSegment("second") view=Outlet>
        {
            // Ideally this is where I would pass the `use_matched` value as a prop
            println!("{}", use_matched().get_untracked());
        }
        <Route path=StaticSegment("") view=HomePage/>
    </ParentRoute>
</Routes>
```

And I got this error:

```
thread 'main' panicked at src/app.rs:46:44:
use_matched called outside a matched Route
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Anything I'm doing wrong?

**Comment by gbj** [comment]
I think I'm confused about what you are trying to achieve. No, you can't access the current matched route in the `{ ... }` sections where you're referring to it above, because those don't really exist in a runtime sense -- the nested tree of `ParentRoute`/`Route` components is just a series of route definitions.

I'm saying you can use `use_matched` inside `HomePage`. Here's a working example of what I mean
```rust
#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <Routes fallback=|| "Page not found.">
                <ParentRoute path=StaticSegment("first") view=Outlet>
                    <Route path=StaticSegment("") view=HomePage/>
                </ParentRoute>
                <ParentRoute path=StaticSegment("second") view=Outlet>
                    <Route path=StaticSegment("") view=HomePage/>
                </ParentRoute>
            </Routes>
        </Router>
    }
}

#[component]
pub fn HomePage() -> impl IntoView {
    let matched = use_matched();
    view! { <p>{matched}</p> }
}
```

**Comment by gbj** [comment]
(Just reopening because I don't know if this actually fixes your issue and am happy to keep discussing)

**Comment by rakshith-ravi** [comment]
Ahh, got it. I guess what I'm looking for is a way to get `first` and `second` from a child route in your example. 

Here's another use-case that I'm trying to tackle with `use_matched()`:
I have a custom `Route` component, (called `AppRoute`, which is a `#[component(transparent)]`). I mount it like so:

```
<AppRoute<Login> view=LoginPage>
    <AppRoute<ConfirmLogin> view=ConfirmLoginPage />
</AppRoute<Login>>
```

Now, `AppRoute` _only_ has absolute paths (for the sake of type safety and to prevent typos). In this simple example, `AppRoute<ConfirmLogin>` needs to know the matched path of `AppRoute<Login>` in order to mount itself in a relative path. I was thinking in the implementation of `AppRoute`, I can get the current mount point and do a simple `trim_start_matches` and mount it to that. Any recommendations on how I could do that?

Now yes, I do understand that I could technically just do simple `Route`s or pass a prop to `AppRoute` to specify the parent component, but I'm trying to keep my code type safe and make sure it prevents me from shooting myself in the foot with typos. If there's no way to achieve this, then I suppose that is the way to go. But if there's a way to get the "parent" component in some way, so that my child route can know where the parent component is mounted (and thereby mount itself in a relative URL), that would be ideal

**Comment by gbj** [comment]
> Ahh, got it. I guess what I'm looking for is a way to get `first` and `second` from a child route in your example.

Isn't that what the example does? It displays `first` on the page where `HomePage` is a child of the route `first`, and `second` on the page where `HomePage` is a child of the route `second`. If this isn't what you mean, could you try explaining it a different way? I am not understanding. 

> For example, if Login is in /login, and ConfirmLogin is at /login/confirm, AppRoute<ConfirmLogin> should mount itself at /confirm instead of /login/confirm (let me know if this example is too confusing. I'll try coming up with a better one).

This is not possible for nested routes, unless I'm again misunderstanding. The parent route is `/login` and the child route is `confirm`, which makes it `/login/confirm`. If the parent route is `/` and the child is `confirm`, the child will be at `/confirm`. There is no way for the parent to be `/login` and the child to be `/confirm`, sorry.

> I was thinking in the implementation of AppRoute, I can get the current mount point and do a simple trim_start_matches and mount it to that. Any recommendations on how I could do that?

No, this is not possible.

The ParentRoute/Route structure is just a way of building up a tree of route definitions. `ParentRoute`, for example, is just a way of building a [`NestedRoute`](https://docs.rs/leptos_router/0.7.0-gamma/leptos_router/struct.NestedRoute.html) struct. If you have more specific needs than the ParentRoute/Route component structure can accommodate, then you should probably build these route definitions manually or build your own components.

**Comment by rakshith-ravi** [comment]
Yeah I suppose this is not possible then.

To clarify, this is what I meant:

```
<Route path="/login" view=Outlet>
    <AppRoute<ConfirmRoute> />
</Route>

#[component(transparent)]
fn AppRoute<Route>() { // Ignore the generic for now. Simplifying the example
    let parent_route = use_matched();
    view! {
        <Route path="" view=LoginPage />
        <Route path={CONFIRM_ROUTE.trim_start_matches(parent_route)} view=ConfirmLoginPage />
    }
}
```

I suppose this isn't possible. I'll try and get this implemented in a different way to build a nested route tree.

Thanks!

**Comment by rakshith-ravi** [comment]
Should I close this issue as fixed? Cuz _one_ of my use-cases was fixed (the back button thing).

**Comment by gbj** [comment]
Yeah my initial confusion here was due to the fact that I was offering a per-request runtime solution (what is the path that the router has matched for this request so far?) and you're looking for a one-time runtime solution (which routes have been defined so far), which would need to apply at both route definition/generation and route matching time. 

ISTM that this can be solved by providing `"login"` as a function argument to something if you don't want to duplicate it -- the important thing is just that you need to provide it; the router doesn't know it and can't provide it at route definition time.
