### ISSUE TITLE
Docs: update 0.7 release notes for HashedStylesheet as it is breaking change

### ISSUE THREAD

**Issue by karpfediem** [leptos-rs/leptos#3132]
**Is your feature request related to a problem? Please describe.**
Previously when using `LEPTOS_HASH_FILES=true` and the `Stylesheet` component, the correct file (with hashed name) was included.
When migrating to leptos 0.7 the `Stylesheet` component does NOT allow using files with hashed names anymore.
For this purpose the new `HashedStylesheet` component was introduced, which needs to be included where `LeptosOptions` are available (e.g. in the `shell`)

**Describe the solution you'd like**
Include this breaking change in the release notes for leptos 0.7.

**Describe alternatives you've considered**
N/A

**Additional context**
```rs
pub fn shell(options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html>
        <html lang="en" data-theme="auto">
            <head>
                <meta charset="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <AutoReload options=options.clone() />
                <HydrationScripts options=options.clone()/>
                <MetaTags/>
                <HashedStylesheet options=options.clone() id="leptos"/>
            </head>
            <body>
                <App/>
            </body>
        </html>
    }
}
```

**Comment by gbj** [comment]
(Just for the sake of clarity: I have not written or updated any release notes since this component was added. I will include it in the release notes for 0.7 when those exist.)

**Comment by gbj** [comment]
Have added this to the draft of release notes for `rc0`, which I plan to release later this week.
