### ISSUE TITLE
Incorrect css class dom update

### ISSUE THREAD

**Issue by AkinAguda** [leptos-rs/leptos#3139]
**Describe the bug**
When I try to dynamically add a css class with the `class:foo=some_rw_signal` it seems to append the class to the first child of the element

Some additional info:

Even when I used a package like [tailwind fuse](https://github.com/gaucho-labs/tailwind-fuse) to concat classes and dynamically add them, I had the same issue with the child dom node updating instead of the parent. (Only difference is that it added all the classes of the parent + the conditional class to the child)

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.7.0-gamma", features = ["nightly"] }
leptos_meta = { version = "0.7.0-gamma" }
leptos_actix = { version = "0.7.0-gamma", optional = true }
leptos_router = { version = "0.7.0-gamma", features = ["nightly"] }
```

**To Reproduce**
1. Paste the following into a component

```
use leptos::{ev, prelude::*};

#[component]
pub fn Nav() -> impl IntoView {
    let is_out_of_threshold = RwSignal::new(false);

    let threshold_setter = move || {
        if let Ok(scroll_y) = window().scroll_y() {
            is_out_of_threshold.set(scroll_y > 20.0);
        } else {
            is_out_of_threshold.set(false);
        }
    };

    let scroll_handle = window_event_listener(ev::scroll, move |_| threshold_setter());
    let load_handle = window_event_listener(ev::load, move |_| threshold_setter());

    on_cleanup(move || scroll_handle.remove());
    on_cleanup(move || load_handle.remove());

    view! {

            <div class:bg-black=is_out_of_threshold>
                <a href="/">
                   Hello World
                </a>
            </div>

    }
}

```

2. Add enough content below this component to make the page scrollable

3. Run `cargo leptos watch`

4. Observe that the `bg-black` is applied to the child `<a>` tag

**Expected behavior**
The `bg-black` class should be applied to the `<div>`

**Screenshots**
<img width="739" alt="Screenshot 2024-10-15 at 12 44 47" src="https://github.com/user-attachments/assets/02ef6c2b-fcaa-49d9-abad-64b6d6423005">

https://github.com/user-attachments/assets/15503473-696d-4dd1-ad2f-777515cac089

**Additional context**
I am not sure this is related but I have the following errors in my console:

<img width="856" alt="Screenshot 2024-10-20 at 21 18 04" src="https://github.com/user-attachments/assets/0dbdaa1d-446b-4194-ba22-8eba3902b92a">

<img width="855" alt="Screenshot 2024-10-20 at 21 18 24" src="https://github.com/user-attachments/assets/b183f9ed-e8eb-44e7-8e2e-ef86a8ee7cb6">

**Comment by gbj** [comment]
I can't reproduce the issue by following the steps provided. Please provide a complete, self-contained example that reproduces the issue. Thanks!

https://github.com/user-attachments/assets/8ee345bb-e129-4dba-b805-3ee738185260

**Comment by AkinAguda** [comment]
I managed to resolve this issue. 

It seemed to be happening because my `<body>` tag was placed here:

<img width="548" alt="Screenshot 2024-10-21 at 20 40 54" src="https://github.com/user-attachments/assets/0576889f-2eb1-4a5d-a652-365ca3dcdff0">


And `<App />` was just rendered like so:

```
  <!DOCTYPE html>
      <html lang="en">
          <head>
               <meta charset="utf-8"/>
               <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <AutoReload options=leptos_options.clone() />
                <HydrationScripts options=leptos_options.clone()/>
                <MetaTags/>
            </head>
           <App/>
  </html>
```

I'll close this issue. I am curious why this caused an issue and if its something to warn against maybe?

**Comment by gbj** [comment]
It caused an issue because your application now has two body tags (one in the `shell` function, and one in your `App` function), which is not valid HTML. While the browser will try to recover as best it can, it will cause issues because the renderer is expecting things to be in the order your declare them, not how the browser rearranges them.  This is a semi-frequent issue (I've seen ~4-5 people have it in 2 years), and one of the goals of moving the `shell` out into user code was to make it a little clearer where the `<body>` tag is declared. Sorry for the inconvenience!

**Comment by AkinAguda** [comment]
> It caused an issue because your application now has two body tags (one in the `shell` function, and one in your `App` function), which is not valid HTML. While the browser will try to recover as best it can, it will cause issues because the renderer is expecting things to be in the order your declare them, not how the browser rearranges them.  This is a semi-frequent issue (I've seen ~4-5 people have it in 2 years), and one of the goals of moving the `shell` out into user code was to make it a little clearer where the `<body>` tag is declared. Sorry for the inconvenience!

Ah I see. Not a problem. Thanks so so much for the help 🙏
