### ISSUE TITLE
Reactive `style=""` overwrites `style:foo`.

### ISSUE THREAD

**Issue by zakstucke** [leptos-rs/leptos#3141]
**Describe the bug**
Discovered during #3119. `style=""` and `style:foo` conflict and overwrite eachother.

**Leptos Dependencies**
Current main

**To Reproduce**
```rust
#[component]
pub fn App() -> impl IntoView {
    let condition = RwSignal::new(true);
    view! {
        <button
            style=move || if condition.get() { "color: red" } else { "" }
            style:background="transparent"
            on:click=move |_| condition.update(|last| *last = !*last)
        >
            "Button"
        </button>
    }
}
```

https://github.com/user-attachments/assets/62db0c0b-6775-47d5-ab05-ae4ab9005a08

**Comment by gbj** [comment]
This is WAD. Updating the `style` overwrites the entire `style` attribute, which will include overwriting any individual styles you've set. There isn't a way around this without expensive runtime checks -- the framework has always worked this way for `style:` and `class:` vs `style` and `class`.

**Comment by zakstucke** [comment]
Noted, thanks!
