### ISSUE TITLE
docs.rs build failed for 0.7.0-rc0

### ISSUE THREAD

**Issue by jaskij** [leptos-rs/leptos#3146]
Just go to https://docs.rs/crate/leptos/0.7.0-rc0

**Comment by jaskij** [comment]
It seems the build [ran into an ICE in the nightly compiler](https://docs.rs/crate/leptos/0.7.0-rc0/builds/1400032)

**Comment by paul-hansen** [comment]
Opened an issue for this here: https://github.com/rust-lang/rust/issues/132743

**Comment by gbj** [comment]
[`rc2` docs are fine on docs.rs](https://docs.rs/leptos/0.7.0-rc2/leptos/) :tada:
