### ISSUE TITLE
Mac linker error

### ISSUE THREAD

**Issue by bambooyuh** [leptos-rs/leptos#3148]
After updating to the 0.7-rc0 I'm now getting a mac linker error:

ld: Assertion failed: (name.size() <= maxLength), function makeSymbolStringInPlace, file SymbolString.cpp, line 74.

versions:
mac M1
Rust: nightly
Leptos: 0.7-rc0

I'm using mac's default linker.

**Comment by gbj** [comment]
Please include a reproducible example. Thanks!

**Comment by seanaye** [comment]
For people in the future: this is still possible to reproduce in 0.7.2, I'm not sure what exactly causes it since my app is fairly large but its fixed by putting this in the `.cargo/config.toml`

```toml
[target.aarch64-apple-darwin]
linker = "rust-lld"
# NOTE: `rustdoc` doesn't currently respect the `linker` setting — keep an eye
# on this issue: https://github.com/rust-lang/rust/issues/125657
rustdocflags = ["-Clink-arg=-fuse-ld=lld"]

# NOTE: Also annoyingly, `target.<cfg>` doesn't let you set `rustdocflags`, so
# something like `[target.'cfg(target_os = "macos")']` doesn't work here and
# this repetition is needed...
[target.x86_64-apple-darwin]
linker = "rust-lld"
rustdocflags = ["-Clink-arg=-fuse-ld=lld"]
```

**Comment by bochaco** [comment]
I'm seeing this error when upgrading from `leptos_axum` from `v0.7.5` to `v0.7.7`.

**Comment by muja** [comment]
I had this error while not even using leptos. Thank you for the suggested fix, it helped.

From my last compilation and this, I added the following nightly features, maybe it's somehow related to those?

```
new_range_api, new_range, never_type, fn_traits, tuple_trait, unboxed_closures
```

Does leptops or any of the users use any of these, maybe it is related to one of them?

**Comment by hadronzoo** [comment]
I'm also seeing symbol names too long for the linker to handle on Leptos 0.8.0. [The fix suggested by @seanaye](https://github.com/leptos-rs/leptos/issues/3148#issuecomment-2564415437) resolved the issue.

**Comment by oiwn** [comment]
Issue still there! leptos (0.8)
