### ISSUE TITLE
generate_routes_with_exclusions() unregisters the server fn

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#3150]
Generally we want to exclude a route here if we want to manually create a route in the server router for it. This is useful for middlewares and other things that depend on the ordering of things in the router, and thus we don't want LeptosRoutes to auto generate a route for it.

Currently we're also unregistering the server fn, which confuses people and is not useful. We just want to exclude it from route generation

**Comment by gbj** [comment]
A test case for the incorrect behavior and what's inspected instead would be really helpful; I don't think there has been a test case for #2735 or this so it's tricky to know what the actual request is and whether it's being addressed.
