### ISSUE TITLE
Can't use multiple class names in `class=(class, signal)` syntax

### ISSUE THREAD

**Issue by AkinAguda** [leptos-rs/leptos#3151]
**Describe the bug**
I have issues trying to dynamically add multiple classes to an existing class based on a boolean signal

Here's how things went:

Note: green is the base class, red is a dynamically added class

1. These worked as expected:
<img width="462" alt="Screenshot 2024-10-23 at 13 43 24" src="https://github.com/user-attachments/assets/7504774f-013e-4356-af23-7aff15ee6858">
<img width="471" alt="Screenshot 2024-10-23 at 13 48 12" src="https://github.com/user-attachments/assets/b6387d29-4b76-4961-90eb-87587bc61c81">

These will add `bg-background-main` when `is_out_of_threshold` is true.

However, the problem comes in the next step

2. I now want to add more than just `bg-background-main` and want to add an extra `px-4` and we've got some issues

Adding `px-4` to my class string yields the following error in the browser console (it also does not work)
<img width="473" alt="Screenshot 2024-10-23 at 13 54 44" src="https://github.com/user-attachments/assets/319312b3-0b45-4dc7-8c22-4c82776d092c">
<img width="480" alt="Screenshot 2024-10-23 at 13 25 48" src="https://github.com/user-attachments/assets/ec43808e-6cb9-49a3-93ea-601be962e1b1">

With the array syntax [here](https://github.com/leptos-rs/leptos/pull/2532):
<img width="804" alt="Screenshot 2024-10-23 at 13 20 34" src="https://github.com/user-attachments/assets/dc387778-fa5a-4e1f-9584-4af8370fdc71">

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "0.7.0-gamma3", features = ["nightly"] }
leptos_meta = { version = "0.7.0-gamma3" }
leptos_actix = { version = "0.7.0-gamma3", optional = true }
leptos_router = { version = "0.7.0-gamma3", features = ["nightly"] }
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup the project
2. Paste the following sample component
```
use leptos::prelude::*;

#[component]
pub fn SampleComponent() -> impl IntoView {
    let boolean_signal = RwSignal::new(false);

    let on_click = move |_| boolean_signal.set(!boolean_signal.get());

    view! {
       <div class="bg-red-300" class=("text-black bg-green-300", boolean_signal)>
        <button on:click=on_click>Toggle</button>
       </div>
    }
}

```
**Expected behavior**
It should concatenate the entire class string without any issues

**Comment by gbj** [comment]
You are correct, you cannot do that.

This works fine:
`<div 
    class="bg-red-300"
    class:text-black=boolean_signal
    class:bg-green-300=boolean_signal
 >`
 This also works 
 `<div 
    class=move || if boolean_signal { 
       "bg-red-300 text-black bg-green-300"
    } else {
      "bg-red-300".into()
    }
 >`

I guess I broke the array syntax in 0.7, so I'll fix that.
