### ISSUE TITLE
`ServerFnError<T>` should impl `From<E: std::error::Error>` for any `T`

### ISSUE THREAD

**Issue by nicolas-guichard** [leptos-rs/leptos#3153]
[Currently](https://github.com/leptos-rs/leptos/blob/7b8cd90a6ef113495d0efc5fb8676bd0694a7705/server_fn/src/error.rs#L178), `ServerFnError` has a blanket `From` impl to convert from `E`, but only with the default `NoCustomError` type:
```
impl<E: std::error::Error> From<E> for ServerFnError {
    fn from(value: E) -> Self {
        ServerFnError::ServerError(value.to_string())
    }
}
```

This means we can't easily use `?` to convert other errors into a `ServerFnError<MyCustomError>`.

Instead I think we should provide a blanket impl for any `T`:
```
impl<T, E: std::error::Error> From<E> for ServerFnError<T> {
    fn from(value: E) -> Self {
        ServerFnError::ServerError(value.to_string())
    }
}
```

**Comment by gbj** [comment]
Feel free to make a PR.

**Comment by benwis** [comment]
That trait implementation interferes with the one in core, so Rust won't let that happen. I'm also not sure people want to convert their E into a String instead of using our WrappedError variant. Closing this as well.
