### ISSUE TITLE
`NoCustomError` should be replaced by `Infallible` (or another empty `enum`)

### ISSUE THREAD

**Issue by nicolas-guichard** [leptos-rs/leptos#3154]
When matching over a `ServerFnError`, we always have to cover the `WrappedServerError` case, even though it should not be used when `CustErr = NoCustomError`.

This happens because `NoCustomError` is an empty `struct`, which _can_ be constructed.

Instead I think we should use an empty `enum` such as `std::convert::Infallible`, which would:
* prevent from creating that variant altogether
* remove the need to match for that variant (since [Rust 1.82](https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html#omitting-empty-types-in-pattern-matching))

This would however be a breaking change.

**Comment by nicolas-guichard** [comment]
If/when this is implemented, we could provide an infallible conversion from `ServerFnError<NoCustomError>` to `ServerFnError<CustErr>`:
```rust
impl<CustErr> From<ServerFnError<NoCustomError>> for ServerFnError<CustErr> {
    fn from(value: ServerFnError<NoCustomError>) -> Self {
        match self {
            // not needed since Rust 1.82 if NoCustomError becomes uninhabited:
            // ServerFnError::<NoCustomError>::WrappedServerError(_) => unreachable!(),
            ServerFnError::<NoCustomError>::Registration(s) => ServerFnError::<CustErr>::Registration(s),
            ServerFnError::<NoCustomError>::Request(s) => ServerFnError::<CustErr>::Request(s),
            ServerFnError::<NoCustomError>::Response(s) => ServerFnError::<CustErr>::Response(s),
            ServerFnError::<NoCustomError>::ServerError(s) => ServerFnError::<CustErr>::ServerError(s),
            ServerFnError::<NoCustomError>::Deserialization(s) => ServerFnError::<CustErr>::Deserialization(s),
            ServerFnError::<NoCustomError>::Serialization(s) => ServerFnError::<CustErr>::Serialization(s),
            ServerFnError::<NoCustomError>::Args(s) => ServerFnError::<CustErr>::Args(s),
            ServerFnError::<NoCustomError>::MissingArg(s) => ServerFnError::<CustErr>::MissingArg(s),
        }
    }
}
```

Currently to enable the `?` operator, I parameterize the functions that return `ServerFnError` to take the `CustError` from their caller.

**Comment by gbj** [comment]
Could you provide an example of the problem you're trying to solve?

**Comment by nicolas-guichard** [comment]
For instance let's say I have a helper function like this:
```rust
pub fn auth() -> Result<AuthSession, ServerFnError> {
    use_context::<AuthSession>().ok_or_else(|| {
        ServerFnError::ServerError("Auth session missing.".into())
    })
}
```

I want to write this:
```rust
enum GetUsernameError {
    NotLoggedIn,
}

#[server]
pub async fn get_username() -> Result<Option<User>, ServerFnError<GetUsernameError>> {
    use crate::todo::ssr::auth;

    let auth = auth()?; // ← this currently fails, adding the From impl above solves that, and making NoCustomError uninhabited makes it infallible

    match auth.current_user {
        None => Err(GetUsernameError::NotLoggedIn.into()),
        Some(user) => Ok(user.name),
    }
}
```

If you don't have anything against those additions, I'll send PRs your way.

**Comment by benwis** [comment]
I understand this one, but expect it's not possible for us. If we replaced NoCustomError, which is an empty struct, with Infallible, we wouldn't be able to derive the traits we need for the orphan rule.

I'm going to close this, but if you can prove me wrong with a PR, that'd be grefat
