### ISSUE TITLE
Fallback is Not Shown on Transition Component

### ISSUE THREAD

**Issue by kmp1** [leptos-rs/leptos#3157]
**Describe the bug**
This is the same problem as described and fixed in issue #2123 a while ago. Essentially, it seems that, the transition component is not showing the fallback.

I don’t have anyother machine to try it on so I don’t know if this is macOS or Safari specific but I am using Safari version 18.0.1 on macOS Sequoia 15.0.1.

**Leptos Dependencies**

```toml
leptos = "0.6.15"
leptos_axum = { version = "0.6.15", optional = true }
leptos_router = "0.6.15"
```

**To Reproduce**

- Clone [https://github.com/lukasschlueter/leptos-transition-fallback-bug](https://github.com/lukasschlueter/leptos-transition-fallback-bug ), relevant code in [src/app.rs](https://github.com/lukasschlueter/leptos-transition-fallback-bug/blob/1d637fdc942dedd3a452c9b39be1ae4383984c1c/src/app.rs)
- Apply the patch file (which is just updating the dependencies) using `git am leptos-transition-fallback-bug/0001-Updated-the-dependendencies-including-the-Rust-compi.patch`: [0001-Updated-the-dependendencies-including-the-Rust-compi.patch](https://github.com/user-attachments/files/17509805/0001-Updated-the-dependendencies-including-the-Rust-compi.patch)
- Run `cargo update`
- Run `cargo leptos watch --release`
- Open a browser and navigate to [http://127.0.0.1:3000/](http://127.0.0.1:3000/)
- Click `Click here to load a buggy transition`
- Wait 2s on a blank screen
- "Success!" appears **but** the transition page was never shown

**Expected behavior**

I expected to see `Loading…!` during that 2 second transition time but I did not.

**Screenshots**

Here's a video showing the last 4 steps:

https://github.com/user-attachments/assets/b833cd39-ea27-49a8-97b3-621610e13776

**Additional context**
```
$ cargo --version
cargo 1.81.0 (2dbb1af80 2024-08-20)
$ rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)
```

**Comment by gbj** [comment]
If this issue is reproducible on 0.7/git main, I'm happy to fix it; unfortunately I do not have the capacity to work on bugfixes for 0.6 at this point.

**Comment by kmp1** [comment]
Oh, that would be great if you could have a look because it does still happen with `git main`.  

Thank you so much for this, by the way, I'm really loving using Leptos!

Anyway, here's a second patch to update the example to work with `main`:

[0002-Updated-to-the-git-main-branch-version-of-Leptos.patch](https://github.com/user-attachments/files/17517409/0002-Updated-to-the-git-main-branch-version-of-Leptos.patch)

So now the steps to reproduce are:

```
$ git clone https://github.com/lukasschlueter/leptos-transition-fallback-bug.git
$ cd leptos-transition-fallback-bug
$ git am 0001-Updated-the-dependendencies-including-the-Rust-compi.patch
$ git am 0002-Updated-to-the-git-main-branch-version-of-Leptos.patch
$ cargo update
$ cargo leptos watch --release
```

Then go to [http://127.0.0.1:3000/](http://127.0.0.1:3000/) and click the link and observe the behaviour.

**Comment by kmp1** [comment]
I tried this with Google Chrome (version `130.0.6723.70`) and there is does work so it seems like this is a `Safari` specific issue...

https://github.com/user-attachments/assets/d0f42ece-3b8d-48a3-859a-9902af58a6b2

**Comment by gbj** [comment]
The issue in this case is rather different; namely, that the 0.7 example is only partially migrated.

It's missing the following changes:
1) from `mount_to_body` to `hydrate_body` in `lib.rs`
2) adding an appropriate `shell` function that includes `HydrationScripts` in the `lib.rs`
3) using `shell` rather than only `App` in the `leptos_routes()` function

The behavior being shown in the videos is that of an unhydrated page, doing full page reloads. Safari, Chrome, and Firefox are all demonstrating slightly different responses to fetching a streaming request from the server in an ordinary navigation, each of which is valid. 

I made the corrections above and tested in all three browsers; the transition works as expected in each case.

Thanks for raising the issue, though!

**Comment by kmp1** [comment]
Thank you for your efforts here! Would it be possible for you to attach the patch you made? Or point me at the docs for the shell function you mentioned as I guess I will need to re- design my real app a bit.

**Comment by gbj** [comment]
Take a look at the [release notes](https://github.com/leptos-rs/leptos/releases/tag/v0.7.0-rc0) and/or any of the SSR examples
