### ISSUE TITLE
Remove `error!`, etc macros from prelude

### ISSUE THREAD

**Issue by spencewenski** [leptos-rs/leptos#3166]
**Is your feature request related to a problem? Please describe.**
I use the `tracing` crate, which provides `error!`, etc macros for logging/tracing. If I import `leptos::prelude::*`, the `error!`, etc macros from leptos conflict with those from the `tracing` crate.

**Describe the solution you'd like**
I'd prefer if Leptos did not provide the `error!` macros in the `prelude` and instead allow consumers to decide how they want to emit logs/traces. Would this be possible? Is there a particular reason it needs to be in the prelude?

**Describe alternatives you've considered**
The alternative is not importing everything from the prelude using `leptos::prelude::*` and instead importing things individually. This kind of defeats the purpose of the prelude, though.

**Additional context**

**Comment by gbj** [comment]
We're talking about the `logging::error!()` macro etc., right? These are not intended to be reexported from the prelude, thanks for noticing this. 

I think #3168 should resolve this; they're supposed to be exported as `leptos::logging` instead.

**Comment by spencewenski** [comment]
Sweet, thanks for the quick fix! :tada:
