### ISSUE TITLE
leptos-router,  crates.io, missing README.md

### ISSUE THREAD

**Issue by martinfrances107** [leptos-rs/leptos#317]
This is a minor DX issue

I just thought you should know the leptos-router pages is looking a little bare 

[This page ](https://crates.io/crates/leptos_router)

Your solution to this problem in leptos/leptos/Cargo.toml is to add this line to the [package] block 

```
readme = "../README.md"
```

It is also missing in a few other crates lepto-config, but I have not done an extensive search.

Anyway love the project ....

**Comment by gbj** [comment]
Thanks! For my future self, or for anyone who wants easy credit for a PR: the `leptos_router` Readme should ideally be basically the same as the [module-level doc comment](https://github.com/leptos-rs/leptos/blob/61ca6465dfd390b4184e215c904731c1c0d2d013/router/src/lib.rs#L3-L182), and the ones for `leptos_core`, `leptos_reactive`, `leptos_dom`, `leptos_server`, and `leptos_macro` (did I miss any?) should be the same as the main Readme.

**Comment by martinfrances107** [comment]
I will create a PR.... development is so rapid,at the moment, and the issue so minor  -  I assumed it would be rolled in with the torrent  ....one sec.

**Comment by martinfrances107** [comment]
#328
