### ISSUE TITLE
[0.7] leptos_router no longer exports `unescape`

### ISSUE THREAD

**Issue by wrl** [leptos-rs/leptos#3177]
`leptos_router::escape` seems to have moved to `leptos_router::location::Url::escape`, but `leptos::router_unescape` does not appear to have a corollary. Is this intentional?

**Comment by gbj** [comment]
I would have considered these all to be internal utilities; I see that they're exported publicly in 0.6 but not documented at all.

Fair enough to find them useful, though... I can just reexport `unescape` and `unescape_minimal` namespaced in the same way as `escape` (so, `Url::unescape()`). See #3179.
