### ISSUE TITLE
Resource subscribed to a Memo has inconsistent fetching behaviour depending on whether it's hydrated or not

### ISSUE THREAD

**Issue by wrl** [leptos-rs/leptos#3181]
1. Start with the axum-0.7 starter
2. You will need to add this line to `Cargo.toml`:
    ```toml
    getrandom = { version = "0.2", features = ["js"] }
    ```
3. [Use this `app.rs`](https://github.com/user-attachments/files/17600485/app.rs.txt)

To test the non-hydrated case:
1. Navigate to `localhost:3000`.
2. Click the "counter" link.
3. Click the counter button. It should behave as expected, and only one `resource fetching with param_dep=Some(())` message will be displayed in the console.

To test the hydrated case:
1. Navigate to `localhost:3000/count`
2. Click the counter button. Note that the number remains "0" and a duplicate `resource fetching with param_dep=Some(())` has been logged to the console.
3. After this, the button will work as expected.

The resource depends on a Memo which depends on a Params struct. Though the URL changes (deliberately) every time the button is clicked, the Memo does not, and thus I would assume the Resource would not re-fetch.

**Comment by gbj** [comment]
Note to self, here's a much more minimal repro, which causes the same issue in hydrate or csr mode:
```rust
#[component]
pub fn App() -> impl IntoView {
    let count = RwSignal::new(0);
    let memo = Memo::new(move |_| {
        count.track();
        // returns () always
    });
    Effect::new(move |_| {
        leptos::logging::log!("memo = {:?}", memo.get());
    });

    view! {
        <button on:click=move |_| *count.write() += 1>Click</button>
    }
}
```

**Comment by gbj** [comment]
These are actually variants on the same issue (not triggering chained memos to check themselves early enough), here's  good reproduction for resources
```rust
use leptos::prelude::*;
use leptos_meta::{provide_meta_context, MetaTags, Stylesheet, Title};
use leptos_router::{
    components::{Route, Router, Routes, A},
    hooks::{use_navigate, use_params},
    params::Params,
    StaticSegment, WildcardSegment,
};

pub fn shell(options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <AutoReload options=options.clone() />
                <HydrationScripts options/>
                <MetaTags/>
            </head>
            <body>
                <App/>
            </body>
        </html>
    }
}

#[component]
pub fn App() -> impl IntoView {
    let counter = RwSignal::new(0);

    let param_dep = Memo::new(move |_| {
        counter.track();
        Some(())
    });

    let res = Resource::new(
        move || param_dep.get(),
        |param_dep| {
            leptos::logging::log!(
                "resource fetching with param_dep={:?}",
                param_dep
            );
            hello()
        },
    );

    view! {
        <button on:click=move |_| *counter.write() += 1>Click</button>
    }
}

#[server]
async fn hello() -> Result<(), ServerFnError> {
    Ok(())
}
```
