### ISSUE TITLE
built-in `Image` element for image optimisation

### ISSUE THREAD

**Issue by yuhime** [leptos-rs/leptos#3184]
it would be great to have something built-in that deals with image optimisation, similar to nextjs
```jsx
export default function Page() {
  return (
    <Image
      src={profilePic}
      alt="author image’
      // width={500} provided automatically
      // height={500} provided automatically
      // blurDataURL=‘data:...’ provided automatically
      // placeholder=‘blur’ // optional blur when uploading
    />
  )
}
```
Image also takes care of providing the images (png, jpg, ...) always in WebP or AVIF

Here are the strengths of this approach:
- Size optimisation: Automatically provides images of the correct size for each device, using modern image formats such as WebP and AVIF.
- Visual stability: Automatically prevents the layout from shifting when loading images.
- Faster page loading: Images are only loaded when they enter the viewport thanks to the browser's native lazy loading, with optional blur markers.
- Resource flexibility: Image resizing on demand, even for images stored on remote servers.

**Comment by gbj** [comment]
I consider this out of scope for the core of the library itself, but you can take a look at a library like [`leptos-image`](https://github.com/gaucho-labs/leptos-image) to see how this  can be done.
