### ISSUE TITLE
Contexts affecting each other outside of component-tree

### ISSUE THREAD

**Issue by reedwoodruff** [leptos-rs/leptos#3205]
**Describe the bug**
When you have two contexts of the same type within an app and certain conditions are met, the contexts behave unexpectedly.
Changing one context will update a separate tree's context but not its own. Or, more accurately, one of the contexts receives all of the updates and none of the others can change themselves.

The key factor in reproducing seems to be having an intermediate layer accessing the context as well as a leaf, or at least I can't seem to reproduce the issue if I'm only consuming the context in one leaf of the providing context-tree. The example shows what I mean.

**Leptos Dependencies**
Main branch 0.7 with only CSR.

leptos = { git = "https://github.com/leptos-rs/leptos", branch = "main", features = [
    "csr",
] }

**To Reproduce**
Here is a minimal reproduction which can be pasted into `main.rs`

```rust
fn main() {
    leptos::mount::mount_to_body(|| {
        view! {
            <RootComponent />
        }
    });
}

#[derive(Clone)]
pub struct IsolatedContext {
    pub toggled: RwSignal<bool>,
}
#[component]
pub fn RootComponent() -> impl IntoView {
    view! {
        <IsolatedContextSection />
        <IsolatedContextSection />
        <IsolatedContextSection />
        <IsolatedContextSection />
    }
}
#[component]
pub fn IsolatedContextSection() -> impl IntoView {
    provide_context(IsolatedContext {
        toggled: RwSignal::new(true),
    });
    view! {
        <NestedConsumer />
    }
}
#[component]
pub fn NestedConsumer() -> impl IntoView {
    let ctx = use_context::<IsolatedContext>().unwrap();
    let matched_view = move || {
        let is_toggled = ctx.toggled.get();
        match is_toggled {
            false => Either::Left(view! {<Sad />}),
            true => Either::Right(view! {<Happy />}),
            // false => view! {<Sad />}.into_any(),
            // true => view! {<Happy />}.into_any(),
        }
    };
    view! {
        <div>
        {matched_view}
        // <Show when=move || ctx.toggled.get()>
        // <Happy/>
        // </Show>
        // <Show when=move || !ctx.toggled.get()>
        // <Sad/>
        // </Show>
        </div>
    }
}
#[component]
pub fn Sad() -> impl IntoView {
    let ctx = use_context::<IsolatedContext>().unwrap();

    view! {
        <div style="color: red">":("</div>
        <button
               on:click=move |_| ctx.toggled.update(|value| *value = !*value)
           >
               "Toggle"
           </button>
    }
}
#[component]
pub fn Happy() -> impl IntoView {
    let ctx = use_context::<IsolatedContext>().unwrap();

    view! {
        <div style="color: blue">":)"</div>
        <button
               on:click=move |_| ctx.toggled.update(|value| *value = !*value)
           >
               "Toggle"
           </button>
    }
}
```

**Expected behavior**
I expected each context-tree to be independent and respond to changes in child nodes of the context-tree

**Screenshots**
![context_bug_reproduction](https://github.com/user-attachments/assets/683d74be-b4d6-40cd-8557-01ad9b028f52)

**Additional context**
At first I thought it was a bug with the `Either` component, but I've tried `into_any` and the `Show` component and they display the same behavior, so I'm not sure what it is. I also tried making the `matched_view` into a `Memo` but also no dice. It's possible I'm overlooking something here but I've tried the things I can think of.

**Comment by reedwoodruff** [comment]
P.S. Awesome work on 0.7! Lots of great changes, but I'm especially excited to have the reactive system decoupled :+1:. Thanks for sharing your efforts.

**Comment by gbj** [comment]
This is true and is why the [`Provider`](https://docs.rs/leptos/0.7.0-gamma2/leptos/context/fn.Provider.html) component exists -- to avoid issues with "context shadowing." I have not tried it out but rewriting your `IsolatedContextSection` to use `Provider` instead of `provide_context` should work.

**Comment by reedwoodruff** [comment]
Ah! That explains it, thanks 👍
