### ISSUE TITLE
`attr:data-` doesn't get applied on components

### ISSUE THREAD

**Issue by tqwewe** [leptos-rs/leptos#3211]
**Describe the bug**
Data attributes applied to components with `attr:data-` are silently ignored and not applied to the html. Other attributes seem to work such as `attr:draggable="true"`, but data attributes do not.

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = { version = "=0.7.0-rc1", features = ["csr"] }
```

**To Reproduce**
```rust
#[component]
fn App() -> impl IntoView {
    view! {
        <Counter
            attr:draggable="true" // Works
            attr:data-foo="bar" // Doesn't get applied to html
        />
    }
}

#[component]
fn Counter() -> impl IntoView {
    view! {
        <div>"Hi</div>
    }
}
```

Running `cargo expand` on this shows that the data attribute is not included in the builder code at all:
```rust
.add_any_attr(
     ::leptos::tachys::html::attribute::draggable("true"),
)
```

**Expected behavior**
All attributes prefixed with `attr:` should be correctly forwarded to the root html element of the component.

**Additional context**
Not sure if this is intended, but `node_ref` doesn't seem to be valid on components either. I initially planned to add a `node_ref` to the component so I could set the data attribute in an effect, however this also was not possible as `node_ref` is interpreted as a component prop.

**Comment by gbj** [comment]
Closed by #3214 but I typed the number of this issue wrong, there.

That addresses the issue but I had not read the point about `node_ref` in the additional context, so I guess I can leave this open to work on that part.

**Comment by gbj** [comment]
Actually the `node_ref` one is significantly trickier since node refs are typed, while the return types of components are typically opaque (`-> IntoView`). And adding attributes to components is also intended to work with components that return multiple top-level elements, but it's not clear what a `NodeRef` should do in that case.

For use cases when you do actually want to pass a `NodeRef` to a component (rather than just as a debugging mechanism) I'd recommend an actual `node_ref` prop with the correct type.

**Comment by tqwewe** [comment]
Could the NodeRef for components in cases like these just be very generic, such as `NodeRef<leptos::html::HtmlElement>` for example?

**Comment by gbj** [comment]
Sure but the second half of the issue remains: components can return multiple top-level elements (`view! { <p>foo</p><p>bar</p> }`), and it's not at all obvious which one of those should go into the `NodeRef`! Every other attribute will just add the attribute to each of those elements; I think `NodeRef` is a case where explicitness is much better, and where the component *author* not the component *user* needs to decide how to handle that one.
