### ISSUE TITLE
Dead link on the main README about the gtk example

### ISSUE THREAD

**Issue by frjol** [leptos-rs/leptos#3215]
**Describe the bug**
Dead link on the main README about the gtk example
In the native UI section about the gtk example, the link is pointing to an example that's not present on the repo. At least I could not find it and the link is dead.

https://github.com/leptos-rs/leptos?tab=readme-ov-file#can-i-use-this-for-native-gui

**Expected behavior**
An example present or no reference to a dead link.

**Additional context**
Here's the link to the missing gtk example https://github.com/leptos-rs/leptos/blob/main/examples/gtk/src/main.rs

**Comment by gbj** [comment]
Oh yeah, that's a really sad story that involves the Rust compiler not quite being able to handle my massive abuse of generics.
