### ISSUE TITLE
Impossible to Provide fallback to Leptos Router

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#322]
It appears the type signature of the fallback method makes it impossible to provide one to leptos_router.
From Jose:
If you see the docs for RouterProps, fallback takes fn() -> View as a type, which means you cannot pass in an environment-capturing closure...in other words, fallback is broken as is because there's no way to return a View without using Scope to create it...and since there is no Scope, no dice.

**Comment by gbj** [comment]
Oh shoot this used to be possible in 0.0. I get the problem...

**Comment by benwis** [comment]
Well, the PR fixes this issue, but it looks like the fallback is never actually rendered regardless, more details in the Discord.
