### ISSUE TITLE
[0.7] panic in static_routing example

### ISSUE THREAD

**Issue by NiklasEi** [leptos-rs/leptos#3224]
**Describe the bug**
When running the `static_routing` example with `cargo leptos watch` it panics with "using static routing, but couldn't find ParamsMap" at `leptos/router/src/static_routes.rs:334:30`

**Leptos Dependencies**

I pulled latest main bb0dff6af57b491ab7372ffd6833024742c7f186 so everything is at `0.7.0-rc1`

**To Reproduce**
1. Navigate to examples/static_routing in your terminal
2. Execute `cargo leptos watch`

**Expected behavior**
The example should start and host the expected pages

**Additional context**
The code path only gets hit when using `regenerate` on the static routes.

**Comment by gbj** [comment]
Same cause as #3226, see #3228. Thanks for noticing this.
