### ISSUE TITLE
[0.7] routing in islands_router is broken in firefox

### ISSUE THREAD

**Issue by NiklasEi** [leptos-rs/leptos#3225]
**Describe the bug**
The routing script in the `islands_router` example fails in Firefox, because it uses `startViewTransition` (see https://caniuse.com/?search=startViewTransition)

**Leptos Dependencies**

Main branch on bb0dff6af57b491ab7372ffd6833024742c7f186 (latest 0.7.0-rc1)

**To Reproduce**
1. Go to the `islands_router` example
2. Execute `cargo leptos serve`
3. Open the page in Firefox and try to use the navigation links

**Expected behavior**
The navigation works

**Comment by benwis** [comment]
Good to know, islands_router is setup to test the very experimental and not at all ready client side islands routing setup, so I am not surprised it fails

**Comment by gbj** [comment]
Any interest in making a PR? I'm fairly comfortable with the ["this is experimental"](https://github.com/leptos-rs/leptos/tree/main/examples/islands_router#readme) statement in the README.
