### ISSUE TITLE
[0.7] static site generation only generates fallback pages

### ISSUE THREAD

**Issue by NiklasEi** [leptos-rs/leptos#3226]
**Describe the bug**
The `static_routing` example generates a static site containing only the fallback pages saying "Page not found." for all blog entries.

**Leptos Dependencies**

Latest main f804a69f2f5bfc2c7580e564730c2dd6878f7257 

**To Reproduce**
1. Navigate to the `static_routing` examples
2. (fix) remove the two `regenerate` calls in the router to get around #3224
3. Run `cargo leptos serve`
4. Check the static site output in `target/site`
    * The pages under "post/post<x>/index.html" are all there, but only contain "Page not found.", not the actual post contents

**Expected behavior**
The build output should contain the same content you get when opening the paths while the server is running.

**Additional context**
The content is correct if we keep the server running and visit the posts in the browser. But, in my opinion, this is not the expected behaviour for a static route. The full content should already be written to the output before any call to the server.

**Comment by gbj** [comment]
Same cause as #3224, see #3228.
