### ISSUE TITLE
[0.7] Server Panic: `leptos_routes_with_context` does not provide context reliably for all routes

### ISSUE THREAD

**Issue by seanaye** [leptos-rs/leptos#3242]
**Describe the bug**
Certain routing conditions cause the `additional_context` callback to be skipped when performing server rendering, resulting in a state where the server fns do not have access to the server side context

**Leptos Dependencies**
```
leptos = { version = "0.7.0-rc1", features = [
  "nightly",
  "experimental-islands",
] }
leptos_meta = { version = "=0.7.0-rc1" }
leptos_router = { version = "=0.7.0-rc1", features = ["nightly"] }
leptos_axum = { version = "=0.7.0-rc1" }
```

**To Reproduce**

See readme in [this repo](https://github.com/seanaye/leptos-repro)

**Expected behavior**
Server should reliably call the additional_context closure for each incoming request

**Screenshots**
N/A

**Additional context**
Initially reported in discord [here](https://discord.com/channels/1031524867910148188/1234308989970550834/1303540441773248593)

**Comment by gbj** [comment]
Note to self -- min repro:
```rust
#[component]
pub fn App() -> impl IntoView {
    view! {
        <Stylesheet id="leptos" href="/pkg/tinyrs.css" />
        <AppRoutes />
    }
}

#[component]
fn AppRoutes() -> impl IntoView {
    #[server]
    async fn load_user_session() -> Result<u8, ServerFnError> {
        let val = expect_context::<u8>();
        Ok(val)
    }

    let res = Resource::new(|| (), |_| load_user_session());

    view! {
        <div/>
        <Suspense>{move || res.get()}</Suspense>
    }
}
```

Can toggle the panic on and off by removing the `<Stylesheet/>`. Seems to have to do with ownership when injecting metadata stream.

**Comment by benwis** [comment]
I was looking at this last night and it's the weirdest thing

**Comment by gbj** [comment]
@seanaye In my minimal reproduction, I was able to narrow it down to the fact that the server function was being called twice, and the second time the context was failing.

I realized that this is because the stylesheet name I was using (copy-pasted from the example) returned a 404 response. When the default `file_and_error_handler` is called, if it hits a 404 for a static asset it renders the App page instead. The main App page in your case calls the server function, but it does not have the additional context -- hence the panic.

**Comment by gbj** [comment]
(This is actually quite an important point: Starting data loading outside/before the router sets up a situation in which every single random 404 loads data unnecessarily. Whereas starting the data loading inside the first nested route would mean that it only began loading if a route had actually been matched.)

**Comment by seanaye** [comment]
@gbj Interesting, thanks for looking into this. That's good to know. What would be the recommended approach for fetching data thats required for routing then? Such as redirects for authed routes? It sound like loading data above the Router level is not ideal

**Comment by gbj** [comment]
I guess there are several different options:
1) Load data above the route level, but don't panic if the context isn't available, just return some sensible error or default
2) Replace the default file/error-handler with a custom one that provides the context you need
3) Load the data inside a top-level `ParentRoute` that matches everything (so, `path!("/")`) and nest your other routes inside it

**Comment by seanaye** [comment]
@gbj wouldnt option 3 not really solve the problem because the router would try to run things inside the top level ParentRoute? Which would cause the same problem. Or would the app not try to enter the top level parent route

**Comment by seanaye** [comment]
Or is the Router "aware" of what it contains so it won't try to run the server fn if it knows in advance that it doesn't contain that route

**Comment by benwis** [comment]
> Or is the Router "aware" of what it contains so it won't try to run the server fn if it knows in advance that it doesn't contain that route

When the trait .leptos_routes() runs, it generates routes only for paths that are used by either Leptos routes or server fns.

3. would work here because if you fetch the data inside the App component it's rendering for the 404 page from the missing stylesheet, then it'll not panic the second time

**Comment by gbj** [comment]
> Or is the Router "aware" of what it contains so it won't try to run the server fn if it knows in advance that it doesn't contain that route

Correct, if none of the possible route combinations match, then the parent Route's view won't run (nor will any of the others), it will just show the fallback.
