### ISSUE TITLE
Store within Signal causes panic

### ISSUE THREAD

**Issue by tqwewe** [leptos-rs/leptos#3243]
**Describe the bug**
When using a store which is in a `RwSignal`, a panic occurs whilst used within a Suspense.

```
you tried to access a reactive value, but it has already been disposed.
```

I'm aware that it might be a better approach to simply make a struct with a single `Option<T>` field for the store, so I don't need to use `RwSignal<Option<Store<T>>>`, however I'm unclear if having a store within a signal is meant to be supported and I've encountered a bug, or if I'm doing something Leptos isn't supposed to support.

**Leptos Dependencies**

```toml
leptos = { version = "0.7.0-rc1", features = ["csr"] }
reactive_stores = "0.1.0-rc1"
```

**To Reproduce**
Smallest reproducable project I could make. Clicking the button twice causes an error in the console.
```rust
#![allow(non_snake_case)]

use leptos::prelude::*;
use reactive_stores::Store;

fn main() {
    console_error_panic_hook::set_once(); // Better debugging
    mount_to_body(App);
}

#[derive(Clone, Debug, Store)]
struct AppState {
    num: f32,
}

#[derive(Clone, Copy, Debug)]
struct AppStateContext {
    app_state: RwSignal<Option<Store<AppState>>>,
}

#[component]
fn App() -> impl IntoView {
    let app_state = RwSignal::new(None);
    provide_context(AppStateContext { app_state });

    view! {
        <ThingThatUpdatesStore num=1.5 />
        {move || {
            app_state
                .get()
                .map(|app_state| {
                    view! { <ThingThatLoads app_state /> }
                })
        }}
    }
}

#[component]
fn ThingThatUpdatesStore(#[prop(into)] num: Signal<f32>) -> impl IntoView {
    let AppStateContext { app_state } = expect_context();
    let set_focused = move || {
        let new_app_state = AppState {
            num: num.get_untracked(),
        };
        app_state.update(|app_state| match app_state {
            Some(app_state) => app_state.set(new_app_state),
            None => *app_state = Some(Store::new(new_app_state)),
        });
    };

    view! {
        <div>
            <button on:click=move |_| set_focused()>"Select this"</button>
            <p>{num}</p>
        </div>
    }
}

#[component]
fn ThingThatLoads(#[prop(into)] app_state: Store<AppState>) -> impl IntoView {
    let num = Signal::derive(move || app_state.num().get());

    view! {
        <Suspense
            fallback=move || view! {
                <DisplayNumber value=Signal::derive(move || num.get()) />
            }
        >
            "Hi"
        </Suspense>
    }
}

#[component]
fn DisplayNumber(#[prop(into)] value: Signal<f32>) -> impl IntoView {
    let class = RwSignal::new("");

    Effect::watch(
        move || value.get(),
        move |_, _, _| {
            class.set("");
        },
        false,
    );

    view! {
        <span class=class />
    }
}
```

**Expected behavior**
Stores nested within a `RwSignal` should be supported without panicking as seen in the example.

**Additional context**
Discord help thread: https://discord.com/channels/1031524867910148188/1306585792835092480

**Comment by gbj** [comment]
It isn't intended to be supported, although I can't say I've ever thought of it before this issue.

**Comment by tqwewe** [comment]
The biggest concern with the approach of having a struct with a single `Option<T>` field, is that does it mean I'll need to null check it every time I want to access a field to make a derived signal for example?
```rust
#[derive(Store)]
struct MaybeAppState {
    app_state: Option<AppState>
}

#[derive(Store)]
struct AppState {
    foo: String,
    bar: String,
    baz: String,
}

let store: Store<MaybeAppState> = ...;

let derived_foo = Signal::derive(move || store.app_state().map(|app_state| format!("{} ...", app_state.foo().get()).unwrap_or(String::new()));
let derived_bar = // Also need to do the whole null checking?
let derived_baz = // Also need to do the whole null checking again?
```
Or can I pass the `Subfield` returned from `store.app_state().unwrap()`? But `store.app_state().unwrap()` actually wouldn't even return a reactive `AppState`.. idk I'm getting confused, but it seems like doing the whole `Option<T>` in the store itself is quite a headache.

Can you suggest a better solution?

**Comment by gbj** [comment]
Presumably in most cases there's some view that you want to display if `app_state` is `Some(_)`, and something else you can display if there's literally *no* app state. In which case you can just

```rust
#[component]
pub fn App() -> impl IntoView {
    let store = Store::new(MaybeAppState { app_state: None });

    move || {
        store.app_state().map(|app_state| {
            view! { <AppWithState app_state/> }
        })
    }
}

#[component]
pub fn AppWithState(#[prop(into)] app_state: Field<AppState>) -> impl IntoView {
    todo!()
}
```
perhaps with an appopriate fallback.

Then you can do whatever you want with context and so on.

> Can you suggest a better solution?

Perhaps this is just too abstracted and it does make sense in your context; I can't really imagine a situation in which it makes sense for the state of the entire app to be an `Option<_>` rather than having default fields of some kind, which wouldn't be covered by the above. I'm not sure.

But it seems to me that what I gave above gets you basically the same thing as the `RwSignal<Option<Store<_>>>`.

**Comment by tqwewe** [comment]
Ah okay in your example you're passing `Field<AppState>` as a prop which I guess pretty much solves my issue. I wasn't sure if this was good or bad.

> I can't really imagine a situation in which it makes sense for the state of the entire app to be an Option<_> rather than having default fields of some kind

I made my example about `AppState`, which is quite broad. In my real project, the `Store` being used is `FocusedEdgeBet`, which when set has a drawer panel open on the page with some reactive fields displayed. And any part of the app can change the current `FocusedEdgeBet`. Then when the drawer popup is closed, the focused edge bet becomes `None`.

**Comment by gbj** [comment]
> Ah okay in your example you're passing `Field<AppState>` as a prop which I guess pretty much solves my issue. 

Oh yeah I'd say this is good: It lets you narrow how much any component knows or needs to know about the overall state, which also means you're limiting what it can modify or not.

> In your example, `store.app_state().map(...)` isn’t directly available, as `app_state()` actually returns a `Subfield<...>`

Oh sorry, `.map()` here is actually from `reactive_stores::OptionStoreExt` which implements `.map()` on any `Option<_>` store field. `.map()` should
1) track the `app_state` field
2) rerun the outer closure when it changes from `Some(_)` to `None`
3) in the `Some(_)` case, give you access to the inner field

**Comment by tqwewe** [comment]
Thank @gbj! Passing `Field<T>`, along with the `OptionStoreExt` looks like the missing pieces I needed
