### ISSUE TITLE
[0.7] Polling SendWrapper<T> variable from a thread different to the one it has been created with

### ISSUE THREAD

**Issue by Nutomic** [leptos-rs/leptos#3258]
**Describe the bug**
After updating my existing project from Leptos 0.6.15 to 0.7.0-rc1 I get the error mentioned above from all reqwest api calls in resources, even if the resources are unused.

```
[INFO  ibis::backend] Listening on 127.0.0.1:3000
thread 'tokio-runtime-worker' panicked at src/frontend/app.rs:69:77:
Polling SendWrapper<T> variable from a thread different to the one it has been created with.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at src/frontend/app.rs:70:77:
Polling SendWrapper<T> variable from a thread different to the one it has been created with.
thread 'tokio-runtime-worker' panicked at src/frontend/app.rs:71:77:
```

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
leptos = "0.7.0-rc1"
leptos_meta = "0.7.0-rc1"
leptos_router = "0.7.0-rc1"
leptos_axum = { version = "0.7.0-rc1", optional = true }
```

**To Reproduce**
I tried to create a minimal reproduction from one of the examples, but there the problem didnt happen at all. So you will have to clone my full project and run it:
1. `git clone https://github.com/Nutomic/ibis.git`
2. `git checkout leptos-0.7`
3. `cargo leptos run`
4. Open http://127.0.0.1:3000/
5. See errors in terminal

**Expected behavior**
No errors (or clearer error message if there really is a problem)

**Additional context**

The code seems pretty simple, basically just this:
```
impl ApiClient {
    pub fn site(&self) -> impl Future<Output = MyResult<SiteView>> + Send + '_ {
        SendWrapper::new(async move {
            let req = self.client.get(self.request_endpoint("/api/v1/site"));
            handle_json_res(req).await
        })
    }
}

pub fn App() -> impl IntoView {
    let site_resource = Resource::new(|| (), |_| async move { CLIENT.site().await.unwrap() });
    ...
}
```

**Comment by gbj** [comment]
A couple clarifying questions so I can give a useful answer:

1. Why are you using a SendWrapper here?
2. Do you understand why this gets sent to a different thread?
3. Do you understand why dropping a SendWrapper from a different thread panics?

**Comment by gbj** [comment]
There is no `leptos-0.7` branch in the repo you linked.

**Comment by Nutomic** [comment]
Sorry I forgot to push the branch, now its there. 

With Leptos 0.6 I used normal `async fn`, but after upgrading to 0.7 that started throwing compile errors ("future created by async block is not `Send`"), so based on the examples I added SendWrapper. I didnt have to use that crate before so I dont understand it well. I dont know why or where it gets sent to a different thread. Note that the error is about *polling* SendWrapper, not dropping it.

**Comment by Nutomic** [comment]
Thanks for the explanation. Then what I should have asked is, why did reqwest simply work in 0.6 with normal `async fn` and no `SendWrapper`? Only after upgrading to 0.7 did it start to throw compile errors about "future is not Send". 

For me it would be much preferable to use the [same api code as before](https://github.com/Nutomic/ibis/blob/master/src/frontend/api.rs), with no `SendWrapper` nor using a separate http client for the frontend. That way its easier to maintain, and binary size is not much of a concern.

**Comment by gbj** [comment]
Because the previous reactive system pinned everything to a single thread, so it pretended that the Send/Sync traits did not matter, which forced us to override the behavior of Axum by forcing it to also pin its request/response cycle to a single thread.
