### ISSUE TITLE
Support `fallback` or `loading_view` prop in `ProtectedRoute`

### ISSUE THREAD

**Issue by tqwewe** [leptos-rs/leptos#3263]
**Is your feature request related to a problem? Please describe.**
The new ProtectedRoute using transition behind the scenes is great. However there doesn't seem to be a way for users to customize the fallback view for when the condition is still being resolved asynchronously.

**Describe the solution you'd like**
The `ProtectedRoute` component should have an optional prop for allowing a view to be rendered while the condition is loading. This allows for nice loading screens etc.

**Comment by gbj** [comment]
Should be a 1-2 line change to add a fallback and pass it through to the Transition -- Are you interested in making a PR?

**Comment by tqwewe** [comment]
Yep sure! I'm a little confused about what to name the new prop. `fallback` in the `Routes` component means the view to render if the route isn't matched. Are we fine to use then name `fallback` in the `ProtectedRoute` for the transition fallback?
