### ISSUE TITLE
Normalize Either Discriminants

### ISSUE THREAD

**Issue by reedwoodruff** [leptos-rs/leptos#3271]
**Is your feature request related to a problem? Please describe.**
Sometimes I'm not sure how many branches of an Either statement I'll need, and when I start with plain `Either`, and subsequently change to `EitherOf3`, I have to change the braches from `Left` and `Right` to `A` and `B`. 

**Describe the solution you'd like**
Not a huge deal but it might be a little ergonomic boost to make `Either`'s discriminants follow the same `A`, `B`  pattern as the other versions. I figure if it's going to change, it would be best before 0.7 is released.

I'd be happy to make a PR for this if it's a good idea and there aren't other considerations I'm missing.
Thanks!

**Comment by benwis** [comment]
I think that makes sense, feel free to PR it

**Comment by gbj** [comment]
I would prefer not breaking everything that's using `Left` and `Right` but I guess feel free to add an `EitherOf2` or something. Also see the `either` macro that will add them for you automatically.

**Comment by reedwoodruff** [comment]
> I would prefer not breaking everything that's using `Left` and `Right` but I guess feel free to add an `EitherOf2` or something. Also see the `either` macro that will add them for you automatically.

Ok, I'm fine with letting this lie :+1:
