### ISSUE TITLE
Allow the class attribute to take variables

### ISSUE THREAD

**Issue by svieujot** [leptos-rs/leptos#3292]
If you use stylance, the class names are variables, like in:

```
stylance::import_style!(css, "my_button.module.css");

view {
    <button class=css:red>...</button>
}
```

To make this dynamic, you can use :
```
    <button class=("red", move || count() % 2 == 1>)> ... </button>
```

But this syntax does not work with the view macro:
```
    <button class=(css::red, move || count() % 2 == 1>)> ... </button>
```
generates the following error: `error: class name must be a string literal or array of string literals`

This is with Leptos 0.6. I did not try it with Leptos 0.7.

**Comment by gbj** [comment]
> This is with Leptos 0.6. I did not try it with Leptos 0.7.

This does, in fact, already work on 0.7 but can't be done in 0.6, so I'm going to close this issue as completed. 0.7 has had a few release candidates and I'm planning on a stable release at the end of this week.
