### ISSUE TITLE
Streamed data is concatenated into a single string on the client side

### ISSUE THREAD

**Issue by anhelinakruk** [leptos-rs/leptos#3314]
**Describe the bug**
We have a vector, for example, [1, 2, 3]. This vector is converted into a stream using stream::unfold. On the server side, each item is processed and emitted sequentially. The server logs confirm that the items are sent one by one (1, 2, 3). However, on the frontend, instead of displaying each item individually, all the items are concatenated into a single string ("123").

This bug causes the frontend to fail to display the streamed data correctly, as it should render each item separately as they arrive, but instead, it shows them together as a single block.

For a detailed example of the issue, you can check out the following example: [leptos-stream-example](https://github.com/anhelinakruk/leptos-stream-example/blob/151505d3b6f88dae3d81e8d163d39bbe3d59819d/app/src/lib.rs#L41C1-L110C2)

**Leptos Dependencies**
```
leptos = { version = "0.6" }
leptos_meta = { version = "0.6" }
leptos_router = { version = "0.6" }
leptos_axum = { version = "0.6" }

axum = "0.7"
cfg-if = "1"
console_error_panic_hook = "0.1.7"
console_log = "1"
futures = "=0.3.31"
http = "1"
log = "0.4.20"
simple_logger = "4.2.0"
thiserror = "1"
tokio = { version = "1.33.0", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.5", features = ["full"] }
wasm-bindgen = "=0.2.93"
```

**To Reproduce**
1. Clone the repository: [leptos-stream-example](https://github.com/anhelinakruk/leptos-stream-example/blob/151505d3b6f88dae3d81e8d163d39bbe3d59819d/app/src/lib.rs#L41C1-L110C2)
2. Open the `StreamExample` component in the code where the stream is implemented.
3. Run the application with `cargo leptos watch` and navigate to the UI.
4. Click the "Start Stream" button to trigger the data stream.
5. Observe the frontend output – instead of showing items like `1`, `2`, and `3` sequentially, they are concatenated into a single string (`"123"`).

**Expected behavior**
Each item in the stream should be rendered separately on the frontend, for example:
```
'1'
'2'
'3'
```

**Screenshots**
N/A

**Additional context**
- On the server side, the stream::unfold function is used to turn a vector like [1, 2, 3] into a stream. The items are processed one by one.
- The frontend should handle the streamed data and render each item separately as they are received.
- The server-side logs show that the items are being emitted sequentially, so the issue seems to be related to the frontend rendering logic.

**Comment by gbj** [comment]
It's actually concatenated into a single string on the server side: If I run your application and call the server function via `curl`, the server only responds with a single chunk of text, buffered to include all three responses in a single string.

Fundamentally, this seems to be a choice that Axum is making about how to handle that: we do hand it a streaming response, but it does not seem to respond with a stream. It seems the server will feel free to concatenate an arbitrary number of chunks from the stream you give it into a single chunk in its response. 

I guess adding a delimiter between items is the simplest way to handle this in your actual code. 

I don't know enough about how/why Axum handles streaming response bodies in this way to give a more helpful answer about what causes the problem or how we could fix it there.

**Comment by anhelinakruk** [comment]
Thank you for your response! 

From what I can see, this behavior seems to work as expected in Axum. Here's a link to my example: [axum-stream-example](https://github.com/anhelinakruk/axum-stream-example/blob/main/src/main.rs#L45-L136)

**Comment by gbj** [comment]
At a glance, it looks like you are using SSE in your (working) Axum example, whereas it's just returning a streaming text body in the non-working (but also Axum!) example, which Axum is then buffering. I think this explains the difference in behavior. 

I can see at least a few options:
1. Use SSE and not a server function
2. Create a server function encoding that uses SSE 
3. Change the underlying mechanism for streaming server fns to be SSE (this is tricky because currently they're just a plain HTTP request, and SSE requires something more than that)

**Comment by anhelinakruk** [comment]
Thanks for the explanation!
Could you please share a minimal example for points 2 and 3? I'm still not completely sure how they should work. Alternatively, is there any documentation that could help me understand this better?

**Comment by gbj** [comment]
[Here](https://github.com/leptos-rs/leptos/blob/8df4f3c71d7bc04b5565946a3584c95b7830d095/examples/server_fns_axum/src/app.rs#L706-L777)'s an example of implementing a custom server function encoding. [Here](https://docs.rs/server_fn/latest/server_fn/#server-function-encodings) are some relevant docs.

But if you want option 1 (just using SSE), then [here](https://github.com/leptos-rs/leptos/blob/8df4f3c71d7bc04b5565946a3584c95b7830d095/examples/counter_isomorphic/src/counters.rs#L178-L236)'s an example that uses SSE.
