### ISSUE TITLE
Support "class" html attribute for leptos_router::components:A

### ISSUE THREAD

**Issue by janschiefer** [leptos-rs/leptos#3369]
I have a situation where I need to apply some CSS classes directly to the HTML "a"-tag to display properly.

I stumbled upon the fact, that "leptos_router::components:A" doesn't support this attribute, while "leptos::html::a" does.

Since I want to use the leptos_router features, itwould be nice these were also supported by the leptos_router link tag.

Thank you!

**Comment by benwis** [comment]
We’ve been moving to attribute spreading on 0.7 instead of class= or id=, does ‘attr:class=“foo” work for you?

**Comment by gbj** [comment]
[See docs here](https://book.leptos.dev/view/03_components.html#spreading-attributes-onto-components).

**Comment by janschiefer** [comment]
Nice.

Thanks!
