### ISSUE TITLE
`use_params_map` updates just before Route is disposed

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#339]
This means that even for a guaranteed like `:id` you can't unwrap if you navigate away from a nested route, because the params will be updated with an empty map immediately before being disposed. This is an artifact of the very-synchronous nature of the reactive system, and can probably be patched for now until there's some movement there.

**Comment by jquesada2016** [comment]
Would it be possible to work around this by updating the `use_param_map` _after_ navigation has taken place? Like within a `spawn_microtask` or something that will make sure the page's scope has been cleaned up before the updated param map is propagated?
