### ISSUE TITLE
[Bug]: `Children` Type Can't Be Passed Inside a Closure

### ISSUE THREAD

**Issue by wiseaidev** [leptos-rs/leptos#3402]
Sup!

I've recently encountered an issue while building [an accordion component](https://github.com/opensass/accordion-rs) for WASM frameworks including Leptos. It seems the `Children` type cannot be passed inside a closure, nor can it be cloned. This results in a compilation error when attempting to use the `Children` type in such scenarios (conditionally render children).

**Steps to Reproduce**  
1. Clone this repository: https://github.com/opensass/accordion-rs
1. Uncomment the following lines: https://github.com/opensass/accordion-rs/blob/b9d6870a94814bbb04b79120183e6f929901b295/src/leptos.rs#L309-L321
1. Run: `cargo test --features=lep`

The compiler throws the following error:  
```sh
error[E0525]: expected a closure that implements the `Fn` trait, but this closure only implements `FnOnce`
   --> src/leptos.rs:284:5
    |
284 | /     view! {
285 | |         <div
286 | |             style=format!("{} {}", size.to_style(), style)
287 | |             class=class
...   |
310 | |                     {children()}
    | |                      -------- closure is `FnOnce` because it moves the variable `children` out of its environment
311 | |             </Show>
312 | |         </div>
313 | |     }
    | |     ^
    | |     |
    | |_____this closure implements `FnOnce`, not `Fn`
    |       the requirement to implement `Fn` derives from here
    |
    = note: required for `TypedChildrenFn<leptos::prelude::AnyView>` to implement `ToChildren<{closure@src/leptos.rs:284:5: 313:6}>`
    = note: this error originates in the macro `view` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I'm unsure if there's a workaround for this issue. Any guidance or suggestions would be much appreciated!

Best!

**Comment by gbj** [comment]
Here's the minimal reproduction of your problem:
```rust
#[component]
pub fn Accordion(children: Children) -> impl IntoView {
    view! {
        <Show when=move || true>
            {children()}
        </Show>
    }
}
```
Here's the solution: using `ChildrenFn` (can be called more than once) instead of `Children` (can be called only once)
```rust
#[component]
pub fn Accordion(children: ChildrenFn) -> impl IntoView {
    view! {
        <Show when=move || true>
            {children()}
        </Show>
    }
}
```

[Here's a link to the relevant docs](https://book.leptos.dev/view/09_component_children.html?highlight=ChildrenFn#component-children).

**Comment by gbj** [comment]
(Double-checking your specific case, in which you use `children()` again below: You'll also want to clone `children`, which `ChildrenFn` does support. The easiest way to do that is just with `clone:children` on the `Show`, as below)
```rust
<Show when=move || expand.0.get() clone:children>
    <div
        id=aria_controls
        class=content_class
        style=format!(
            "overflow: hidden; transition: all {}ms; {}",
            duration,
            content_style
        )
    >
        {children()}
    </div>
</Show>
```
