### ISSUE TITLE
cargo leptos watch crashes on hot module reloading

### ISSUE THREAD

**Issue by SorenHolstHansen** [leptos-rs/leptos#341]
Tried the `cargo-leptos` setup today, and really liked it, but the hot-module-reloading crashed the page for me. See the video for what happened.

https://user-images.githubusercontent.com/54755687/213494633-1b38b0fa-1900-4f30-b176-952488de90af.mov

If it helps, here is my environment
```
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 521.48 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Browsers:
    Firefox: 107.0.1
```

**Comment by gbj** [comment]
Could you open an issue [in the `cargo-leptos` repo](https://github.com/leptos-rs/cargo-leptos) please?

**Comment by SorenHolstHansen** [comment]
Yes, will do
