### ISSUE TITLE
Customize the output filename of the main .wasm file

### ISSUE THREAD

**Issue by epenabella** [leptos-rs/leptos#3416]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I upload a new SSG version of my site to cloudflare but the caching is still getting messed up..

**Describe the solution you'd like**
is there some way to customize the output filename of the .wasm file
_in this case I'd like to just add a randomized guid query param to ensure no caching per version_

![image](https://github.com/user-attachments/assets/c5e82f22-88a5-419b-b142-882ebb4be56a)

**Describe alternatives you've considered**
I tried messing with cloudflare & adding script tags inside my main.rs file, but it just doubles up

Otherwise I get a .wasm mixup in production:
![image](https://github.com/user-attachments/assets/4390e56f-5da4-4462-95e0-67e33dd6b5d8)

**Comment by gbj** [comment]
Not a lot of details here about what kind of build process you're using. `cargo-leptos` supports hashing the file names -- are you using that `hash-files` option?

**Comment by epenabella** [comment]
you're amazing thank you!

got it working btw after shifting things around from the actix starter like moving the stylesheet to here and using the HashedStylesheet I found after digger deeper instead

ps if there's some way i can help lmk this project is super interesting !

![image](https://github.com/user-attachments/assets/788b882c-869e-4824-a92d-13963d4b586a)
