### ISSUE TITLE
Weirdness with navigate not updating outlets in routes

### ISSUE THREAD

**Issue by mclark4386** [leptos-rs/leptos#348]
So I have attached a little toy project to show this in action. Honestly it may be that I just don't understand the system enough and it's working as intended. The important file looks like this:

```
use leptos::{*, web_sys::KeyboardEvent};
use leptos_meta::*;
use leptos_router::*;

const ENTER_KEY: u32 = 13;

#[component]
pub fn App(cx: Scope) -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context(cx);

    view! {
        cx,

        // injects a stylesheet into the document <head>
        // id=leptos means cargo-leptos will hot-reload this stylesheet
        <Stylesheet id="leptos" href="/pkg/leptos_start.css"/>

        // sets the document title
        <Title text="Welcome to Leptos"/>

        // content for this welcome page
        <Router>
            <main>
                <Routes>
                    <Route path="" view=|cx| view! { cx, <HomePage/> }>
                        <Route path=":id" view=|cx| view! { cx, <TryIdWidget/> }/>
                        <Route path="/" view=|cx| view! { cx, <p>"No ID selected"</p> }/>
                    </Route>
                </Routes>
            </main>
        </Router>
    }
}

/// Renders the home page of your application.
#[component]
fn HomePage(cx: Scope) -> impl IntoView {
    let nav = use_navigate(cx);
    let id_input = move |ev: KeyboardEvent|{
        ev.stop_propagation();
        let key_code = ev.key_code();
        if key_code == ENTER_KEY {
            let id = event_target_value(&ev);
            let id = id.trim();
            if !id.is_empty() {
                _ = nav(&format!("/{}", id)[..],Default::default());
            }
        }
    };

    view! { cx,
        <h1>"Trying this out"</h1>
        <input class="try-id-input" placeholder="Enter Try ID..." on:keydown=id_input/>
        <Outlet/>
    }
}

#[component]
fn TryIdWidget(cx: Scope) -> impl IntoView {
    let params = use_params_map(cx)();
    let id = params.get("id");

    view! {
        cx,
        <div>
            <p>"Current id:"{id}</p>
        </div>
    }
}
```

I would expect it to both change the url (which it does), but also re-load the TryIdWidget as well which it does the first time, but then never again. Could someone let me know if this is in fact a bug and if not what I'm doing wrong?

Test project: [nav-bug.zip](https://github.com/leptos-rs/leptos/files/10470138/nav-bug.zip)

**Comment by gbj** [comment]
The first thing I notice is that your `let id = params.get("id");` is not reactive. That should be `let id = move || params.get("id");` Reactive values always need to be functions; the framework doesn't rerun your component function, so if `id` is a plain value and not a function it can never be updated.

Try that, and if it doesn't resolve your issue I'll take a deeper look.

**Comment by mclark4386** [comment]
With that change I get:

```
error: lifetime may not live long enough
  --> src/app.rs:62:22
   |
62 |     let id = move || params.get("id");
   |              ------- ^^^^^^^^^^^^^^^^ returning this value requires that `'1` must outlive `'2`
   |              |     |
   |              |     return type of closure is Option<&'2 String>
   |              lifetime `'1` represents this closure's body
   |
   = note: closure implements `Fn`, so references to captured variables can't escape the closure

error: could not compile `leptos_start` due to previous error
```

Which exposes one of the places I'm still learning in rust >.<;

**Comment by gbj** [comment]
Sorry I think I missed a set of parentheses you had. It should be

```rust
let params = use_params_map(cx);
let id = move || params().get("id").cloned()
```

`params` is a signal/memo, so you want to access it (by calling it) _inside_ the closure. Then the `.get(...)` returns `&String`, so you clone it to get an owned string.

**Comment by mclark4386** [comment]
That was it! Thank you!
So is the idea that we mark variables as "reactive" by making them lambdas/closures instead of bare values? So I take it it's not just re-running the component "function" again?

**Comment by gbj** [comment]
Exactly! The function you rerun is the closure, not the component. It's SolidJS style, not React, if that means anything. 

If you use Discord by the way, check out our server (link in Readme)--it's very active and great for these kinds of conversations too.
