### ISSUE TITLE
SVG script takes precedence over JS script tag

### ISSUE THREAD

**Issue by WafflePersonThing** [leptos-rs/leptos#349]
In 0.1.0 you were able to specify <html::script> inside of view! to get a js script but that is no longer the case in 0.1.1 where the macro doesn't recognize it 

relevant files:
- https://github.com/leptos-rs/leptos/blob/a49dfd3f8e346254ed6e55e84d0500814e5e0c66/leptos_dom/src/html/svg.rs#L288
- https://github.com/leptos-rs/leptos/blob/a49dfd3f8e346254ed6e55e84d0500814e5e0c66/leptos_dom/src/html.rs#L1205

example:
if you call a function that requires a parameter of HtmlElement<Script> and pass in: view!{ cx, <script/>} it will fail to compile saying something like: expected struct 'leptos::HtmlElement<leptos::Script>'found struct 'leptos::HtmlElement<leptos::svg::Script>'

**Comment by gbj** [comment]
Oops! Good catch. 

It's actually this function: https://github.com/leptos-rs/leptos/blob/a49dfd3f8e346254ed6e55e84d0500814e5e0c66/leptos_macro/src/view.rs#L1090

I think we missed the fact that <script> is also an ambiguous tag. 

Just curious, is this when compiling for SSR or for WASM or both?
