### ISSUE TITLE
Dynamically loading js files

### ISSUE THREAD

**Issue by koopa1338** [leptos-rs/leptos#355]
Hi,

I'm currently testing frontend development in general with rust and kind of
hit a use case that might be very common but currently is not working as
expected.

What I try to achieve is that the framework is loading some JS files and it
gets loaded. What I got working is to load the JS file with the `leptos_meta`
crate into the head section of the `index.html`, but things like event
handler for dropdowns for example are not registered. (I try to use flowbite
with tailwind CSS here)

I am kind of confused, is this not a general use case to load JS files on page
load that depend on the DOM? How can I solve this problem? Any information
that I found was about how to call into JS functions from rust, which I don't
even want to do in this scenario.

Is there any solution to this? How are other people using frameworks like
bootstrap, flowbite etc. with leptos?

**Comment by gbj** [comment]
Can you provide any more information about what you're trying to do and what isn't working, with a code example? It's not really possible to answer your question without more information than the problem that event listeners aren't registered.

**Comment by koopa1338** [comment]
Having the following example:

main.rs
```rust
use leptos::*;
use leptos_meta::*;

#[component]
pub fn Root(cx: Scope) -> impl IntoView {
    provide_meta_context(cx);
    view! { cx,
        <aside class="fixed top-0 left-0 w-64 h-full" aria-label="Sidenav">
          <div class="overflow-y-auto py-5 px-3 h-full bg-white border-r border-gray-200 dark:bg-gray-800 dark:border-gray-700">
              <ul class="space-y-2">
                  <li>
                      <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                          <svg aria-hidden="true" class="w-6 h-6 text-gray-400 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
                        <span class="ml-3">"Overview"</span>
                      </a>
                  </li>
                  <li>
                      <button type="button" class="flex items-center p-2 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" aria-controls="dropdown-pages" data-collapse-toggle="dropdown-pages">
                          <span class="flex-1 ml-3 text-left whitespace-nowrap">"Pages"</span>
                      </button>
                      <ul id="dropdown-pages" class="hidden py-2 space-y-2">
                          <li>
                              <a href="#" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">"Settings"</a>
                          </li>
                          <li>
                              <a href="#" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">"Kanban"</a>
                          </li>
                          <li>
                              <a href="#" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">"Calendar"</a>
                          </li>
                      </ul>
                  </li>
                  <li>
                      <button type="button" class="flex items-center p-2 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" aria-controls="dropdown-sales" data-collapse-toggle="dropdown-sales">
                          <span class="flex-1 ml-3 text-left whitespace-nowrap">"Sales"</span>
                      </button>
                      <ul id="dropdown-sales" class="hidden py-2 space-y-2">
                              <li>
                                  <a href="#" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">"Products"</a>
                              </li>
                              <li>
                                  <a href="#" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">"Billing"</a>
                              </li>
                              <li>
                                  <a href="#" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">"Invoice"</a>
                              </li>
                      </ul>
                  </li>
                  <li>
                      <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                          <span class="flex-1 ml-3 whitespace-nowrap">"Messages"</span>
                          <span class="inline-flex justify-center items-center w-5 h-5 text-xs font-semibold rounded-full text-primary-800 bg-primary-100 dark:bg-primary-200 dark:text-primary-800">
                              6
                          </span>
                      </a>
                  </li>
                  <li>
                      <button type="button" class="flex items-center p-2 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" aria-controls="dropdown-authentication" data-collapse-toggle="dropdown-authentication">
                          <span class="flex-1 ml-3 text-left whitespace-nowrap">"Authentication"</span>
                      </button>
                      <ul id="dropdown-authentication" class="hidden py-2 space-y-2">
                          <li>
                            <a href="#" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">"Sign In"</a>
                          </li>
                          <li>
                            <a href="#" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">"Sign Up"</a>
                          </li>
                          <li>
                            <a href="#" class="flex items-center p-2 pl-11 w-full text-base font-normal text-gray-900 rounded-lg transition duration-75 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">"Forgot Password"</a>
                          </li>
                      </ul>
                  </li>
              </ul>
          </div>
        </aside>
        <Script defer="true" src="/flowbite.js"></Script>
    }
}

fn main() {
    console_error_panic_hook::set_once();
    _ = console_log::init_with_level(log::Level::Debug);
    console_error_panic_hook::set_once();
    mount_to_body(|cx| view! { cx,  <Root/> })
}
```

index.html using trunk
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Testing</title>
    <link rel="stylesheet" href="/app.css"/>
    <link data-trunk rel="rust" data-wasm-opt="z" />
    <link data-trunk rel="copy-file" href="node_modules/flowbite/dist/flowbite.js" />
    <base data-trunk-public-url />
</head>
<body class="bg-slate-800 w-full h-full"></body>
</html>
```

I then get the following in the browser:
![dropdown](https://user-images.githubusercontent.com/20669804/213939059-e302fa97-cf95-42de-a54d-d6b85369ced7.png)

But the dropdowns don't work because the event handlers from `flowbite.js` are missing. It works if I try the exact same component in a static index.html file with the js file beside it.

I can see that the script is correctly added:
![script](https://user-images.githubusercontent.com/20669804/213939170-f00e9c8c-9961-4264-a9db-e05dd791fa74.png)

And I also can open the script by clicking on the path, so the path is also correct.

I hope I could get my use cases clearer.

**Comment by gbj** [comment]
If I had to guess I'd assume that the JavaScript is loading before the WebAssembly has rendered your interface, so it doesn't find any drop downs that already exist. Is there a way to call your JS library so it only looks for drop downs when you tell it to, rather than when it loads? This would also be necessary when integrating with a JS front end framework I'd think.

**Comment by koopa1338** [comment]
I already tried the same in yew, and my guess was the same, the DOM is not fully rendered by the WebAssembly and therefore no event handlers get attached correctly. I think it is not a good practice to change the library to work with my setup. For one package this might work, but imagine dozens of packages that you have to patch, updates would get a nightmare I assume.

Another solution would be to write a custom JavaScript loader that checks if the DOM is already fully generated (if someone knows how to do this in rust with `wasm_bindgen` or integrate it even in `leptos_meta` feel free to join the discussion and share some ideas here).

My hope wit leptos was the `Script` function, but unfortunately the behavior is quite the same. What I wanted to get clear in my issue: **this will be the same for every JavaScript code that depend on the DOM in some way**
IMO this is a huge shortcoming for frontend frameworks in rust, don't get me wrong, I like rust (somewhat a member of rust evangelism strike force) but this is not very appealing for frontend development. There are millions of NPM packages there, and we cripple ourselves by making it that difficult, maybe even impossible, to use.

At this point I'll have to admit that my experience with WebAssembly is not sufficient to even tackle this problem, I wouldn't even know where to start, but I hope someone comes up with an idea to solve this in a really simple, robust and elegant way, so frontends get much easier with rust.

Maybe my comment is a bit harsh and I want to end it on a positive note:
Leptos is really fun to use. It might need some more documentation (or examples, maybe I'll open a PR for an example using trunk like I did in my testing). If I'd compare it to yew, for example, I think it's much simpler without loosing expressiveness. So keep up the good work and I try to contribute where I can :grinning:

**Comment by gbj** [comment]
I actually don't think the real issue has anything to do with JavaScript vs. Rust/Wasm. A library that assumes that everything it needs to do has already been rendered in the DOM will be wrong if you're pairing it with *any* front-end framework, unless there's a custom-built integration, or you use the framework to render the script tag to load it. To be clear, IMO this is an issue with flowbite's design (i.e., using an IIFE to check once for DOM elements immediately when it's run rather than exposing a function that you can call when you're ready to set it up)

I was able to get your example working by just using a `<script>` tag, i.e., having your component end
```
  </div>
</aside>
<script src="/flowbite.js"></script>
```
This seems to work in Chrome, but not in Firefox. I am not sure why. The dropdown menus work properly in Chrome.

It seems like maybe there's an issue with the `<Script/>` component in client-side-rendering mode, so, fair enough. I don't know if this is a security issue or something else.

I'm going to close this because I don't think there's any fundamental issue here, and I'll open a separate issue about `<Script/>` in CSR mode.

Thanks for your kind words about the framework. I'm doing a lot of work right now on additional intro-level docs. There are several Trunk examples in the repo (for example, the `counter`, `router`, and `fetch` examples) if you wanted to take a look at any of them.

**Comment by gbj** [comment]
Final note: the issue with `<Script/>`, I suspect, was actually that you need to enable the `csr` feature on `leptos_meta` for it to work.

So in `Cargo.toml`

```toml
leptos = { version = "0.1", features = ["csr"] }
```

**Comment by koopa1338** [comment]
My `Cargo.toml` in my tests looked like this:
```toml
[package]
name = "leptos-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { git = "https://github.com/leptos-rs/leptos", default-features = false, features = [
    "csr",
] }
leptos_meta = { git = "https://github.com/leptos-rs/leptos", default-features = false, features = [ "csr" ]}
leptos_router = { git = "https://github.com/leptos-rs/leptos", default-features = false, feature = ["csr"] }
log = "0.4"
console_log = "0.2"
console_error_panic_hook = "0.1"
```
