### ISSUE TITLE
Googling Leptos is Unfortunate

### ISSUE THREAD

**Issue by shellscape** [leptos-rs/leptos#357]
This is a very meta issue so please feel free to nuke this from orbit:

I'm a Rust newbie. This and Tauri are two projects I'm keeping an eye on while I pick up Rust. Whenever I google leptos I get suggestions for https://www.avma.org/resources/pet-owners/petcare/leptospirosis, which is just a bummer. fwiw the same thing happens with Brave search and the duck.

I'm not sure what leptos means (and there's no faq addressing meaning or origin), but perhaps a branding a bit further away from a canine bacterial infection might be something to think about.

**Comment by gbj** [comment]
[Leptos](https://en.m.wiktionary.org/wiki/λεπτός#Ancient_Greek) means something like "thin, light, fine grained" in Ancient Greek. I assume leptospirosis as a medical term is derived from that same word. 

When I Google Leptos in an incognito window or something the top results I get are related to the framework, and especially so if I include Rust, web, or framework as keywords. The other ones relate to a real estate company in Cyprus. I wonder if this is Google still somehow personalizing things for me?

**Comment by shellscape** [comment]
It's possible, and here as well, as I'm a dog owner
