### ISSUE TITLE
edit HTML attributes 

### ISSUE THREAD

**Issue by yzn-h** [leptos-rs/leptos#376]
we need a way to edit html attributes in leptos

currently this is the HTML by default
![image](https://user-images.githubusercontent.com/63852512/214846185-898808cc-5427-476b-b83a-8d381cc5e086.png)

**Comment by gbj** [comment]
Thanks. I think the best way to do this will be to add `<Html/>` and `<Body/>` components to `leptos_meta`, to set valid attributes on the `<html>` element and to set things like `class` on the `<body>`, which are (IIRC) the only hard-coded elements in either the SSR integrations or a typical Trunk setup that aren't already included in `leptos_meta`. I'll work on this soonish.
