### ISSUE TITLE
Support Compiling to Web Component

### ISSUE THREAD

**Issue by seanaye** [leptos-rs/leptos#402]
It would be great if leptos supported compiling to web components so that is can be interoperated with other frontend frameworks.

A lot of web apps have a need for a few high performance components but are deployed by a team where a majority of devs dont know rust.

I have looked at trunk and leptos docs and afaik there is no mention of web components

**Comment by gbj** [comment]
I don't have any time to work on this but you should check out my [`custom-elements`](https://github.com/gbj/custom-elements) crate, which makes it very easy to create custom elements/web components in Rust. If someone wants to make it even easier to convert Leptos components to web components.

**Comment by seanaye** [comment]
Amazing, that's more or less exactly what I'm looking for. Thanks for both these awesome crates!
