### ISSUE TITLE
failed to resolve: could not find `Option` in `leptos`

### ISSUE THREAD

**Issue by TmLev** [leptos-rs/leptos#411]
I was trying to build a `<select />`-based component with a few `<option />`-s to choose from:

<details>

```rust
#[component]
pub fn SelectNumber(cx: Scope) -> impl IntoView {
    view! { cx,
        "Select number:"
        <select name="number_from_select">
            <For
                each=|| [1, 2, 3, 4]
                key=|&number| number
                view=move |number| {
                    view! { cx,
                        <option value=number>
                            {number}
                        </option>
                    }
                }
            />
        </select>
    }
}
```

</details>

However, using `<option />` seems to trigger some strange error:

<details>

```logs
❯ cargo leptos watch
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
       Cargo finished cargo build --package=leptos_start --lib --target-dir=target/front --target=wasm32-unknown-unknown --no-default-features --features=hydrate
   Compiling leptos_start v0.1.0 (/Users/lev/repos/leptos-start)
error[E0433]: failed to resolve: could not find `Option` in `leptos`
    --> src/app.rs:55:26
     |
55   |                           <option value=number>
     |                            ^^^^^^
     |
    ::: /Users/lev/.cargo/git/checkouts/leptos-2c8932a5258b3db6/62061f9/leptos_dom/src/html.rs:963:1
     |
963  | / generate_html_tags![
964  | |   // ==========================
965  | |   //        Main root
966  | |   // ==========================
...    |
1252 | |   template HtmlTemplateElement,
1253 | | ];
     | |_- similarly named struct `Option_` defined here
     |
help: a struct with a similar name exists
     |
55   |                         <Option_ value=number>
     |                          ~~~~~~~
help: consider importing one of these items
     |
1    | use core::option::Option;
     |
1    | use crate::app::tracing::log::__private_api::Option;
     |
1    | use log::__private_api::Option;
     |
1    | use std::option::Option;
     |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `leptos_start` due to previous error
      Notify watching folders src, style, assets
```

</details>

I'm using `stable` feature.

OS: macOS 12.4.
Cargo: 1.67.0 (8ecd4f20a 2023-01-10)
rustc: 1.67.0 (fc594f156 2023-01-24)

Here's the repro: https://github.com/TmLev/leptos-start  
And relevant commit: https://github.com/TmLev/leptos-start/commit/2625c2f0a5a51b34debee8c4e9da48bb431067fe

Is this line of code relevant?
https://github.com/leptos-rs/leptos/blob/62061f90ea29b83810edc25df7cb9b9c35cb9517/leptos_dom/src/html.rs#L1226

**Comment by gbj** [comment]
Yep thanks. If I had to guess I'd say you get this error on Leptos `0.1.3` but not `0.1.1` correct? I think I forgot to cover this case in the new SSR version of the view macro. I can make a fix later today.

**Comment by TmLev** [comment]
> If I had to guess I'd say you get this error on Leptos `0.1.3` but not `0.1.1` correct? I think I forgot to cover this case in the new SSR version of the view macro. 

I was trying Leptos out for the first time, so I just went with the template. It has `git = "https://github.com/leptos-rs/leptos"`, not a `version = "0.1.3"`.

I can test `0.1.1` if needed :)

**Comment by gbj** [comment]
Thanks! This should be fixed now.
