### ISSUE TITLE
Handle validation in server functions

### ISSUE THREAD

**Issue by Bechma** [leptos-rs/leptos#413]
# Motivation

Hook a validation function in both server and client, so in case the validation is failing in the client side, we don't need to send the request.
If the validation is different in the server and the client, a `cfg(feature="ssr")` can be used to do different workflows.

# Problem

Not a problem, but convenient to reduce code size and save requests.

# Solution

This was discussed in discord to find a solution:
- A form validator library might be use to extend an easy validation -> https://github.com/Keats/validator (this is an example)
- Hook the responses from that library into an ActionForm

**Comment by gbj** [comment]
So there's actually a pretty good pattern for this now — see the PR I just made. 

I added a helper trait to make it easier for you to deserialize a type that implements `DeserializeOwned` (which includes server function argument types) from form data or event just a form `submit` event.

If you put an `on:submit` event on an `<ActionForm/>` or `<MultiActionForm/>` it will fire before the more complex form submission logic runs. And if you call `ev.prevent_default()`, that will cancel the submission.

So now you can do something like this
```rust
<MultiActionForm
    // we can handle client-side validation in the on:submit event 
    // leptos_router implements a `FromFormData` trait that lets you
    // parse deserializable types from form data and check them
    on:submit=move |ev| {
        let data = AddTodo::from_event(&ev).expect("to parse form data");
        // silly example of validation: if the todo is "nope!", nope it
        if data.title == "nope!" {
            // ev.prevent_default() will prevent form submission
            ev.prevent_default();
        }
    }
    action=add_todo
>
// ...
```

This means you can use any kind of form validation library or approach you'd like, totally independent of the framework, or just do some simple validation, and then decide whether to let the submission process continue or not.

For anyone reading this later: you should always validate form input on the server, this client-side validation is not guaranteed to run (if WASM hasn't loaded yet) and it can easily be avoided by a user with any kind of malicious intent.
