### ISSUE TITLE
Is there a way to insert raw html?

### ISSUE THREAD

**Issue by ModProg** [leptos-rs/leptos#428]
Say you use https://docs.rs/syntect/latest/syntect/ to generate syntax highlighted code and want to emit that inside of a leptos Fragment.

**Comment by gbj** [comment]
You can use the `inner_html` attribute on any element. I need to make sure this is documented (better? at all?)

**Comment by theAkito** [comment]
Seems it is not part of the documentation, yet. Are there any plans for documenting this?

**Comment by gbj** [comment]
> Seems it is not part of the documentation, yet. Are there any plans for documenting this?

At the moment it's only documented as the [`inner_html`](https://docs.rs/leptos/0.2.5/leptos/struct.HtmlElement.html#method.inner_html) method on an `HtmlElement`, which — while it may make sense to search for to someone who knows that [`innerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) is a thing —  could probably be improved.

Do you have a suggestion for where else in the documentation it should be included? Maybe in the `view` macro?

**Comment by theAkito** [comment]
> Do you have a suggestion for where else in the documentation it should be included? Maybe in the `view` macro?

Ah, I see now. I just checked https://leptos-rs.github.io/leptos/testing.html?search=inner_html.

It would be nice to have an example of how to do it with Leptos. For example, I am not sure how I would use that to "mark" something as raw HTML in a Leptos project.

I would also be ready to write the documentation for this, if I knew exactly how it works.

**Comment by gbj** [comment]
> It would be nice to have an example of how to do it with Leptos. For example, I am not sure how I would use that to "mark" something as raw HTML in a Leptos project.

You can inject raw HTML as the child of an element using the `inner_html` attribute:
```rust
let some_html = "<span>Hello!</span>";
view! { cx,
  <div inner_html=some_html/>
}
```

**Comment by gbj** [comment]
> Seems it is not part of the documentation, yet. Are there any plans for documenting this?

I did not think to actually check this when I replied initially, but this is in fact documented as part of the [`view`](https://docs.rs/leptos/latest/leptos/macro.view.html) macro (see point 10) so I'm going to close this again.
