### ISSUE TITLE
Order of execution with `<Show />`

### ISSUE THREAD

**Issue by joksas** [leptos-rs/leptos#444]
My code (at commit cbfb724af2006aa5c4d7a6723c4d185410571a21):

```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    let (my_value, set_my_value) = create_signal(cx, String::new());
    let (my_optional_value, set_optional_my_value) = create_signal(cx, Option::<String>::None);

    create_effect(cx, move |_| {
        if my_value.get().len() > 0 {
            set_optional_my_value(Some(my_value.get()));
        } else {
            set_optional_my_value(None);
        }
    });

    view! { cx,
        <input
            prop:value=my_value
            on:input= move |ev| set_my_value(event_target_value(&ev))
        />

        <p>
            <code>"my_optional_value"</code>
            " is "
            <code>
                <Show
                    when=move || my_optional_value().is_some()
                    fallback=|cx| view! { cx, "None" }
                >
                    "Some(\"" {my_optional_value().unwrap()} "\")"
                </Show>
            </code>
        </p>
    }
}
```

This works fine if I write something the first time, but when I delete the text within `<input>`, the program panics:

```
called `Option::unwrap()` on a `None` value
```
at `"Some(\"" {my_optional_value().unwrap()} "\")"`, despite the condition `when=move || my_optional_value().is_some()`.

It seems that `my_optional_value().unwrap()` is executed before `my_optional_value().is_some()`.

Is this the expected behaviour?

**Comment by gbj** [comment]
So, just for the sake of curiosity I rewrote your example to use a derived signal instead of creating an effect to write into a signal.

```rust
    let my_optional_value = move || {
        let value = my_value.get();
        if value.is_empty() {
            None
        } else {
            Some(value)
        }
    };
```

This is what I generally recommend to people — [as the `create_effect` docs say](https://docs.rs/leptos/latest/leptos/fn.create_effect.html),

> Effects are intended to run side-effects of the system, not to synchronize state within the system. In other words: don’t write to signals within effects. (If you need to define a signal that depends on the value of other signals, use a derived signal or [create_memo](https://docs.rs/leptos/latest/leptos/fn.create_memo.html)).

When I test it, this seems to solve your issue. It's a little tricky to explain why this is, but it has to do with creating the extra effect which *always* depends on `my_value`. I don't know that the full explanation is totally necessary.
