### ISSUE TITLE
`site-addr`, `site_addr`, `site_address`

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#446]
`leptos_config` and `cargo-leptos` have used different names in the past and there's some inconsistency left. (See https://github.com/leptos-rs/start/pull/13)

We just need to make sure we're consistent and using the correct name across examples and in `leptos_config`, possibly maintaining backwards-compatibility with the incorrect versions but trying not to replicate them.

**Comment by benwis** [comment]
Yeah, so Id love to standardize on site-address, I feel like it's the clearest of them all. But I believe cargo-leptos uses site-addr, so I wonder if we can change that or if I shouldn't bother and just use site-addr
