### ISSUE TITLE
Properties don't seem to be correctly set by Leptos

### ISSUE THREAD

**Issue by aWeinzierl** [leptos-rs/leptos#507]
Reproduction:
1. Prepare tailwind example (current latest master, cargo-leptos 0.1.7, rustc 1.69.0-nightly (ef934d9b6 2023-02-08), tailwind 3.2.6)
2. Replace the implementation of the app component with the following code:
    ```rust

   provide_meta_context(cx);

    let open = create_rw_signal(cx, false);
    let toggle = move |_| open.update(|open| *open = !*open);

    view! {
        cx,
        <Stylesheet id="leptos" href="/pkg/tailwind.css"/>
        <Link rel="shortcut icon" type_="image/ico" href="/favicon.ico"/>
        <main class="my-0 mx-auto max-w-3xl text-center">
            "Don't toggle 'aria-expanded' at all"<br/>
            <button type="button" 
                class="aria-expanded:bg-green-700 bg-red-700"
                aria-expanded=open()
                on:click=toggle                 
            >
                "Should toggle background color"
            </button>
            <br/><br/>
            <button type="button" 
                class="aria-expanded:bg-green-700 bg-red-700"
                aria-expanded=open.get()
                on:click=toggle                 
            >
                "Should toggle background color"
            </button>
            <br/><br/>
            <button type="button" 
                class="aria-expanded:bg-green-700 bg-red-700"
                attr:aria-expanded=open()
                on:click=toggle                 
            >
                "Should toggle background color"
            </button>
            <br/><br/>
            "Add aria-expanded='aria-expanded' instead of aria-expanded='true'"<br/>
            <button type="button" 
                class="aria-expanded:bg-green-700 bg-red-700"
                aria-expanded=move || open.get()
                on:click=toggle                 
            >
                "Should toggle background color"
            </button>
            <br/><br/>
            <button type="button" 
                class="aria-expanded:bg-green-700 bg-red-700"
                aria-expanded=open.read_only()
                on:click=toggle                 
            >
                "Should toggle background color"
            </button>
            <br/><br/>
            <button type="button" 
                class="aria-expanded:bg-green-700 bg-red-700"
                attr:aria-expanded=open.read_only()
                on:click=toggle                 
            >
                "Should toggle background color"
            </button>
        </main>
    }
    ```
The code shows several buttons.
I would expect that for the first button `aria-expanded="true"` is set after any button is clicked and a change of the background color to green accordingly, because
   1. `open` is a `bool` Signal
   2. setting the property like this is standard behavior, see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded

The other buttons are a simply a selection of attempts to fix the behavior, which show interesting behavior. 

PS: When importing things from leptos individually (like e.g. shown in the HN example in `nav.rs`), `cargo leptos watch` warns `warning: unused import: 'IntoAttribute'` and produces a compiler error when I remove the import.

**Comment by gbj** [comment]
In a Leptos template passing a `bool` to an attribute makes it behave like an HTML boolean attribute, i.e., the attribute is present if `true` and absent if `false`. Passing a string to an attribute sets the value of the attribute.  In other words, the boolean `true` and the string `"true"` are not the same thing, and what you want is to set the value of the attribute to the string `"true"`. If you convert to a string, your first attempt seems to work correctly to me

```
        <button type="button" 
            class="aria-expanded:bg-green-700 bg-red-700"
            aria-expanded=move || open().to_string()
            on:click=toggle                 
        >
            "Should toggle background color"
        </button>
```

But let me know if I'm missing something.

**Comment by aWeinzierl** [comment]
> If you convert to a string, your first attempt seems to work correctly to me

It does indeed, thank you.

> In a Leptos template passing a bool to an attribute makes it behave like an HTML boolean attribute, i.e., the attribute is present if true and absent if false.

This doesn't seem to be the case though, see the HTML, which always looks like one of the following options:
- `<button type="button" class="aria-expanded:bg-green-700 bg-red-700">Should toggle background color</button>` (it doesn't add anything)
- `<button type="button" class="aria-expanded:bg-green-700 bg-red-700" aria-expanded="aria-expanded">Should toggle background color</button>` (adds `aria-expanded='aria-expanded'`)

**Comment by gbj** [comment]
> This doesn't seem to be the case though, see the HTML, which always looks like one of the following options:
> 
>     * `<button type="button" class="aria-expanded:bg-green-700 bg-red-700">Should toggle background color</button>` (it doesn't add anything)
> 
>     * `<button type="button" class="aria-expanded:bg-green-700 bg-red-700" aria-expanded="aria-expanded">Should toggle background color</button>` (adds `aria-expanded='aria-expanded'`)

This looks correct to me. [Per MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute):

> Boolean attributes are considered to be true if they're present on the element at all. You should set value to the empty string ("") or the attribute's name, with no leading or trailing whitespace.

We could change this to only render `aria-expanded` and not `aria-expanded="aria-expanded"` in HTML but they mean exactly the same thing AFAIK.
