### ISSUE TITLE
`Transition` doesn't show fallback while pending

### ISSUE THREAD

**Issue by kiyov09** [leptos-rs/leptos#562]
I noticed that the `Transition` component is not rendering the `fallback` while the resource inside is still pending.

**Example Code**

```rust
pub async fn test_resources() -> Vec<String> {
    std::thread::sleep(std::time::Duration::from_secs(2));
    vec![
        "Fizz".to_string(),
        "Buzz".to_string(),
        "FizzBuzz".to_string(),
    ]
}

#[component]
pub fn ResourcesIssue(cx: Scope) -> impl IntoView {
    let resource = create_resource(cx, move || (), move |_| test_resources());

    view! {
        cx,
        <div>
            <Transition fallback=move || view!{ cx, <p>"Loading..."</p>}>
            {
                move || resource.read(cx).map(|strs|
                    strs.iter()
                        .map(|s| view!{ cx, <p>{s}</p>})
                        .collect::<Vec<_>>(),
                )
            }
            </Transition>
        </div>
    }
}

```

I was analyzing the code and seems to be related to this if-else block:
https://github.com/leptos-rs/leptos/blob/4ff08f042b643d542546076edc748a0b4582cb55/leptos/src/transition.rs#L87-L91

**Comment by gbj** [comment]
Ah, thanks very much for reporting this!

**Comment by kiyov09** [comment]
@gbj 
First of all thnx for your work on this. 💪

It's working now but only when combined with `create_resource`. If I used `create_local_resource` (which I'm doing in my project) the issue is still there.

**Comment by kiyov09** [comment]
Probably the new `first_run` Cell needs to be read/modified inside the `fallback` instead of the `children`
At least that works for me. 

I can continue with this if you want.

**Comment by gbj** [comment]
> Probably the new `first_run` Cell needs to be read/modified inside the `fallback` instead of the `children`
> 
> At least that works for me. 
> 
> 
> 
> I can continue with this if you want.

Ah okay! Want to make a PR?

**Comment by kiyov09** [comment]
Sure. I'll work on that tomorrow morning. It's that ok?

**Comment by kiyov09** [comment]
@gbj 
Ok, I found what's the issue, but I don't know the proper way to fix it.
When on `hydrate` mode, the first run happens on the server, which sends the initial HTML with the fallback on it ("Loading..." in this case). When it gets to the client, the `prev_children` gets updated right away in the first run but it is an "invisible" element cause the resource is still pending (See screenshot below), so the fallback element sent by the server is removed.

<img width="1300" alt="Screenshot 2023-02-23 at 10 13 10" src="https://user-images.githubusercontent.com/15782488/220965193-915f56e2-8f74-4413-9d7a-52b3ae1d8cc5.png">

**Comment by gbj** [comment]
Ah okay I'll take a look.
