### ISSUE TITLE
Android/IOs support

### ISSUE THREAD

**Issue by srghma** [leptos-rs/leptos#564]
is it being planned?

**Comment by gbj** [comment]
No plans at present — While the framework's reactivity could be used to build any kind of application (see the `gtk` example in the repo) it is primarily intended for web applications. Given how tightly iOS and Android interfaces are tied to Swift/ObjC and Kotlin/Java, it seems unlikely that any Rust framework will have particularly good support in the near future. Of course it's already possible using something like Capacitor to wrap a webview into a native app, and my understanding is that Tauri now has at least some support for mobile apps. But I don't plan on doing any work myself to use Leptos to drive native mobile app interfaces.
