### ISSUE TITLE
example for error handling broken

### ISSUE THREAD

**Issue by 4ldas** [leptos-rs/leptos#584]
I've tested the code for error handling example using the official sandbox (https://codesandbox.io/p/sandbox/7-error-handling-and-error-boundaries-sroncx?file=%2Fsrc%2Fmain.rs) and i have a reason to believe that the example is broken, due to the fact that 
![image](https://user-images.githubusercontent.com/40773946/221433661-15f6fd7e-be46-4d36-b9a2-f2324dc85c5c.png)
the error stays, even if u input number. This doesnt occur after first website load, however if u input any character thats not a number and then input the number the error stays, also it just spams the error log like this if u input alot of characters
![image](https://user-images.githubusercontent.com/40773946/221433708-721ae03e-cea3-444d-8e1a-fda8f251e4bc.png)

P.S: When reading the issue ive also spotted that it talks about empty string

**Comment by gbj** [comment]
Thanks — Sometimes the CodeSandboxes get locked on old git versions, so I've updated this one and it's fixed. If anyone sees a similar issue in future, feel free to open an issue as well.
