### ISSUE TITLE
possible memory leak in server integrations, origins unclear

### ISSUE THREAD

**Issue by 617a7a** [leptos-rs/leptos#590]
Context: #581

Removed all API use in [valeralabs/web](https://github.com/valeralabs/web) and hardcoded a user profile into users.rs. Running a stress test for 120 seconds:
```  
Concurrency Level:      10
Time taken for tests:   120.001 seconds
Complete requests:      904656
Failed requests:        0
Total transferred:      4358651880 bytes
HTML transferred:       4260043940 bytes
Requests per second:    7538.75 [#/sec] (mean)
Time per request:       1.326 [ms] (mean)
Time per request:       0.133 [ms] (mean, across all concurrent requests)
Transfer rate:          35470.55 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       2
Processing:     0    1   0.5      1      23
Waiting:        0    1   0.5      1      23
Total:          0    1   0.5      1      23

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      2
  80%      2
  90%      2
  95%      2
  98%      2
  99%      3
 100%     23 (longest request)
```

The memory usage of the web server increased from ~5MB to 357MB, and _did not_ decrease after the benchmark. This may be due to #529 somewhere. I'm not sure where this issue is coming from yet.

**Comment by 617a7a** [comment]
Tested on the hackernews example with Actix using regular serde. 3190 requests increased memory usage from 5MB to 17.5MB (again, not decreasing after).

**Comment by gbj** [comment]
Do you have a reason to believe this is coming from within Leptos in particular? In other words, if you run the same stress test in Actix with the same number of requests but serve some static or generated HTML instead of running it through Leptos, what are the results?

**Comment by gbj** [comment]
[This conversation](https://www.reddit.com/r/rust/comments/ybu6gz/memory_leak_free_memory_not_being_reclaimed_what/) may also provide a helpful frame of reference.

**Comment by 617a7a** [comment]
The first test called another Actix server, our API, on every request (so 1:1 with leptos). The API instance remained at 4.8MB throughout the whole test, but the Leptos server grew to 977MB (check latest reply on

**Comment by gbj** [comment]
I'm happy to take a look at this locally to try to figure it out, if you can give me some steps you did to do the stress-testing. This is an area I'm pretty unfamiliar with.

**Comment by 617a7a** [comment]
I'm using ApacheBench - if you're on a MacBook (I think...), it should be preinstalled. The command I'm using is:

```console
ab -n 25000 -k -c 10 http://127.0.0.1:3000/
```

**Comment by gbj** [comment]
Thanks. I ran this against the todo apps to avoid spamming the 3rd-party hackernews API I use, and was able to reproduce on a smaller scale. Interestingly Axum seems to do a better job of shrinking its memory footprint back down between bursts of requests but I agree there's probably a Leptos leak somewhere.

I checked and can confirm that the `Runtime` structs are being dropped for each request, and the `RUNTIMES` slotmap capacity is staying stable, both of which which are very good (although it would have been an easy fix). 

I think the same behavior appears with very simple Leptos examples based on some limiting testing. I'm not very familiar with tools to trace this kind of memory leak so I'd appreciate any help.

**Comment by gbj** [comment]
Okay I tested this against a route that just uses `render_to_string` and found completely flat memory use, which is great.  So it's something inside the `render_to_stream` implementation, which makes perfect sense to me.

**Comment by 617a7a** [comment]
A similar thing may have occurred in #103 (adding for potential extra context).

**Comment by gbj** [comment]
> A similar thing may have occurred in #103 (adding for potential extra context).

Thanks — That particular issue was before I implemented proper management for runtimes, which I've confirmed are now being disposed properly, so it's a red herring I think. But having narrowed it down to the streaming implementation is very helpful, and I can dig in a little more later.

**Comment by gbj** [comment]
Edited the title, if you don't mind. I was able to reproduce with this very simple `main.rs`, which makes it much easier for me to test.
```rust
use leptos::{ssr::render_to_stream, view, IntoView};
use futures::StreamExt;

#[tokio::main]
async fn main() {
    loop {
        let mut stream = Box::pin(render_to_stream(|cx| view! { cx,
            <div>
                <p>"Paragraph 1."</p>
                <p>"Paragraph 2."</p>
                <p>"Paragraph 3."</p>
            </div>
        }.into_view(cx)));
        while let Some(chunk) = stream.next().await {
            println!("{chunk}");
        }
    }
}
```

**Comment by 617a7a** [comment]
That made me laugh. Nice job. Let me know when you have and I’ll run the initial stress test again to confirm.

**Comment by gbj** [comment]
Okay so it turns out this was coming from a slightly different direction than I thought. There *was* a memory leak coming from `render_to_stream`, but I soon discovered that `create_resource` *also* had a leak, even if I was just rendering to a string.

It turns out that this is actually a leak related to the interaction between `tokio::task::spawn_local` and, apparently, some or most allocators? It appears to be this issue: https://github.com/tokio-rs/tokio/issues/4406 If I change nothing else about the code but comment out the `tokio::task::spawn_local` in our SSR `spawn_local` function, there is no leak (but of course, resource loading doesn't work correctly.)

**Comment by gbj** [comment]
I was actually able to reproduce  the memory leak (or "leak" depending on who you ask) that I think is causing most of this problem. 

It has to do with the interaction between spawning a large number of Tokio tasks and memory allocators not returning memory to the system. 

I could toggle the memory leak on and off by rendering an app with a single `create_resource`, and then toggling a `tokio::task::spawn_local` on and off within `leptos::spawn_local`, which is used to load `async` resources. 

It's entirely possible I'm using Tokio wrong here and there's an easy solution. But see also discussion in several Tokio issues:

https://github.com/tokio-rs/tokio/issues/4406

https://github.com/tokio-rs/tokio/issues/4321#issuecomment-1000237820

**Comment by gbj** [comment]
Nope I was wrong. It was clearly a real leak, the longer I ran it. I have managed to create a streaming, non-leaking version, so I should be able to get those changes integrated into the Actix and Axum pieces I think.

**Comment by gbj** [comment]
...Okay, sorry for all the back and forth here. I've managed to create *several* different memory leaks during my experiments here, usually due to my doing something in a relatively stupid way. (For example, my 

Importantly: when I isolate the largest possible chunks of

**Comment by 617a7a** [comment]
I'm going to have a go at containerising the server, limiting its memory and then stressing it and seeing if it runs out of memory or not. I will get back if this is an actual issue with leptos. 

I am curious that it keeps increasing, however, since I’d expect it to plateau at some point and start reusing allocated memory. The RPS doesn't change throughout the bench in a major way.

**Comment by 617a7a** [comment]
I managed to containerise the server and... boom. That confirms it. There isn't a memory leak, but the allocator is not returning the memory to the system.

Again - continuous benchmark as before for 10 minutes. The web server's container was limited to using 32 MB of memory, and the server had no issues staying within that. So, I'm just marking this as done.

![image](https://user-images.githubusercontent.com/67651251/222555959-72b30e56-18cc-43ef-ae03-cc5286185e6e.png)
![image](https://user-images.githubusercontent.com/67651251/222556054-db1ac210-1349-4c69-b01f-5b147d1edcc6.png)

**Comment by gbj** [comment]
Beautiful! And thanks for raising it... I feel much more confident that we're not doing anything wrong, having worked through it all, than I did before.
