### ISSUE TITLE
feat: add custom handlers for `leptos_actix` as in `leptos_axum` so you can use extractors

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#600]

**Comment by benwis** [comment]
With #632 and assuming something similar exists in Actix, we should be able to do Extractors in Components/Server Functions. We should document that.

Still probably need to handler methods for leptos_actix though

**Comment by gbj** [comment]
Yes this is just a documentation issue, which is awesome. I'll add it to my docs to-do list to show how to do this in both Axum and Actix, but it's super simple thanks to the goodness of the Rust trait system. An extractor in Actix is just a type that implements [`FromRequest`](https://docs.rs/actix-web/latest/actix_web/trait.FromRequest.html), which has an [`extract`](https://docs.rs/actix-web/latest/actix_web/trait.FromRequest.html#method.extract) function. We provide `HttpRequest` via context, so you can just...

```rust
#[server(GetUsers, "/api")]
pub async fn get_users(cx: Scope, page_size: u32, page_number: u32) -> Result<(), ServerFnError> {
    let req = use_context::<HttpRequest>(cx).unwrap();
    let data = actix_web::web::Data::<AppState>::extract(&req).await;
}
```
