### ISSUE TITLE
Uncaught error when using view! class parameter inside a For component

### ISSUE THREAD

**Issue by jmintb** [leptos-rs/leptos#612]
Hello, thanks for the awesome! framework :fire: 

I am getting an error when using  the class parameter for the view macro inside a For component. I have narrowed it down to the code below, if I don't use the class parameter in the view! macro below everything works fine. I don't think this is expected behavior :thinking: 

I will create a reproducible example on Github when I get a moment.

Edit: I would be up for working on this if it turns out to be an actual issue and not just a user error on my part.

The components:

```rust
#[component]
fn ProjectSrcs(cx: Scope) -> impl IntoView {
    let srcs = create_local_resource(cx, || 1, list_project_srcs);

    view! {
        cx,
        {move || { view! {cx, <div class="d-flex flex-wrap">
            <For
            each=move || srcs.read(cx).clone().unwrap_or(vec![])
            key=|s| s.clone()
            view=move |cx, s: String | {
            view! {cx, <Plabel class=" Label Label--danger m-2".to_string() 
                                                     variant=LabelVarient::Danger}></Plabel>
            }} />
    </div> }.into_any()
                 }}

        }
}
```

```rust
#[component]
pub fn plabel(
    cx: Scope,
    variant: LabelVarient,
    #[prop(optional)] class: String,
) -> impl IntoView {
    view! {cx, class={class.clone()},
        <span >  </span>
    }
}

```
Error output from the chrome console:
```
start-axum.js:1191 Uncaught (in promise) Error: `unwrap_throw` failed
    at imports.wbg.__wbindgen_throw (start-axum.js:1191:7)
    at wasm_bindgen::throw_str::he85961a9beb486ef (start-axum.wasm:0x2f698b)
    at <core::result::Result<T,E> as wasm_bindgen::UnwrapThrowExt<T>>::expect_throw::h105f3e946624c7b7 (start-axum.wasm:0x28f4db)
    at wasm_bindgen::UnwrapThrowExt::unwrap_throw::h4845ac204b5dcc59 (start-axum.wasm:0x2e9b1a)
    at leptos_dom::macro_helpers::into_class::class_expression::hf576058d47623c76 (start-axum.wasm:0x208d10)
    at leptos_dom::macro_helpers::into_class::class_helper::h31704eb221654a63 (start-axum.wasm:0x17ba6a)
    at leptos_dom::html::HtmlElement<El>::class::h7a2872dacb907da0 (start-axum.wasm:0x17ca12)
    at web::app::Plabel::__plabel::h676d285b2e57d2d9 (start-axum.wasm:0x17c209)
    at web::app::Plabel::{{closure}}::h6409702c8a62c1cb (start-axum.wasm:0x181122)
    at <leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}::{{closure}}::h95dbd5ca1c793aee (start-axum.wasm:0x189e72)
```

Dependeny versions:
```
├── leptos v0.2.0 (https://github.com/leptos-rs/leptos#cebc824f) (*)
├── leptos_meta v0.2.0 (https://github.com/leptos-rs/leptos#cebc824f)
│   ├── cfg-if v1.0.0
│   ├── leptos v0.2.0 (https://github.com/leptos-rs/leptos#cebc824f) (*)
│   ├── tracing v0.1.37 (*)
│   ├── typed-builder v0.12.0 (proc-macro) (*)
│   ├── wasm-bindgen v0.2.84 (*)
│   └── web-sys v0.3.61 (*)
├── leptos_router v0.2.0 (https://github.com/leptos-rs/leptos#cebc824f)
│   ├── cfg-if v1.0.0
│   ├── common_macros v0.1.1
│   ├── gloo-net v0.2.6 (*)
│   ├── js-sys v0.3.61 (*)
│   ├── lazy_static v1.4.0
│   ├── leptos v0.2.0 (https://github.com/leptos-rs/leptos#cebc824f) (*)
│   ├── linear-map v1.2.0
│   ├── log v0.4.17 (*)
│   ├── percent-encoding v2.2.0
│   ├── serde v1.0.152 (*)
│   ├── serde_urlencoded v0.7.1 (*)
│   ├── thiserror v1.0.38 (*)
│   ├── tracing v0.1.37 (*)
│   ├── wasm-bindgen v0.2.84 (*)
│   ├── wasm-bindgen-futures v0.4.34 (*)
│   └── web-sys v0.3.61 (*)
```

**Comment by gbj** [comment]
This is working as designed, although it may not be ideal — The way it works is by calling a function that adds a class using `classList.add()`. This is erroring because you're passing three classes in a single string, which `classList` rejects. The problem is that if we use it to set the `class` attribute instead of adding a class via `classList` it will wipe out all other classes in the view, which we definitely don't want.

Are you really trying to add all three classes to every element in the view, or only to the top-level `<span/>`? Can they be consolidated into a single class?

**Comment by gbj** [comment]
Okay I came up with a fairly straightforward solution here. It's a small deoptimization to check for multiple class names but is probably worth it, as it's only when using `class = ...` in the view. Try the branch in PR #614 and let me know if it solves the problem for you.

**Comment by jmintb** [comment]
> This is working as designed, although it may not be ideal — The way it works is by calling a function that adds a class using `classList.add()`. This is erroring because you're passing three classes in a single string, which `classList` rejects. The problem is that if we use it to set the `class` attribute instead of adding a class via `classList` it will wipe out all other classes in the view, which we definitely don't want.
> 
> Are you really trying to add all three classes to every element in the view, or only to the top-level `<span/>`? Can they be consolidated into a single class?

I see that makes sense, I was experimenting with how best to support applying classes to custom components. For example when implementing component libraries. It just surpised me that an error was produced. I only have a single element in the component I was experimenting with so I was definitely abusing the macro a bit in this case haha.

> Okay I came up with a fairly straightforward solution here. It's a small deoptimization to check for multiple class names but is probably worth it, as it's only when using `class = ...` in the view. Try the branch in PR #614 and let me know if it solves the problem for you.

That was fast!, it did solve the problem :+1:
