### ISSUE TITLE
Missing response header `Content-Type: text/html; charset=utf-8` in axum integration

### ISSUE THREAD

**Issue by vaniusrb** [leptos-rs/leptos#624]
When trying to use VSCode Remote Tunnels, it adds more headers that end up with the browser considering the page as non-HTML content.

In the `generate_response` function, adding these lines fixes the problem:

```rust
res_headers.insert(
    CONTENT_TYPE,
    HeaderValue::from_static("text/html; charset=utf-8"),
);
```
I believe there is a better solution than this, there seem to be many points where it could be implemented. I don't know if it would be that simple, so I didn't create a PR.

**Comment by gbj** [comment]
I'd say the canonical way to do this is just, in something like an `<App/>` component so it's rendered on every page,
```rust
#[cfg(feature = "ssr")]
if let Some(res_options) = use_context::<leptos_axum::ResponseOptions>(cx) {
  res_options.append_header(CONTENT_TYPE, HeaderValue::from_static("text/html; charset=utf-8"));
}
```

This should you to do it once in a few lines and then forget about it.
