### ISSUE TITLE
feat: allow routes to accept other HTTP verbs

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#627]
It's entirely possible for routes to opt into accepting `POST` or `DELETE` requests or whatever, even though they're currently only set up for `GET` requests. This would allow the traditional multi-page-app/PHP-style process in which, for example, a form page can post to itself and render a response.

We would want to be somewhat careful here in thinking about the client-side-routing story. It's fine if we want to just use a `<form>` and do a page refresh. What does it look like to upgrade this to a `<Form/>` and post to the route without a full-page refresh?

This could work the same way that SSR modes work now: an optional `methods` prop (or `verbs`?) on the `<Route/>` components. If any method is present on any nested route in a full path, then the path can accept that verb, i.e., if I have

```html
<Routes>
   <Route
        path="about"
        view=move |cx| view! { cx,  <About/> }
    >
    <Route
        path="contacts"
        view=move |cx| view! { cx,  <ContactList/> }
        methods=[Method::Post]
    >
        <Route
            path=":id"
            view=move |cx| view! { cx,  <Contact/> }
            methods=[Method::Delete]
        />
        <Route
            path="/"
            view=move |_| view! { cx,  <p>"Select a contact."</p> }
        />
    </Route>
 </Routes>
```
Then `"/about"` only accepts `GET`, `"/contacts"` accepts `GET` or `POST`, and `"/contacts/42"` would accept `GET`, `POST`, or `DELETE`, even if they don't necessarily handle all of those verbs.

Tagging in @underscorefunk whose idea it was and @benwis who was also in this discussion. No obligation for either of you to reply or take any action, just wanted you to know it's on my radar.

**Comment by underscorefunk** [comment]
I think this is a pretty elegant way to progressively enhance the happy path. 

I'm inclined to suggest that methods defaults to [Method::Get]... but if you provide methods=[...] then it's explicit. In the case of /contacts, it would only handle Post. It's maybe a bit more verbose in that you need to specify both, but I think it makes it more clear. I can see people being confused about a route handling a GET when the method only says "Method::Delete". 

In cases like that we could have Method::Any?

My gut tells me that this might be a very ergonomic way to setup a simple JSON api with a set of routes and their path arguments. Almost like defining your interface and then the views or handlers are the implementations elsewhere. 

Totally off topic but it does make me want to have something like this:
```
<Api>
    <ActionRoute
        path="contacts/:id"
        action=get_contacts
        />
</Api>
```
Piggy back on ActionForm :)

**Comment by gbj** [comment]
Parsing a POST request inside a server function during SSR in Axum!

![Screenshot 2023-03-17 at 5 11 52 PM](https://user-images.githubusercontent.com/286622/226052804-944bad71-3eea-4add-b302-20e49707adb5.png)

**Comment by underscorefunk** [comment]
Christmas comes early!!!! :D  ❤️

**Comment by gbj** [comment]
So I still need to write up a good example, and it may be that the APIs need to change between now and the next release, but I wanted to merge this so we have something to work with!
