### ISSUE TITLE
Mounting Element twice (Hydrate/SSR)

### ISSUE THREAD

**Issue by andreanidouglas** [leptos-rs/leptos#635]
When I am using **Hydrate** and **SSR** modes on the same project (e.g.: examples/ssr_modes), what do I need to avoid mounting and displaying <App/> twice?

On the given example, on `main.rs:27`: `<App />` is mounted in the SSR part
and on `lib.rs:18` `<App />` is mounted again...

The generated page then, `<App/>` is shown twice, one as **SSR** and one as **Hydrate**

**Comment by andreanidouglas** [comment]
Initially I was using `wasm pack` + cargo build and I had the issue.

with `cargo leptos watch` there is no issue

**Comment by gbj** [comment]
Sorry, what example are you talking about? Happy to try to help you fix the issue if you can give enough detail that I can reproduce it.

**Comment by andreanidouglas** [comment]
https://github.com/leptos-rs/leptos/tree/main/examples/ssr_modes

**Comment by gbj** [comment]
I'm not able to reproduce this issue in Safari, Chrome, or Firefox when following the instructions in `README.md` and running the following in the `ssr_modes` example
```bash
wasm-pack build --target=web --debug --no-default-features --features=hydrate
cargo run --no-default-features --features=ssr
```

For the sake of information: the two lines you cite don't mount the app twice. The one in `main.rs` only runs on the server side, where it renders the app to HTML; the one in `lib.rs` only runs in the browser, where it "hydrates" the app by adding event listeners and reactivity.

In any case I'm not really sure what's going on here as I can't reproduce.

**Comment by andreanidouglas** [comment]
thank you for your time, i will see if i am doing something wrong on my side.
