### ISSUE TITLE
[Typo] Typo in the readme of the login_with_token_csr example

### ISSUE THREAD

**Issue by nilsdev** [leptos-rs/leptos#645]
https://github.com/leptos-rs/leptos/blob/main/examples/login_with_token_csr_only/README.md

![image](https://user-images.githubusercontent.com/72463901/223689832-4202e5bf-f4c9-4ea5-94c6-69d7d5bc4b80.png)

I know it really isn't important, but I just noticed. Thanks for your work on leptos :).

**Comment by gbj** [comment]
Thanks!
