### ISSUE TITLE
Reexport window.navigator() in leptos_dom

### ISSUE THREAD

**Issue by Chief-Detektor** [leptos-rs/leptos#650]
Hi!
Thanks for this awesome project!
I am building my website and want to be able read out the users language string which is usually returned from the navigator object within the window object in JS world.
The "Navigator" feature is not used in leptos_dom and now I'm wondering which approach would be the best way to archive this:
1. import web_sys with "Navigator" feature myself?
2. Fork leptos_dom and add this as optional feature for leptos_dom?

Any help or hint is highly appreciated.

Thanks in advance!

**Comment by gbj** [comment]
You can just add your own `web-sys` dependency in `Cargo.toml`

`web-sys = { version = "0.3", features = ["Navigator"] }`

and this will be merged with what `leptos_dom` already uses.
