### ISSUE TITLE
compile errors in leptos_macro v0.2.1 on new project

### ISSUE THREAD

**Issue by d4b0zz** [leptos-rs/leptos#664]
**Environment:**
rustc --version
rustc 1.70.0-nightly (8a73f50d8 2023-03-11)
Windows 10, PS 5.1

**Steps to reproduce:**
1. Fresh install
rustup toolchain install nightly
rustup default nightly
rustup target add wasm32-unknown-unknown
cargo install cargo-leptos

2. Setup new project
cargo leptos new --git https://github.com/leptos-rs/start
cd <project_name>

3. run cargo leptos watch and get compile errors:

Compiling leptos_macro v0.2.1
    |
213 |         let encoding = input.parse().unwrap_or(Encoding::Url);
    |                              ^^^^^ the trait `Parse` is not implemented for `Encoding`
    |
    = help: the following other types implement trait `Parse`:
              Abi
              Abstract
              AndAnd
              AndEq
              AngleBracketedGenericArguments
              Arm
              As
              At
            and 254 others
note: required by a bound in `ParseBuffer::<'a>::parse`
   --> C:\_redacted_\.cargo\registry\src\index.crates.io-6f17d22bba15001f\syn-1.0.109\src\parse.rs:467:21
    |
467 |     pub fn parse<T: Parse>(&self) -> Result<T> {
    |                     ^^^^^ required by this bound in `ParseBuffer::<'a>::parse`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `leptos_macro` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
      Notify watching folders assets, style, src
      Leptos ctrl-c received

**Comment by gbj** [comment]
Hi — Can you run `cargo update` and try again? There was an issue that caused about an 8-12 hour gap in the publishing between `0.2.1` and `0.2.2` for some of the crates. I just tried with `0.2.2` and was not able to reproduce.

**Comment by d4b0zz** [comment]
> 

That solved it! Thanks for your quick response on this - looking forward to using leptos!
