### ISSUE TITLE
README starter template build fails and watch doesn't work

### ISSUE THREAD

**Issue by AddictArts** [leptos-rs/leptos#686]
Just tried to use the starter, but it doesn't work out of the box.

This is unfortunate and a show stopper to even having a chance to look at the framework. I thought the issue was related to nightly so I followed the step:

`rustup override set nightly`

This did not work though. It still fails. I don't think I should have to set my whole toolchain to nightly and all projects on my machine.

**Comment by AddictArts** [comment]
The error is `error[E0463]: can't find crate for `core`

**Comment by gbj** [comment]
That error indicates that you do not have the `wasm32-unknown-unknown` target installed for the toolchain you're using.

I'm not sure which example you're trying to run -- Do you just mean the simple counter in the Readme? I'm assuming you read [the section in the Readme on `nightly` vs. `stable`](https://github.com/leptos-rs/leptos#nightly-note).

**Comment by gbj** [comment]
Or do you mean the [`leptos-rs/start`](https://github.com/leptos-rs/start) template? 

In that case, to use stable I think you just need to add the `stable` feature on the Leptos dependencies and then change [this line](https://github.com/leptos-rs/start/blob/2fa8b0648424bdeb3e98b4449eccaeefee2d79df/src/app.rs#L40) from `{count}` to 
```rust
{move || count.get()}
```

**Comment by AddictArts** [comment]
Hi @gbj Thanks

I had that target on stable, but didn't realize I needed to do it again on nightly, but it makes total sense. Apologies.

I was doing this, but now it works after `rustup target add wasm32-unknown-unknown`.

```
cargo leptos new --git https://github.com/leptos-rs/start
cd [your project name]
cargo leptos watch
```

**Comment by gbj** [comment]
Okay, great. For anyone else reading this on future the additional tooling needed to run the starter can be found in the README [here](https://github.com/leptos-rs/start#installing-additional-tools)
