### ISSUE TITLE
feat: make `request_animation_frame`, `request_idle_callback`, and `set_timeout` cancellable

### ISSUE THREAD

**Issue by elliotwaite** [leptos-rs/leptos#693]
Currently, in [leptos_dom/src/helpers.rs](https://github.com/leptos-rs/leptos/blob/main/leptos_dom/src/helpers.rs), there are:
* `request_animation_frame` - not cancellable
* `request_idle_callback` - not cancellable
* `set_timeout` - not cancellable
* `set_interval` - returns a handle, `handle.clear()` → `window().clear_interval_with_handle(self.0)`

It would be nice if they were all cancellable:
* `request_animation_frame` - returns a handle, `handle.cancel()` → `window().cancel_animation_frame(self.0)`
* `request_idle_callback` - returns a handle, `handle.cancel()` → `window().cancel_idle_callback(self.0)`
* `set_timeout` - returns a handle, `handle.clear()` → `window().clear_timeout_with_handle(self.0)`
* `set_interval` - returns a handle, `handle.clear()` → `window().clear_interval_with_handle(self.0)`

I can work on a PR for this, but I wanted to check first to see if this change was actually wanted.

**Comment by gbj** [comment]
Yep, makes perfect sense. I just had to do this [while implementing a simple debounce helper](https://github.com/leptos-rs/leptos/pull/691). Changing the current functions is a breaking change, so for the sake of semantic versioning, you could implement new functions that return their handles, then implement the old functions in term of them, just ignoring the handle.

**Comment by elliotwaite** [comment]
Sounds good. I created a PR (https://github.com/leptos-rs/leptos/pull/698) to also add `request_animation_frame_with_handle(...)` and `request_idle_callback_with_handle(...)`.

However, now `set_interval` seems like the odd one out since it does return a handle. To me, it would seem more consistent if it didn't return a handle, and then `set_interval_with_handle` was also added. But it's somewhat justifiable that `set_interval` does return a handle since it's probably quite rare that someone would want to set an interval callback that they never wanted to cancel.

Do you have a preference between making `set_interval` consistent with the others versus leaving it as is?

Cause if it was preferred to make it consistent, we could add `set_interval_with_handle`, which would be an alias of `set_interval`, and then mark `set_interval` as deprecated until it is updated to not return a handle with one of the future breaking changes updates.

**Comment by gbj** [comment]
Yes adding `set_interval_with_handle` and marking `set_interval` is deprecated is a good approach. I'll open a PR to do that right now.

**Comment by elliotwaite** [comment]
Okay, sounds good.
