### ISSUE TITLE
Allow adding scripts above default head scripts

### ISSUE THREAD

**Issue by chenasraf** [leptos-rs/leptos#694]
### Description

I'm trying to implement a wasm bridge crate ([firebase-wasm](https://github.com/jquesada2016/firebase-wasm-rs)), which loads modules via their npm name. I want to use ESM modules, so I would like to use an [import map](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) to specify a remote CDN instead of NPM module.

This causes an error:

```
An import map is added after module script load was triggered.
```

### How to reproduce

1. Make a minimal app using [leptos-start](https://github.com/leptos-rs/start) (or manually)
2. Add the following code to the `app.rs` right above or below the `<Stylesheet/>` call:
    ```rust
        <script type="importmap">
          {"{
            \"imports\": {
              \"firebase/auth\": \"https://www.gstatic.com/firebasejs/9.18.0/firebase-auth.js\",
              \"firebase/app\": \"https://www.gstatic.com/firebasejs/9.18.0/firebase-app.js\",
            }
          }"}
        </script>
    ```
3. See console - the error appears there. The importmap doesn't work and breaks the rest of the import process.

### Source of issue

This is caused by the file [integrations/utils/src/lib.rs](https://github.com/leptos-rs/leptos/blob/a9f778459a568c27472e37db41a3af85fbf80305/integrations/utils/src/lib.rs#L67)

```rust
    let head = format!(
        r#"<!DOCTYPE html>
            <html{html_metadata}>
                <head>
                    <meta charset="utf-8"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="modulepreload" href="/{pkg_path}/{output_name}.js">
                    <link rel="preload" href="/{pkg_path}/{wasm_output_name}.wasm" as="fetch" type="application/wasm" crossorigin="">
                    <script type="module">import init, {{ hydrate }} from '/{pkg_path}/{output_name}.js'; init('/{pkg_path}/{wasm_output_name}.wasm').then(hydrate);</script>
                    {leptos_autoreload}
                    "#
    );
```

As you can see from the code above, there is a `<script type="module">` being loaded before any user-specified script is provided in the source.

### Expected behavior

I expect some way to hook into the actual HTML content generated at custom points, more specifically hopefully at the top of the `<head>` element, or at the very least above the `<link rel="modulepreload" href="/{pkg_path}/{output_name}.js">` line.

### Possible solutions

1. Maybe a custom property on `script` tags that define their loading priority/position? Maybe with options like `head_top`, `head_bottom`, `body_bottom` etc
  ```html
  <script leptos:hookpoint="head_top" type="importmap">...</script>
  ```
2. Some string loader that you can call before the app's `view! {... }` call that can add to hook points mentioned above
  ```rust
  #[component]
  pub fn App(cx: Scope) -> impl IntoView {
      // Provides context that manages stylesheets, titles, meta tags, etc.
      provide_meta_context(cx);
      provide_custom_html(HtmlHookPosition::HeadTop, "<script type=\"importmap\">...</script>");

      view! {
          cx,
          // ...
      }
  ```

I'm willing to try to take a go at this if an OK is given about the idea

**Comment by gbj** [comment]
I'm not familiar enough with import maps to know the answer: This has to be injected before *any* `<script type="module">` or `<link rel="modulepreload">`, is that correct?

The example you gave using a `<script>` inside a component is just going to put it into the body alongside your component content.

Currently you can use the [`leptos_meta::Script`](https://docs.rs/leptos_meta/0.2.3/leptos_meta/fn.Script.html) component to inject a `<script>` into the `<head>`, but this content will be located below the `<head>` chunk you quote above.

You're very welcome to take a try. It will require changing how [`generate_head_metadata`](https://github.com/leptos-rs/leptos/blob/55ce805b60ce27ca4f475206c00665e7da2923c2/meta/src/lib.rs#L284) works by injecting the head content from `leptos_meta` higher up, and will touch all three of the current integrations (Actix, Axum, Viz) as far as I can tell.

**Comment by chenasraf** [comment]
> I'm not familiar enough with import maps to know the answer: This has to be injected before _any_ `<script type="module">` or `<link rel="modulepreload">`, is that correct?

Yes, that is correct

> Currently you can use the [`leptos_meta::Script`](https://docs.rs/leptos_meta/0.2.3/leptos_meta/fn.Script.html) component to inject a `<script>` into the `<head>`, but this content will be located below the `<head>` chunk you quote above.
> 
> You're very welcome to take a try. It will require changing how [`generate_head_metadata`](https://github.com/leptos-rs/leptos/blob/55ce805b60ce27ca4f475206c00665e7da2923c2/meta/src/lib.rs#L284) works by injecting the head content from `leptos_meta` higher up, and will touch all three of the current integrations (Actix, Axum, Viz) as far as I can tell.

I will do my best :) 

Which approach do you think should be taken here?

**Comment by gbj** [comment]
I think this would've been a little too tricky and I discovered it was quicker for me to work through it myself than describe it.

Check out PR #731 and see if that fixes the issue adequately. If it does, I'll test this against the other examples to make sure I didn't break anything, and merge it as the default behavior.
