### ISSUE TITLE
Misbehaving `DynChild` in hydrate mode with SSR optimizations

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#697]
This will double-render the SVG on the first change. ~If I use CSR or swap `Mode::default()` for `Mode::Client` it's fixed, which suggests it's something in the SSR opt interacting with hydration.~
```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    let (menu_open, set_menu_open) = create_signal(cx, false);

    let menu = move || {
        if menu_open.get() {
            view! {cx, <svg width="50" height="50" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>}
        } else {
            view! {cx, <svg width="50" height="50" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5"/></svg>}
        }
    };

    view! { cx,
        <button on:click=move |_| set_menu_open.update(|n| *n = !*n)>"Toggle"</button>
        {menu}
    }
}
```

**Comment by Houski** [comment]
Another clue may be if you change this to default to true instead of false:

`    let (menu_open, set_menu_open) = create_signal(cx, true);`
    
It seemingly fixes the issue.

**Comment by gbj** [comment]
Looks like this is actually one of a handful of bugs I've seen that are introduced by the comment markers I've inserted around each `view` invocation as part of building hot-reloading support for cargo-leptos. I think I was actually butting my head against it in my own app this morning, so I'm glad to have (hopefully) figured out at least this iteration of it.
