### ISSUE TITLE
Put WASM Bindgen under a feature flag for Leptos Reactive

### ISSUE THREAD

**Issue by MinusGix** [leptos-rs/leptos#720]
It would be nice for programs that aren't intended to run in a web-browser (or, which have optional support for it) that directly use Leptos Reactive ([floem](https://github.com/lapce/floem) is my motivation) to avoid including bindgen (and friends, like web-sys, js-sys, and serde-wasm-bindgen).

**Comment by gbj** [comment]
Eminently reasonable request, should be done now.
