### ISSUE TITLE
Accessing to body: web::Bytes in server functions actix integration 

### ISSUE THREAD

**Issue by sichacvah** [leptos-rs/leptos#744]
Hello! I want to create server action for file uploading, but can't get Multipart from scope. Seems like web::Body not provided to context. Is we have any possibility to get Multipart or web::Body from HttpRequest or from Scope? Or it not idiomatic way and i need just create pure actix endpoint for file uploading?

**Comment by gbj** [comment]
The `actix_web::HttpRequest` type is provided via the scope. The way Actix extractors work is by implementing a `FromRequest` trait. So you can do something like this (apologies for any typos, it's from memory but should be enough to get you headed in the right direction)

```rust
use actix_web::{HttpRequst, web, FromRequest}'
#[server(UploadFile, "/api")] 
pub async fn upload_file(cx: Scope) -> Result<String, ServerFnError> {
  let req = use_request::<HttpRequest>(cx).unwrap();
  let body = <web::Body as FromRequest>::extract(&req)
        .await
        .unwrap();
  todo!()
}
```
