### ISSUE TITLE
Do not require FooProps for component Foo to be imported

### ISSUE THREAD

**Issue by MarekWojt** [leptos-rs/leptos#746]
When I import a custom component, for it to be used it is required to import its props as well. I feel this might be unintuitive and confusing to new users and produces boilerplate code.

I would suggest binding a component's props to it by trait. This way, instead of internally using FooProps for the props, Foo::Props could be used. By having that trait present in the prelude, there would be no extra code needed to make it work while simultaneously ensuring backwards compatibility.

Unfortunately I currently do not have the knowledge nor time to implement these changes myself and create a pull request, that's why I create this issue.

**Comment by gbj** [comment]
Yes this would be nice and different options for it have been discussed. Your suggestion isn't possible unfortunately, because you can't implement traits for `fn` pointers (as far as I know) because they are values, not types. So you can't implement something like a `Component` trait for a function `MyComponent` that has an associated type.

Others have proposed that the framework should rewrite your components from functions to structs, so that
```rust
#[component]
pub fn MyComponent(cx: Scope, a: i32, b: String) -> impl IntoView {}
```
becomes 
```rust
struct MyComponent {
  a: i32,
  b: String
}

impl Component for MyComponent {
  fn view(self) -> View {
  }
}
```
Personally, I don't really like the idea of the macro rewriting someone's code to such an extent that something you declare as a function with arguments ends up as a struct of the arguments... that's a little too "black box macro magic" for me, and I prefer the trade-off of deriving a Props type and requiring it to be imported, which I think we've documented pretty well.

If people have ideas for other ways to do this, I'm very open to them.

**Comment by takeisit** [comment]
I'm not sure that it works well, how about this?

component! macro generates roughly from

```rust
// in other_mod
pub fn MyComponent(cx:Scope, message: &'static str) -> impl IntoView {
    view!{cx, {message}}
}
```

to

```diff
#[derive(TypedBuilder)]
pub struct MyComponentProps {
    pub message: &'static str,
}

+ #[cfg(not(feature = "stable"))]
+ impl FnOnce<(MyComponentPropsBuilder,)> for MyComponentProps {
+     type Output = MyComponentProps;
+ 
+     extern "rust-call" fn call_once(self, _args: (MyComponentPropsBuilder,)) -> Self::Output {
+         self
+     }
+ }

- pub fn MyComponent(cx:Scope, props: MyComponentProps) -> impl IntoView {
+ pub fn MyComponent(cx:Scope, f: impl FnOnce(MyComponentPropsBuilder) -> MyComponentProps) -> impl IntoView {
+     let props = f(MyComponentProps::builder());

    fn __MyComponent(cx:Scope, message: &'static str) -> impl IntoView {
        view!{cx, {message}}
    }
    let MyComponentProps { message } = props;
    __MyComponent(cx, message)
}

```

usages
```rust
use other_mod::MyComponent;

view! { cx,
  <>
    // view! macro generates from
    <MyComponent message="generate by view! macro like this" />
    // to 
    {MyComponent(cx, move|builder| builder.message("generate by view! macro like this").build())}

     // without view! macro
    {MyComponent(cx, other_mod::MyComponentProps{ message: "without view! macro (nightly)" })}
    {MyComponent(cx, |_| other_mod::MyComponentProps{ message: "without view! macro (stable)" })}
  </>
}

```

**Comment by Lej77** [comment]
While it's not possible to directly write a trait impl for a function type it is possible to write blanket traits for all `Fn` types. That blanket impl can then infer the types of the functions parameters and interact with those via any traits they implement. So 
I think this issue could be solved if the [`component` macro](https://docs.rs/leptos/0.2.5/leptos/attr.component.html) generated a trait implementation for the props type.

This is actually exactly how [sycamore solves this problem](https://github.com/sycamore-rs/sycamore/blob/3885a9e67c8cbb6042f5a758965338df95930580/packages/sycamore-core/src/component.rs#L48-L102).

For example, [a component like](https://github.com/leptos-rs/leptos/blob/2a13609efffa82526b5a9108554365e8ee0802ad/examples/counter/src/lib.rs):

```rust
#[component]
pub fn SimpleCounter(
    cx: Scope,
    /// The starting value for the counter
    initial_value: i32,
    /// The change that should be applied each time the button is clicked.
    step: i32
) -> impl IntoView { /* ... */ }
```

is currently [expanded to](https://github.com/leptos-rs/leptos/blob/64e056ffa97595fcedb65ff8c1e9afb49fa61bfc/leptos_macro/src/component.rs#L192-L224) (with the help of the [TypedBuilder](https://docs.rs/typed-builder/0.14.0/typed_builder/derive.TypedBuilder.html#) macro):

```rust
pub struct SimpleCounterProps {
    pub initial_value: i32,
    pub step: i32,
}
impl SimpleCounterProps {
    pub fn builder() -> SimpleCounterPropsBuilder<((), ())> { /* ... */ }
}
pub struct SimpleCounterPropsBuilder<TypedBuilderFields = ((), ())> {
    fields: TypedBuilderFields,
    phantom: (),
}
/* Lots of impls for the builder... */

pub fn SimpleCounter(cx: ::leptos::Scope,
    props: SimpleCounterProps) -> impl IntoView { /* ... */ }
```

The type of the `SimpleCounter` functions second parameter can be inferred using a trait like:

```rust
pub trait Component<P> {}

impl<P, F, R> Component<P> for F
where
    F: FnOnce(::leptos::Scope, P) -> R,
{}
```

The props type can then be interacted with using another trait:

```rust
pub trait Props {
    type Builder;
    fn builder() -> Self::Builder;
}
```

that the `component` macro would derive:

```rust
impl Props for SimpleCounterProps {
    type Builder = SimpleCounterPropsBuilder;
    fn builder() -> Self::Builder {
        SimpleCounterProps::builder()
    }
}
```

finally all of these traits could be used by a helper function to create the builder by only specifying the name of the function:
```rust
#[doc(hidden)]
pub fn component_props_builder<P: Props>(_f: &impl Component<P>) -> <P as Props>::Builder {
    <P as Props>::builder()
}
```

A `view` macro invocation such as:

```rust
view! { cx,
    <SimpleCounter
        initial_value=0
        step=1
    />
}
```

that previously expanded to:

```rust
SimpleCounter(
    cx,
    SimpleCounterProps::builder()
        .initial_value(
            #[allow(unused_braces)]
            0,
        )
        .step(
            #[allow(unused_braces)]
            1,
        )
        .build(),
)
```

could then instead be expanded to:

```rust
SimpleCounter(
    cx,
    ::leptos::component_props_builder(&SimpleCounter)
        .initial_value(
            #[allow(unused_braces)]
            0,
        )
        .step(
            #[allow(unused_braces)]
            1,
        )
        .build(),
)
```

[Here is a playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ca33d0468928148d27253dc2e48f4436) that shows how this could work.

**Comment by gbj** [comment]
@Lej77 I cannot tell you how helpful this is. Thank you so much. 

I will be able to get around to this in a few weeks, I think. In the meantime, if anyone wants to make a PR, I and the entire community will thank you.
