### ISSUE TITLE
docs: unresolved import `web_sys` when compiling 3.8 parent-child communication 

### ISSUE THREAD

**Issue by jfloresremar** [leptos-rs/leptos#753]
Thank you for your great book!. I'm learning rust and leptos together

I'm running the sample code of each chapter with copy & paste with this sequence:
```console
cargo new demo9-parent-child-communication
cd  demo9-parent-child-communication
cargo add leptos
trunk serve
```
It was fine on previous sections but on section 3.8  it gives me an error:

```console
error[E0432]: unresolved import `web_sys`
 --> src\main.rs:2:5
  |
2 | use web_sys::MouseEvent;
  |     ^^^^^^^ use of undeclared crate or module `web_sys`

error[E0277]: expected a `FnMut<(MouseEvent,)>` closure, found `F`
   --> src\main.rs:89:22
    |
89  |             on:click=on_click
    |             --       ^^^^^^^^ expected an `FnMut<(MouseEvent,)>` closure, found `F`
    |             |
    |             required by a bound introduced by this call
    |
note: required by a bound in `HtmlElement::<El>::on`
   --> C:\Users\jfr\.cargo\git\checkouts\leptos-2c8932a5258b3db6\97d88c6\leptos_dom\src\html.rs:712:33
    |
712 |         mut event_handler: impl FnMut(E::EventType) + 'static,
    |                                 ^^^^^^^^^^^^^^^^^^^ required by this bound in `HtmlElement::<El>::on`
help: consider further restricting this bound
    |
84  |     F: Fn(MouseEvent) + 'static + std::ops::FnMut<(leptos::ev::MouseEvent,)>,
    |                                 ++++++++++++++++++++++++++++++++++++++++++++

Some errors have detailed explanations: E0277, E0432.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `demo9-parent-child-communication` (bin "demo9-parent-child-communication") due to 2 previous errors
```
I followed these instructions:
https://github.com/rustwasm/wasm-bindgen/issues/1039#issuecomment-439784257
and the sample code compiles fine.

I'm not an expert so i could not explain the cause of the error but maybe it helps somebody

Cargo.toml content:

[package]
name = "demo9-parent-child-communication"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { git = "https://github.com/leptos-rs/leptos" }
console_log = "0.2"
log = "0.4"
console_error_panic_hook = "0.1.7"

[dependencies.web-sys]
version = "0.3"
features = [ "console" ]

**Comment by gbj** [comment]
Sorry about that! Leptos does now reexport events so you should be able to `use leptos::ev::MouseEvent;` instead of needing to add a `web-sys` dependency. I've updated the CodeSandbox example.
