### ISSUE TITLE
Async SsrMode Not Working in Axum

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#765]
I've setup a basic blog with meta tags, and added <Meta> tags to the posts page. All of the resources seem to be loading in the default streaming mode, and not in async. Meta tags like og:image are not set until WASM loads, which won't do.

**Comment by gbj** [comment]
For anyone reading, we figured this one out — It was just because routes were being passed off to a custom handler that was using streaming, not async rendering.
