### ISSUE TITLE
Bug: Memoizing attributes/props breaks `value` for `<input />` elements

### ISSUE THREAD

**Issue by jquesada2016** [leptos-rs/leptos#768]
When setting the value prop fo an `<input />` to a signal which yields the same value, does not update the value correctly. Here's an example:

```rust
mount_to_body(|cx| {
  use leptos_daisyui_components::{
    TextInput,
    TextInputProps,
  };

  let (read, write) = create_signal(cx, "$0.00".to_string());

  view! { cx,
    <input prop:value=read on:input=move |_| write("$0.00".into()) />
    <input prop:value=read />
  }
});
```

In the above example, the `value` prop is being set to `$0.00` on any inpu event. This should essentially disable typing for the user on `<input />`. Currently this does not work because values are being memoized internally.

We should remove attribute/property memoization, or provide an entry point where we can opt out of it, such as `unmemoized_prop:value`.

...I know, it's the greatest name you've ever heard!

**Comment by jquesada2016** [comment]
Yes, this is right, but why is this not considered a bug, as it's not the expected behavior? Memoizing values and attributes may not be a worthwhile optimization, since these things tend to be set once, and then updated as events come in, making performance a non-problem, I think.

**Comment by jquesada2016** [comment]
Perhaps opting in to this behavior, via `Memo` might be the better strategy?

What do you think?

**Comment by gbj** [comment]
Ah, thanks. I had not previously linked this in my mind with the fact that it was memoized, but of course you're correct. Removing memoization on property values fixes this whole set of issues, which is really good. Would you like to make a PR or should I?

**Comment by jquesada2016** [comment]
If you can do it, I'd be very grateful! I'm mega busy working on a small project right now so only really have time whenever I find an issue like this. I still need to finish fixing the `<For />` algorithm, which I haven't been able to do because it's a little hard and haven't had a solid chunk of time to finish it :(
