### ISSUE TITLE
RFC: Typed Component Children for `view!` Macro

### ISSUE THREAD

**Issue by jquesada2016** [leptos-rs/leptos#769]
# Summary

Allow specifying typed children of components at compile-time rather than at runtime.

# Motivation

Currently, components can only have a default `children` prop that accepts a fragment, which can contain any type of child. This can be restrictive for API possibilities, and is less compile-time safe, since components cannot explicitely opt in to requiring specific child components from being present.

Let's take as an example an `<If />` component. I will be using this, as it's a familiar construct to many, although this can apply to many other components, such as leptos' `<Router />`.

Let's say I would like to support the following API:

```rust
view! { cx,
  <If signal=a_is_true>
    <Then>"show content when a is true"</Then>
    <ElseIf signal=b_is_true>"b is true"</ElseIf>
    <ElseIf signal=c_is_true>"c is true"</ElseIf>
  <Else>"none of the aboe are true"</Else>
  </If>
}
```

As the API stands right now, the only way to support this, is to take a fragment which must be checked at runtime to make sure the children you require exist, and decide what to do with extrenuous children..

One possibility would be for us to do:

```rust
#[component]
pub fn If(
  cx: Scope,
  signal: MaybeSignal<bool>,
  then: Then,
  else_if: Option<Vec<ElseIf>>,
  else_: Option<Else>,
) -> impl IntoView { /* ... */ }
```

This would be far from ideal, because it promotes "flow breaks", which is what I call when you need to break out of the current `view!` in order to define your input outside of it, and then come pack to the flow of your component. In this example, this would be:

```rust
let then = view! { cx, /* ... */ };

view! { cx,
  <If signal then />
}
```

or, even worse:

```rust
view! { cx,
  <If signal then=view! { cx, /* ... */ } />
}
```

Thus, we need a better way to be able to declare inline where component children should go.

# Guide-level Explanation

Let's introduce the concept of `slots`. The idea is borrowed from Svelte. A slot is a pseudo attribute that can be added to children of a component to denote that they should not be included into a component's default children. For example:

```rust
view! { cx,
  <If signal>
    <Then slot:then>/* ... */</Then>
  </If>
}
```

Here, whe're telling the `view` macro that the `<Then />` child should not be included in `.children()`, but rather in `.then()`. This can be rewritten, and is equivalent to:

```rust
view! { cx,
  <If signal then=view! { cx, <Then>/* ... */</Then> } />
}
```

This has the advantage of components which relied on the following pattern:

```rust
#[component]
fn SomeComponent(cx: Scope, fallback: Children, children: Children) -> impl IntoView { /* ... */ }

// ...

view! { cx,
  <SomeComponent fallback=view! { cx, /* ... */}>
    <p>"show me"</p>
  </SomeComponent>
}
```

to work with the new slot API without needint to be migrated:

```rust
view! { cx,
  <SomeComponent fallback=view! { cx, <p>"fallback"</p>}>
    <p>"show me"</p>
    <p slot:fallback>"fallback"</p>
  </SomeComponent>
}
```

# Reference-level explanation

The biggest challenge we have for implementing this, is the fact that components are not typable, since they are just functions, and functions cannot currently be typed. However, we have the props, which can be typed, and we know we can create a component given the props and the component function. I propose that:

```rust
view! { cx,
  <If>
    <Then slot:then></Then>
  </If>
}
```

be expanded to:

```rust
If(
  cx,
  IfProps::builder()
    .then(ThenProps::builder().build())
    .build()
)
```

And if component authors need to accept anything that is not a `#[component]`, but would like to be emulated as one, perhaps such as the `<Route />`, it can be done as so:

```rust
pub struct RouteProps { /* ... */ }

#[component]
pub fn Routes(cx: Scope, route: Vec<RouteProps>) -> impl IntoView { /* ... */ }
```

There are 3 cases I think we should keep in mind. Slotted children can appear:

- 0 times
- 1 time
- n times

For the first 2 cases, `#[prop(optional)]` should be more than enough. For the final case, if the `view!` macro sees the slot appears more than once, they should all be placed into a `vec![]`.

In all cases, `.into()` should be called on the type to allow supporting enum and other types, as well as allowing repeating types to go into a `Vec`.

For example, let's say we have:

```rust
enum CompAProps {
  One(OneProps),
  Two(TwoProps),
}

#[derive(TypedBuilder)]
struct OneProp { /* ... */ }
#[derive(TypedBuilder)]
struct TwoProp { /* ... */ }

impl From<OneProps> for CompAPropS {
  fn from(one: OneProps) -> Self {
    Self::One(one)
  }
}

impl From<TwoProps> for CompAPropS {
  fn from(two: TwoProps) -> Self {
    Self::One(two)
  }
}

#[component]
fn Comp(cx: Scope, a_prop: CompAProps, a_prop_multiple: Vec<CompAProps>) -> impl IntoView { /* ... */ }
```
In the above example, struct `OneProps` and `TwoProps` can be converted into `CompAProps` using the `Into` trait: This allows components to be able to take a well-typed set of children for any given prop.

```rust
view! { cx,
  <Comp>
    <One slot:a_prop />
    <One slot:a_prop_multiple />
    <Two slot:a_prop_multiple />
  </Comp>
}
```

We also need to provided named variants of `Fragment` (`<></>`) and `Text` (`" ... "`) components, since we need a tag-like to use the `slot:name` pseudo attribute. These should be done in the `view!` macro, in my opinion.

It would also be nice to provide a shorthand syntax for when components have the same name as their slot, perhaps just `slot`

```rust
view! { cx,
  <Routes>
    <Route slot />
    <Route slot />
    <Route slot />
  </Routes>
}
```

which the macro can deduce by removing the `Prop` at the end and converting to `snake_case`.

# Drawbacks

Adding `slot` pseudo attribute to child components can possibly be a little annoying.

# Rationale and alternatives

Most of the API described above came up from me needing to tie generics between a parent and child component, which is not currently possible. This API would make that use case possible to create more type-safe and thus less error prone components.

Most of what was proposed in the reference-level guide, are attempts at jumping through hoops placed by the choice to use functions instead of structs to represent components. In this case, I don't think it's too much of a problem, but perhaps  a motivation for consideration for the future.

# Prior art

This particular implementation came as an inspiration from `Svelte` and the way they handle component children. The way we would do it, would be much more powerful because in `Svelte`, it's not possible to check what type component children are, for us, we would not only know the types, but be able to manipulate them directly.

# Unresolved questions

- [ ] Is `slot` the best name?
- [ ] Are there other, better way to comunicate with the `view!` macro the component should not be in the default `children` slot?
  
  Regarding this point, it would be worth pointing out that we may be able to "reverse" this approach. As in, assume component children belong to a slot and default children would need to be annotated, perhaps with `default` or something similarly...it be a very good idea to consider if most components don't care about their children, if so, then `slot` might be better, but if most components _do_ care about the types of their children, it may be best to go with the opposite.
- [ ] supporting parent components passing props to children

   This is an important question to answer, because if we want to do this, we should explain this mechanism now, as it will most likely be a breaking change in the future if we don't think about this scenario now. I'll explain a _possible_ implementation of this in the case we would care to try and implement it. If not, the traditional context channels can be used to pass props down from parent to child.

# Future Possibilities

## Passing Props to Children

Imagine we wanted to port `<For />` to use this slot API.

```rust
view! { cx,
  <For each key>
    <Fragment prop:item>
      <p>"This item is: " {item}</p>
    </Fragment>
  </For>
}
```

We should discuss if the above is something we would like to support, and if so, the best mechanism to do so.

**Comment by jquesada2016** [comment]
This RFC may also address #766.

**Comment by gbj** [comment]
Sorry for the slow response here.

I think it makes sense to provide some way to build typed props without breaking out of the RSX syntax, especially for things like `<Then/>` in this example that are basically just `children`. As I understand it, the proposal is that adding `<Y slot:y/>` to a component that is a child of another component should construct `YProps` and pass them to the parent as the property `y`, but not run the component `<Y/>`. This provides an alternative to something like
```
<X y=Y { /* some struct or function call */ }/>
```

In other words, "slots" are an alternative to "render props."

I would be interested in seeing a reference implementation of this in the macro.

Some open questions to consider:
- Does this return `YProps` or does it return a `Fn(Scope) -> YProps`? In many cases the callback form is necessary here to have the correct ordering of `Scope`s in the tree that's being constructed.
- Is it unintuitive that `<Y/>` runs the body of the `fn Y`, and `<Y slot:y/>` does not? 
- Can we make this play nicely with hot-reloading?

I think you probably know me well enough at this point to know that I am *always* going to default to the minimum in terms of syntactic sugar. Personally, I would rather write
```
<If signal
  then=|cx| view! { cx, /* ... */ }
  else=|cx| view! { cx, /* ... */ }
/>
```
than
```
<If signal>
  <Then slot:then>/* ... */</Then>
  <Else slot:else>/* ... */</Else>
</If>
```
but I also understand that I am not the only user of this library! :smile:

**Comment by maccesch** [comment]
I personally would love slots. Coming from Vue this is one of the features I really loved to write ergonomic reusable components. In my opinion it would be easier to read. And easier to learn coming from other frameworks.

**Comment by vldm** [comment]
I know it's a bit outdated, but i found that current implementation is not fully cover the case of first snippet from RFC.

Is there any reason to enforce placing attribute "slot" inside component?

@gbj Maybe leptos can generate builder with typed `.child()` instead of `.children()` ?

So slots example can be rewritten :
```rust
view! { cx,
<SlotIf cond=is_even>
   <Then>"even"</Then>
    <ElseIf cond=is_div5>"divisible by 5"</ElseIf>
    <ElseIf cond=is_div7>"divisible by 7"</ElseIf>
    <Fallback>"odd"</Fallback>
</SlotIf>
}
```
And expansion will look like
```rust
  SlotIf(cx, ::leptos::component_props_builder(&SlotIf)
        .cond(is_even)
        .child(ElseIf::builder()
              .cond(is_div5)
              .children(...).build().into())
        .child(ElseIf::builder()
              .cond(is_div7)
              .children(...).build().into())
        .child(Then::builder()
              .children({...}).build().into(),)
        .child(Fallback::builder().children({...}).build().into(),)
        .build())
```

This probably can be compatible with current `children` implementation, to do it, builder should collect second or more call to `fn child` and wrap them to `Fragment`

**Comment by jquesada2016** [comment]
@vldm the reason we need a `slot` attribute is to communicate with the `view` macro to tell it that the component should be treated specially. Otherwise, there's no way to tell if a child should be a typed child, or a default child.

**Comment by vldm** [comment]
> @vldm the reason we need a `slot` attribute is to communicate with the `view` macro to tell it that the component should be treated specially. Otherwise, there's no way to tell if a child should be a typed child, or a default child.

@jquesada2016 I see, but what do you think, is it possible to change builder, so instead of generating single `fn children(` it will instead generate `fn child(impl IntoView)` and internally collect all children to it. And only emiting it during `fn build`?

So there will be no differences for view macro, is it typed child or default.

**Comment by jquesada2016** [comment]
@vldm as written, this wouldn't really be possible because how would you know where to place which child? `.children()` is where default children are placed into, i.e., those without a `slot` attribute. Children that have a `slot` attribute are treated the same as if they were props.

```
<MyComp prop_1={view! { cx, <Child />}}>
</MyComp>
```

is the exact same thing as doing:

```
<MyComp>
  <Child slot:prop_1 />
</MyComp>
```

Since were using compile-time type checking with slots, changing the builder to use `.child()` and then passing the children to the component builder wouldn't work for 2 reasons

1. There's no easy way to forward the children to their repsective prop
2. Because of 1, this would need to be done at runtime, which would defeat the purpose

**Comment by vldm** [comment]
>There's no easy way to forward the children to their repsective prop

We can use position argument/props instead of named props for passing typed child. So it will be more like function call.

Yes, i understand that slot has it's usecase, and it's more convenient to pass prop by it's name, but for short components, avoiding "slot" can enhance usability. Especially for components with only one child.

I will try to implement some examples for `Builder` (with typed child and default), in order to show my vision.

**Comment by jquesada2016** [comment]
@vldm I think relying on position for typed children is a really bad idea, as it breaks the mental model of components, and requires users to learn or check the order of children. I do see the similarity, however, of function calls, but it's not the same mental model.

What I think might be a more reasonable alternative, would be instead to mark the parent component as having all children be slots, like this, `slot` is implied for all children.

Perhaps something like:

```
<ParentWithOnlySlots slottable>
  <Child1 /> // slot:child_1
  <Child2 /> // slot:child_2
</ParentWithOnlySlots>
```

Nevertheless, though this _is possible_, I would argue against it, just because, although it is a little more verbose, it's very flexible, and having to worry about checking 2 places to see if a component is a slot or not, is more cumbersome, in my opinion.

@gbj any additional thoughts here?

**Comment by vldm** [comment]
@jquesada2016 
> as it breaks the mental model of components

I am not sure why it should break mental model. It's just a method of handling childs.
It's already possible in runtime to get child by its possition and change it's behaviour (hide, or modify it), what i suggest is just move it on type level.

Moreover, for declarative `If` component positional component (with type check) can be better then passing by named slots.

Imagine example from slots:

```rust
       <SlotIf cond=is_even>
            <ElseIf slot cond=is_div5>"divisible by 5"</ElseIf>
            <Then slot>"even"</Then>
            <ElseIf slot cond=is_div7>"divisible by 7"</ElseIf>
        </SlotIf>
```

I have reordered `elseif` and `then` so code still compile, but it is now less readable.
In positional slots - compiler will complain that "then" is expected as first "if" positional slot.

For an imaginary match/switch component, it's also doesn't metter is it implemented by position slots, or by named.

```rust 

<Switch value=foo>
    <Case cond=|| value==1>/* ... */</Case>
    <Case cond=|| value==2>/* ... */</Case>
    <Case cond=|| value==3>/* ... */</Case>
</Switch>
```

I think, it's also possible to mix them together in some cases.
