### ISSUE TITLE
global_class disappear

### ISSUE THREAD

**Issue by luoxiaozero** [leptos-rs/leptos#773]
When the button was clicked, the class changed from 'melt-button melt-button--text my-test' to 'melt-button', and the 'my-test' class disappeared.
Is this normal?
```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    let (button_type, set_button_type) = create_signal(cx, "TEXT".into());
    view! { cx,
        <Button on:click=move |_| set_button_type.update(move |value| *value = "PRIMARY".into()) type_=button_type> 
            "click"
        </Button>
    }
}

#[component]
pub fn Button(
    cx: Scope,
    #[prop(optional, into)] type_: MaybeSignal<String>,
    children: Children,
) -> impl IntoView {
    let class_name = "my-test";
    let class = move || {
        if type_.get() == String::from("TEXT") {
            "melt-button melt-button--text"
        } else {
            "melt-button"
        }
    };
    view! {cx, class=class_name,
        <button class=class>
            {children(cx)}
        </button>
    }
}
```
leptos: `{ version = "0.2.4", features = ["stable"] }`

**Comment by gbj** [comment]
I’m actually surprised that it _ever_ applied `my-test`. I would’ve expected the global class to be overridden by `class=class` in both cases. But you could do
`
view! { cx, class=class_name,
  <button class:melt-button=true
    class:melt-button-text=move || type_.get() == "TEXT"
  // …
`
(although maybe an enum for the type would be better than a string!)

Not sure if your use case here is more complex, but using the global class for a single element doesn’t really make sense; it’s intended for things like scoped CSS where it needs to be applied to every single element in the tree.

**Comment by luoxiaozero** [comment]
I'm giving you a simple example here. I actually use the scoped CSS functionality provided by [stylers](https://github.com/abishekatp/stylers).
For this example，the CSS naming convention I use is [BEM](https://getbem.com/naming/), which requires' -- '

**Comment by gbj** [comment]
For any class names that can't be parsed by the macro (possibly one with `--`) you can use a slightly different syntax `class=("melt-button--text", true)`
```rust
view! { cx, class=class_name,
  <button
    class:melt-button=true
    class=("melt-button-text", move || type_.get() == "TEXT")
  // …
```

**Comment by luoxiaozero** [comment]
good

**Comment by gbj** [comment]
> Although this can be solved, I think it is still necessary to solve the inconsistency problem in these two cases

Yes, agreed. I'm keeping it open and will work on it.

**Comment by gbj** [comment]
So this turned out to be genuinely hard to solve without adding some kind of runtime check that would add overhead across the board. I opted instead to have the `view` macro emit an error if you tell it to do this, with some instructions and a link to this issue. (See #850) I'd like to find a better way to do this but at least now it will not let you compile code that is going to be bugged at runtime.
