### ISSUE TITLE
MDX?

### ISSUE THREAD

**Issue by songlinshu** [leptos-rs/leptos#774]
HI,leptos rendering Markdown with embdedded dynamic leptos components

**Comment by gbj** [comment]
There’s no support for this at this time. It would be possible to create a library to do it in user-land without additional support from the framework, I think. 

I’ll leave the issue open in case others are interested in the idea, but I don’t have any plans for MDX support.

**Comment by benwis** [comment]
While not mdx, a couple of us are compiling regular markdown with [femark](https://crates.io/crates/femark). Perhaps that could work as a substitute or might help you create your own MDX compiler
