### ISSUE TITLE
`leptos_meta` does not work?!

### ISSUE THREAD

**Issue by d-hain** [leptos-rs/leptos#796]
I just wanted to try out the [darkmode example](https://github.com/leptos-rs/example-darkmode) without using ssr because I don't need it, so I made this:
```rust
use leptos::*;
use leptos_meta::*;

pub fn main() {
    _ = console_log::init_with_level(log::Level::Debug);
    console_error_panic_hook::set_once();
    
    mount_to_body(|cx| view! { cx, <App /> })
}

#[component]
pub fn App(cx: Scope) -> impl IntoView {
    provide_meta_context(cx);
    
    view! {
        cx,
        
        <Title text="test" />
        <Stylesheet href="/style.css" />
        
        <main>
            <h1>"Hello, World"</h1>
        </main>
    }
}
```
And even without the darkmode code the `Title` and `Stylesheet` components do not work.

# My file structure:
/src/main.rs (the file with the code given above)
/Cargo.toml (version 2.4 of `leptos` and `leptos_meta`)
/index.html
/style.css

## `index.html`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Appointments Manager</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link data-trunk rel="rust" data-wasm-opt="z"/>
    <!--<link data-trunk rel="icon" type="image/ico" href="/public/favicon.ico"/>-->
</head>
<body>

</body>
</html>
```

## `style.css`
```css
body {
    text-align: center;
}
```

**Comment by gbj** [comment]
Make sure that you've enabled one of the features in `leptos_meta` in Cargo.toml (`csr`, `ssr`, or `hydrate`)

**Comment by d-hain** [comment]
Ohhhh, that was it.
Thank you so much for your fast reply. :D

**Comment by gbj** [comment]
All good! I've added a runtime warning for this, so that it's less confusing for anyone who comes across it in the future.
