### ISSUE TITLE
leptos_meta compilation error

### ISSUE THREAD

**Issue by MinaMatta98** [leptos-rs/leptos#798]
Hello,

Firstly, thanks for the amazing crate.

I find myself running into an issue where I am receiving a compilation error upon setting the following within my Cargo.toml:

```leptos_meta = { version = "0.2.3", features = ["ssr"] }```

When the ssr feature is turned off, compilation is smooth and works, when it's on I get the following compilation error:

`error[E0599]: no method named render_to_string found for enum leptos::View in the current scope
   --> /home/mina/cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_meta-0.2.5/src/lib.rs:125:51
    |
125 |                 builder_el.clone().into_view(*cx).render_to_string(*cx)`
    |                                               

I have attached my Cargo.toml.

The following is my version of rustc: 1.70.0-nightly (3a8a131e9 2023-04-02)

Any help with this issue will be greatly appreciated. If I find a solution beforehand, I will post it.

[Cargo.toml.txt](https://github.com/leptos-rs/leptos/files/11142620/Cargo.toml.txt)

**Comment by gbj** [comment]
`leptos` defaults to `csr` so your `leptos` dependency should have `default-features = false`. Let me know if that fixes it. (Latest release is 0.2.5 too for what it's worth)

**Comment by MinaMatta98** [comment]
Unfortunately, I have set the `default-features = false` as per the following but the error persists:

leptos_actix = { version = "0.2.5", optional = true , default-features = false }
leptos_meta = { version = "0.2.5", features = ["ssr"], default-features = false }
leptos_router = { version = "0.2.5", features = ["ssr"], default-features = false }
leptos_dom = { version = "0.2.5", features = ["ssr"], default-features = false }
leptos = { version = "0.2.5", features = ["ssr"], default-features = false }


The first thought I had in mind was that it was a versioning issue, but cargo-leptos adds a layer of ambiguity on top. For example, I initially had leptos set to version 0.2.3, but cargo-leptos enforced version 0.2.5 (I've since changed it to 0.2.5 above).

If you have any ideas as to how I would approach this, please let me know.

Thanks for your help so far.

**Comment by gbj** [comment]
Looking at your full `Cargo.toml` it looks like you're enabling `ssr` for all the Leptos dependencies, and then also enabling `hydrate` in the hydration case. It should look more like this:

```toml
leptos = { version = "0.2", default-features = false, features = [
  "serde",
] }
leptos_meta = { version = "0.2", default-features = false }
leptos_actix = { version = "0.2", optional = true }
leptos_router = { version = "0.2", default-features = false }
# ...

[features]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = [
  "dep:actix-files",
  "dep:actix-web",
  "dep:leptos_actix",
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
]
```

**Comment by MinaMatta98** [comment]
The reason I initially had set the features is because I wasn't getting ssr to work without explicitly stating so (even then, the dynamic nature was lost).

Even now, in order to not get an error on an unwrap (as csr is assumed), I have to specifically set ssr within the leptos_dom crate.

I'll go through the ssr examples again. I may have missed something.

**Comment by gbj** [comment]
What commands are you using to compile or run these? From your description there is definitely something awry. Check the Readme file in each example for the right commands.

**Comment by MinaMatta98** [comment]
Well,

You hit the nail on the head. I was under the impression that a call to unwrap() would be resolved server side provided that ssr was turned on.

I instead now decorated the function with the server macro, and rendering now works as expected.

Thank you for your help.

**Comment by gbj** [comment]
Awesome! 😄

In the future we may have something like "server components" that *only* run on the server, but right now everything that's not in a `#[server]` function is "isomorphic," i.e., it runs on both the server and the client.
