### ISSUE TITLE
Dynamically loading JS files (weback/flowbite) is not calling the load callback

### ISSUE THREAD

**Issue by kerkmann** [leptos-rs/leptos#819]
Hi, I've seen in the ticket #355 that you wrote a `Script` Wrapper to load external Javascript Libraries.

When using external JavaScript libraries that utilize webpack, such as Flowbite, the init function which initializes the library is not consistently triggered. This issue can be observed in line 4327 of the [Flowbite.js](https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.js) file, where the loader is supposed to call every init function. This behavior has been reported to occur inconsistently, with some users, such as @koopa1338, reporting that it worked with a cache, but failed without one. This issue seems to be related to webpack's failure to call the load callback within WebAssembly and leptos. The root cause of this issue is not yet known.

Koopa and I tried a lot of things out, for example, adding priorities to the function call. Adding some timeout within the flowbite, to ensure that flowbite is loaded after everything else.

Do you have any idea, how could we investigate the root cause further? Sadly, we are getting out of ideas. ^^:

Thank you very much. :heart:

**Comment by gbj** [comment]
Could you please share a code example or minimal reproduction of the trouble you're having? I'm not very familiar with Flowbite, but JavaScript libraries like this are often written in such a way that they are to be called once, on page load, and add their behavior to elements that already exist on the page. This makes them a naturally poor fit for most web frameworks, which dynamically create elements during the user's session. I imagine this is why there are Flowbite wrapper libraries for all of the most popular frameworks: there is code that might need to be called every time you want to use a Flowbite component to add Flowbite functionality.

**Comment by kerkmann** [comment]
Of course, you can find on that branch the code: https://gitlab.com/getrusty/frontend_new/-/tree/broken-flowbite-examplw

Here you can find the Router: https://gitlab.com/getrusty/frontend_new/-/blob/broken-flowbite-examplw/src/app.rs#L20-L32
On http::/localhost:8080/testi there is a small dismiss button, which is called with flowbite, to clode the alert box.

The Script is included at the end of the Router: https://gitlab.com/getrusty/frontend_new/-/blob/broken-flowbite-examplw/src/app.rs#L76

The small Test example with just the alert dialog is in the called Testi (which is called from the Router /testi): https://gitlab.com/getrusty/frontend_new/-/blob/broken-flowbite-examplw/src/app.rs#L80-L99

Thanks for your quick answer, if you want, you can also talk with both of us in Discord, maybe that is helping. :)

https://discord.gg/eVqvS6tU

**Comment by kerkmann** [comment]
Also a small hint, adding some breakpoints to the flowbite library, shows that the init calls are not triggered (for example initDismmisses in that example). It's working f you try that example out and past the content of the initDismisses in the console:
```javascript
    document.querySelectorAll('[data-dismiss-target]').forEach(function ($triggerEl) {
        var targetId = $triggerEl.getAttribute('data-dismiss-target');
        var $dismissEl = document.querySelector(targetId);
        if ($dismissEl) {
            new Dismiss($dismissEl, $triggerEl);
        }
        else {
            console.error("The dismiss element with id \"".concat(targetId, "\" does not exist. Please check the data-dismiss-target attribute."));
        }
    });
```

But that init function should be called with webpack. Under a normal environment it's working, but in the wasm/leptos environment the entire Javascript file is loaded, but the load callback from webpack isn't working. ^^"

**Comment by kerkmann** [comment]
Okay, me again, I think we found the root cause. After rendering the DOM, it should call the load event with `dispatchEvent(new Event('load'));`. That event needs also be called every time, a route is changed. Otherwise, it's not working again.

Do you know how hard it is to call that event, every time a route has changed and for the first time the page has loaded? So, I could try around and create a PR for that. :)

**Comment by gbj** [comment]
> Okay, me again, I think we found the root cause. After rendering the DOM, it should call the load event with `dispatchEvent(new Event('load'));`. That event needs also be called every time, a route is changed. Otherwise, it's not working again.
> 
> Do you know how hard it is to call that event, every time a route has changed and for the first time the page has loaded? So, I could try around and create a PR for that. :)

You can use the [`leptos_router::use_location`](https://docs.rs/leptos_router/latest/leptos_router/fn.use_location.html) hook to do something like this in your root route:
```rust
    use web_sys::{Event, EventTarget};
    use wasm_bindgen::JsCast;
    let location = leptos_router::use_location(cx);
    create_effect(cx, move |_| {
        location.pathname.track();
        let window = window().unchecked_into::<EventTarget>();
        window.dispatch_event(&Event::new("load").unwrap());
    });
```

I just tested this and it fires the `load` event on every client-side navigation, so it seems like this issue can be closed? Let me know if it needs to be reopened.
