### ISSUE TITLE
novice question: Leptos and graphics

### ISSUE THREAD

**Issue by FrankReh** [leptos-rs/leptos#821]
This project is very impressive.

I think I've run through the examples, having skipped the tailwind examples because of the extra install requisitions.

There don't seem to be any examples showing 2D or 3D graphics. Is that because the basics are covered by other examples so one's own creativity is all that's needed for generating plots and charts and other graphics like three.js or babylon.js? Or is there something fundamental to using DOM and WebGL graphics that doesn't lend itself to Leptos yet?

Having asked that question, I should say the breadth of the examples is already impressive. Everything worked if I enabled the needed nightly build from time to time. And all but one came with a clear/short README that expressed what it was being demonstrating. And if I understand the idea behind the reactive system being client side *or* server side, there isn't anything stopping someone from implementing the next level of control over the DOM or the WebGL interface. (I'm hoping to allow users to decide whether their session is client-side rendered with JavaScript and WASM or server-side rendered with JavaScript entirely disabled.)

I'm okay with a framework that is slower than pure JS for manipulating DOMs if it means being able to code in Rust and especially if it means having options like client rendering or server rendering. And having server side events demonstrated is very nice too. And the framework being reactive seems super cool - gives the impression that no matter how large the system got, it would be responsive and you would only pay for what you needed - very rust-like.

Of course there should be room for supporting both canvas and WebGL in a framework - probably they are both orthogonal to the framework. Sometimes the canvas commands are perfect for wanting to draw something that doesn't change sixty times a second (like a chart), and sometimes it would be preferable to be able to program  something that required getting into shaders so that things could move on the screen and not use up battery or make the phone too hot.

The first examples that come to mind for a graphical example, both 2D and slow, would be a 2D plot and a 2D mind map. One that showed the results of plotted data, with some extra information when the mouse hovered over a point, and one that allowed grabbing and moving things around and clicking on them to get a menu of methods on the object to change them in some way.

**Comment by gbj** [comment]
The simple truth: The reason there are no examples with 2D or 3D graphics is simply that I know literally nothing about either topic!

I would love to have such an example in the repo, so if you're interested in making one of the graphics examples you describe and contributing it, that would be really wonderful.

**Comment by FrankReh** [comment]
Giving it just a little high level thought. SVG elements being DOM objects should fit better with the react model so could be an easier way to start.

If your project were around long enough, I could ask ChatGPT how to code dragging an SVG circle with the mouse. And maybe even how to build a small framework around keyboard input to allow selection and movement to be accomplished through the keyboard too. Maybe I can gain some insight by asking it how to do that in ReactJS as a starting point.

There is also the question of how to support TouchEvents and how much to leave to JavaScript before translating to an event that is sent to the WASM instance. There is a WASM-JS speedup mechanism named [Sledgehammer](https://docs.rs/sledgehammer/latest/sledgehammer/) that is better at sending large amounts of data to the the JS side but it sounds best when there are a lot of strings that would have to be passed - if its coordinates and arrays of coordinates, maybe it doesn't help. Is it possible Leptos could have a similar mechanism sometime in the future? Not asking for any kind of roadmap even, just whether you've looked at it. If you are building the best reactive system you can, you might not be thinking about how to send many updates to the JS event loop efficiently. I haven't been keeping up with the WASM plans, there was an idea that WASM could be given a much more efficient API to the DOM in the future. I never heard that was about to become a reality.

This is mostly spitballing, with the hopes that someone with a similar interest may have figured more out already and could chime in.

**Comment by FrankReh** [comment]
Here's a [blog](https://www.connorrothschild.com/post/svelte-and-d3) about programming SVG directly from Svelte rather than programming directly in D3 and I think I'm leaning the same way at trying to get SVG drawn from Leptos's `view!`.

**Comment by gbj** [comment]
> Giving it just a little high level thought. SVG elements being DOM objects should fit better with the react model so could be an easier way to start.

Yes, it should be fairly straightforward to do dynamic SVG stuff in Leptos.

> If your project were around long enough, I could ask ChatGPT how to code dragging an SVG circle with the mouse. And maybe even how to build a small framework around keyboard input to allow selection and movement to be accomplished through the keyboard too. Maybe I can gain some insight by asking it how to do that in ReactJS as a starting point.

Leptos is much more similar to SolidJS, which has a large enough presence that ChatGPT will certainly give less hallucinatory answers.

> There is also the question of how to support TouchEvents and how much to leave to JavaScript before translating to an event that is sent to the WASM instance.

Not sure I understand the question, really... We just do support touch events, I think?

> There is a WASM-JS speedup mechanism named [Sledgehammer](https://docs.rs/sledgehammer/latest/sledgehammer/) that is better at sending large amounts of data to the the JS side but it sounds best when there are a lot of strings that would have to be passed - if its coordinates and arrays of coordinates, maybe it doesn't help. Is it possible Leptos could have a similar mechanism sometime in the future?

I'm very familiar with Sledgehammer and haven't found that the cost/benefit is worth it in testing. i.e., the performance improvements over what Leptos can already do are pretty marginal, in exchange for a fairly significant binary size increase.

> I haven't been keeping up with the WASM plans, there was an idea that WASM could be given a much more efficient API to the DOM in the future. I never heard that was about to become a reality.

You're probably thinking of [interface types](https://github.com/WebAssembly/interface-types/blob/main/proposals/interface-types/Explainer.md) and/or the [component model](https://github.com/WebAssembly/component-model). Neither is likely to be finalized or shipped any time soon, neither is particularly necessary to have very good performance for WASM DOM manipulations.

***

I'm wondering if this conversation may be better suited to a GitHub discussion or Discord thread (see Discord link in readme) rather than a GitHub issue. If the question is basically "Should we add an example of a declarative SVG animation using Leptos?" I think it's a great idea and would welcome a PR.

**Comment by FrankReh** [comment]
Thanks for the individual answers. Glad you've looked at Sledgehammer and made a decision about it. Yes, I was thinking about interface types and glad to hear you don't think it is worth waiting for.

Thanks for the SolidJS pointer.

And my timing was bad. When I looked for the book this morning, the link didn't work nor did what I thought would be the old link. But now it's fixed and you addressed why in another issue already. If I had read the book, I would probably know that touch events are already handled.

My plan is to read the  book now. See if I know how CSS transforms are handled, see if I know how a slider input device is handled, and then offer an SVG example or two if nobody has beaten me to it.

Thanks for your time. The energy on your project is impressive.

**Comment by PeterNjeim** [comment]
Just as a heads up, WebGL has been superseded by WebGPU
