### ISSUE TITLE
Server Function generates invalid code with an argument named `url`

### ISSUE THREAD

**Issue by HBnetDE** [leptos-rs/leptos#823]
I've tried to write a server function that takes a String (which seems like it should work according to the example in leptos_server).

```rs
#[server(Foo, "/api")]
pub async fn foo(cx: Scope, url: String) -> Result<(), ServerFnError> {
    Ok(())
}
```

This generates a compile time error "cannot move out of 'url' because it is borrowed move out of 'url' occurs here"

Using cargo-expand I believe I have found the actual location of the error:
```rs
    #[cfg(not(feature = "ssr"))]
    pub async fn foo(cx: Scope, #[allow(unused)] url: String) -> Result<(), ServerFnError> {
        let prefix = Foo::prefix().to_string();
        let url = prefix + "/" + Foo::url();
        ::leptos::server_fn::call_server_fn(&url, Foo { url }, ::leptos::server_fn::Encoding::Url)
            .await
    }
```
It borrows the url and then moves it into Foo while it is still borrowed.

**Comment by gbj** [comment]
It looks like the issue here is actually that the variable is named `url` so it's shadowed by the other variable named URL. This should be fairly easy to fix. Thanks for the expansion.
