### ISSUE TITLE
Tracing Improvements

### ISSUE THREAD

**Issue by benwis** [leptos-rs/leptos#829]
I'd like to do some work on the tracing implementation in Leptos.

The current version is enabled with the feature flag "tracing" on the Leptos package.
It looks geared to trace all the reactive primitives and all the components from your root app on down. I'd like to do these things

1. Enable the tracing feature on production.
2. Add to the existing implementation to display less, but some useful info at a log level higher than trace
3. Instrument all the functions in the render path, so that tracing tools can connect a Request received from Axum or Actix to instrumented calls to server function calls, and components themselves.

**Comment by gbj** [comment]
Enabling tracing in production makes a lot of sense for the server. It's disabled in prod for WASM binary size so maybe it could be `#[cfg(any(debug_assertions, feature = "ssr"))]` instead.

Otherwise: Go for it, this is a great idea.

**Comment by akarras** [comment]
> Enable tracing on production
1. Can we just make it a feature flag? I'd guess most people are fine with tracing being enabled by default, but nice to have a way to disable if you really aren't using it.
> Display useful, but less detailed info
2. Do you have specifics here? I can kind of see doing something like, time spent rendering app vs time spent awaiting resources but I'm not sure how that'd be implemented.
> Instrument all the things
3. This seems like a good thing overall. It probably would make sense to make more use of the different trace levels here as well if we go down this route

**Comment by benwis** [comment]
> > Enable tracing on production
> 
> 1. Can we just make it a feature flag? I'd guess most people are fine with tracing being enabled by default, but nice to have a way to disable if you really aren't using it.
> 
> > Display useful, but less detailed info
> 
> 2. Do you have specifics here? I can kind of see doing something like, time spent rendering app vs time spent awaiting resources but I'm not sure how that'd be implemented.
> 
> > Instrument all the things
> 
> 3. This seems like a good thing overall. It probably would make sense to make more use of the different trace levels here as well if we go down this route

1. It is a feature flag currently, the "tracing" feature flag. Or do you want a "tracing-prod" flag?
2. I do not. I think we probably collect too much now, but I would love to discuss what we think should be accessible at different levels.

**Comment by gbj** [comment]
@benwis I know you threw a lot of tracing at your blog when you were looking at performance — Do you have those changes in a branch you want to put up for a PR?

**Comment by benwis** [comment]
We can close this for now, as the PR is merged. More improvements will surely be needed, but we're a lot closer
