### ISSUE TITLE
Allow unquoted text in view macro

### ISSUE THREAD

**Issue by wxyer** [leptos-rs/leptos#833]
i think the feature is very convenient，is this nightly rust give or the framework give

**Comment by gbj** [comment]
Here’s a tracking issue for unquoted text in [`syn-rsx`](https://github.com/stoically/syn-rsx/issues/2), which is the underlying library we use for parsing the `view` macro.

**Comment by wxyer** [comment]
thank you ,i expect it very much

**Comment by brahimABD98** [comment]
quoted text is can have benefits  writing stuff in  Arabic is easier no  extra work is needed , maybe if it's possible to keep both

**Comment by gbj** [comment]
This was added in #1054. Quoted text is still supported as usual, but unquoted text is also supported. Extra whitespace is trimmed, so you may find that you still need quoted text in situations where you need to ensure whitespace is included, and you can still use quoted text in any case.

This is available on both nightly and stable.
