### ISSUE TITLE
Detached Nodes memory leak

### ISSUE THREAD

**Issue by novacrazy** [leptos-rs/leptos#834]
If you run an example with dynamically-present elements (such as from `<Show>` and `<For>`), like the Hackernews example, after switching pages a few times go into the Chrome dev-tools Memory tab and take a heap snapshot. You will see many thousands of detached nodes.
![detached2](https://user-images.githubusercontent.com/4708645/230742962-e829a7db-3135-4310-a031-1f18250f6a6c.PNG)

This is caused by the nodes being kept in the `heap` JS array variable used by wasm_bindgen to hold `JsValue`s, and not being freed. The WASM program refers to these heap values by index, and upon Drop of a `JsValue` in Rust code the value on the heap is replaced with an integer pointing to the previous free slot, freeing whatever other reference was there. Cloning a `JsValue` just makes a copy of the reference in `heap` at another index. It's pretty air-tight on the wasm_bindgen side despite JS references being weird.

Therefore, it seems somewhere in Leptos's code the `JsValue` is being retained. Unfortunately, tracking this down is difficult, as the devtools always point to the `heap` variable, not Rust code. For some of the retainer graphs of these detached nodes, I have seen them point to multiple indexes in `heap`, implying the `JsValue` has been cloned via `Clone` and all are being retained. 

Note that pretty much everything in `js_sys` and `web_sys` are built on `JsValue`, including `HtmlElement`. If it refers to something living in JS-land, it uses the `JsValue` system.

**Comment by novacrazy** [comment]
It's definitely the `<For>` component, at least. `<Show>` by itself seems to not have any issues at the time of testing today, knock on wood.

Modifying the `counter` example to be:
```
<div>
    <div>
        <button on:click=move |_| set_value(0)>"Clear"</button>
        <button on:click=move |_| set_value.update(|value| *value -= step)>"-1"</button>
        <span>"Value: " {value} "!"</span>
        <button on:click=move |_| set_value.update(|value| *value += step)>"+1"</button>
    </div>
    <Show when={move || value() % 2 == 0} fallback=|_| ()>
        <For each={|| vec![1, 2, 3]} key=|key| *key view={move |cx, k| {
            view! {
                cx,
                <article>{k}</article>
            }
        }}/>
    </Show>
</div>
```
then clicking the increment button N times results in N*3/2 leaked `<article>` nodes, so a leak every time it becomes visible.

It also leaks N/2 number of `Comment` nodes.

**Comment by gbj** [comment]
Someone's reported a similar issue which occurs with `<Suspense/>`. Not sure if there's a shared root cause here or not. 

But I'm hopeful that with two examples we can solve both the `<For/>` and `<Suspense/Transition/>` cases. I'll put some work into this. 

```rust
fn update_counter_bg(mut value: i32, step: i32, sig: WriteSignal<i32>) {
    sig.set(value);
    value += step;
    leptos::set_timeout(
        move || {
            update_counter_bg(value, step, sig);
        },
        std::time::Duration::from_millis(20),
    );
}

async fn get_resource(value: i32) -> i32 {
    value
}


#[component]
pub fn SimpleCounter(
    cx: Scope,
    initial_value: i32,
    step: i32,
) -> impl IntoView {
    let (value, set_value) = create_signal(cx, initial_value);

    // update the value signal periodically
    update_counter_bg(initial_value, step, set_value);

    // simulate a resource that is fetched from the server when the signal is triggered
    let resource = create_resource(cx, value, get_resource);

    view! { cx,
        <Transition fallback=move || {
            view! { cx, <p>"Loading..."</p> }
        }>

                { move || resource
                    .with(
                        cx,
                        |value| {
                            view! { cx,
                                <div>
                                    <h3>{format!("{value}")}</h3>
                                </div>
                            }
                        },
                    )
            }
        </Transition>
    }
}
```

**Comment by gbj** [comment]
I'm wondering if what happens in both cases might be that nodes are being moved into a DocumentFragment and then forgotten about.

**Comment by gbj** [comment]
> It's definitely the `<For>` component, at least. `<Show>` by itself seems to not have any issues at the time of testing today, knock on wood.

So I think there's definitely something here that involves `Fragment`s leaking nodes. In both the `<Suspense/>` leak (which I've mostly figured out) and the `<For/>` case, I can basically toggle the behavior on and off by "anchoring" a loose fragment (which includes the children projected into another component) in an actual HTML element. 

So for example I can reproduce a leak with the example you gave. With *only* a `<Show/>` or *only* a `<For/>` I can't. Moreover, if I edit to to have a `<div>` wrapping the inner `<For/>` (so that `<For/>` is the sole child of an element, not of a fragment), it also no longer leaks.

```rust
    view! { cx,
        <div>
            <div>
                <button on:click=move |_| set_value(0)>"Clear"</button>
                <button on:click=move |_| set_value.update(|value| *value -= step)>"-1"</button>
                <span>"Value: " {value} "!"</span>
                <button on:click=move |_| set_value.update(|value| *value += step)>"+1"</button>
            </div>
            <Show when={move || value() % 2 == 0} fallback=|_| ()>
                // added inner element
                <div>
                    <For each={|| vec![1, 2, 3]} key=|key| *key view={move |cx, k| {
                        view! {
                            cx,
                            <article>{k}</article>
                        }
                    }}/>
                </div>
            </Show>
        </div>
    }
```

Obviously this is still troubling and something to be addressed, but it does seem to be quite specific to the way we're handling fragments, or possibly even fragments inside fragments. (Recalling that the `Children` type passed to functions is an alias for `Box<dyn FnOnce(Scope) -> Fragment>`.)

**Comment by gbj** [comment]
Ach you know what, I just realized I think the Suspense case is actually #802 / #918 striking again, because Suspense isn’t creating and disposing of scopes for its children so it doesn’t dispose of the previous child when it rerenders. 

For and Show should both be doing that correctly but maybe there’s something else there.

**Comment by novacrazy** [comment]
I was not using Suspense in the tests with For that leaked all the children of For. Does that particular leak still occur? I’ll check it myself when I can.

**Comment by gbj** [comment]
> I was not using Suspense in the tests with For that leaked all the children of For. Does that particular leak still occur? I’ll check it myself when I can. 

I'm not able to reproduce a memory leak in Chrome with the For/Show example you posted, i.e., if I set it to toggle continuously and take memory snapshots over the course of several thousand iterations, memory usage remains stable. Not sure if that's consistent with what you were observing, or if something else changed in between, or if the detached nodes are being GCed. Happy to reopen if you think it's still a problem.

**Comment by gbj** [comment]
Here's the memory behavior I'm describing, with the signal updated every millisecond. When I search for "detached" in the memory summary I see fluctuations over time, but actually decreasing overall over the course of things. I guess whether the increase from 2.3mb to 3.0mb over the course of 10,000 iterations is a leak or not is in the eye of the beholder, but I think it's pretty distinct from the behavior you were seeing with the hackernews example, which was driven by the Suspense leak.

https://user-images.githubusercontent.com/286622/236629009-c0a58a45-b450-44ff-bfd1-45d1d979eaa0.mov

```rust
use leptos::*;

fn update_counter_bg(mut value: i32, step: i32, sig: WriteSignal<i32>) {
    sig.set(value);
    if value < 10000 {
        value += step;
        leptos::set_timeout(
            move || {
                update_counter_bg(value, step, sig);
            },
            std::time::Duration::from_millis(1),
        );
    }
}

#[component]
pub fn SimpleCounter(cx: Scope, initial_value: i32, step: i32) -> impl IntoView {
    let (value, set_value) = create_signal(cx, initial_value);

    // update the value signal every ms up to 10k iterations
    update_counter_bg(initial_value, step, set_value);

    view! { cx,
        <div>{value}</div>
        <div>
            <Show when=move || value() % 2 == 0 fallback=|_| ()>
                <div>
                    <For
                        each=|| vec![1, 2, 3]
                        key=|key| *key
                        view=move |cx, k| {
                            view! { cx, <article>{k}</article> }
                        }
                    />
                </div>
            </Show>
        </div>
    }
}

fn main() {
    mount_to_body(|cx| {
        view! { cx, <SimpleCounter initial_value=0 step=1/> }
    })
}
```

**Comment by gbj** [comment]
Here it is with PR #918, which I'm pretty sure is the answer to all memory leaks related to the gross-ness of manual scope disposal. Absolutely smooth memory use at 2.3MB over 10,000 iterations.

<img width="709" alt="Screenshot 2023-05-06 at 9 29 19 PM" src="https://user-images.githubusercontent.com/286622/236653141-d600b7b4-b837-4357-8580-5d408d6f0f45.png">
