### ISSUE TITLE
todo_app_sqlite build error (CSR only)

### ISSUE THREAD

**Issue by jasonsydes** [leptos-rs/leptos#845]
Hi there, Leptos looks pretty interesting... I'm trying out some of the examples/, and they're mostly working for me.

I was able to get todo_app_sqlite working with the [Server Side Rendering with cargo-leptos](https://github.com/leptos-rs/leptos/tree/main/examples/todo_app_sqlite#server-side-rendering-with-cargo-leptos). However, when I tried to build/run todo_app_sqlite with the [Client Side Rendering](https://github.com/leptos-rs/leptos/tree/main/examples/todo_app_sqlite#client-side-rendering) (i.e., with trunk serve --open), it's telling me that "index.html" is missing (see below). 

I'm pretty new to Leptos, so I'm not sure what to expect. I wasn't sure if this was perhaps a documentation oversight, as I'm noticing that examples/todo_app_sqlite_axum and examples/todo_app_sqlite_viz both specifically state that they "cannot be built as a trunk standalone CSR-only app. Only the server may directly connect to the database."... Is todo_app_sqlite an exception (i.e., can todo_app_sqlite "talk" to the database?)?

I did a fresh install of rust/cargo/leptos today, here are my versions:
cargo 1.70.0-nightly (0e474cfd7 2023-03-31)
trunk 0.16.0

``` 
∴ trunk serve --open
Error: error getting canonical path to source HTML file "index.html"

Caused by:
    No such file or directory (os error 2)

∴ ls -a1
.
..
.gitignore
Cargo.lock
Cargo.toml
LICENSE
Makefile.toml
README.md
Todos.db
dist
migrations
public
src
style.css
target
```

**Comment by gbj** [comment]
This example just shouldn't have that section of the README. It's an example of how to integrate server functions (running a SQL database on the server) so it doesn't make any sense to run on the client only.
