### ISSUE TITLE
Manually mutable resources

### ISSUE THREAD

**Issue by vhslib** [leptos-rs/leptos#856]
On `Resource` ergonimics: I wonder if it is possible to extend the `Resource` API to support manually `update`'ing them. There _are_ actual cases when it is reasonable, the most obvious one (and which I'm actually working on right now) is a chat app. I'm fetching a `Vec` of `Message`s from the server, and then on the client I want to push to it whenever a new message comes from WebSocket. I guess I could currently deal with this by keeping a copy of the `Vec` in a signal and somehow synchronizing it with the resource (it seems that I would need a dedicated `<Suspense>` for this in order to read from the resource). This approach would involve unnecessary cloning and is simply awkward. So, why not just implement `update` on `Resource` instead?

**Comment by gbj** [comment]
Seems like a reasonable use case to me. This should be fairly straightforward to implement, it you'd like to make a PR... it should just be a question of implementing the `SignalUpdate` and, for `T: Clone`, `SignalSet` traits, and adding some docs/tests as needed. `ResourceState` already contains a signal with the current value so I think it's just a matter of passing the calls through.

**Comment by vhslib** [comment]
Great, I'll try to implement this in a few days
