### ISSUE TITLE
`#server` url munging broken under Bazel

### ISSUE THREAD

**Issue by snapbug** [leptos-rs/leptos#857]
👋 Hi, the url munging for server functions breaks when using the Bazel build system.

Specifically [this line](https://github.com/leptos-rs/leptos/blob/main/server_fn_macro/src/lib.rs#L211), which uses `env!("CARGO_MANIFEST_DIR")` to munge the urls causes the following:

On the server side,
```rust
register_server_functions()
info!("{:#?}", leptos_server::server_fns_by_path());
info!(concat!(env!("CARGO_MANIFEST_DIR")));
```
results in the following output:
```
[
    "get_single_config4869621392562198152",
    "get_event_config2255429015822590071",
]
/private/var/tmp/_bazel_user/4b541d909237bb1ea4e282a886cf6762/sandbox/darwin-sandbox/5148/execroot/project/www
```

On the client side, sticking
```rust
log::info!(concat!(env!("CARGO_MANIFEST_DIR")));
```
results in the following output:
```
/private/var/tmp/_bazel_user/4b541d909237bb1ea4e282a886cf6762/sandbox/darwin-sandbox/5140/execroot/project/www
```
and using the chrome developer tools (and logging on the server side, a representative url being hit for serverfn is):
```
http://localhost:8000/api/get_event_config12333777864187817067
```
different from the registered `get_event_config2255429015822590071`, results in `http 400` errors.

Because the client wasm bundle and the server binary are different bazel targets they get executed in their own sandbox directory. This results from the minor difference in the `CARGO_MANIFEST_DIR` (`5148` vs `5140`).

I realize this is somewhat down to build tool choice, but I'm working in an environment where that's not changeable, but Bazel has plenty of other upsides even if it were a Greenfield project 🙂.

I _suspect_ that this was added in to help reduce potential of naming collisions? Can this clobbering be made an option in the macro? Happy to try and attempt once day job doesn't get in the way. This behavior wasn't exhibited in 0.2.1 which I'e been developing against for now, and I'd rather not be stuck on.

Thanks in advance.

**Comment by gbj** [comment]
Makes sense to me. Yes, this is a way of preventing naming collisions that works on both stable and nightly. 

I don't know anything about Bazel. Does it allow you to provide another environment variable to be used during the build, such that we could use something like `option_env!("SERVER_FN_OVERRIDE_KEY").unwrap_or(env!("CARGO_MANIFEST_DIR"))`? (I'm not sure if this is actually allowed in this given `const` context but I'm sure we could figure something out)

**Comment by gbj** [comment]
Sounds good, and thanks!

**Comment by snapbug** [comment]
I've put up #878 with proposed solution. If it doesn't fit, then it's not critical, learned the Bazel rules I'm using support providing patches to libraries, so I've just used that for the meantime (and can continue).

Going to close issue to move any discussion to the PR 🙂. Thanks!
