### ISSUE TITLE
Add missing <banner> HTML element

### ISSUE THREAD

**Issue by nekodjin** [leptos-rs/leptos#858]
Leptos does not currently support the `<banner>` HTML element. As far as I can tell, adding support for this element should be relatively trivial.

**Comment by gbj** [comment]
I don't think there is a `<banner>` element? Or rather, `BANNER` is an element [in HTML 3.0](https://www.w3.org/MarkUp/html3/banners.html) but I can't find it anywhere in the spec for HTML 4 or HTML 5. Could you clarify?

**Comment by nekodjin** [comment]
Sorry, you're absolutely correct that it doesn't exist. I must have been hallucinating its existence based on the ARIA role of the same name 😅. My apologies.
