### ISSUE TITLE
Broken Doc Links across Crates

### ISSUE THREAD

**Issue by nekodjin** [leptos-rs/leptos#859]
There are many instances across the documentation where the `[member]` syntax is used to create a link to a member but, since the member in question is from a different crate, the link is not generated. Here's an example from the [leptos_router](https://docs.rs/leptos_router/latest/leptos_router/fn.Route.html) crate:

> This can be any function that takes a [Scope] and returns a type that implements [IntoView] ...

This also applies to the type annotations in the documentation automatically generated by the `component` macro for a component's properties. The macro issue is more difficult to resolve, but the issue with the handwritten doc comments is trivial.

**Comment by gbj** [comment]
Thanks, yeah. I noticed the other day the `clippy` catches these in pedantic mode but not normal mode. There are quite a few, it seems. If anyone wants to help clear these up it would be fantastic.

**Comment by ChaudhariPrasad** [comment]
Hi. I would like to contribute to make this changes. I am new to rust though. Could you please assign this issue to me. Thanks.

**Comment by nekodjin** [comment]
@ChaudhariPrasad here's [a page you may find helpful](https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html). Make sure to run `cargo doc` to generate the documentation locally and verify that your changes have worked before submitting a PR. You can review the Cargo documentation to see where you can locate the generated documentation files.

**Comment by nekodjin** [comment]
As Greg noted, you can use `cargo clippy` on pedantic mode to find everything that needs fixing.

**Comment by nekodjin** [comment]
I wonder if I shouldn't open a separate issue for the bug as it applies to `#[component]` macro-generated documentation, as neither the nature of the problem nor its difficulty to solve are similar to that of the handwritten doc comments?

**Comment by gbj** [comment]
@ChaudariPrasad Sorry I took a look at this and it's actually more complicated than I thought because `cargo doc` isn't warning for unresolved links here as I thought it would. 

@nekodjin You mention there are many instances — are they mostly in component props like the one you link to from the `<Route/>` component? In that case I think this really is one issue and will need to be handled somewhere in the interaction between the `#[component]` macro and `cargo doc`, which is more complicated than I thought this issue was initially.

**Comment by nekodjin** [comment]
@gbj I'd guess that most of them arise from the component macro but there are also a fair number in the handwritten doc comments. I can start by addressing those.
