### ISSUE TITLE
panic at leptos_dom/src/components/dyn_child.rs:311:34 during hydration

### ISSUE THREAD

**Issue by markcatley** [leptos-rs/leptos#896]
I keep getting the above panic during hydration and I've been unable to figure out what I am doing wrong. Would this #802 be related to this? Do you have any suggestions on how to debug this? I've been trying to comment things out and see when I do and don't get the error but I'm still struggling to figure it out.

**Comment by gbj** [comment]
Could you please provide some kind of reproducible example?

**Comment by markcatley** [comment]
I can't reproduce this. I am a bit lost as to why I got it or why I don't still have it. I'll be on the lookout for it again.
