### ISSUE TITLE
Nested update calls cause panic

### ISSUE THREAD

**Issue by Nonakesh** [leptos-rs/leptos#906]
I'm working on a small game with a nested game state. For example, I use `RwSignal<HashMap<ResourceId, RwSignal<u32>>>`.

When calling something like 
```rust
resources.update(|resources| 
    resources
        .entry(id)
        .or_insert_with(|| create_rw_signal(cx, 0))
        .update(|amount| *amount += 1);
```
it causes a panic in `RefCell::borrow` because the subscribers try to access the `HashMap` which is still mutably borrowed.

I've fixed the problem with a small helper script to delay notifying subscribers until the whole operation is done.

```rust
#[derive(Default)]
pub struct DelayedUpdater {
    updates: RefCell<Vec<Box<dyn Fn()>>>,
}

impl DelayedUpdater {
    pub fn new() -> Self {
        Default::default()
    }

    #[instrument(skip_all)]
    pub fn add<T>(&self, signal: impl SignalUpdate<T> + 'static) {
        self.updates
            .borrow_mut()
            .push(Box::new(move || signal.update(|_| ())));
    }

    #[instrument(skip_all)]
    fn update(&self) {
        let mut updates = self.updates.borrow_mut();
        for update in updates.drain(..).rev() {
            update();
        }
    }
}

impl Drop for DelayedUpdater {
    fn drop(&mut self) {
        self.update()
    }
}

pub trait SignalUpdateDelayed<T>:
    SignalUpdate<T> + SignalUpdateUntracked<T> + Copy + 'static
{
    fn update_delayed(&self, f: impl FnOnce(&DelayedUpdater, &mut T)) {
        let updater = DelayedUpdater::new();

        self.update_after_parent(&updater, |v| f(&updater, v));
    }

    fn update_after_parent(&self, updater: &DelayedUpdater, f: impl FnOnce(&mut T)) {
        self.update_untracked(f);
        updater.add(*self);
    }
}

impl<T, S: SignalUpdate<T> + SignalUpdateUntracked<T> + Copy + 'static> SignalUpdateDelayed<T>
    for S
{
}
```

Which looks like this in the end:
```rust
resources.update_delayed(|updater, resources| 
    resources
        .entry(id)
        .or_insert_with(|| create_rw_signal(cx, 0))
        .update_after_parent(updater, |amount| *amount += 1);
```

I realize that calling update twice in a row somewhat defeats the purpose of the fine-grained reactivity, so maybe a better solution would be to make it more convenient to do something like this:
```rust
let contains_key = resources.with(|resources| resources.contains_key(&id));
if !contains_key {
    resources.update(|resources| resources.insert(id, create_rw_signal(cx, 0)));
}
resources.with(|resource| resource.get(&id).unwrap().update(|amount| *amount += 1));
```
For example a function like this:
```rust
fn maybe_update(&self, f: impl FnOnce(&mut T) -> bool) -> &Self {
    // ...
}
```
So it would be possible to make this call instead:
```rust
resources.maybe_update(|resources| {
        if !resources.contains_key(&id) { 
            resources.insert(id, create_rw_signal(cx, 0));
            true
        } else {
            false
        }
    })
    .with(|resource| resource.get(&id).unwrap().update(|amount| *amount += 1));
```

I'm not sure my solutions would work in the crate, but I think the problem should be addressed in the documentation. By the way, I wrote some of the code right here instead of in an IDE, so sorry in case there are any errors.

I've found leptos to be very convenient, intuitive, and fun to work with otherwise, so thanks for creating it! 😄

**Comment by Nonakesh** [comment]
I've experimented move with the `maybe_update` idea and it seems a lot better than the somewhat hacky `DelayedUpdates` idea.
Again, I'm just sharing my process here, I'm not sure if it wouldn't be better to just mention the problem in the documentation for `update`.

First I added a maybe update trait
```rust
pub trait SignalMaybeUpdate<T>: SignalUpdate<T> + SignalUpdateUntracked<T> {
    /// Update the value but only notify subscribers if `f` returns true.
    fn maybe_update(&self, f: impl FnOnce(&mut T) -> bool) {
        let was_updated = self.try_update_untracked(|v| f(v)).unwrap_or(false);
        if was_updated {
            self.update(|_| ());
        }
    }
}

impl<T, S: ?Sized + SignalUpdate<T> + SignalUpdateUntracked<T>> SignalMaybeUpdate<T> for S {}
```

Then I added a helper for working directly with HashMaps
```rust
pub trait SignalHashMap<K, T> {
    fn insert_if_missing<F>(&self, key: K, value: F)
    where
        Self: SignalMaybeUpdate<HashMap<K, T>>,
        K: Eq + Hash,
        F: FnOnce() -> T,
    {
        self.maybe_update(|map| {
            if let Entry::Vacant(entry) = map.entry(key.clone()) {
                entry.insert(value());
                true
            } else {
                false
            }
        });
    }

    fn with_entry<F, U, A>(&self, key: K, value: F, action: A) -> U
    where
        Self: SignalMaybeUpdate<HashMap<K, T>> + SignalWith<HashMap<K, T>>,
        K: Eq + Hash + Clone,
        F: FnOnce() -> T,
        A: FnOnce(&T) -> U,
    {
        self.insert_if_missing(key.clone(), value);

        self.with(|map| {
            let value = map.get(&key).expect("key should have been inserted");
            action(value)
        })
    }
}

impl<K, T, S> SignalHashMap<K, T> for S {}
```

So now I have two ways of solving my original problem:
```rust
// Split into two steps, a bit verbose and redundant IMO
resources.insert_if_missing(id, || create_rw_signal(self.cx, 0));
resources.with(|resources| resources.get(id).unwrap().update(|amount| *amount += *added));

// Using closures. I don't really like the name `with_entry`, but that's not really a problem in my toy project
resources.with_entry(
    id,
    || create_rw_signal(self.cx, 0),
    |resource| resource.update(|amount| *amount += *added)
);
```

**Comment by gbj** [comment]
Yep, so the issue here is actually not in the code that you posted but presumably you're reading the value somewhere such that the two signal reads are nested. Calling the `update` function on `resources` immediately took out a mutable borrow on `resources`, then updated the `resource` signal which re-ran the effect that reads from the signals, which tried to immutably access `resources`. 

I reproduced it like this
```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    let resources = create_rw_signal(cx, HashMap::new());

    let update = move |id: usize| {
        resources.update(|resources| {
            resources
                .entry(id)
                .or_insert_with(|| create_rw_signal(cx, 0))
                .update(|amount| *amount += 1)
        })
    };

    view! { cx,
        <div>
            <pre>{move || format!("{:#?}", resources.get().into_iter().map(|(id, resource)| (id, resource.get())).collect::<Vec<_>>())}</pre>
            <button on:click=move |_| update(1)>"+"</button>
        </div>
    }
}
```
It's a little hard to explain but I was able to fix this by just changing the `update` function to this:
```rust
    let update = move |id: usize| {
        let resource = resources.try_update(|resources| {
            *resources
                .entry(id)
                .or_insert_with(|| create_rw_signal(cx, 0))
        });
        if let Some(resource) = resource {
            resource.update(|n| *n += 1);
        }
    };
```

## Skip to here if you want

The ideal situation would be if there were some way we could batch these updates so that the effect only ran once they were both done updating. And in fact, we can do that with [`cx.batch()`](https://docs.rs/leptos/latest/leptos/struct.Scope.html#method.batch), which yields what is probably the best way to deal with this:

```rust
    let update = move |id: usize| {
        cx.batch(move || {
            resources.update(|resources| {
                resources
                    .entry(id)
                    .or_insert_with(|| create_rw_signal(cx, 0))
                    .update(|amount| *amount += 1)
            })
        });
    };
```

This runs the rendering side effect once, after both updates are made, without you needing to rewrite your code at all.

I'm open to suggestions on how better to document this etc. but I think batching is the answer for you.

**Comment by Nonakesh** [comment]
Oh nice, I completely missed the existence of batch! That's a much better solution than having to deal with the whole `maybe_update` situation.

I think it would be great to document its existence and how it can be used to solve nested updates with nested reads (you're right, I forgot to mention that's where the problem _actually_ happens).

**Comment by Nonakesh** [comment]
Actually, after thinking about it some more, `maybe_update` would still have the advantage of only notifying subscribers when an entry is _actually_ added. With the cx.batch and nested updates it would update with every change, right?

**Comment by gbj** [comment]
> I think it would be great to document its existence and how it can be used to solve nested updates with nested reads (you're right, I forgot to mention that's where the problem _actually_ happens).

For now I've stuck it in our ["Common Bugs"](https://github.com/leptos-rs/leptos/blob/main/docs/COMMON_BUGS.md#nested-signal-updatesreads-triggering-panic) doc, and will include it somewhere in the guide docs when I get into slightly more advanced reactivity.

> Actually, after thinking about it some more, `maybe_update` would still have the advantage of only notifying subscribers when an entry is _actually_ added. With the cx.batch and nested updates it would update the HashMap with every change, right?

I think this is wise actually. Yes `.update` does not do any kind of equality checking after you call it—it assumes that an update is an update, even if nothing's actually changed. I think the most efficient implementation here is something like
```rust
let resource = resources.with_untracked(|resources| r.get(entry).copied()); // copy is cheap because signals are `Copy`
if let Some(resource) = resource {
  resource.update(/* */);
else {
  resources.update(|resources| resources.insert(/* */);
}
```
I'll close this just to keep it off my visual to-do list but feel free to reply, I still get a notification.
