### ISSUE TITLE
errors_axum compile error: `hydrate` and `ssr` enabled as features

### ISSUE THREAD

**Issue by agilarity** [leptos-rs/leptos#917]
Run `cargo make test -p errors_axum` from `leptos/examples` to reproduce.

**Comment by gbj** [comment]
Closing as a duplicate of #916, let's just keep it to one report for any of the examples so I can answer you in one place.

**Comment by agilarity** [comment]
Sure thing. I will add similar errors to #916.

Thank you for looking into this so quickly.
