### ISSUE TITLE
Slots are not constructed recursively

### ISSUE THREAD

**Issue by jquesada2016** [leptos-rs/leptos#926]
Currently, slots are not constructed recursively, so the following won't compile.

```rust
#[slot]
struct AProps { b: BProps }

#[slot]
struct BProps {}

#[component]
fn Comp(cx: Scope, a: AProps) -> impl IntoView {}

fn example(cx: Scope) {
  view! { cx,
    <Comp>
      <A slot>
        <B slot />
      </A>
    </Comp>
  };
}
```

Currently, this will first create a compile error that says only components can have slots, but if we comment out that part of the code which bails out, then the nested slot isn't constructed recursively, but rather is treated like a normal component.

**Comment by yuuma03** [comment]
I already have a fix ready, do you want me to create a PR just for it, or maybe we should do a bigger PR with more improvements?

**Comment by gbj** [comment]
> I already have a fix ready, do you want me to create a PR just for it, or maybe we should do a bigger PR with more improvements?

Small, targeted, and done is better than big, multi-purpose, and yet-to-do :smile: Go ahead and make a PR for the fix for this now, and you can do other changes to come separately.
