### ISSUE TITLE
Forcing the return type of `#[component]` to be `impl IntoView` is overly restrictive

### ISSUE THREAD

**Issue by ModProg** [leptos-rs/leptos#933]
As there are concrete types that implement `IntoView` there are situations where you might want to return those directly instead of obfuscating them trough `-> impl IntoView`.

I propose removing the following from the component attribute macro:
```rs
// Make sure return type is correct
if !is_valid_into_view_return_type(&item.sig.output) {
    abort!(
        item.sig,
        "return type is incorrect";
        help = "return signature must be `-> impl IntoView`"
    );
}
```

## Contra
- It makes it harder to spot the mistake when one forgets to add `-> impl IntoView`

## Pro
- makes `#[component]` more vercitile

## Alternative
add a parameter to `#[component(disable_arbitrary_checks_that_are_ensured_by_rustc_as_well)]` to disable the check when needed.

**Comment by gbj** [comment]
The `#[component]` macro adds some debugging and tracing information in debug mode that is genuinely useful — for example, it shows the boundaries between different components in your browser's DOM inspector with named comments:
https://github.com/leptos-rs/leptos/blob/9a4f3ab08c93f735b57e9443ea4635bdbd835f2b/leptos_macro/src/component.rs#L181-L190

It does that by wrapping the component body in a lightweight `Component` type. Because `Component` implements `IntoView` and the type you return must also implement `IntoView`, this means that both the wrapped type and the unwrapped type meet the type definition, namely `-> impl IntoView`

I'm not sure I understand the argument for changing this. The title of the issue says that "forcing the return type to be `-> impl IntoView` is overly restrictive." The alternative would be to make the `#[component]` requirement *less* restrictive by allowing you to return types that are *more* restrictive, do I have that right? So you could say for example
```rust
#[component] 
pub fn MyButton(cx: Scope, children: Children) -> HtmlElement<Button> {
  view! { cx,
    <button class="fancy-button-class>{children(cx)}</button>
}
``` 
Is that the idea?

I can see the advantage of returning accurate types in a situation like this, where you might want to have access to the underlying HTML element for some reason. I'm not really sure what other advantages there would be. Did you have an example in mind where the status quo is causing you an issue?

**Comment by ModProg** [comment]
Well I ran into the issue that I couldn't call `.into_any()` on  a `view!{}` containing only one of my components.
```rs
view! {
    cx,
    <Card kind=CardKind::Filled>
        <Actions>
            <ActionForm action=delete_timer>
                <input type="hidden" name="name" value={timer.name}/>
                <Button kind=ButtonKind::Text icon="delete_forever"/>
            </ActionForm>
        </Actions>
    </Card>
}
.into_any()
```

> Diagnostics:
>1. no method named `into_any` found for opaque type `impl leptos::IntoView` in the >current scope
>   method not found in `impl IntoView` [E0599]


<details><summary>Context</summary>

```rs
let existing_timers = {
    move || {
        timers.read(cx)
            .map(move |todos| match todos {
                Err(e) => {
                    vec![view! { cx, <pre class="error">"Server Error: " {e.to_string()}</pre>}.into_any()]
                }
                Ok(todos) => {
                    if todos.is_empty() {
                        vec![view! { cx, <p>"No tasks were found."</p> }.into_any()]
                    } else {
                        todos
                            .into_iter()
                            .map(move |timer| {
                                view! {
                                    cx,
                                    <Card kind=CardKind::Filled>
                                        <Actions>
                                            <ActionForm action=delete_timer>
                                                <input type="hidden" name="name" value={timer.name}/>
                                                <Button kind=ButtonKind::Text icon="delete_forever"/>
                                            </ActionForm>
                                        </Actions>
                                    </Card>
                                }
                                .into_any()
                            })
                            .collect::<Vec<_>>()
                    }
                }
            })
            .unwrap_or_default()
    }
};
```
</details> 

But then I noticed that it isn't possible to have a non `impl IntoView` return type at all.

**Comment by ModProg** [comment]
Maybe it would be possible to at least allow `impl IntoView` and `Component<...>`? the first being preferred in most places, but the second allowing for an improved API while accepting that you'd have an error about the return type if the macro isn't expanded.

**Comment by gbj** [comment]
> Well I ran into the issue that I couldn't call `.into_any()` on a `view!{}` containing only one of my components.

Right — in this case you want `.into_view(cx)`, and I think you're actually better served by that in any case as it saves you the two extra vecs.

```rust
let existing_timers = {
    move || {
        timers.read(cx)
            .map(move |todos| match todos {
                Err(e) => {
                    view! { cx, <pre class="error">"Server Error: " {e.to_string()}</pre>}.into_view(cx)
                }
                Ok(todos) => {
                    if todos.is_empty() {
                        view! { cx, <p>"No tasks were found."</p> }.into_view(cx)
                    } else {
                        todos
                            .into_iter()
                            .map(move |timer| {
                                view! {
                                    cx,
                                    <Card kind=CardKind::Filled>
                                        <Actions>
                                            <ActionForm action=delete_timer>
                                                <input type="hidden" name="name" value={timer.name}/>
                                                <Button kind=ButtonKind::Text icon="delete_forever"/>
                                            </ActionForm>
                                        </Actions>
                                    </Card>
                                }
                            })
                            .collect::<Vec<_>>()
                            .into_view(cx)
                    }
                }
            })
            .unwrap_or_default()
    }
};
```

> Maybe it would be possible to at least allow `impl IntoView` and `Component<...>`? the first being preferred in most places, but the second allowing for an improved API while accepting that you'd have an error about the return type if the macro isn't expanded.

Not sure what this would enable? It wouldn't solve your `.into_any()` problem.

**Comment by ModProg** [comment]
> Not sure what this would enable? It wouldn't solve your `.into_any()` problem. 

Oh, I just now noticed that this is a function on `HtmlElement`, my bad. So yeah, this would only be possible if there was a way to return the `HtmlElement` directly/a component containing an `HtmlElement` gaining this method.

> Right — in this case you want `.into_view(cx)`, and I think you're actually better served by that in any case as it saves you the two extra vecs.

If this is a general improvement, it would maybe be a good idea to update the [todo example](https://github.com/leptos-rs/leptos/blob/9a4f3ab08c93f735b57e9443ea4635bdbd835f2b/examples/todo_app_sqlite/src/todo.rs#L159). It was the reason I tried doing this in the first place.

As this was my only reason to need this, I cannot really argue in favor of changing this. I think it would be neat to allow this “advanced” usage, but I personally do not need it as of now.

**Comment by gbj** [comment]
> If this is a general improvement, it would maybe be a good idea to update the [todo example](https://github.com/leptos-rs/leptos/blob/9a4f3ab08c93f735b57e9443ea4635bdbd835f2b/examples/todo_app_sqlite/src/todo.rs#L159). It was the reason I tried doing this in the first place.

You're totally right. I'll clean those examples up (#940) and close this for now.
