### ISSUE TITLE
Client-side rendering stuck at loading when running trunk serve --open

### ISSUE THREAD

**Issue by MisterFISHUP** [leptos-rs/leptos#935]
Hello,

I've been following the tutorial guide (Book or Examples) and I found that after running `trunk serve --open` for client-side rendering apps, the served page was stuck at loading even though the command showed `✅ success`. I thought it's becuase I didn't install [wasm-pack](https://github.com/rustwasm/wasm-pack) but the problem persists even with wasm-pack installed. Apps using `cargo-leptos` don't have this problem though.

Thank you for creating leptos and providing the tutorial guide!

**Comment by MisterFISHUP** [comment]
Update: I found that if I already have a browser open and then run `trunk serve --open`, the app loads correctly. The problem only occurs when I don't have any browser open, and I think maybe this problem doesn't come from leptos, but rather from trunk.

**Comment by gbj** [comment]
Sounds like a trunk issue, then?

**Comment by MisterFISHUP** [comment]
@gbj I've opened an issue on Trunk (https://github.com/thedodd/trunk/issues/537) to see if other users are experiencing the same problem. Thank you for your response. Please feel free to close the issue if you think it has been resolved.
