### ISSUE TITLE
Hydration: JS event handling <-> Leptos Runtime

### ISSUE THREAD

**Issue by ActuallyHappening** [leptos-rs/leptos#937]
Hello leptos community, 

Firstly thanks for making such an awesome rust project!

I have what seems to me a 'special' case of this library, I want to be able to receive updates from some JS code.
My first (and currently last) attempt at this is to pass a Rust closure into the 'JS world', then inside the 'JS world' whenever an update occurs the JS calls the Rust closure, theoretically allowing the Rust to update its state in response to the JS update.

My specific use case involves the Firebase Javascript SDK. I want to create a website (using as much Rust as possible) that updates its state in response to database events I receive through JS APIs (i.e., from the Firebase JS SDK).

Unfortunately, the Rust closure approach falls short because the `wasm-bindgen` closure implementation requires that a struct (`wasm_bindgen::prelude::Closure`) be alive (as in, not `drop` ed) for its corresponding JS closure to be valid. In other words, as long as the Closure you created is still alive in Rust, calling it from the 'JS world' will be fine, but as soon as the Rust end is dropped (so removed from the stack), calling from the 'JS world' gives an error and doesn't achieve the `Closure`'s purpose

<img width="364" alt="image" src="https://user-images.githubusercontent.com/105958073/233827493-da0335ca-a48e-4819-95a6-24e9eb73db32.png">

## My question is: Can I somehow affect the `leptos` state of my app arbitrarily from JS?
Here is my Rust-JS interop:
```rs
#[wasm_bindgen(inline_js = "
export function register_event_handler(f) {
	console.log('RS-JS: Registering event handler');
	window._event_handler = f;
}
")]
extern "C" {
	// fn closure_test(f: &mut dyn FnMut());
	fn register_event_handler(f: &Closure<dyn FnMut()>);
}
```
My problem is that any closure I use from `leptos` eventually is `drop`ped, so any closure I pass into this interop function is eventually invalidated when I need to call it.
Here is an example struct which demonstrates what I mean:
```rs
pub struct JSEventHandler {
	closure: Closure<dyn FnMut()>,
}

impl JSEventHandler {
	pub fn new_with_callback<F: 'static>(f: F) -> Self
	where
		F: FnMut(),
	{
		let closure = Closure::new(f);

		register_event_handler(&closure);

		info!("RS: Registered event handler");

		Self {
			closure: closure,
		}
	}
}

impl Drop for JSEventHandler {
	fn drop(&mut self) {
		info!("RS: Dropping event handler");
	}
}
```
Say I initialise this (using `cargo-leptos`, I am initialising this in the `#[wasm_bindgen] pub fn hydrate() { ... leptos::mount_to_body(...) }` function, just before the `mount_to_body` func:
```rs
info!("RS: Initialising JS event handler");
let handler = JSEventHandler::new_with_callback(|| info!("RS: Event handler called"));
```
And I run the app, sometime after initial load calling `window._event_handler()` from JS like this:
```js
console.log("index.js loaded")
// Wait some time
console.log("calling RS Closure")
window._event_handler()
```
The console outputs (paraphrased):
```
index.js loaded
RS: Initialising JS event handler
RS-JS: Registering event handler
RS: Registered event handler
RS: Dropping event handler // <-- THIS IS THE PROBLEM
JS: Calling RS Closure // <-- THIS happens after JSEventHandler struct is `dropped
Error: closure invoked recursively or after being dropped // From wasm-bindgen
```

## Why?
I suppose this is expected, the `hydrate` function is being called once and then finished.
Any struct initialised in this function will eventually be deallocated.
Therefor, keeping a struct alive beyond this function is difficult (idk how to keep things alive longer than its parent function scope/call, although in Rust I believe this is impossible due to borrow checker)

## A solution
There is a solution to this which I have devised (yet to implement, will post here).
If you designated a DOM element, say a button, which you hide (using CSS), the 'JS world' can freely manipulate some part of the DOM (e.g. the buttons text) which the leptos app can read at any time.
Then, an event listener can be attached to the button, so when the 'JS world' want to signal an event has happened some arbitrary code is run inside the `leptos` runtime, which can then read the data left by the JS raw DOM manipulation.

## Why this is a problem
The above solution seems very, well, ugly. Surely there is a better way?

**Comment by gbj** [comment]
This is a [pretty standard thing](https://github.com/rustwasm/wasm-bindgen/blob/main/examples/closures/src/lib.rs#L72-L82) in Rust/WASM interop. 

if you want the closure to stay alive forever, you can call `.forget()`. 

If you want the closure to stay alive for as long as the Leptos component you created it in, you can do 
`on_cleanup(cx, move || drop(closure));`

This moves the closure into the reactive system and keeps ownership of it until this `Scope` is cleaned up.

**Comment by ActuallyHappening** [comment]
> This is a [pretty standard thing](https://github.com/rustwasm/wasm-bindgen/blob/main/examples/closures/src/lib.rs#L72-L82) in Rust/WASM interop.

Wow thanks, well that solves my issue well :)
