### ISSUE TITLE
impl FromIterator for View

### ISSUE THREAD

**Issue by ModProg** [leptos-rs/leptos#941]
While `Fragment::into_view` takes a `Scope` it is not used in the whole call chain. So it should be possible to implement `FromIterator<View> for View`.
A naive implementation would just copy the code from `Fragment::into_view()` and `ComponentRepr::into_view()`:

```rs
impl FromIterator<View> for View {
    fn from_iter<T: IntoIterator<Item = View>>(iter: T) -> Self {
        let fragment = iter.into_iter().collect::<Fragment>();
        let mut frag = ComponentRepr::new_with_id("", fragment.id().clone());

        #[cfg(debug_assertions)]
        {
            frag.view_marker = fragment.view_marker;
        }

        frag.children = fragment.nodes;
        #[cfg(all(target_arch = "wasm32", feature = "web"))]
        if !HydrationCtx::is_hydrating() {
            for child in &self.children {
                mount_child(MountKind::Before(&self.closing.node), child);
            }
        }

        View::Component(frag)
    }
}

```

_Originally posted by @ModProg in https://github.com/leptos-rs/leptos/pull/940#discussion_r1174657148_
           
One could also implement `Into<View>` for types that do not need the `Scope` to convert, thought that would lock us in to nether (until a breaking change) use `Scope` to convert from such a type to `View`. I'm not sure if there are any reasons to need to use `Scope` so this could be fine.

**Comment by ModProg** [comment]
I thought this makes more sense as a standalone issue than a footnote on a PR.

**Comment by gbj** [comment]
I think this is a great idea. It would be very nice not to have to collect into a `Vec`.

 Last time I tried it I recall issues with conflicting trait implementations possibly having to do with the fact that `IntoView` is implemented for `Fn -> impl IntoView` but you're probably right that implementing `From` would actually work. 

Do you want to try it? If not I can do it at some point.

**Comment by ModProg** [comment]
this would allow calling `collect_view(cx)` on e.g. `Vec<impl IntoView>` but also a `.map(|| view!{})` etc.
