### ISSUE TITLE
compile error at view!{cx, <></>}

### ISSUE THREAD

**Issue by takeisit** [leptos-rs/leptos#951]
After pulling latest main branch, my code couldn't be compiled because of the error.
Is it a breaking change? Or just a bug?

```
error: expected expression, found end of macro arguments
  --> leptos1/src/main.rs:47:18
   |
47 |         let v1 = view!{cx, <></>};
   |                  ^^^^^^^^^^^^^^^^
```

`0.2.5`: Pass
`main( #6c3381ce )`: Error

Although `view!{cx, <>{}</>}` can be compiled, it's a little redundant.

**Comment by gbj** [comment]
Hm okay so I was initially not able to reproduce this (i.e., `view!{ cx, <></> }` compiled fine), then I ran a `cargo clean` and reproduced it once, but when I run `cargo clean && cargo update && cargo leptos build` with a git dependency I don't get an error. Is this still happening for you?

**Comment by takeisit** [comment]
Oops. Sorry, I didn't run `cargo clean`. After running it, my code could be compiled. Thanks!
