### ISSUE TITLE
Create an `Iteator<IntoView>::collect_view method to collect a view from an iterator

### ISSUE THREAD

**Issue by ModProg** [leptos-rs/leptos#953]
As we cannot implement `IntoView for impl IntoIterator<Item=impl IntoView>` due to trait constraints, I thought we could consider adding a `collect_view` method for everything that implements `IntoView`:
```rs
/// Collects an iterator or collection into a [`View`].
pub trait CollectView {
    /// Collects an iterator or collection into a [`View`].
    fn collect_view(self, cx: Scope) -> View;
}

impl<I: IntoIterator<Item = T>, T: IntoView> CollectView for I {
    #[cfg_attr(
        any(debug_assertions, feature = "ssr"),
        instrument(level = "info", name = "#text", skip_all)
    )]
    fn collect_view(self, cx: Scope) -> View {
        self.into_iter()
            .map(|v| v.into_view(cx))
            .collect::<Fragment>()
            .into_view(cx)
    }
}
```
this would allow calling collect_view(cx) on e.g. `Vec<impl IntoView>` but also a `.map(|_| view!{})` etc.

_Originally posted by @ModProg in https://github.com/leptos-rs/leptos/issues/941#issuecomment-1520428848_

**Comment by gbj** [comment]
Yes, this makes perfect sense to me.
