### ISSUE TITLE
Optional event listeners

### ISSUE THREAD

**Issue by ModProg** [leptos-rs/leptos#963]
It is currently not possible to set an eventlistener optionally. I could just set the event listener always and not do something in cases where I don't need it, but I would like there to be a different way.

One would be to allow `on:event=...` to take an option, the other more general feature would be some form of conditional parameter in rsx. i.e. something like
```rs
<input 
   on:input=if condition {
      move |ev: Event| { value.set(event_target_value(&ev))}
   } // no else block to differentiate from an actual `if ... {...} else {...}` expression
/> 
```

**Comment by gbj** [comment]
What's the advantage, in your mind, of this
```rust
<input 
   on:input=if condition {
      move |ev: Event| { value.set(event_target_value(&ev))}
   } // no else block to differentiate from an actual `if ... {...} else {...}` expression
/> 
```
over this
```rust
<input 
   on:input=move |ev: Event| if condition {
       value.set(event_target_value(&ev))
   }
/> 
```
If you genuinely want to make sure that the event listener isn't added under some circumstances, the other way to express this is to use the builder syntax `.on()`, either non-reactively
```rust
let mut input = view! { cx, <input/> };
if let Some(callback) = callback {
  input = input.on(ev::click, callback)
}
```
or reactively
```rust
let input_ref = create_node_ref::<html::Input>(cx);

create_effect(cx, move |_| {
  if let (Some(button), Some(handler)) = (input_ref.get(), handler()) {
    button.on(ev::click, handler);
  }
});

view! { cx,
  <input node_ref=node_ref/>
}
```
I'm generally kind of skeptical of adding additional syntax to the view macro, as proc-macro changes are harder to maintain, and I'm generally kind of skeptical of adding syntax that doesn't work as ordinary Rust syntax (like as `if` expression without an `else` clause). 

So I'm open to being convinced but starting from a place of skepticism.

**Comment by ModProg** [comment]
I didn't know about this, that would already be enough for me I think.

> ```rust
> let mut input = view! { cx, <input/> };
> if let Some(callback) = callback {
>   input = input.on(ev::click, callback)
> }
> ```

**Comment by gbj** [comment]
> Though, a mutating builder would make this even nicer to use.

Yeah in this case we could actually add something to `HtmlElement` like `fn add_event_listener(&mut self, cb: Option<_>)`

Which would allow you to just do those three lines in one.

**Comment by gbj** [comment]
So I threw up a quick PR with a `.optional_event` helper. I realized that one of the reasons we *didn't* do this in the past is that typing `None` is impossible for `Option<impl FnMut>`, because the type of a closure can't be written out.

So this version takes a boxed closure instead. It lets you write something like 
```rust
.optional_event(ev::click, Some(Box::new(move |_| leptos::log!("something"))))
```

I'm not sure I love this but it was extremely easy to implement. What do you think is better, this one-line-but-boxed syntax or the three-liner `if let` version?

**Comment by ModProg** [comment]
> I realized that one of the reasons we _didn't_ do this in the past is that typing `None` is impossible for `Option<impl FnMut>`, because the type of a closure can't be written out.

Well would it even make sense to call with a literal None, and even when one did this would work even when it takes an `Option<impl FnMut>`

```rs
const NONE_FN_MUT: Option<Box<dyn FnMut()>> = None::<Box<dyn FnMut()>>;

fn main() {
    fun(Some(|| {}));
    fun(NONE_FN_MUT);
}

fn fun(_: Option<impl FnMut()>) {}
```

**Comment by gbj** [comment]
> > I realized that one of the reasons we _didn't_ do this in the past is that typing `None` is impossible for `Option<impl FnMut>`, because the type of a closure can't be written out.
> 
> Well would it even make sense to call with a literal None, and even when one did this would work even when it takes an `Option<impl FnMut>`

No you're right, the bigger issue is to do with optional generic-function props on components.

Could you give a quick example of a context in which you're hoping to use this just so I can make sure it compiles/works correctly?

**Comment by ModProg** [comment]
> Could you give a quick example of a context in which you're hoping to use this just so I can make sure it compiles/works correctly?

```rs
#[component]
pub fn Input(
    /// Scope
    cx: Scope,
    #[prop(optional)] filled: bool,
    #[prop(optional)] value: Option<RwSignal<String>>,
) -> impl IntoView {
    let mut view = view! {cx,
        <input 
            class:filled=filled 
            prop:value=value
            // only if value is some:
            // on:input=move |ev: Event| value.set(event_target_value(&ev))
        />
    };
    if let Some(value) = value {
        view = view.on(ev::input, move |ev: Event| value.set(event_target_value(&ev)))
    }
    view
}
```

**Comment by gbj** [comment]
Thanks! So I just merged this with a syntax like this
```rust
pub fn Input(
    cx: Scope,
    #[prop(optional)] value: Option<RwSignal<String>>,
) -> impl IntoView {
    view! { cx, <input/> }
        // only add event if `value` is `Some(signal)`
        .optional_event(
            ev::input,
            value.map(|value| move |ev| value.set(event_target_value(&ev))),
        )
}
```
