### ISSUE TITLE
Recommend using `Resource::with()` instead of `Resource::read()`

### ISSUE THREAD

**Issue by gbj** [leptos-rs/leptos#970]
The examples and book currently use `Resource::read()`, which is a perfectly fine function but slightly more awkward to use than `Resource::with()`, especially when combined with `<Suspense/>`. 

`.read(cx)` clones the current value and returns it to you, which is `None` if loading
```rust
pub fn read(&self, cx: Scope) -> Option<T>
```

`.with(cx)` takes a callback, which will only run if the resource has loaded, and returns `Option`.
```rust
pub fn with<U>(&self, cx: Scope, f: impl FnOnce(&T) -> U) -> Option<U> {
```

This lets you avoid matching or using `.map()` on the result of `.read(cx)`, because the `None` case is automatically handled by the renderer.

I'd like to update the examples and docs to recommend `.with(cx)` as the default for this reason. 

This should be pretty easy for someone else to take on, so that I can work on other stuff.

**Comment by anacrolix** [comment]
I'm a bit of a Rust noob, but I found that switching from `read` to `with` meant that I had to add a `clone()`, like [this](https://github.com/anacrolix/leptos/commit/1c763beff17e020f3d5016073b0749f510b23f4b). Is that preferable, because there are cases where having the reference might be sufficient, and `read` does a clone for you? Or would it be better if `with` took a `FnOnce(T) -> U` instead of `FnOnce(&T) -> U`?

**Comment by gbj** [comment]
> I'm a bit of a Rust noob, but I found that switching from `read` to `with` meant that I had to add a `clone()`, like [this](https://github.com/anacrolix/leptos/commit/1c763beff17e020f3d5016073b0749f510b23f4b). Is that preferable, because there are cases where having the reference might be sufficient, and `read` does a clone for you? Or would it be better if `with` took a `FnOnce(T) -> U` instead of `FnOnce(&T) -> U`?

Right, all the `.with()` functions here take values by reference. The relevant distinction here is more tha, due to what's probably just a weird early design decision on my part, `.with()` takes `&T` and `.read()` returns `Option<T>`, making the `.with()` slightly easier to work with in that sense. The fact that I haven't actually done anything about my own suggestion in the month says I'm kind of ambivalent about it, but had written it down at some point! :smile:
