### ISSUE TITLE
IDE support for syn-rsx, or can I just not use it?

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [leptos-rs/leptos#975]
Hi,

while I like the idea of embedded html, I need IDE support (highlighting, auto-formatting) for me to really work.

As far as I can see it, this support is not here, am I wrong?

Is there IDE support for the `view!` macros?

If not, can I leave out this syntax and somehow builds the DOM in pure rust? Does that make sense?

Thank you!
Nathan

**Comment by gbj** [comment]
So to start with, if you don't want to use the `view` macro you can just use the builder syntax it expands to. See an example [here](https://github.com/leptos-rs/leptos/blob/main/examples/counter_without_macros/src/lib.rs).

You don't say what IDE you're using, which makes it a little hard to answer. There is pretty good rust-analyzer support for the macro, but not perfect; but for example in IDEs (VS Code for example) that use rust-analyzer semantic information for syntax highlighting, you get syntax highlighting on pretty much everything as expected, except for closing HTML tags.

You should check out [`leptos-language-server`](https://github.com/bram209/leptos-language-server)/[`leptosfmt`](https://lib.rs/crates/leptosfmt) for view macro formatting. `leptos-language-server` has a VS Code plugin but follows the LSP so should be usable with other IDEs too.

If there are other, more specific questions, happy to try to answer them.

**Comment by RudolfVonKrugstein** [comment]
Sorry for not mentioning my IDE, I am using neovim but if vscode or intellij would have made a different, I would maybe switch :).

Thank you for your tip! I added:

```lua
-- leptos cusotm lsp
vim.api.nvim_create_autocmd({"BufRead"},{
  pattern = {"*.rs"},
  callback = function()
    vim.lsp.start({
      name = "leptos-language-server",
      cmd = {"leptos-language-server"},
      root_dir = vim.fs.dirname(vim.fs.find({'Cargo.toml'}, { upward = true })[1]),
    });
  end
})
```

to my `init.lua` and I can use the LSP to format!

Thanks!
