### ISSUE TITLE
Dynamic classes with class names containing numbers

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [leptos-rs/leptos#976]
Hello,

It seems to me, that the dynamic class names syntax fails, when there is a number in the class name:

```
<div class:grid-cols-1=move || one_col()></div>
```

Does not work with "invalid tag name or attribute key" error.

While:

```
<div class:grid-cols-one=move || one_col()></div>
```

works!

**Comment by gbj** [comment]
See #73, #776 and particularly [the solution](https://github.com/leptos-rs/leptos/issues/73#issuecomment-1374695419), which is to use `class=("class-name-with-numbers-as-string", some_value)`
```rust
view! { cx,
  <span class=("pt-4", true)/>
}
```

This is documented in the [`view`](https://docs.rs/leptos/latest/leptos/macro.view.html) macro docs.

**Comment by RudolfVonKrugstein** [comment]
Oh, did not see that. Thank you very much!
