### ISSUE TITLE
Expose a way to access base websys element

### ISSUE THREAD

**Issue by tiberiusferreira** [leptos-rs/leptos#982]
Hey, is there a way to turn an HtmlElement into a https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Element.html?

I need this to call https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Element.html#method.get_bounding_client_rect .

It works if I manually add websys as a dependency with the correct flags and do:
```
let container = container_ref.get().expect("container to already exist");
let dom_rect = web_sys::Element::from(container.deref().clone()).get_bounding_client_rect();
```
but it would be better to have leptos expose it to avoid compiling websys twice.

**Comment by gbj** [comment]
What you are doing is correct -- using `wasm-bindgen::JsCast` also works. 

Adding a `web-sys` dependency with the needed flags is the correct way to handle this. We enable the subset of features required for Leptos itself to compile. If you need additional features you add them in your Cargo.toml and they are unified, not compiled twice.

**Comment by tiberiusferreira** [comment]
Oh, good to know, thank you for the quick response!
