### ISSUE TITLE
Option to wait until resources are loaded when navigating 

### ISSUE THREAD

**Issue by Skyliegirl33** [leptos-rs/leptos#994]
I think it'd be great if we can have an option to wait until the resources of a page are resolved before rendering the page.
Example: if I'm viewing a blog post and want to navigate to the list of all posts, currently the navigation occurs before the resource is resolved, which, depending on how long that takes, can result in a noticeable delay or flicker. In such a case, it might be preferable to not navigate to the page at all until the resource(s) are resolved.

Assuming this can be implemented on the route level, something like this would work:
```rust
<Route path="posts" view=|cx| view!{ cx, <Blog/> } load=LoadingMode::WaitResolved />
<Route path="" view=|cx| view!{ cx, <Home/> } load=LoadingMode::Fallback />
```
or
```rust
<Route path="posts" view=|cx| view!{ cx, <Blog/> } render=RenderMode::Blocking />
<Route path="" view=|cx| view!{ cx, <Home/> } render=RenderMode::Fallback />
```

**Comment by gbj** [comment]
Yep this makes perfect sense and is built into the router in e.g., SolidJS, with its more-advanced transition system. I played around a little with wrapping `<Outlet/>` in `<Transition/>` and so on and got the dread hydration mismatch warnings, but this should definitely be doable and possibly even the default behavior.
